import type { WeapiCrossPlatformMethodDocsOpenSystemBluetoothSettingToChooseLicensePlateOpenSystemBluetoothSettingToPauseVoice } from './openSystemBluetoothSettingToPauseVoice'
import type { WeapiCrossPlatformMethodDocsOpenSystemBluetoothSettingToChooseLicensePlatePlayBackgroundAudioToChooseLicensePlate } from './playBackgroundAudioToChooseLicensePlate'

export type WeapiCrossPlatformMethodDocsOpenSystemBluetoothSettingToChooseLicensePlate
  = WeapiCrossPlatformMethodDocsOpenSystemBluetoothSettingToChooseLicensePlateOpenSystemBluetoothSettingToPauseVoice
    & WeapiCrossPlatformMethodDocsOpenSystemBluetoothSettingToChooseLicensePlatePlayBackgroundAudioToChooseLicensePlate
