import {
  APP_PRELUDE_CHUNK_MARKER,
  REQUEST_GLOBAL_BUNDLE_MARKER,
  REQUEST_GLOBAL_SYNTHETIC_EXPORT_NAME,
  WEAPP_I18N_JS_FILE,
  WEAPP_I18N_LOCALE_DATA_KEY,
  WEAPP_I18N_PUBLIC_MODULE_ID,
  WEAPP_I18N_RUNTIME_MARKER,
  WEAPP_I18N_VIRTUAL_MODULE_ID,
  WEAPP_I18N_WXS_FILE,
  WEAPP_VITE_EXTERNAL_OUTPUT_DIRECTORY,
  WEAPP_VITE_RUNTIME_CONTRACT_VERSION,
  WEAPP_VITE_RUNTIME_REACTIVITY_VIRTUAL_ID,
  WEAPP_VITE_RUNTIME_TEMPLATE_VIRTUAL_ID,
  WEAPP_VITE_RUNTIME_VIRTUAL_ID,
  WEAPP_VITE_RUNTIME_VIRTUAL_IDS,
  WEAPP_VITE_STATEFUL_HMR_BRIDGE_KEY,
  WEAPP_VITE_STATEFUL_HMR_CLIENT_KEY,
  WEAPP_VITE_STATEFUL_HMR_CONTROL_FILE,
  WEAPP_VITE_STATEFUL_HMR_CONTROL_KEY,
  WEAPP_VITE_STATEFUL_HMR_DIRECTORY,
  WEAPP_VITE_STATEFUL_HMR_PRELOAD_FILE,
  WEAPP_VITE_STATEFUL_HMR_UPDATE_FILE,
  WEVU_CLASS_STYLE_RUNTIME_MODULE,
  WEVU_COMPONENT_NAME_KEY,
  WEVU_INLINE_MAP_KEY,
  WEVU_PARENT_INSTANCE_KEY,
  WEVU_PROPS_ALIASES_KEY,
  WEVU_PROPS_DERIVED_KEYS_KEY,
  WEVU_PROVIDES_KEY,
  WEVU_PUBLIC_RUNTIME_KEY,
  WEVU_RESOLVE_PUBLIC_INSTANCE_METHOD,
  WEVU_RUNTIME_OWNER_ID_KEY,
  WEVU_SETUP_STATE_KEY,
  WEVU_SLOT_FALLBACK_VIRTUAL_HOST_BASE,
  WEVU_SLOT_FALLBACK_VIRTUAL_HOST_GLOBAL_PATH,
  WEVU_SLOT_FALLBACK_VIRTUAL_HOST_TAG_NAME,
  WEVU_SLOT_NAMES_ATTR,
  WEVU_SLOT_NAMES_PROP,
} from '../src'

describe('@weapp-core/constants', () => {
  it('exports stable runtime markers and keys', () => {
    expect(APP_PRELUDE_CHUNK_MARKER).toBe('__wvAPR__')
    expect(REQUEST_GLOBAL_BUNDLE_MARKER).toBe('__wvRGB__')
    expect(REQUEST_GLOBAL_SYNTHETIC_EXPORT_NAME).toBe('__wvRGI__')
    expect(WEAPP_I18N_PUBLIC_MODULE_ID).toBe('weapp-vite/i18n')
    expect(WEAPP_I18N_VIRTUAL_MODULE_ID).toBe('virtual:weapp-vite/i18n')
    expect(WEAPP_I18N_RUNTIME_MARKER).toBe('__WEAPP_VITE_I18N__')
    expect(WEAPP_I18N_LOCALE_DATA_KEY).toBe('__wv_i18n_locale')
    expect(WEAPP_I18N_JS_FILE).toBe('i18n/locales.js')
    expect(WEAPP_I18N_WXS_FILE).toBe('i18n/locales.wxs')
    expect(WEAPP_VITE_RUNTIME_CONTRACT_VERSION).toBe(1)
    expect(WEAPP_VITE_EXTERNAL_OUTPUT_DIRECTORY).toBe('weapp_vite_external')
    expect(WEAPP_VITE_EXTERNAL_OUTPUT_DIRECTORY).not.toMatch(/^__|__$/)
    expect(WEAPP_VITE_RUNTIME_VIRTUAL_ID).toBe('virtual:weapp-vite/runtime')
    expect(WEAPP_VITE_RUNTIME_REACTIVITY_VIRTUAL_ID).toBe('virtual:weapp-vite/runtime/reactivity')
    expect(WEAPP_VITE_RUNTIME_TEMPLATE_VIRTUAL_ID).toBe('virtual:weapp-vite/runtime/template')
    expect(WEAPP_VITE_RUNTIME_VIRTUAL_IDS).toEqual({
      runtime: WEAPP_VITE_RUNTIME_VIRTUAL_ID,
      reactivity: WEAPP_VITE_RUNTIME_REACTIVITY_VIRTUAL_ID,
      template: WEAPP_VITE_RUNTIME_TEMPLATE_VIRTUAL_ID,
    })
    expect(WEAPP_VITE_STATEFUL_HMR_DIRECTORY).toBe('__weapp_vite_hmr')
    expect(WEAPP_VITE_STATEFUL_HMR_CONTROL_FILE).toBe('__weapp_vite_hmr/control.js')
    expect(WEAPP_VITE_STATEFUL_HMR_PRELOAD_FILE).toBe('__weapp_vite_hmr/preload.js')
    expect(WEAPP_VITE_STATEFUL_HMR_UPDATE_FILE).toBe('__weapp_vite_hmr/update.js')
    expect(WEAPP_VITE_STATEFUL_HMR_CONTROL_KEY).toBe('__WEAPP_VITE_STATEFUL_HMR_CONTROL__')
    expect(WEAPP_VITE_STATEFUL_HMR_CLIENT_KEY).toBe('__WEAPP_VITE_STATEFUL_HMR_CLIENT__')
    expect(WEAPP_VITE_STATEFUL_HMR_BRIDGE_KEY).toBe('__WEAPP_VITE_STATEFUL_HMR_BRIDGE__')
    expect(WEVU_CLASS_STYLE_RUNTIME_MODULE).toBe('__weapp_vite')
    expect(WEVU_COMPONENT_NAME_KEY).toBe('__wevuComponentName')
    expect(WEVU_INLINE_MAP_KEY).toBe('__weapp_vite_inline_map')
    expect(WEVU_PUBLIC_RUNTIME_KEY).toBe('$wevu')
    expect(WEVU_RESOLVE_PUBLIC_INSTANCE_METHOD).toBe('__weapp_vite_resolvePublicInstance')
    expect(WEVU_RUNTIME_OWNER_ID_KEY).toBe('__wevuRuntimeOwnerId')
    expect(WEVU_PROVIDES_KEY).toBe('__wevuProvides')
    expect(WEVU_PARENT_INSTANCE_KEY).toBe('__wevuParentInstance')
    expect(WEVU_SETUP_STATE_KEY).toBe('__wevuSetupState')
    expect(WEVU_PROPS_ALIASES_KEY).toBe('__wevuPropsAliases')
    expect(WEVU_PROPS_DERIVED_KEYS_KEY).toBe('__wevuPropsDerivedKeys')
    expect(WEVU_SLOT_NAMES_PROP).toBe('vueSlots')
    expect(WEVU_SLOT_NAMES_ATTR).toBe('vue-slots')
    expect(WEVU_SLOT_FALLBACK_VIRTUAL_HOST_TAG_NAME).toBe('weapp-slot-wrapper')
    expect(WEVU_SLOT_FALLBACK_VIRTUAL_HOST_BASE).toBe('weapp_vite_internal/slot-wrapper/index')
    expect(WEVU_SLOT_FALLBACK_VIRTUAL_HOST_GLOBAL_PATH).toBe('/weapp_vite_internal/slot-wrapper/index')
  })
})
