import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_CROP_IMAGE_TO_START_HCE: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'cropImage',
    description: '裁剪图片。',
    wxStrategy: '直连 `wx.cropImage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'editImage',
    description: '编辑图片。',
    wxStrategy: '直连 `wx.editImage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'exitVoIPChat',
    description: '退出音视频通话。',
    wxStrategy: '直连 `wx.exitVoIPChat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'faceDetect',
    description: '人脸检测。',
    wxStrategy: '直连 `wx.faceDetect`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getApiCategory',
    description: '获取 API 分类信息。',
    wxStrategy: '直连 `wx.getApiCategory`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getBackgroundFetchToken',
    description: '获取后台拉取 token。',
    wxStrategy: '直连 `wx.getBackgroundFetchToken`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getChannelsLiveInfo',
    description: '获取视频号直播信息。',
    wxStrategy: '直连 `wx.getChannelsLiveInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getChannelsLiveNoticeInfo',
    description: '获取视频号直播预告信息。',
    wxStrategy: '直连 `wx.getChannelsLiveNoticeInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getChannelsShareKey',
    description: '获取视频号分享 key。',
    wxStrategy: '直连 `wx.getChannelsShareKey`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getChatToolInfo',
    description: '获取客服工具信息。',
    wxStrategy: '直连 `wx.getChatToolInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getCommonConfig',
    description: '获取通用配置。',
    wxStrategy: '直连 `wx.getCommonConfig`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getGroupEnterInfo',
    description: '获取群聊进入信息。',
    wxStrategy: '直连 `wx.getGroupEnterInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getPrivacySetting',
    description: '获取隐私设置。',
    wxStrategy: '直连 `wx.getPrivacySetting`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'initFaceDetect',
    description: '初始化人脸检测。',
    wxStrategy: '直连 `wx.initFaceDetect`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'join1v1Chat',
    description: '发起 1v1 通话。',
    wxStrategy: '直连 `wx.join1v1Chat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareAppMessageToGroup',
    description: '分享到群聊会话。',
    wxStrategy: '直连 `wx.shareAppMessageToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareEmojiToGroup',
    description: '分享到群聊表情。',
    wxStrategy: '直连 `wx.shareEmojiToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareFileMessage',
    description: '分享文件消息。',
    wxStrategy: '直连 `wx.shareFileMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareFileToGroup',
    description: '分享文件到群。',
    wxStrategy: '直连 `wx.shareFileToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareImageToGroup',
    description: '分享图片到群。',
    wxStrategy: '直连 `wx.shareImageToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareToOfficialAccount',
    description: '分享至公众号。',
    wxStrategy: '直连 `wx.shareToOfficialAccount`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareToWeRun',
    description: '分享至微信运动。',
    wxStrategy: '直连 `wx.shareToWeRun`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareVideoMessage',
    description: '分享视频消息。',
    wxStrategy: '直连 `wx.shareVideoMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareVideoToGroup',
    description: '分享视频到群。',
    wxStrategy: '直连 `wx.shareVideoToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'showRedPackage',
    description: '展示红包组件。',
    wxStrategy: '直连 `wx.showRedPackage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startDeviceMotionListening',
    description: '开始监听设备方向变化。',
    wxStrategy: '直连 `wx.startDeviceMotionListening`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startHCE',
    description: '启动 HCE 功能。',
    wxStrategy: '直连 `wx.startHCE`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
