import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_ADD_PHONE_CONTACT_TO_OPEN_OFFICIAL_ACCOUNT_CHAT: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'addPhoneContact',
    description: '添加手机联系人。',
    wxStrategy: '直连 `wx.addPhoneContact`',
    alipayStrategy: '直连 `my.addPhoneContact`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPhoneRepeatCalendar',
    description: '添加重复日历事件。',
    wxStrategy: '直连 `wx.addPhoneRepeatCalendar`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addVideoToFavorites',
    description: '添加视频到收藏。',
    wxStrategy: '直连 `wx.addVideoToFavorites`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'authorizeForMiniProgram',
    description: '获取小程序授权码。',
    wxStrategy: '直连 `wx.authorizeForMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'authPrivateMessage',
    description: '校验私密消息。',
    wxStrategy: '直连 `wx.authPrivateMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'bindEmployeeRelation',
    description: '绑定员工关系。',
    wxStrategy: '直连 `wx.bindEmployeeRelation`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'canAddSecureElementPass',
    description: '检测是否可添加安全元素卡片。',
    wxStrategy: '直连 `wx.canAddSecureElementPass`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'canvasGetImageData',
    description: '获取 canvas 区域像素数据。',
    wxStrategy: '直连 `wx.canvasGetImageData`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'canvasPutImageData',
    description: '将像素数据绘制到 canvas。',
    wxStrategy: '直连 `wx.canvasPutImageData`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkDeviceSupportHevc',
    description: '检测设备是否支持 HEVC 解码。',
    wxStrategy: '直连 `wx.checkDeviceSupportHevc`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkEmployeeRelation',
    description: '查询员工关系绑定状态。',
    wxStrategy: '直连 `wx.checkEmployeeRelation`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsAddedToMyMiniProgram',
    description: '检测是否已添加到我的小程序。',
    wxStrategy: '直连 `wx.checkIsAddedToMyMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsOpenAccessibility',
    description: '检测系统无障碍是否开启。',
    wxStrategy: '直连 `wx.checkIsOpenAccessibility`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsPictureInPictureActive',
    description: '检测是否处于画中画状态。',
    wxStrategy: '直连 `wx.checkIsPictureInPictureActive`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsSoterEnrolledInDevice',
    description: '检测设备是否录入 SOTER 信息。',
    wxStrategy: '直连 `wx.checkIsSoterEnrolledInDevice`',
    alipayStrategy: '映射到 `my.checkIsIfaaEnrolledInDevice`，`speech` 模式按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsSupportSoterAuthentication',
    description: '检测设备是否支持 SOTER 生物认证。',
    wxStrategy: '直连 `wx.checkIsSupportSoterAuthentication`',
    alipayStrategy: '映射到 `my.checkIsSupportIfaaAuthentication`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openCard',
    description: '打开卡券详情。',
    wxStrategy: '直连 `wx.openCard`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsActivity',
    description: '打开视频号活动页。',
    wxStrategy: '直连 `wx.openChannelsActivity`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsEvent',
    description: '打开视频号活动详情。',
    wxStrategy: '直连 `wx.openChannelsEvent`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsLive',
    description: '打开视频号直播。',
    wxStrategy: '直连 `wx.openChannelsLive`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsLiveNoticeInfo',
    description: '打开视频号直播预告详情。',
    wxStrategy: '直连 `wx.openChannelsLiveNoticeInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsUserProfile',
    description: '打开视频号用户主页。',
    wxStrategy: '直连 `wx.openChannelsUserProfile`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChatTool',
    description: '打开客服工具页。',
    wxStrategy: '直连 `wx.openChatTool`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openHKOfflinePayView',
    description: '打开香港线下支付视图。',
    wxStrategy: '直连 `wx.openHKOfflinePayView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openInquiriesTopic',
    description: '打开询价话题。',
    wxStrategy: '直连 `wx.openInquiriesTopic`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openOfficialAccountArticle',
    description: '打开公众号文章。',
    wxStrategy: '直连 `wx.openOfficialAccountArticle`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openOfficialAccountChat',
    description: '打开公众号会话。',
    wxStrategy: '直连 `wx.openOfficialAccountChat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
