import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_PART_7: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'startLocalServiceDiscovery',
    description: '开始本地服务发现。',
    wxStrategy: '直连 `wx.startLocalServiceDiscovery`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startLocationUpdate',
    description: '开始持续定位。',
    wxStrategy: '直连 `wx.startLocationUpdate`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startLocationUpdateBackground',
    description: '开始后台持续定位。',
    wxStrategy: '直连 `wx.startLocationUpdateBackground`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startRecord',
    description: '开始录音。',
    wxStrategy: '直连 `wx.startRecord`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startSoterAuthentication',
    description: '开始 SOTER 认证。',
    wxStrategy: '直连 `wx.startSoterAuthentication`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopBackgroundAudio',
    description: '停止后台音频。',
    wxStrategy: '直连 `wx.stopBackgroundAudio`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopDeviceMotionListening',
    description: '停止监听设备方向变化。',
    wxStrategy: '直连 `wx.stopDeviceMotionListening`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopFaceDetect',
    description: '停止人脸检测。',
    wxStrategy: '直连 `wx.stopFaceDetect`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestCommonPayment',
    description: '发起通用支付请求。',
    wxStrategy: '直连 `wx.requestCommonPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestDeviceVoIP',
    description: '请求设备 VoIP 能力。',
    wxStrategy: '直连 `wx.requestDeviceVoIP`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestMerchantTransfer',
    description: '发起商家转账请求。',
    wxStrategy: '直连 `wx.requestMerchantTransfer`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requirePrivacyAuthorize',
    description: '请求隐私授权。',
    wxStrategy: '直连 `wx.requirePrivacyAuthorize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'reserveChannelsLive',
    description: '预约视频号直播。',
    wxStrategy: '直连 `wx.reserveChannelsLive`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'selectGroupMembers',
    description: '选择群成员。',
    wxStrategy: '直连 `wx.selectGroupMembers`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'sendHCEMessage',
    description: '发送 HCE 消息。',
    wxStrategy: '直连 `wx.sendHCEMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'sendSms',
    description: '发送短信。',
    wxStrategy: '直连 `wx.sendSms`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setBackgroundFetchToken',
    description: '设置后台拉取 token。',
    wxStrategy: '直连 `wx.setBackgroundFetchToken`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setEnable1v1Chat',
    description: '设置 1v1 通话可用状态。',
    wxStrategy: '直连 `wx.setEnable1v1Chat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setTopBarText',
    description: '设置顶栏文本。',
    wxStrategy: '直连 `wx.setTopBarText`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setWindowSize',
    description: '设置窗口尺寸。',
    wxStrategy: '直连 `wx.setWindowSize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopHCE',
    description: '停止 HCE 功能。',
    wxStrategy: '直连 `wx.stopHCE`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopLocalServiceDiscovery',
    description: '停止本地服务发现。',
    wxStrategy: '直连 `wx.stopLocalServiceDiscovery`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopLocationUpdate',
    description: '停止持续定位。',
    wxStrategy: '直连 `wx.stopLocationUpdate`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopRecord',
    description: '停止录音。',
    wxStrategy: '直连 `wx.stopRecord`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopVoice',
    description: '停止播放语音。',
    wxStrategy: '直连 `wx.stopVoice`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'subscribeVoIPVideoMembers',
    description: '订阅 VoIP 视频成员变化。',
    wxStrategy: '直连 `wx.subscribeVoIPVideoMembers`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'updateVoIPChatMuteConfig',
    description: '更新 VoIP 静音配置。',
    wxStrategy: '直连 `wx.updateVoIPChatMuteConfig`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
