import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_PART_9: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'createMediaContainer',
    description: '创建媒体容器实例。',
    wxStrategy: '直连 `wx.createMediaContainer`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createMediaRecorder',
    description: '创建媒体录制器。',
    wxStrategy: '直连 `wx.createMediaRecorder`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.createMediaRecorder`',
    support: '⚠️',
  },
  {
    method: 'createTCPSocket',
    description: '创建 TCP Socket。',
    wxStrategy: '直连 `wx.createTCPSocket`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createUDPSocket',
    description: '创建 UDP Socket。',
    wxStrategy: '直连 `wx.createUDPSocket`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createVideoDecoder',
    description: '创建视频解码器。',
    wxStrategy: '直连 `wx.createVideoDecoder`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'loadBuiltInFontFace',
    description: '加载内置字体。',
    wxStrategy: '直连 `wx.loadBuiltInFontFace`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'notifyGroupMembers',
    description: '通知群成员。',
    wxStrategy: '直连 `wx.notifyGroupMembers`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestIdleCallback',
    description: '空闲时回调请求。',
    wxStrategy: '直连 `wx.requestIdleCallback`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'revokeBufferURL',
    description: '释放缓冲区 URL。',
    wxStrategy: '直连 `wx.revokeBufferURL`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'rewriteRoute',
    description: '重写路由规则。',
    wxStrategy: '直连 `wx.rewriteRoute`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'seekBackgroundAudio',
    description: '调整后台音频播放进度。',
    wxStrategy: '直连 `wx.seekBackgroundAudio`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setEnableDebug',
    description: '设置调试开关。',
    wxStrategy: '直连 `wx.setEnableDebug`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setInnerAudioOption',
    description: '设置内部音频选项。',
    wxStrategy: '直连 `wx.setInnerAudioOption`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
