import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_PART_1: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'showToast',
    description: '显示消息提示框。',
    wxStrategy: '直连 `wx.showToast`',
    alipayStrategy: '`title/icon` 映射到 `content/type` 后调用 `my.showToast`',
    douyinStrategy: '`icon=error` 映射为 `fail` 后调用 `tt.showToast`',
    support: '✅',
  },
  {
    method: 'showLoading',
    description: '显示 loading 提示框。',
    wxStrategy: '直连 `wx.showLoading`',
    alipayStrategy: '`title` 映射到 `content` 后调用 `my.showLoading`',
    douyinStrategy: '直连 `tt.showLoading`',
    support: '✅',
  },
  {
    method: 'showActionSheet',
    description: '显示操作菜单。',
    wxStrategy: '直连 `wx.showActionSheet`',
    alipayStrategy: '`itemList` ↔ `items`、`index` ↔ `tapIndex` 双向对齐',
    douyinStrategy: '直连 `tt.showActionSheet`；缺失时按 unsupported 报错',
    support: '✅',
  },
  {
    method: 'showModal',
    description: '显示模态弹窗。',
    wxStrategy: '直连 `wx.showModal`',
    alipayStrategy: '调用 `my.confirm` 并对齐按钮字段与 `cancel/content`；`showCancel=false`、`editable` 等场景按 unsupported 报错',
    douyinStrategy: '直连 `tt.showModal`',
    support: '⚠️',
  },
  {
    method: 'chooseImage',
    description: '选择图片。',
    wxStrategy: '直连 `wx.chooseImage`',
    alipayStrategy: '返回值 `apFilePaths` 映射到 `tempFilePaths`',
    douyinStrategy: '`tempFilePaths` 字符串转数组，缺失时从 `tempFiles.path` 兜底',
    support: '✅',
  },
  {
    method: 'chooseMedia',
    description: '选择图片或视频。',
    wxStrategy: '直连 `wx.chooseMedia`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.chooseMedia`，并补齐 `tempFiles[].tempFilePath/fileType`',
    support: '⚠️',
  },
  {
    method: 'chooseMessageFile',
    description: '选择会话文件。',
    wxStrategy: '直连 `wx.chooseMessageFile`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getFuzzyLocation',
    description: '获取模糊地理位置。',
    wxStrategy: '直连 `wx.getFuzzyLocation`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'previewMedia',
    description: '预览图片和视频。',
    wxStrategy: '直连 `wx.previewMedia`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createInterstitialAd',
    description: '创建插屏广告实例。',
    wxStrategy: '直连 `wx.createInterstitialAd`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.createInterstitialAd`',
    support: '⚠️',
  },
  {
    method: 'createRewardedVideoAd',
    description: '创建激励视频广告实例。',
    wxStrategy: '直连 `wx.createRewardedVideoAd`',
    alipayStrategy: '映射到 `my.createRewardedAd`，并将 `load/show/destroy` 参数对齐为微信调用方式',
    douyinStrategy: '直连 `tt.createRewardedVideoAd`',
    support: '⚠️',
  },
  {
    method: 'createLivePlayerContext',
    description: '创建直播播放器上下文。',
    wxStrategy: '直连 `wx.createLivePlayerContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.createLivePlayerContext`',
    support: '⚠️',
  },
  {
    method: 'createLivePusherContext',
    description: '创建直播推流上下文。',
    wxStrategy: '直连 `wx.createLivePusherContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getVideoInfo',
    description: '获取视频详细信息。',
    wxStrategy: '直连 `wx.getVideoInfo`',
    alipayStrategy: '直连 `my.getVideoInfo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'saveFile',
    description: '保存文件（跨端扩展，微信 typings 未声明同名 API）。',
    wxStrategy: '微信当前 typings 未声明同名 API，保留为跨端扩展能力',
    alipayStrategy: '请求参数 `tempFilePath` ↔ `apFilePath`、结果映射为 `savedFilePath`',
    douyinStrategy: '直连 `tt.saveFile`，并在缺失时用 `filePath` 兜底 `savedFilePath`',
    support: '⚠️',
  },
  {
    method: 'setClipboardData',
    description: '设置剪贴板内容。',
    wxStrategy: '直连 `wx.setClipboardData`',
    alipayStrategy: '转调 `my.setClipboard` 并映射 `data` → `text`',
    douyinStrategy: '直连 `tt.setClipboardData`',
    support: '✅',
  },
  {
    method: 'getClipboardData',
    description: '获取剪贴板内容。',
    wxStrategy: '直连 `wx.getClipboardData`',
    alipayStrategy: '转调 `my.getClipboard` 并映射 `text` → `data`',
    douyinStrategy: '直连 `tt.getClipboardData`',
    support: '✅',
  },
  {
    method: 'chooseAddress',
    description: '选择收货地址。',
    wxStrategy: '直连 `wx.chooseAddress`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.chooseAddress`',
    support: '⚠️',
  },
  {
    method: 'createAudioContext',
    description: '创建音频上下文。',
    wxStrategy: '直连 `wx.createAudioContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createWebAudioContext',
    description: '创建 WebAudio 上下文。',
    wxStrategy: '直连 `wx.createWebAudioContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSystemInfoAsync',
    description: '异步获取系统信息。',
    wxStrategy: '直连 `wx.getSystemInfoAsync`',
    alipayStrategy: '映射到 `my.getSystemInfo`',
    douyinStrategy: '映射到 `tt.getSystemInfo`',
    support: '⚠️',
  },
  {
    method: 'openAppAuthorizeSetting',
    description: '打开小程序授权设置页。',
    wxStrategy: '直连 `wx.openAppAuthorizeSetting`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'pluginLogin',
    description: '插件登录。',
    wxStrategy: '直连 `wx.pluginLogin`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'login',
    description: '登录。',
    wxStrategy: '直连 `wx.login`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.login`',
    support: '⚠️',
  },
  {
    method: 'authorize',
    description: '提前向用户发起授权请求。',
    wxStrategy: '直连 `wx.authorize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.authorize`',
    support: '⚠️',
  },
  {
    method: 'checkSession',
    description: '检查登录态是否过期。',
    wxStrategy: '直连 `wx.checkSession`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.checkSession`',
    support: '⚠️',
  },
  {
    method: 'requestSubscribeDeviceMessage',
    description: '请求订阅设备消息。',
    wxStrategy: '直连 `wx.requestSubscribeDeviceMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
