export const tabRoutes = new Set([
  'pages/home/home',
  'pages/category/index',
  'pages/cart/index',
  'pages/usercenter/index',
])

export const navigationTitleMap: Record<string, string> = {
  'pages/home/home': '首页',
  'pages/category/index': '分类',
  'pages/cart/index': '购物车',
  'pages/usercenter/index': '个人中心',
  'pages/user/person-info/index': '个人资料',
  'pages/user/address/list/index': '收货地址',
  'pages/user/address/edit/index': '添加新地址',
  'pages/user/name-edit/index': '昵称',
  'pages/goods/list/index': '商品列表',
  'pages/goods/details/index': '商品详情',
  'pages/goods/search/index': '搜索',
  'pages/goods/result/index': '搜索',
  'pages/goods/comments/index': '全部评价',
  'pages/goods/comments/create/index': '评价商品',
  'pages/order/order-confirm/index': '订单确认',
  'pages/order/receipt/index': '发票',
  'pages/order/pay-result/index': '支付结果',
  'pages/order/order-list/index': '我的订单',
  'pages/order/order-detail/index': '订单详情',
  'pages/order/apply-service/index': '选择售后类型',
  'pages/order/after-service-list/index': '退款/售后',
  'pages/order/after-service-detail/index': '售后详情',
  'pages/order/fill-tracking-no/index': '填写运单号',
  'pages/order/delivery-detail/index': '物流信息',
  'pages/order/invoice/index': '发票详情',
  'pages/coupon/coupon-list/index': '优惠券',
  'pages/coupon/coupon-detail/index': '优惠券详情',
  'pages/coupon/coupon-activity-goods/index': '活动商品',
  'pages/promotion/promotion-detail/index': '营销详情',
}
