export {
  callHookList,
  callHookReturn,
  getCurrentInstance,
  getCurrentSetupContext,
  setCurrentInstance,
  setCurrentSetupContext,
} from './hooks/base'

export {
  onAddToFavorites,
  onAttached,
  onDetached,
  onError,
  onHide,
  onLaunch,
  onLoad,
  onMemoryWarning,
  onMoved,
  onPageNotFound,
  onPageScroll,
  onPullDownRefresh,
  onReachBottom,
  onReady,
  onResize,
  onRouteDone,
  onSaveExitState,
  onShareAppMessage,
  onShareTimeline,
  onShow,
  onTabItemTap,
  onThemeChange,
  onUnhandledRejection,
  onUnload,
} from './hooks/register'

export {
  callUpdateHooks,
  onActivated,
  onBeforeMount,
  onBeforeUnmount,
  onBeforeUpdate,
  onDeactivated,
  onErrorCaptured,
  onMounted,
  onServerPrefetch,
  onUnmounted,
  onUpdated,
} from './hooks/vue'
