packages:
  - apps/*
  - templates/*
  - packages/*
  - '@weapp-core/*'
  - 'extensions/*'
  - website
  - '!**/test/**'

onlyBuiltDependencies:
  - '@swc/core'
  - '@weapp-tailwindcss/merge'
  - oxc-resolver
  - rolldown
  - weapp-tailwindcss

shamefullyHoist: true
