import type { WeapiCrossPlatformMethodDocsShowToastToOpenAppAuthorizeSettingCreateLivePlayerContextToOpenAppAuthorizeSetting } from './createLivePlayerContextToOpenAppAuthorizeSetting'
import type { WeapiCrossPlatformMethodDocsShowToastToOpenAppAuthorizeSettingShowToastToCreateRewardedVideoAd } from './showToastToCreateRewardedVideoAd'

export type WeapiCrossPlatformMethodDocsShowToastToOpenAppAuthorizeSetting
  = WeapiCrossPlatformMethodDocsShowToastToOpenAppAuthorizeSettingShowToastToCreateRewardedVideoAd
    & WeapiCrossPlatformMethodDocsShowToastToOpenAppAuthorizeSettingCreateLivePlayerContextToOpenAppAuthorizeSetting
