import type { WeapiCrossPlatformMethodDocsCanvasGetImageDataToOpenPrivacyContractCanvasGetImageDataToOpenChannelsActivity } from './canvasGetImageDataToOpenChannelsActivity'
import type { WeapiCrossPlatformMethodDocsCanvasGetImageDataToOpenPrivacyContractOpenChannelsEventToOpenPrivacyContract } from './openChannelsEventToOpenPrivacyContract'

export type WeapiCrossPlatformMethodDocsCanvasGetImageDataToOpenPrivacyContract
  = WeapiCrossPlatformMethodDocsCanvasGetImageDataToOpenPrivacyContractCanvasGetImageDataToOpenChannelsActivity
    & WeapiCrossPlatformMethodDocsCanvasGetImageDataToOpenPrivacyContractOpenChannelsEventToOpenPrivacyContract
