import type { WevuNamedRouteMap } from '../router'
import type { WevuAutoRoute } from './types'
import { WEVU_AUTO_ROUTES_MODULE_ID } from '@weapp-core/constants'

export type { WevuAutoRoute } from './types'

export type WevuAutoRoutes<TRouteMap extends object = WevuNamedRouteMap>
  = readonly WevuAutoRoute<TRouteMap>[]

function unavailableOutsideVite(): never {
  throw new Error(`${WEVU_AUTO_ROUTES_MODULE_ID} is generated by weapp-vite and is unavailable outside a weapp-vite build.`)
}

export const routes: WevuAutoRoutes = unavailableOutsideVite()
