import type {
  Alias,
  AliasOptions,
  AutoImportComponents,
  CopyGlobs,
  EnhanceOptions,
  EnhanceWxmlOptions,
  GenerateFileType,
  GenerateOptions,
  GenerateTemplate,
  GenerateTemplateContext,
  GenerateTemplateEntry,
  GenerateTemplateFactory,
  GenerateTemplateFileSource,
  GenerateTemplateInlineSource,
  GenerateTemplatesConfig,
  GenerateTemplateScope,
  HandleWxmlOptions,
  Resolver,
  ScanWxmlOptions,
  SubPackage,
  WeappViteConfig,
  WxmlRemoveAttrRule,
  WxmlRemoveOptions,
} from './types'

export type {
  Alias,
  AliasOptions,
  AutoImportComponents,
  CopyGlobs,
  EnhanceOptions,
  EnhanceWxmlOptions,
  GenerateFileType,
  GenerateOptions,
  GenerateTemplate,
  GenerateTemplateContext,
  GenerateTemplateEntry,
  GenerateTemplateFactory,
  GenerateTemplateFileSource,
  GenerateTemplateInlineSource,
  GenerateTemplatesConfig,
  GenerateTemplateScope,
  HandleWxmlOptions,
  Resolver,
  ScanWxmlOptions,
  SubPackage,
  WeappViteConfig,
  WxmlRemoveAttrRule,
  WxmlRemoveOptions,
}

export type { WxmlAttribute, WxmlAttributeValue, WxmlElementInfo, WxmlSourceLocation, WxmlTransform, WxmlTransformContext, WxmlTransformNode, WxmlTransformResult, WxmlTransformVisitor } from './types/config/wxmlTransform'

export type { WxmlValidate, WxmlValidationContext, WxmlValidationDiagnostic, WxmlValidationVisitor } from './types/config/wxmlValidate'
