import type {
  Alias,
  AliasOptions,
  AutoImportComponents,
  CopyGlobs,
  EnhanceOptions,
  EnhanceWxmlOptions,
  GenerateFileType,
  GenerateOptions,
  GenerateTemplate,
  GenerateTemplateContext,
  GenerateTemplateEntry,
  GenerateTemplateFactory,
  GenerateTemplateFileSource,
  GenerateTemplateInlineSource,
  GenerateTemplatesConfig,
  GenerateTemplateScope,
  HandleWxmlOptions,
  Resolver,
  ScanWxmlOptions,
  SubPackage,
  WeappViteConfig,
} from './types'

export type {
  Alias,
  AliasOptions,
  AutoImportComponents,
  CopyGlobs,
  EnhanceOptions,
  EnhanceWxmlOptions,
  GenerateFileType,
  GenerateOptions,
  GenerateTemplate,
  GenerateTemplateContext,
  GenerateTemplateEntry,
  GenerateTemplateFactory,
  GenerateTemplateFileSource,
  GenerateTemplateInlineSource,
  GenerateTemplatesConfig,
  GenerateTemplateScope,
  HandleWxmlOptions,
  Resolver,
  ScanWxmlOptions,
  SubPackage,
  WeappViteConfig,
}
