// Auto-generated by weapp-vite. Do not edit.
declare module 'weapp-vite/typed-components' {
  export interface ComponentProps {
    HelloWorld: Record<string, any>;
    [component: string]: Record<string, any>;
  }
  export type ComponentPropName = keyof ComponentProps;
  export type ComponentProp<Name extends ComponentPropName> = ComponentProps[Name];
  export const componentProps: ComponentProps;
}
