// Auto-generated by weapp-vite. Do not edit.
declare module 'weapp-vite/auto-routes' {
  export type AutoRoutesPages = readonly [
  "pages/index/index"
];
  export type AutoRoutesEntries = readonly [
  "pages/index/index"
];
  export type AutoRoutesSubPackages = readonly [];
  export type AutoRoutesSubPackage = AutoRoutesSubPackages[number];
  export interface AutoRoutes {
    readonly pages: AutoRoutesPages;
    readonly entries: AutoRoutesEntries;
    readonly subPackages: AutoRoutesSubPackages;
  }
  export const routes: AutoRoutes;
  export const pages: AutoRoutesPages;
  export const entries: AutoRoutesEntries;
  export const subPackages: AutoRoutesSubPackages;
  export default routes;
}
