use std::path::PathBuf;

use oxc_allocator::Allocator;
use oxc_ast::ast::*;
use oxc_ast_visit::{VisitMut, walk_mut};
use oxc_codegen::{Codegen, CodegenOptions};
use oxc_parser::Parser;
use oxc_sourcemap::SourceMap;
use oxc_span::SourceType;

use super::generate;
use crate::script_transform::fragments;

mod boundaries;
mod consumer;
mod identity;

fn parse<'a>(allocator: &'a Allocator, source: &'a str) -> Program<'a> {
    let parsed = Parser::new(allocator, source, SourceType::mjs()).parse();
    assert!(parsed.diagnostics.is_empty(), "{:?}", parsed.diagnostics);
    parsed.program
}

fn options(minify: bool) -> CodegenOptions {
    CodegenOptions {
        minify,
        source_map_path: Some(PathBuf::from("input.js")),
        ..CodegenOptions::default()
    }
}

fn checked<'a>(
    program: &mut Program<'a>,
    allocator: &'a Allocator,
    options: CodegenOptions,
) -> (String, SourceMap<'a>) {
    let snapshot = format!("{program:?}");
    let source = program.source_text;
    let expected = Codegen::new().with_options(options.clone()).build(program);
    let actual = generate(program, allocator, options).unwrap();
    assert_eq!(
        actual.code, expected.code,
        "provenance must preserve every generated byte"
    );
    assert_eq!(
        actual.legal_comments, expected.legal_comments,
        "returned comment coordinates must also be restored"
    );
    assert_eq!(
        format!("{program:?}"),
        snapshot,
        "every AST span, comment and source field must be restored"
    );
    let map = actual.map.unwrap();
    assert_eq!(map.get_source_content(0), Some(source));
    assert_eq!(map.get_sources().collect::<Vec<_>>(), vec!["input.js"]);
    assert!(!map.get_names().any(|name| name.contains('\0')));
    (actual.code, map)
}

fn point(text: &str, needle: &str, within: usize) -> (u32, u32) {
    let byte = text
        .find(needle)
        .unwrap_or_else(|| panic!("missing {needle:?} in {text}"))
        + within;
    let prefix = &text[..byte];
    (
        prefix.bytes().filter(|byte| *byte == b'\n').count() as u32,
        prefix.rsplit('\n').next().unwrap().encode_utf16().count() as u32,
    )
}

fn origin(map: &SourceMap<'_>, point: (u32, u32)) -> Option<(u32, u32)> {
    map.lookup_source_view_token(&map.generate_lookup_table(), point.0, point.1)
        .filter(|token| token.get_source().is_some())
        .map(|token| (token.get_src_line(), token.get_src_col()))
}

fn unmapped(code: &str, map: &SourceMap<'_>, needle: &str, within: usize) {
    assert_eq!(
        origin(map, point(code, needle, within)),
        None,
        "{needle:?}+{within} must not inherit real source"
    );
}

fn real(code: &str, map: &SourceMap<'_>, generated: &str, original: (u32, u32)) {
    assert_eq!(
        origin(map, point(code, generated, 0)),
        Some(original),
        "{generated:?}"
    );
}

fn nested<'a>(allocator: &'a Allocator, source: &'a str, synthetic: &str) -> Program<'a> {
    let mut program = parse(allocator, source);
    let Statement::ExpressionStatement(expression) = program.body.remove(0) else {
        panic!("expected source expression")
    };
    program.body = fragments::statements(synthetic, allocator).unwrap();
    struct Insert<'a> {
        original: Option<Expression<'a>>,
    }
    impl<'a> VisitMut<'a> for Insert<'a> {
        fn visit_expression(&mut self, expression: &mut Expression<'a>) {
            if matches!(expression, Expression::NullLiteral(_))
                && let Some(original) = self.original.take()
            {
                *expression = original;
                return;
            }
            walk_mut::walk_expression(self, expression);
        }
    }
    let mut insert = Insert {
        original: Some(expression.unbox().expression),
    };
    insert.visit_program(&mut program);
    assert!(insert.original.is_none());
    program
}
