import type { WeapiCrossPlatformMethodDocsGetRealtimeLogManagerToCreateUDPSocketGetRealtimeLogManagerToIsBluetoothDevicePaired } from './getRealtimeLogManagerToIsBluetoothDevicePaired'
import type { WeapiCrossPlatformMethodDocsGetRealtimeLogManagerToCreateUDPSocketIsVKSupportToCreateUDPSocket } from './isVKSupportToCreateUDPSocket'

export type WeapiCrossPlatformMethodDocsGetRealtimeLogManagerToCreateUDPSocket
  = WeapiCrossPlatformMethodDocsGetRealtimeLogManagerToCreateUDPSocketGetRealtimeLogManagerToIsBluetoothDevicePaired
    & WeapiCrossPlatformMethodDocsGetRealtimeLogManagerToCreateUDPSocketIsVKSupportToCreateUDPSocket
