export { MINI_PROGRAM_PLATFORM_DESCRIPTORS } from './descriptors'
export {
  getDefaultMiniProgramPlatform,
  getDefaultMiniProgramRuntimeGlobalKey,
  getMiniProgramAppTypesPackage,
  getMiniProgramDefaultBuildTarget,
  getMiniProgramDirectivePrefix,
  getMiniProgramPlatformByRuntimeGlobalKey,
  getMiniProgramPlatformDescriptor,
  getMiniProgramRouteRuntimeGlobalKeys,
  getMiniProgramRuntimeCapabilities,
  getMiniProgramRuntimeGlobalKey,
  getMiniProgramRuntimeGlobalKeys,
  getMiniProgramRuntimeGlobalKeysByResolvePriority,
  getMiniProgramRuntimeHostConfigKey,
  getMiniProgramTemplatePreset,
  getSupportedMiniProgramDirectivePrefixes,
  getSupportedMiniProgramPlatforms,
  MINI_PROGRAM_PLATFORM_ALIASES,
  normalizeMiniProgramPlatform,
  resolveMiniProgramPageKeys,
  resolveMiniProgramPlatform,
  supportsMiniProgramAutoTouchAppStyle,
  supportsMiniProgramRuntimeCapability,
} from './helpers'
export type {
  MiniProgramPageIdentityRule,
  MiniProgramPlatformDescriptor,
  MiniProgramPlatformFamily,
  MiniProgramRuntimeCapabilities,
  MiniProgramRuntimeCapabilityName,
  MiniProgramTemplatePreset,
  MpPlatform,
  OutputExtensions,
} from './types'
