export const DEVTOOLS_E2E_FILES = [
  'app-lifecycle.test.ts',
  'github-issues.test.ts',
  'index.test.ts',
  'lifecycle-compare.test.ts',
  'template-weapp-vite-tailwindcss-tdesign-template.test.ts',
  'template-weapp-vite-tailwindcss-template.test.ts',
  'template-weapp-vite-tailwindcss-vant-template.test.ts',
  'template-weapp-vite-template.test.ts',
  'template-weapp-vite-wevu-tailwindcss-tdesign-template.test.ts',
  'template-weapp-vite-wevu-template.dynamic-bindings.test.ts',
  'template-weapp-vite-wevu-template.test.ts',
  'template-wevu-features-app.test.ts',
  'wevu-features.test.ts',
  'wevu-runtime.class-computed.weapp.test.ts',
  'wevu-runtime.inline-object-reactivity.weapp.test.ts',
  'wevu-runtime.weapp.test.ts',
  'wevu-watch.test.ts',
] as const
