export const vantComponentTags = [
  'van-action-sheet',
  'van-area',
  'van-button',
  'van-calendar',
  'van-card',
  'van-cascader',
  'van-cell',
  'van-cell-group',
  'van-checkbox',
  'van-checkbox-group',
  'van-circle',
  'van-col',
  'van-config-provider',
  'van-count-down',
  'van-datetime-picker',
  'van-dialog',
  'van-divider',
  'van-dropdown-item',
  'van-dropdown-menu',
  'van-empty',
  'van-field',
  'van-goods-action',
  'van-goods-action-button',
  'van-goods-action-icon',
  'van-grid',
  'van-grid-item',
  'van-icon',
  'van-image',
  'van-index-anchor',
  'van-index-bar',
  'van-info',
  'van-loading',
  'van-nav-bar',
  'van-notice-bar',
  'van-notify',
  'van-overlay',
  'van-panel',
  'van-picker',
  'van-picker-column',
  'van-popup',
  'van-progress',
  'van-radio',
  'van-radio-group',
  'van-rate',
  'van-row',
  'van-search',
  'van-share-sheet',
  'van-sidebar',
  'van-sidebar-item',
  'van-skeleton',
  'van-slider',
  'van-stepper',
  'van-steps',
  'van-sticky',
  'van-submit-bar',
  'van-swipe-cell',
  'van-switch',
  'van-tab',
  'van-tabbar',
  'van-tabbar-item',
  'van-tabs',
  'van-tag',
  'van-toast',
  'van-transition',
  'van-tree-select',
  'van-uploader',
] as const

export type VantComponentTag = typeof vantComponentTags[number]

export function toVantComponentName(tag: VantComponentTag) {
  return tag.replace(/^van-/, '')
}

