export function wevuFixture() {
  const apis = [
    ...Array.from({ length: 20 }, (_, index) => ({ categoryKey: 'base', fullName: `wx.base${String(index).padStart(2, '0')}`, docUrl: `/docs/base/${index}` })),
    { categoryKey: 'device', fullName: 'wx.deviceBattery', docUrl: '/docs/battery' },
    { categoryKey: 'device', fullName: 'wx.deviceWifi', docUrl: '/docs/wifi' },
  ]
  const categories = {
    base: { key: 'base', title: '基础', description: '基础能力', order: 1, demoPath: '/pages/api-demos/base/index' },
    device: { key: 'device', title: '设备', description: '设备能力', order: 2, demoPath: '/pages/api-demos/device/index' },
  }
  return { apis: apis.reverse(), categories }
}

export function retailFixture() {
  const specList = [{ specId: 'color', title: '颜色', specValueList: [{ specValueId: 'red', specValue: '红色' }, { specValueId: 'blue', specValue: '蓝色' }] }]
  return {
    detail: {
      spuId: 'goods-semantic',
      title: '语义商品',
      etitle: '完整模块执行',
      available: 1,
      primaryImage: '/images/primary.png',
      images: ['/images/front.png', '/images/back.png'],
      desc: ['/images/description.png'],
      specList,
      limitInfo: [{ text: '限购5件' }],
      minSalePrice: '1250',
      maxSalePrice: '1750',
      maxLinePrice: '1999',
      spuStockQuantity: '7',
      isPutOnSale: 1,
      soldNum: '23',
      skuList: [
        { skuId: 'sku-red', skuImage: '/images/red.png', priceInfo: [{ priceType: 1, price: '1250' }], stockInfo: { stockQuantity: 5 }, specInfo: [{ specId: 'color', specValueId: 'red' }] },
        { skuId: 'sku-blue', skuImage: '', priceInfo: [{ priceType: 1, price: '1750' }], stockInfo: { stockQuantity: 2 }, specInfo: [{ specId: 'color', specValueId: 'blue' }] },
      ],
    },
    activities: Array.from({ length: 5 }, (_, index) => ({ promotionId: `promo-${index}`, promotionSubCode: index === 0 ? 'MYJ' : 'ZK', activityLadder: index === 0 ? [{ label: '满200减20' }] : [] })),
    comments: { homePageComments: [
      { spuId: 'goods-semantic', userName: '甲', commentScore: '5', commentContent: '实测评价', userHeadUrl: '/images/user.png', isAnonymity: false },
      { spuId: '', userName: '', commentScore: 0, commentContent: '', userHeadUrl: '/images/private.png', isAnonymity: true },
    ] },
    statistics: { badCount: '1', commentCount: '2', goodCount: '1', goodRate: '98.76', hasImageCount: '1', middleCount: '0' },
  }
}

export const retailFunctionPaths = [
  'current',
  'autoplay',
  'duration',
  'interval',
  'navigation',
  'detailImages',
  'minSalePrice',
  'maxLinePrice',
  'commentItem.userHeadUrl',
  'commentItem.commentScore',
  'recLeftImg',
  'recRightImg',
  'item',
  'jumpArray',
  'soldout',
  'isStock',
  'cartNum',
  'buttonType',
  'isSpuSelectPopupShow',
  'detailTitle',
  'detailSpecList',
  'skuArray',
  'detailLimitBuyInfo',
  'outOperateStatus',
  'maxSalePrice',
  'list',
  'isShowPromotionPop',
]

export const retailBindingPaths = [
  'detailImages.length',
  'current',
  'autoplay',
  'duration',
  'interval',
  'navigation',
  'detailImages',
  'minSalePrice',
  'maxLinePrice',
  'soldNum',
  'activityList.length',
  'visibleActivityList',
  'visibleActivityList',
  'visibleActivityList',
  'detailTitle',
  'intro',
  '__wv_cls_0',
  'selectedAttrStr',
  'buyNum',
  'selectedAttrStr',
  'commentsStatistics.commentCount',
  'commentsStatistics.commentCount',
  'commentsStatistics.goodRate',
  '__wv_bind_0',
  'commentsList',
  'commentsList',
  'commentsList',
  'commentsList',
  'commentsList',
  'commentsList',
  'detailDesc.length',
  'recLeftImg',
  'recRightImg',
  'detailDesc',
  'detailDesc',
  'jumpArray',
  'soldout',
  'isStock',
  'cartNum',
  'buttonType',
  'isSpuSelectPopupShow',
  'detailTitle',
  'specImg',
  'primaryImage',
  'detailSpecList',
  'skuArray',
  'detailLimitBuyInfo',
  'isStock',
  'outOperateStatus',
  'selectSkuSellsPrice',
  'minSalePrice',
  'selectSkuSellsPrice',
  'minSalePrice',
  'maxSalePrice',
  'isAllSelectedSku',
  'maxSalePrice',
  'list',
  'isShowPromotionPop',
]
