/* eslint-disable */
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by weapp-vite autoImportComponents
import type { ComponentOptionsMixin, DefineComponent, PublicProps } from 'vue'
import type { ComponentProp } from 'weapp-vite/typed-components'

export {}

type WeappComponent<Props = Record<string, any>> = DefineComponent<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, PublicProps, Props, {}>

declare module 'vue' {
  export interface GlobalComponents {
    't-action-sheet': WeappComponent<ComponentProp<"t-action-sheet">> & typeof import("tdesign-miniprogram/miniprogram_dist/action-sheet/action-sheet.js");
    't-avatar': WeappComponent<ComponentProp<"t-avatar">> & typeof import("tdesign-miniprogram/miniprogram_dist/avatar/avatar.js");
    't-avatar-group': WeappComponent<ComponentProp<"t-avatar-group">> & typeof import("tdesign-miniprogram/miniprogram_dist/avatar-group/avatar-group.js");
    't-back-top': WeappComponent<ComponentProp<"t-back-top">> & typeof import("tdesign-miniprogram/miniprogram_dist/back-top/back-top.js");
    't-badge': WeappComponent<ComponentProp<"t-badge">> & typeof import("tdesign-miniprogram/miniprogram_dist/badge/badge.js");
    't-button': WeappComponent<ComponentProp<"t-button">> & typeof import("tdesign-miniprogram/miniprogram_dist/button/button.js");
    't-calendar': WeappComponent<ComponentProp<"t-calendar">> & typeof import("tdesign-miniprogram/miniprogram_dist/calendar/calendar.js");
    't-cascader': WeappComponent<ComponentProp<"t-cascader">> & typeof import("tdesign-miniprogram/miniprogram_dist/cascader/cascader.js");
    't-cell': WeappComponent<ComponentProp<"t-cell">> & typeof import("tdesign-miniprogram/miniprogram_dist/cell/cell.js");
    't-cell-group': WeappComponent<ComponentProp<"t-cell-group">> & typeof import("tdesign-miniprogram/miniprogram_dist/cell-group/cell-group.js");
    't-check-tag': WeappComponent<ComponentProp<"t-check-tag">> & typeof import("tdesign-miniprogram/miniprogram_dist/check-tag/check-tag.js");
    't-checkbox': WeappComponent<ComponentProp<"t-checkbox">> & typeof import("tdesign-miniprogram/miniprogram_dist/checkbox/checkbox.js");
    't-checkbox-group': WeappComponent<ComponentProp<"t-checkbox-group">> & typeof import("tdesign-miniprogram/miniprogram_dist/checkbox-group/checkbox-group.js");
    't-col': WeappComponent<ComponentProp<"t-col">> & typeof import("tdesign-miniprogram/miniprogram_dist/col/col.js");
    't-collapse': WeappComponent<ComponentProp<"t-collapse">> & typeof import("tdesign-miniprogram/miniprogram_dist/collapse/collapse.js");
    't-collapse-panel': WeappComponent<ComponentProp<"t-collapse-panel">> & typeof import("tdesign-miniprogram/miniprogram_dist/collapse-panel/collapse-panel.js");
    't-color-picker': WeappComponent<ComponentProp<"t-color-picker">> & typeof import("tdesign-miniprogram/miniprogram_dist/color-picker/color-picker.js");
    't-count-down': WeappComponent<ComponentProp<"t-count-down">> & typeof import("tdesign-miniprogram/miniprogram_dist/count-down/count-down.js");
    't-date-time-picker': WeappComponent<ComponentProp<"t-date-time-picker">> & typeof import("tdesign-miniprogram/miniprogram_dist/date-time-picker/date-time-picker.js");
    't-dialog': WeappComponent<ComponentProp<"t-dialog">> & typeof import("tdesign-miniprogram/miniprogram_dist/dialog/dialog.js");
    't-divider': WeappComponent<ComponentProp<"t-divider">> & typeof import("tdesign-miniprogram/miniprogram_dist/divider/divider.js");
    't-drawer': WeappComponent<ComponentProp<"t-drawer">> & typeof import("tdesign-miniprogram/miniprogram_dist/drawer/drawer.js");
    't-dropdown-item': WeappComponent<ComponentProp<"t-dropdown-item">> & typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-item/dropdown-item.js");
    't-dropdown-menu': WeappComponent<ComponentProp<"t-dropdown-menu">> & typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-menu/dropdown-menu.js");
    't-empty': WeappComponent<ComponentProp<"t-empty">> & typeof import("tdesign-miniprogram/miniprogram_dist/empty/empty.js");
    't-fab': WeappComponent<ComponentProp<"t-fab">> & typeof import("tdesign-miniprogram/miniprogram_dist/fab/fab.js");
    't-footer': WeappComponent<ComponentProp<"t-footer">> & typeof import("tdesign-miniprogram/miniprogram_dist/footer/footer.js");
    't-form': WeappComponent<ComponentProp<"t-form">>;
    't-form-item': WeappComponent<ComponentProp<"t-form-item">>;
    't-grid': WeappComponent<ComponentProp<"t-grid">> & typeof import("tdesign-miniprogram/miniprogram_dist/grid/grid.js");
    't-grid-item': WeappComponent<ComponentProp<"t-grid-item">> & typeof import("tdesign-miniprogram/miniprogram_dist/grid-item/grid-item.js");
    't-guide': WeappComponent<ComponentProp<"t-guide">> & typeof import("tdesign-miniprogram/miniprogram_dist/guide/guide.js");
    't-icon': WeappComponent<ComponentProp<"t-icon">> & typeof import("tdesign-miniprogram/miniprogram_dist/icon/icon.js");
    't-image': WeappComponent<ComponentProp<"t-image">> & typeof import("tdesign-miniprogram/miniprogram_dist/image/image.js");
    't-image-viewer': WeappComponent<ComponentProp<"t-image-viewer">> & typeof import("tdesign-miniprogram/miniprogram_dist/image-viewer/image-viewer.js");
    't-indexes': WeappComponent<ComponentProp<"t-indexes">> & typeof import("tdesign-miniprogram/miniprogram_dist/indexes/indexes.js");
    't-indexes-anchor': WeappComponent<ComponentProp<"t-indexes-anchor">> & typeof import("tdesign-miniprogram/miniprogram_dist/indexes-anchor/indexes-anchor.js");
    't-input': WeappComponent<ComponentProp<"t-input">> & typeof import("tdesign-miniprogram/miniprogram_dist/input/input.js");
    't-link': WeappComponent<ComponentProp<"t-link">> & typeof import("tdesign-miniprogram/miniprogram_dist/link/link.js");
    't-loading': WeappComponent<ComponentProp<"t-loading">> & typeof import("tdesign-miniprogram/miniprogram_dist/loading/loading.js");
    't-message': WeappComponent<ComponentProp<"t-message">> & typeof import("tdesign-miniprogram/miniprogram_dist/message/message.js");
    't-message-item': WeappComponent<ComponentProp<"t-message-item">> & typeof import("tdesign-miniprogram/miniprogram_dist/message-item/message-item.js");
    't-navbar': WeappComponent<ComponentProp<"t-navbar">> & typeof import("tdesign-miniprogram/miniprogram_dist/navbar/navbar.js");
    't-notice-bar': WeappComponent<ComponentProp<"t-notice-bar">> & typeof import("tdesign-miniprogram/miniprogram_dist/notice-bar/notice-bar.js");
    't-overlay': WeappComponent<ComponentProp<"t-overlay">> & typeof import("tdesign-miniprogram/miniprogram_dist/overlay/overlay.js");
    't-picker': WeappComponent<ComponentProp<"t-picker">> & typeof import("tdesign-miniprogram/miniprogram_dist/picker/picker.js");
    't-picker-item': WeappComponent<ComponentProp<"t-picker-item">> & typeof import("tdesign-miniprogram/miniprogram_dist/picker-item/picker-item.js");
    't-popup': WeappComponent<ComponentProp<"t-popup">> & typeof import("tdesign-miniprogram/miniprogram_dist/popup/popup.js");
    't-progress': WeappComponent<ComponentProp<"t-progress">> & typeof import("tdesign-miniprogram/miniprogram_dist/progress/progress.js");
    't-pull-down-refresh': WeappComponent<ComponentProp<"t-pull-down-refresh">> & typeof import("tdesign-miniprogram/miniprogram_dist/pull-down-refresh/pull-down-refresh.js");
    't-qrcode': WeappComponent<ComponentProp<"t-qrcode">> & typeof import("tdesign-miniprogram/miniprogram_dist/qrcode/qrcode.js");
    't-radio': WeappComponent<ComponentProp<"t-radio">> & typeof import("tdesign-miniprogram/miniprogram_dist/radio/radio.js");
    't-radio-group': WeappComponent<ComponentProp<"t-radio-group">> & typeof import("tdesign-miniprogram/miniprogram_dist/radio-group/radio-group.js");
    't-rate': WeappComponent<ComponentProp<"t-rate">> & typeof import("tdesign-miniprogram/miniprogram_dist/rate/rate.js");
    't-result': WeappComponent<ComponentProp<"t-result">> & typeof import("tdesign-miniprogram/miniprogram_dist/result/result.js");
    't-row': WeappComponent<ComponentProp<"t-row">> & typeof import("tdesign-miniprogram/miniprogram_dist/row/row.js");
    't-scroll-view': WeappComponent<ComponentProp<"t-scroll-view">> & typeof import("tdesign-miniprogram/miniprogram_dist/scroll-view/scroll-view.js");
    't-search': WeappComponent<ComponentProp<"t-search">> & typeof import("tdesign-miniprogram/miniprogram_dist/search/search.js");
    't-side-bar': WeappComponent<ComponentProp<"t-side-bar">> & typeof import("tdesign-miniprogram/miniprogram_dist/side-bar/side-bar.js");
    't-side-bar-item': WeappComponent<ComponentProp<"t-side-bar-item">> & typeof import("tdesign-miniprogram/miniprogram_dist/side-bar-item/side-bar-item.js");
    't-skeleton': WeappComponent<ComponentProp<"t-skeleton">> & typeof import("tdesign-miniprogram/miniprogram_dist/skeleton/skeleton.js");
    't-slider': WeappComponent<ComponentProp<"t-slider">> & typeof import("tdesign-miniprogram/miniprogram_dist/slider/slider.js");
    't-step-item': WeappComponent<ComponentProp<"t-step-item">> & typeof import("tdesign-miniprogram/miniprogram_dist/step-item/step-item.js");
    't-stepper': WeappComponent<ComponentProp<"t-stepper">> & typeof import("tdesign-miniprogram/miniprogram_dist/stepper/stepper.js");
    't-steps': WeappComponent<ComponentProp<"t-steps">> & typeof import("tdesign-miniprogram/miniprogram_dist/steps/steps.js");
    't-sticky': WeappComponent<ComponentProp<"t-sticky">> & typeof import("tdesign-miniprogram/miniprogram_dist/sticky/sticky.js");
    't-swipe-cell': WeappComponent<ComponentProp<"t-swipe-cell">> & typeof import("tdesign-miniprogram/miniprogram_dist/swipe-cell/swipe-cell.js");
    't-swiper': WeappComponent<ComponentProp<"t-swiper">> & typeof import("tdesign-miniprogram/miniprogram_dist/swiper/swiper.js");
    't-swiper-nav': WeappComponent<ComponentProp<"t-swiper-nav">> & typeof import("tdesign-miniprogram/miniprogram_dist/swiper-nav/swiper-nav.js");
    't-switch': WeappComponent<ComponentProp<"t-switch">> & typeof import("tdesign-miniprogram/miniprogram_dist/switch/switch.js");
    't-tab-bar': WeappComponent<ComponentProp<"t-tab-bar">> & typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar/tab-bar.js");
    't-tab-bar-item': WeappComponent<ComponentProp<"t-tab-bar-item">> & typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar-item/tab-bar-item.js");
    't-tab-panel': WeappComponent<ComponentProp<"t-tab-panel">> & typeof import("tdesign-miniprogram/miniprogram_dist/tab-panel/tab-panel.js");
    't-tabs': WeappComponent<ComponentProp<"t-tabs">> & typeof import("tdesign-miniprogram/miniprogram_dist/tabs/tabs.js");
    't-tag': WeappComponent<ComponentProp<"t-tag">> & typeof import("tdesign-miniprogram/miniprogram_dist/tag/tag.js");
    't-textarea': WeappComponent<ComponentProp<"t-textarea">> & typeof import("tdesign-miniprogram/miniprogram_dist/textarea/textarea.js");
    't-toast': WeappComponent<ComponentProp<"t-toast">> & typeof import("tdesign-miniprogram/miniprogram_dist/toast/toast.js");
    't-transition': WeappComponent<ComponentProp<"t-transition">> & typeof import("tdesign-miniprogram/miniprogram_dist/transition/transition.js");
    't-tree-select': WeappComponent<ComponentProp<"t-tree-select">> & typeof import("tdesign-miniprogram/miniprogram_dist/tree-select/tree-select.js");
    't-upload': WeappComponent<ComponentProp<"t-upload">> & typeof import("tdesign-miniprogram/miniprogram_dist/upload/upload.js");
    't-watermark': WeappComponent<ComponentProp<"t-watermark">> & typeof import("tdesign-miniprogram/miniprogram_dist/watermark/watermark.js");
    'van-action-sheet': WeappComponent<ComponentProp<"van-action-sheet">> & typeof import("@vant/weapp/lib/action-sheet/index.js");
    'van-area': WeappComponent<ComponentProp<"van-area">> & typeof import("@vant/weapp/lib/area/index.js");
    'van-button': WeappComponent<ComponentProp<"van-button">> & typeof import("@vant/weapp/lib/button/index.js");
    'van-calendar': WeappComponent<ComponentProp<"van-calendar">> & typeof import("@vant/weapp/lib/calendar/index.js");
    'van-card': WeappComponent<ComponentProp<"van-card">> & typeof import("@vant/weapp/lib/card/index.js");
    'van-cascader': WeappComponent<ComponentProp<"van-cascader">> & typeof import("@vant/weapp/lib/cascader/index.js");
    'van-cell': WeappComponent<ComponentProp<"van-cell">> & typeof import("@vant/weapp/lib/cell/index.js");
    'van-cell-group': WeappComponent<ComponentProp<"van-cell-group">> & typeof import("@vant/weapp/lib/cell-group/index.js");
    'van-checkbox': WeappComponent<ComponentProp<"van-checkbox">> & typeof import("@vant/weapp/lib/checkbox/index.js");
    'van-checkbox-group': WeappComponent<ComponentProp<"van-checkbox-group">> & typeof import("@vant/weapp/lib/checkbox-group/index.js");
    'van-circle': WeappComponent<ComponentProp<"van-circle">> & typeof import("@vant/weapp/lib/circle/index.js");
    'van-col': WeappComponent<ComponentProp<"van-col">> & typeof import("@vant/weapp/lib/col/index.js");
    'van-collapse': WeappComponent<ComponentProp<"van-collapse">> & typeof import("@vant/weapp/lib/collapse/index.js");
    'van-collapse-item': WeappComponent<ComponentProp<"van-collapse-item">> & typeof import("@vant/weapp/lib/collapse-item/index.js");
    'van-config-provider': WeappComponent<ComponentProp<"van-config-provider">> & typeof import("@vant/weapp/lib/config-provider/index.js");
    'van-count-down': WeappComponent<ComponentProp<"van-count-down">> & typeof import("@vant/weapp/lib/count-down/index.js");
    'van-datetime-picker': WeappComponent<ComponentProp<"van-datetime-picker">> & typeof import("@vant/weapp/lib/datetime-picker/index.js");
    'van-definitions': WeappComponent<ComponentProp<"van-definitions">> & typeof import("@vant/weapp/lib/definitions/index.js");
    'van-dialog': WeappComponent<ComponentProp<"van-dialog">> & typeof import("@vant/weapp/lib/dialog/index.js");
    'van-divider': WeappComponent<ComponentProp<"van-divider">> & typeof import("@vant/weapp/lib/divider/index.js");
    'van-dropdown-item': WeappComponent<ComponentProp<"van-dropdown-item">> & typeof import("@vant/weapp/lib/dropdown-item/index.js");
    'van-dropdown-menu': WeappComponent<ComponentProp<"van-dropdown-menu">> & typeof import("@vant/weapp/lib/dropdown-menu/index.js");
    'van-empty': WeappComponent<ComponentProp<"van-empty">> & typeof import("@vant/weapp/lib/empty/index.js");
    'van-field': WeappComponent<ComponentProp<"van-field">> & typeof import("@vant/weapp/lib/field/index.js");
    'van-goods-action': WeappComponent<ComponentProp<"van-goods-action">> & typeof import("@vant/weapp/lib/goods-action/index.js");
    'van-goods-action-button': WeappComponent<ComponentProp<"van-goods-action-button">> & typeof import("@vant/weapp/lib/goods-action-button/index.js");
    'van-goods-action-icon': WeappComponent<ComponentProp<"van-goods-action-icon">> & typeof import("@vant/weapp/lib/goods-action-icon/index.js");
    'van-grid': WeappComponent<ComponentProp<"van-grid">> & typeof import("@vant/weapp/lib/grid/index.js");
    'van-grid-item': WeappComponent<ComponentProp<"van-grid-item">> & typeof import("@vant/weapp/lib/grid-item/index.js");
    'van-icon': WeappComponent<ComponentProp<"van-icon">> & typeof import("@vant/weapp/lib/icon/index.js");
    'van-image': WeappComponent<ComponentProp<"van-image">> & typeof import("@vant/weapp/lib/image/index.js");
    'van-index-anchor': WeappComponent<ComponentProp<"van-index-anchor">> & typeof import("@vant/weapp/lib/index-anchor/index.js");
    'van-index-bar': WeappComponent<ComponentProp<"van-index-bar">> & typeof import("@vant/weapp/lib/index-bar/index.js");
    'van-info': WeappComponent<ComponentProp<"van-info">> & typeof import("@vant/weapp/lib/info/index.js");
    'van-loading': WeappComponent<ComponentProp<"van-loading">> & typeof import("@vant/weapp/lib/loading/index.js");
    'van-nav-bar': WeappComponent<ComponentProp<"van-nav-bar">> & typeof import("@vant/weapp/lib/nav-bar/index.js");
    'van-notice-bar': WeappComponent<ComponentProp<"van-notice-bar">> & typeof import("@vant/weapp/lib/notice-bar/index.js");
    'van-notify': WeappComponent<ComponentProp<"van-notify">> & typeof import("@vant/weapp/lib/notify/index.js");
    'van-overlay': WeappComponent<ComponentProp<"van-overlay">> & typeof import("@vant/weapp/lib/overlay/index.js");
    'van-panel': WeappComponent<ComponentProp<"van-panel">> & typeof import("@vant/weapp/lib/panel/index.js");
    'van-picker': WeappComponent<ComponentProp<"van-picker">> & typeof import("@vant/weapp/lib/picker/index.js");
    'van-picker-column': WeappComponent<ComponentProp<"van-picker-column">> & typeof import("@vant/weapp/lib/picker-column/index.js");
    'van-popup': WeappComponent<ComponentProp<"van-popup">> & typeof import("@vant/weapp/lib/popup/index.js");
    'van-progress': WeappComponent<ComponentProp<"van-progress">> & typeof import("@vant/weapp/lib/progress/index.js");
    'van-radio': WeappComponent<ComponentProp<"van-radio">> & typeof import("@vant/weapp/lib/radio/index.js");
    'van-radio-group': WeappComponent<ComponentProp<"van-radio-group">> & typeof import("@vant/weapp/lib/radio-group/index.js");
    'van-rate': WeappComponent<ComponentProp<"van-rate">> & typeof import("@vant/weapp/lib/rate/index.js");
    'van-row': WeappComponent<ComponentProp<"van-row">> & typeof import("@vant/weapp/lib/row/index.js");
    'van-search': WeappComponent<ComponentProp<"van-search">> & typeof import("@vant/weapp/lib/search/index.js");
    'van-share-sheet': WeappComponent<ComponentProp<"van-share-sheet">> & typeof import("@vant/weapp/lib/share-sheet/index.js");
    'van-sidebar': WeappComponent<ComponentProp<"van-sidebar">> & typeof import("@vant/weapp/lib/sidebar/index.js");
    'van-sidebar-item': WeappComponent<ComponentProp<"van-sidebar-item">> & typeof import("@vant/weapp/lib/sidebar-item/index.js");
    'van-skeleton': WeappComponent<ComponentProp<"van-skeleton">> & typeof import("@vant/weapp/lib/skeleton/index.js");
    'van-slider': WeappComponent<ComponentProp<"van-slider">> & typeof import("@vant/weapp/lib/slider/index.js");
    'van-stepper': WeappComponent<ComponentProp<"van-stepper">> & typeof import("@vant/weapp/lib/stepper/index.js");
    'van-steps': WeappComponent<ComponentProp<"van-steps">> & typeof import("@vant/weapp/lib/steps/index.js");
    'van-sticky': WeappComponent<ComponentProp<"van-sticky">> & typeof import("@vant/weapp/lib/sticky/index.js");
    'van-submit-bar': WeappComponent<ComponentProp<"van-submit-bar">> & typeof import("@vant/weapp/lib/submit-bar/index.js");
    'van-swipe-cell': WeappComponent<ComponentProp<"van-swipe-cell">> & typeof import("@vant/weapp/lib/swipe-cell/index.js");
    'van-switch': WeappComponent<ComponentProp<"van-switch">> & typeof import("@vant/weapp/lib/switch/index.js");
    'van-tab': WeappComponent<ComponentProp<"van-tab">> & typeof import("@vant/weapp/lib/tab/index.js");
    'van-tabbar': WeappComponent<ComponentProp<"van-tabbar">> & typeof import("@vant/weapp/lib/tabbar/index.js");
    'van-tabbar-item': WeappComponent<ComponentProp<"van-tabbar-item">> & typeof import("@vant/weapp/lib/tabbar-item/index.js");
    'van-tabs': WeappComponent<ComponentProp<"van-tabs">> & typeof import("@vant/weapp/lib/tabs/index.js");
    'van-tag': WeappComponent<ComponentProp<"van-tag">> & typeof import("@vant/weapp/lib/tag/index.js");
    'van-toast': WeappComponent<ComponentProp<"van-toast">> & typeof import("@vant/weapp/lib/toast/index.js");
    'van-transition': WeappComponent<ComponentProp<"van-transition">> & typeof import("@vant/weapp/lib/transition/index.js");
    'van-tree-select': WeappComponent<ComponentProp<"van-tree-select">> & typeof import("@vant/weapp/lib/tree-select/index.js");
    'van-uploader': WeappComponent<ComponentProp<"van-uploader">> & typeof import("@vant/weapp/lib/uploader/index.js");
    [component: string]: WeappComponent;
  }
}

// For TSX support
declare global {
}
