/* eslint-disable */
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by weapp-vite autoImportComponents
import type { ComponentOptionsMixin, DefineComponent, PublicProps } from 'vue'
import type { ComponentProp } from 'weapp-vite/typed-components'

export {}

type WeappComponent<Props = Record<string, any>> = DefineComponent<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, PublicProps, Props, {}>

declare module 'vue' {
  export interface GlobalComponents {
    't-action-sheet': WeappComponent<ComponentProp<"t-action-sheet">>;
    't-avatar': WeappComponent<ComponentProp<"t-avatar">>;
    't-avatar-group': WeappComponent<ComponentProp<"t-avatar-group">>;
    't-back-top': WeappComponent<ComponentProp<"t-back-top">>;
    't-badge': WeappComponent<ComponentProp<"t-badge">>;
    't-button': WeappComponent<ComponentProp<"t-button">>;
    't-calendar': WeappComponent<ComponentProp<"t-calendar">>;
    't-cascader': WeappComponent<ComponentProp<"t-cascader">>;
    't-cell': WeappComponent<ComponentProp<"t-cell">>;
    't-cell-group': WeappComponent<ComponentProp<"t-cell-group">>;
    't-check-tag': WeappComponent<ComponentProp<"t-check-tag">>;
    't-checkbox': WeappComponent<ComponentProp<"t-checkbox">>;
    't-checkbox-group': WeappComponent<ComponentProp<"t-checkbox-group">>;
    't-col': WeappComponent<ComponentProp<"t-col">>;
    't-collapse': WeappComponent<ComponentProp<"t-collapse">>;
    't-collapse-panel': WeappComponent<ComponentProp<"t-collapse-panel">>;
    't-color-picker': WeappComponent<ComponentProp<"t-color-picker">>;
    't-count-down': WeappComponent<ComponentProp<"t-count-down">>;
    't-date-time-picker': WeappComponent<ComponentProp<"t-date-time-picker">>;
    't-dialog': WeappComponent<ComponentProp<"t-dialog">>;
    't-divider': WeappComponent<ComponentProp<"t-divider">>;
    't-drawer': WeappComponent<ComponentProp<"t-drawer">>;
    't-dropdown-item': WeappComponent<ComponentProp<"t-dropdown-item">>;
    't-dropdown-menu': WeappComponent<ComponentProp<"t-dropdown-menu">>;
    't-empty': WeappComponent<ComponentProp<"t-empty">>;
    't-fab': WeappComponent<ComponentProp<"t-fab">>;
    't-footer': WeappComponent<ComponentProp<"t-footer">>;
    't-form': WeappComponent<ComponentProp<"t-form">>;
    't-form-item': WeappComponent<ComponentProp<"t-form-item">>;
    't-grid': WeappComponent<ComponentProp<"t-grid">>;
    't-grid-item': WeappComponent<ComponentProp<"t-grid-item">>;
    't-guide': WeappComponent<ComponentProp<"t-guide">>;
    't-icon': WeappComponent<ComponentProp<"t-icon">>;
    't-image': WeappComponent<ComponentProp<"t-image">>;
    't-image-viewer': WeappComponent<ComponentProp<"t-image-viewer">>;
    't-indexes': WeappComponent<ComponentProp<"t-indexes">>;
    't-indexes-anchor': WeappComponent<ComponentProp<"t-indexes-anchor">>;
    't-input': WeappComponent<ComponentProp<"t-input">>;
    't-link': WeappComponent<ComponentProp<"t-link">>;
    't-loading': WeappComponent<ComponentProp<"t-loading">>;
    't-message': WeappComponent<ComponentProp<"t-message">>;
    't-message-item': WeappComponent<ComponentProp<"t-message-item">>;
    't-navbar': WeappComponent<ComponentProp<"t-navbar">>;
    't-notice-bar': WeappComponent<ComponentProp<"t-notice-bar">>;
    't-overlay': WeappComponent<ComponentProp<"t-overlay">>;
    't-picker': WeappComponent<ComponentProp<"t-picker">>;
    't-picker-item': WeappComponent<ComponentProp<"t-picker-item">>;
    't-popup': WeappComponent<ComponentProp<"t-popup">>;
    't-progress': WeappComponent<ComponentProp<"t-progress">>;
    't-pull-down-refresh': WeappComponent<ComponentProp<"t-pull-down-refresh">>;
    't-qrcode': WeappComponent<ComponentProp<"t-qrcode">>;
    't-radio': WeappComponent<ComponentProp<"t-radio">>;
    't-radio-group': WeappComponent<ComponentProp<"t-radio-group">>;
    't-rate': WeappComponent<ComponentProp<"t-rate">>;
    't-result': WeappComponent<ComponentProp<"t-result">>;
    't-row': WeappComponent<ComponentProp<"t-row">>;
    't-scroll-view': WeappComponent<ComponentProp<"t-scroll-view">>;
    't-search': WeappComponent<ComponentProp<"t-search">>;
    't-side-bar': WeappComponent<ComponentProp<"t-side-bar">>;
    't-side-bar-item': WeappComponent<ComponentProp<"t-side-bar-item">>;
    't-skeleton': WeappComponent<ComponentProp<"t-skeleton">>;
    't-slider': WeappComponent<ComponentProp<"t-slider">>;
    't-step-item': WeappComponent<ComponentProp<"t-step-item">>;
    't-stepper': WeappComponent<ComponentProp<"t-stepper">>;
    't-steps': WeappComponent<ComponentProp<"t-steps">>;
    't-sticky': WeappComponent<ComponentProp<"t-sticky">>;
    't-swipe-cell': WeappComponent<ComponentProp<"t-swipe-cell">>;
    't-swiper': WeappComponent<ComponentProp<"t-swiper">>;
    't-swiper-nav': WeappComponent<ComponentProp<"t-swiper-nav">>;
    't-switch': WeappComponent<ComponentProp<"t-switch">>;
    't-tab-bar': WeappComponent<ComponentProp<"t-tab-bar">>;
    't-tab-bar-item': WeappComponent<ComponentProp<"t-tab-bar-item">>;
    't-tab-panel': WeappComponent<ComponentProp<"t-tab-panel">>;
    't-tabs': WeappComponent<ComponentProp<"t-tabs">>;
    't-tag': WeappComponent<ComponentProp<"t-tag">>;
    't-textarea': WeappComponent<ComponentProp<"t-textarea">>;
    't-toast': WeappComponent<ComponentProp<"t-toast">>;
    't-transition': WeappComponent<ComponentProp<"t-transition">>;
    't-tree-select': WeappComponent<ComponentProp<"t-tree-select">>;
    't-upload': WeappComponent<ComponentProp<"t-upload">>;
    't-watermark': WeappComponent<ComponentProp<"t-watermark">>;
    'van-action-sheet': WeappComponent<ComponentProp<"van-action-sheet">>;
    'van-area': WeappComponent<ComponentProp<"van-area">>;
    'van-button': WeappComponent<ComponentProp<"van-button">>;
    'van-calendar': WeappComponent<ComponentProp<"van-calendar">>;
    'van-card': WeappComponent<ComponentProp<"van-card">>;
    'van-cascader': WeappComponent<ComponentProp<"van-cascader">>;
    'van-cell': WeappComponent<ComponentProp<"van-cell">>;
    'van-cell-group': WeappComponent<ComponentProp<"van-cell-group">>;
    'van-checkbox': WeappComponent<ComponentProp<"van-checkbox">>;
    'van-checkbox-group': WeappComponent<ComponentProp<"van-checkbox-group">>;
    'van-circle': WeappComponent<ComponentProp<"van-circle">>;
    'van-col': WeappComponent<ComponentProp<"van-col">>;
    'van-collapse': WeappComponent<ComponentProp<"van-collapse">>;
    'van-collapse-item': WeappComponent<ComponentProp<"van-collapse-item">>;
    'van-config-provider': WeappComponent<ComponentProp<"van-config-provider">>;
    'van-count-down': WeappComponent<ComponentProp<"van-count-down">>;
    'van-datetime-picker': WeappComponent<ComponentProp<"van-datetime-picker">>;
    'van-definitions': WeappComponent<ComponentProp<"van-definitions">>;
    'van-dialog': WeappComponent<ComponentProp<"van-dialog">>;
    'van-divider': WeappComponent<ComponentProp<"van-divider">>;
    'van-dropdown-item': WeappComponent<ComponentProp<"van-dropdown-item">>;
    'van-dropdown-menu': WeappComponent<ComponentProp<"van-dropdown-menu">>;
    'van-empty': WeappComponent<ComponentProp<"van-empty">>;
    'van-field': WeappComponent<ComponentProp<"van-field">>;
    'van-goods-action': WeappComponent<ComponentProp<"van-goods-action">>;
    'van-goods-action-button': WeappComponent<ComponentProp<"van-goods-action-button">>;
    'van-goods-action-icon': WeappComponent<ComponentProp<"van-goods-action-icon">>;
    'van-grid': WeappComponent<ComponentProp<"van-grid">>;
    'van-grid-item': WeappComponent<ComponentProp<"van-grid-item">>;
    'van-icon': WeappComponent<ComponentProp<"van-icon">>;
    'van-image': WeappComponent<ComponentProp<"van-image">>;
    'van-index-anchor': WeappComponent<ComponentProp<"van-index-anchor">>;
    'van-index-bar': WeappComponent<ComponentProp<"van-index-bar">>;
    'van-info': WeappComponent<ComponentProp<"van-info">>;
    'van-loading': WeappComponent<ComponentProp<"van-loading">>;
    'van-nav-bar': WeappComponent<ComponentProp<"van-nav-bar">>;
    'van-notice-bar': WeappComponent<ComponentProp<"van-notice-bar">>;
    'van-notify': WeappComponent<ComponentProp<"van-notify">>;
    'van-overlay': WeappComponent<ComponentProp<"van-overlay">>;
    'van-panel': WeappComponent<ComponentProp<"van-panel">>;
    'van-picker': WeappComponent<ComponentProp<"van-picker">>;
    'van-picker-column': WeappComponent<ComponentProp<"van-picker-column">>;
    'van-popup': WeappComponent<ComponentProp<"van-popup">>;
    'van-progress': WeappComponent<ComponentProp<"van-progress">>;
    'van-radio': WeappComponent<ComponentProp<"van-radio">>;
    'van-radio-group': WeappComponent<ComponentProp<"van-radio-group">>;
    'van-rate': WeappComponent<ComponentProp<"van-rate">>;
    'van-row': WeappComponent<ComponentProp<"van-row">>;
    'van-search': WeappComponent<ComponentProp<"van-search">>;
    'van-share-sheet': WeappComponent<ComponentProp<"van-share-sheet">>;
    'van-sidebar': WeappComponent<ComponentProp<"van-sidebar">>;
    'van-sidebar-item': WeappComponent<ComponentProp<"van-sidebar-item">>;
    'van-skeleton': WeappComponent<ComponentProp<"van-skeleton">>;
    'van-slider': WeappComponent<ComponentProp<"van-slider">>;
    'van-stepper': WeappComponent<ComponentProp<"van-stepper">>;
    'van-steps': WeappComponent<ComponentProp<"van-steps">>;
    'van-sticky': WeappComponent<ComponentProp<"van-sticky">>;
    'van-submit-bar': WeappComponent<ComponentProp<"van-submit-bar">>;
    'van-swipe-cell': WeappComponent<ComponentProp<"van-swipe-cell">>;
    'van-switch': WeappComponent<ComponentProp<"van-switch">>;
    'van-tab': WeappComponent<ComponentProp<"van-tab">>;
    'van-tabbar': WeappComponent<ComponentProp<"van-tabbar">>;
    'van-tabbar-item': WeappComponent<ComponentProp<"van-tabbar-item">>;
    'van-tabs': WeappComponent<ComponentProp<"van-tabs">>;
    'van-tag': WeappComponent<ComponentProp<"van-tag">>;
    'van-toast': WeappComponent<ComponentProp<"van-toast">>;
    'van-transition': WeappComponent<ComponentProp<"van-transition">>;
    'van-tree-select': WeappComponent<ComponentProp<"van-tree-select">>;
    'van-uploader': WeappComponent<ComponentProp<"van-uploader">>;
    [component: string]: WeappComponent;
  }
}

// For TSX support
declare global {
}
