/* eslint-disable */
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by weapp-vite autoImportComponents
import type { ComponentOptionsMixin, DefineComponent, PublicProps } from 'wevu'
import type { ComponentProp } from 'weapp-vite/typed-components'

export {}

type WeappComponent<Props = Record<string, any>> = new (...args: any[]) => InstanceType<DefineComponent<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, PublicProps, Props, {}>>

declare module 'vue' {
  export interface GlobalComponents {
    TActionSheet: typeof import("tdesign-miniprogram/miniprogram_dist/action-sheet/action-sheet.js") & WeappComponent<ComponentProp<"t-action-sheet">>;
    't-action-sheet': typeof import("tdesign-miniprogram/miniprogram_dist/action-sheet/action-sheet.js") & WeappComponent<ComponentProp<"t-action-sheet">>;
    TAvatar: typeof import("tdesign-miniprogram/miniprogram_dist/avatar/avatar.js") & WeappComponent<ComponentProp<"t-avatar">>;
    't-avatar': typeof import("tdesign-miniprogram/miniprogram_dist/avatar/avatar.js") & WeappComponent<ComponentProp<"t-avatar">>;
    TAvatarGroup: typeof import("tdesign-miniprogram/miniprogram_dist/avatar-group/avatar-group.js") & WeappComponent<ComponentProp<"t-avatar-group">>;
    't-avatar-group': typeof import("tdesign-miniprogram/miniprogram_dist/avatar-group/avatar-group.js") & WeappComponent<ComponentProp<"t-avatar-group">>;
    TBackTop: typeof import("tdesign-miniprogram/miniprogram_dist/back-top/back-top.js") & WeappComponent<ComponentProp<"t-back-top">>;
    't-back-top': typeof import("tdesign-miniprogram/miniprogram_dist/back-top/back-top.js") & WeappComponent<ComponentProp<"t-back-top">>;
    TBadge: typeof import("tdesign-miniprogram/miniprogram_dist/badge/badge.js") & WeappComponent<ComponentProp<"t-badge">>;
    't-badge': typeof import("tdesign-miniprogram/miniprogram_dist/badge/badge.js") & WeappComponent<ComponentProp<"t-badge">>;
    TButton: typeof import("tdesign-miniprogram/miniprogram_dist/button/button.js") & WeappComponent<ComponentProp<"t-button">>;
    't-button': typeof import("tdesign-miniprogram/miniprogram_dist/button/button.js") & WeappComponent<ComponentProp<"t-button">>;
    TCalendar: typeof import("tdesign-miniprogram/miniprogram_dist/calendar/calendar.js") & WeappComponent<ComponentProp<"t-calendar">>;
    't-calendar': typeof import("tdesign-miniprogram/miniprogram_dist/calendar/calendar.js") & WeappComponent<ComponentProp<"t-calendar">>;
    TCascader: typeof import("tdesign-miniprogram/miniprogram_dist/cascader/cascader.js") & WeappComponent<ComponentProp<"t-cascader">>;
    't-cascader': typeof import("tdesign-miniprogram/miniprogram_dist/cascader/cascader.js") & WeappComponent<ComponentProp<"t-cascader">>;
    TCell: typeof import("tdesign-miniprogram/miniprogram_dist/cell/cell.js") & WeappComponent<ComponentProp<"t-cell">>;
    't-cell': typeof import("tdesign-miniprogram/miniprogram_dist/cell/cell.js") & WeappComponent<ComponentProp<"t-cell">>;
    TCellGroup: typeof import("tdesign-miniprogram/miniprogram_dist/cell-group/cell-group.js") & WeappComponent<ComponentProp<"t-cell-group">>;
    't-cell-group': typeof import("tdesign-miniprogram/miniprogram_dist/cell-group/cell-group.js") & WeappComponent<ComponentProp<"t-cell-group">>;
    TCheckTag: typeof import("tdesign-miniprogram/miniprogram_dist/check-tag/check-tag.js") & WeappComponent<ComponentProp<"t-check-tag">>;
    't-check-tag': typeof import("tdesign-miniprogram/miniprogram_dist/check-tag/check-tag.js") & WeappComponent<ComponentProp<"t-check-tag">>;
    TCheckbox: typeof import("tdesign-miniprogram/miniprogram_dist/checkbox/checkbox.js") & WeappComponent<ComponentProp<"t-checkbox">>;
    't-checkbox': typeof import("tdesign-miniprogram/miniprogram_dist/checkbox/checkbox.js") & WeappComponent<ComponentProp<"t-checkbox">>;
    TCheckboxGroup: typeof import("tdesign-miniprogram/miniprogram_dist/checkbox-group/checkbox-group.js") & WeappComponent<ComponentProp<"t-checkbox-group">>;
    't-checkbox-group': typeof import("tdesign-miniprogram/miniprogram_dist/checkbox-group/checkbox-group.js") & WeappComponent<ComponentProp<"t-checkbox-group">>;
    TCol: typeof import("tdesign-miniprogram/miniprogram_dist/col/col.js") & WeappComponent<ComponentProp<"t-col">>;
    't-col': typeof import("tdesign-miniprogram/miniprogram_dist/col/col.js") & WeappComponent<ComponentProp<"t-col">>;
    TCollapse: typeof import("tdesign-miniprogram/miniprogram_dist/collapse/collapse.js") & WeappComponent<ComponentProp<"t-collapse">>;
    't-collapse': typeof import("tdesign-miniprogram/miniprogram_dist/collapse/collapse.js") & WeappComponent<ComponentProp<"t-collapse">>;
    TCollapsePanel: typeof import("tdesign-miniprogram/miniprogram_dist/collapse-panel/collapse-panel.js") & WeappComponent<ComponentProp<"t-collapse-panel">>;
    't-collapse-panel': typeof import("tdesign-miniprogram/miniprogram_dist/collapse-panel/collapse-panel.js") & WeappComponent<ComponentProp<"t-collapse-panel">>;
    TColorPicker: typeof import("tdesign-miniprogram/miniprogram_dist/color-picker/color-picker.js") & WeappComponent<ComponentProp<"t-color-picker">>;
    't-color-picker': typeof import("tdesign-miniprogram/miniprogram_dist/color-picker/color-picker.js") & WeappComponent<ComponentProp<"t-color-picker">>;
    TCountDown: typeof import("tdesign-miniprogram/miniprogram_dist/count-down/count-down.js") & WeappComponent<ComponentProp<"t-count-down">>;
    't-count-down': typeof import("tdesign-miniprogram/miniprogram_dist/count-down/count-down.js") & WeappComponent<ComponentProp<"t-count-down">>;
    TDateTimePicker: typeof import("tdesign-miniprogram/miniprogram_dist/date-time-picker/date-time-picker.js") & WeappComponent<ComponentProp<"t-date-time-picker">>;
    't-date-time-picker': typeof import("tdesign-miniprogram/miniprogram_dist/date-time-picker/date-time-picker.js") & WeappComponent<ComponentProp<"t-date-time-picker">>;
    TDialog: typeof import("tdesign-miniprogram/miniprogram_dist/dialog/dialog.js") & WeappComponent<ComponentProp<"t-dialog">>;
    't-dialog': typeof import("tdesign-miniprogram/miniprogram_dist/dialog/dialog.js") & WeappComponent<ComponentProp<"t-dialog">>;
    TDivider: typeof import("tdesign-miniprogram/miniprogram_dist/divider/divider.js") & WeappComponent<ComponentProp<"t-divider">>;
    't-divider': typeof import("tdesign-miniprogram/miniprogram_dist/divider/divider.js") & WeappComponent<ComponentProp<"t-divider">>;
    TDrawer: typeof import("tdesign-miniprogram/miniprogram_dist/drawer/drawer.js") & WeappComponent<ComponentProp<"t-drawer">>;
    't-drawer': typeof import("tdesign-miniprogram/miniprogram_dist/drawer/drawer.js") & WeappComponent<ComponentProp<"t-drawer">>;
    TDropdownItem: typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-item/dropdown-item.js") & WeappComponent<ComponentProp<"t-dropdown-item">>;
    't-dropdown-item': typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-item/dropdown-item.js") & WeappComponent<ComponentProp<"t-dropdown-item">>;
    TDropdownMenu: typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-menu/dropdown-menu.js") & WeappComponent<ComponentProp<"t-dropdown-menu">>;
    't-dropdown-menu': typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-menu/dropdown-menu.js") & WeappComponent<ComponentProp<"t-dropdown-menu">>;
    TEmpty: typeof import("tdesign-miniprogram/miniprogram_dist/empty/empty.js") & WeappComponent<ComponentProp<"t-empty">>;
    't-empty': typeof import("tdesign-miniprogram/miniprogram_dist/empty/empty.js") & WeappComponent<ComponentProp<"t-empty">>;
    TFab: typeof import("tdesign-miniprogram/miniprogram_dist/fab/fab.js") & WeappComponent<ComponentProp<"t-fab">>;
    't-fab': typeof import("tdesign-miniprogram/miniprogram_dist/fab/fab.js") & WeappComponent<ComponentProp<"t-fab">>;
    TFooter: typeof import("tdesign-miniprogram/miniprogram_dist/footer/footer.js") & WeappComponent<ComponentProp<"t-footer">>;
    't-footer': typeof import("tdesign-miniprogram/miniprogram_dist/footer/footer.js") & WeappComponent<ComponentProp<"t-footer">>;
    TForm: WeappComponent<ComponentProp<"t-form">>;
    't-form': WeappComponent<ComponentProp<"t-form">>;
    TFormItem: WeappComponent<ComponentProp<"t-form-item">>;
    't-form-item': WeappComponent<ComponentProp<"t-form-item">>;
    TGrid: typeof import("tdesign-miniprogram/miniprogram_dist/grid/grid.js") & WeappComponent<ComponentProp<"t-grid">>;
    't-grid': typeof import("tdesign-miniprogram/miniprogram_dist/grid/grid.js") & WeappComponent<ComponentProp<"t-grid">>;
    TGridItem: typeof import("tdesign-miniprogram/miniprogram_dist/grid-item/grid-item.js") & WeappComponent<ComponentProp<"t-grid-item">>;
    't-grid-item': typeof import("tdesign-miniprogram/miniprogram_dist/grid-item/grid-item.js") & WeappComponent<ComponentProp<"t-grid-item">>;
    TGuide: typeof import("tdesign-miniprogram/miniprogram_dist/guide/guide.js") & WeappComponent<ComponentProp<"t-guide">>;
    't-guide': typeof import("tdesign-miniprogram/miniprogram_dist/guide/guide.js") & WeappComponent<ComponentProp<"t-guide">>;
    TIcon: typeof import("tdesign-miniprogram/miniprogram_dist/icon/icon.js") & WeappComponent<ComponentProp<"t-icon">>;
    't-icon': typeof import("tdesign-miniprogram/miniprogram_dist/icon/icon.js") & WeappComponent<ComponentProp<"t-icon">>;
    TImage: typeof import("tdesign-miniprogram/miniprogram_dist/image/image.js") & WeappComponent<ComponentProp<"t-image">>;
    't-image': typeof import("tdesign-miniprogram/miniprogram_dist/image/image.js") & WeappComponent<ComponentProp<"t-image">>;
    TImageViewer: typeof import("tdesign-miniprogram/miniprogram_dist/image-viewer/image-viewer.js") & WeappComponent<ComponentProp<"t-image-viewer">>;
    't-image-viewer': typeof import("tdesign-miniprogram/miniprogram_dist/image-viewer/image-viewer.js") & WeappComponent<ComponentProp<"t-image-viewer">>;
    TIndexes: typeof import("tdesign-miniprogram/miniprogram_dist/indexes/indexes.js") & WeappComponent<ComponentProp<"t-indexes">>;
    't-indexes': typeof import("tdesign-miniprogram/miniprogram_dist/indexes/indexes.js") & WeappComponent<ComponentProp<"t-indexes">>;
    TIndexesAnchor: typeof import("tdesign-miniprogram/miniprogram_dist/indexes-anchor/indexes-anchor.js") & WeappComponent<ComponentProp<"t-indexes-anchor">>;
    't-indexes-anchor': typeof import("tdesign-miniprogram/miniprogram_dist/indexes-anchor/indexes-anchor.js") & WeappComponent<ComponentProp<"t-indexes-anchor">>;
    TInput: typeof import("tdesign-miniprogram/miniprogram_dist/input/input.js") & WeappComponent<ComponentProp<"t-input">>;
    't-input': typeof import("tdesign-miniprogram/miniprogram_dist/input/input.js") & WeappComponent<ComponentProp<"t-input">>;
    TLink: typeof import("tdesign-miniprogram/miniprogram_dist/link/link.js") & WeappComponent<ComponentProp<"t-link">>;
    't-link': typeof import("tdesign-miniprogram/miniprogram_dist/link/link.js") & WeappComponent<ComponentProp<"t-link">>;
    TLoading: typeof import("tdesign-miniprogram/miniprogram_dist/loading/loading.js") & WeappComponent<ComponentProp<"t-loading">>;
    't-loading': typeof import("tdesign-miniprogram/miniprogram_dist/loading/loading.js") & WeappComponent<ComponentProp<"t-loading">>;
    TMessage: typeof import("tdesign-miniprogram/miniprogram_dist/message/message.js") & WeappComponent<ComponentProp<"t-message">>;
    't-message': typeof import("tdesign-miniprogram/miniprogram_dist/message/message.js") & WeappComponent<ComponentProp<"t-message">>;
    TMessageItem: typeof import("tdesign-miniprogram/miniprogram_dist/message-item/message-item.js") & WeappComponent<ComponentProp<"t-message-item">>;
    't-message-item': typeof import("tdesign-miniprogram/miniprogram_dist/message-item/message-item.js") & WeappComponent<ComponentProp<"t-message-item">>;
    TNavbar: typeof import("tdesign-miniprogram/miniprogram_dist/navbar/navbar.js") & WeappComponent<ComponentProp<"t-navbar">>;
    't-navbar': typeof import("tdesign-miniprogram/miniprogram_dist/navbar/navbar.js") & WeappComponent<ComponentProp<"t-navbar">>;
    TNoticeBar: typeof import("tdesign-miniprogram/miniprogram_dist/notice-bar/notice-bar.js") & WeappComponent<ComponentProp<"t-notice-bar">>;
    't-notice-bar': typeof import("tdesign-miniprogram/miniprogram_dist/notice-bar/notice-bar.js") & WeappComponent<ComponentProp<"t-notice-bar">>;
    TOverlay: typeof import("tdesign-miniprogram/miniprogram_dist/overlay/overlay.js") & WeappComponent<ComponentProp<"t-overlay">>;
    't-overlay': typeof import("tdesign-miniprogram/miniprogram_dist/overlay/overlay.js") & WeappComponent<ComponentProp<"t-overlay">>;
    TPicker: typeof import("tdesign-miniprogram/miniprogram_dist/picker/picker.js") & WeappComponent<ComponentProp<"t-picker">>;
    't-picker': typeof import("tdesign-miniprogram/miniprogram_dist/picker/picker.js") & WeappComponent<ComponentProp<"t-picker">>;
    TPickerItem: typeof import("tdesign-miniprogram/miniprogram_dist/picker-item/picker-item.js") & WeappComponent<ComponentProp<"t-picker-item">>;
    't-picker-item': typeof import("tdesign-miniprogram/miniprogram_dist/picker-item/picker-item.js") & WeappComponent<ComponentProp<"t-picker-item">>;
    TPopup: typeof import("tdesign-miniprogram/miniprogram_dist/popup/popup.js") & WeappComponent<ComponentProp<"t-popup">>;
    't-popup': typeof import("tdesign-miniprogram/miniprogram_dist/popup/popup.js") & WeappComponent<ComponentProp<"t-popup">>;
    TProgress: typeof import("tdesign-miniprogram/miniprogram_dist/progress/progress.js") & WeappComponent<ComponentProp<"t-progress">>;
    't-progress': typeof import("tdesign-miniprogram/miniprogram_dist/progress/progress.js") & WeappComponent<ComponentProp<"t-progress">>;
    TPullDownRefresh: typeof import("tdesign-miniprogram/miniprogram_dist/pull-down-refresh/pull-down-refresh.js") & WeappComponent<ComponentProp<"t-pull-down-refresh">>;
    't-pull-down-refresh': typeof import("tdesign-miniprogram/miniprogram_dist/pull-down-refresh/pull-down-refresh.js") & WeappComponent<ComponentProp<"t-pull-down-refresh">>;
    TQrcode: typeof import("tdesign-miniprogram/miniprogram_dist/qrcode/qrcode.js") & WeappComponent<ComponentProp<"t-qrcode">>;
    't-qrcode': typeof import("tdesign-miniprogram/miniprogram_dist/qrcode/qrcode.js") & WeappComponent<ComponentProp<"t-qrcode">>;
    TRadio: typeof import("tdesign-miniprogram/miniprogram_dist/radio/radio.js") & WeappComponent<ComponentProp<"t-radio">>;
    't-radio': typeof import("tdesign-miniprogram/miniprogram_dist/radio/radio.js") & WeappComponent<ComponentProp<"t-radio">>;
    TRadioGroup: typeof import("tdesign-miniprogram/miniprogram_dist/radio-group/radio-group.js") & WeappComponent<ComponentProp<"t-radio-group">>;
    't-radio-group': typeof import("tdesign-miniprogram/miniprogram_dist/radio-group/radio-group.js") & WeappComponent<ComponentProp<"t-radio-group">>;
    TRate: typeof import("tdesign-miniprogram/miniprogram_dist/rate/rate.js") & WeappComponent<ComponentProp<"t-rate">>;
    't-rate': typeof import("tdesign-miniprogram/miniprogram_dist/rate/rate.js") & WeappComponent<ComponentProp<"t-rate">>;
    TResult: typeof import("tdesign-miniprogram/miniprogram_dist/result/result.js") & WeappComponent<ComponentProp<"t-result">>;
    't-result': typeof import("tdesign-miniprogram/miniprogram_dist/result/result.js") & WeappComponent<ComponentProp<"t-result">>;
    TRow: typeof import("tdesign-miniprogram/miniprogram_dist/row/row.js") & WeappComponent<ComponentProp<"t-row">>;
    't-row': typeof import("tdesign-miniprogram/miniprogram_dist/row/row.js") & WeappComponent<ComponentProp<"t-row">>;
    TScrollView: typeof import("tdesign-miniprogram/miniprogram_dist/scroll-view/scroll-view.js") & WeappComponent<ComponentProp<"t-scroll-view">>;
    't-scroll-view': typeof import("tdesign-miniprogram/miniprogram_dist/scroll-view/scroll-view.js") & WeappComponent<ComponentProp<"t-scroll-view">>;
    TSearch: typeof import("tdesign-miniprogram/miniprogram_dist/search/search.js") & WeappComponent<ComponentProp<"t-search">>;
    't-search': typeof import("tdesign-miniprogram/miniprogram_dist/search/search.js") & WeappComponent<ComponentProp<"t-search">>;
    TSideBar: typeof import("tdesign-miniprogram/miniprogram_dist/side-bar/side-bar.js") & WeappComponent<ComponentProp<"t-side-bar">>;
    't-side-bar': typeof import("tdesign-miniprogram/miniprogram_dist/side-bar/side-bar.js") & WeappComponent<ComponentProp<"t-side-bar">>;
    TSideBarItem: typeof import("tdesign-miniprogram/miniprogram_dist/side-bar-item/side-bar-item.js") & WeappComponent<ComponentProp<"t-side-bar-item">>;
    't-side-bar-item': typeof import("tdesign-miniprogram/miniprogram_dist/side-bar-item/side-bar-item.js") & WeappComponent<ComponentProp<"t-side-bar-item">>;
    TSkeleton: typeof import("tdesign-miniprogram/miniprogram_dist/skeleton/skeleton.js") & WeappComponent<ComponentProp<"t-skeleton">>;
    't-skeleton': typeof import("tdesign-miniprogram/miniprogram_dist/skeleton/skeleton.js") & WeappComponent<ComponentProp<"t-skeleton">>;
    TSlider: typeof import("tdesign-miniprogram/miniprogram_dist/slider/slider.js") & WeappComponent<ComponentProp<"t-slider">>;
    't-slider': typeof import("tdesign-miniprogram/miniprogram_dist/slider/slider.js") & WeappComponent<ComponentProp<"t-slider">>;
    TStepItem: typeof import("tdesign-miniprogram/miniprogram_dist/step-item/step-item.js") & WeappComponent<ComponentProp<"t-step-item">>;
    't-step-item': typeof import("tdesign-miniprogram/miniprogram_dist/step-item/step-item.js") & WeappComponent<ComponentProp<"t-step-item">>;
    TStepper: typeof import("tdesign-miniprogram/miniprogram_dist/stepper/stepper.js") & WeappComponent<ComponentProp<"t-stepper">>;
    't-stepper': typeof import("tdesign-miniprogram/miniprogram_dist/stepper/stepper.js") & WeappComponent<ComponentProp<"t-stepper">>;
    TSteps: typeof import("tdesign-miniprogram/miniprogram_dist/steps/steps.js") & WeappComponent<ComponentProp<"t-steps">>;
    't-steps': typeof import("tdesign-miniprogram/miniprogram_dist/steps/steps.js") & WeappComponent<ComponentProp<"t-steps">>;
    TSticky: typeof import("tdesign-miniprogram/miniprogram_dist/sticky/sticky.js") & WeappComponent<ComponentProp<"t-sticky">>;
    't-sticky': typeof import("tdesign-miniprogram/miniprogram_dist/sticky/sticky.js") & WeappComponent<ComponentProp<"t-sticky">>;
    TSwipeCell: typeof import("tdesign-miniprogram/miniprogram_dist/swipe-cell/swipe-cell.js") & WeappComponent<ComponentProp<"t-swipe-cell">>;
    't-swipe-cell': typeof import("tdesign-miniprogram/miniprogram_dist/swipe-cell/swipe-cell.js") & WeappComponent<ComponentProp<"t-swipe-cell">>;
    TSwiper: typeof import("tdesign-miniprogram/miniprogram_dist/swiper/swiper.js") & WeappComponent<ComponentProp<"t-swiper">>;
    't-swiper': typeof import("tdesign-miniprogram/miniprogram_dist/swiper/swiper.js") & WeappComponent<ComponentProp<"t-swiper">>;
    TSwiperNav: typeof import("tdesign-miniprogram/miniprogram_dist/swiper-nav/swiper-nav.js") & WeappComponent<ComponentProp<"t-swiper-nav">>;
    't-swiper-nav': typeof import("tdesign-miniprogram/miniprogram_dist/swiper-nav/swiper-nav.js") & WeappComponent<ComponentProp<"t-swiper-nav">>;
    TSwitch: typeof import("tdesign-miniprogram/miniprogram_dist/switch/switch.js") & WeappComponent<ComponentProp<"t-switch">>;
    't-switch': typeof import("tdesign-miniprogram/miniprogram_dist/switch/switch.js") & WeappComponent<ComponentProp<"t-switch">>;
    TTabBar: typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar/tab-bar.js") & WeappComponent<ComponentProp<"t-tab-bar">>;
    't-tab-bar': typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar/tab-bar.js") & WeappComponent<ComponentProp<"t-tab-bar">>;
    TTabBarItem: typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar-item/tab-bar-item.js") & WeappComponent<ComponentProp<"t-tab-bar-item">>;
    't-tab-bar-item': typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar-item/tab-bar-item.js") & WeappComponent<ComponentProp<"t-tab-bar-item">>;
    TTabPanel: typeof import("tdesign-miniprogram/miniprogram_dist/tab-panel/tab-panel.js") & WeappComponent<ComponentProp<"t-tab-panel">>;
    't-tab-panel': typeof import("tdesign-miniprogram/miniprogram_dist/tab-panel/tab-panel.js") & WeappComponent<ComponentProp<"t-tab-panel">>;
    TTabs: typeof import("tdesign-miniprogram/miniprogram_dist/tabs/tabs.js") & WeappComponent<ComponentProp<"t-tabs">>;
    't-tabs': typeof import("tdesign-miniprogram/miniprogram_dist/tabs/tabs.js") & WeappComponent<ComponentProp<"t-tabs">>;
    TTag: typeof import("tdesign-miniprogram/miniprogram_dist/tag/tag.js") & WeappComponent<ComponentProp<"t-tag">>;
    't-tag': typeof import("tdesign-miniprogram/miniprogram_dist/tag/tag.js") & WeappComponent<ComponentProp<"t-tag">>;
    TTextarea: typeof import("tdesign-miniprogram/miniprogram_dist/textarea/textarea.js") & WeappComponent<ComponentProp<"t-textarea">>;
    't-textarea': typeof import("tdesign-miniprogram/miniprogram_dist/textarea/textarea.js") & WeappComponent<ComponentProp<"t-textarea">>;
    TToast: typeof import("tdesign-miniprogram/miniprogram_dist/toast/toast.js") & WeappComponent<ComponentProp<"t-toast">>;
    't-toast': typeof import("tdesign-miniprogram/miniprogram_dist/toast/toast.js") & WeappComponent<ComponentProp<"t-toast">>;
    TTransition: typeof import("tdesign-miniprogram/miniprogram_dist/transition/transition.js") & WeappComponent<ComponentProp<"t-transition">>;
    't-transition': typeof import("tdesign-miniprogram/miniprogram_dist/transition/transition.js") & WeappComponent<ComponentProp<"t-transition">>;
    TTreeSelect: typeof import("tdesign-miniprogram/miniprogram_dist/tree-select/tree-select.js") & WeappComponent<ComponentProp<"t-tree-select">>;
    't-tree-select': typeof import("tdesign-miniprogram/miniprogram_dist/tree-select/tree-select.js") & WeappComponent<ComponentProp<"t-tree-select">>;
    TUpload: typeof import("tdesign-miniprogram/miniprogram_dist/upload/upload.js") & WeappComponent<ComponentProp<"t-upload">>;
    't-upload': typeof import("tdesign-miniprogram/miniprogram_dist/upload/upload.js") & WeappComponent<ComponentProp<"t-upload">>;
    TWatermark: typeof import("tdesign-miniprogram/miniprogram_dist/watermark/watermark.js") & WeappComponent<ComponentProp<"t-watermark">>;
    't-watermark': typeof import("tdesign-miniprogram/miniprogram_dist/watermark/watermark.js") & WeappComponent<ComponentProp<"t-watermark">>;
    VanActionSheet: typeof import("@vant/weapp/lib/action-sheet/index.js") & WeappComponent<ComponentProp<"van-action-sheet">>;
    'van-action-sheet': typeof import("@vant/weapp/lib/action-sheet/index.js") & WeappComponent<ComponentProp<"van-action-sheet">>;
    VanArea: typeof import("@vant/weapp/lib/area/index.js") & WeappComponent<ComponentProp<"van-area">>;
    'van-area': typeof import("@vant/weapp/lib/area/index.js") & WeappComponent<ComponentProp<"van-area">>;
    VanButton: typeof import("@vant/weapp/lib/button/index.js") & WeappComponent<ComponentProp<"van-button">>;
    'van-button': typeof import("@vant/weapp/lib/button/index.js") & WeappComponent<ComponentProp<"van-button">>;
    VanCalendar: typeof import("@vant/weapp/lib/calendar/index.js") & WeappComponent<ComponentProp<"van-calendar">>;
    'van-calendar': typeof import("@vant/weapp/lib/calendar/index.js") & WeappComponent<ComponentProp<"van-calendar">>;
    VanCard: typeof import("@vant/weapp/lib/card/index.js") & WeappComponent<ComponentProp<"van-card">>;
    'van-card': typeof import("@vant/weapp/lib/card/index.js") & WeappComponent<ComponentProp<"van-card">>;
    VanCascader: typeof import("@vant/weapp/lib/cascader/index.js") & WeappComponent<ComponentProp<"van-cascader">>;
    'van-cascader': typeof import("@vant/weapp/lib/cascader/index.js") & WeappComponent<ComponentProp<"van-cascader">>;
    VanCell: typeof import("@vant/weapp/lib/cell/index.js") & WeappComponent<ComponentProp<"van-cell">>;
    'van-cell': typeof import("@vant/weapp/lib/cell/index.js") & WeappComponent<ComponentProp<"van-cell">>;
    VanCellGroup: typeof import("@vant/weapp/lib/cell-group/index.js") & WeappComponent<ComponentProp<"van-cell-group">>;
    'van-cell-group': typeof import("@vant/weapp/lib/cell-group/index.js") & WeappComponent<ComponentProp<"van-cell-group">>;
    VanCheckbox: typeof import("@vant/weapp/lib/checkbox/index.js") & WeappComponent<ComponentProp<"van-checkbox">>;
    'van-checkbox': typeof import("@vant/weapp/lib/checkbox/index.js") & WeappComponent<ComponentProp<"van-checkbox">>;
    VanCheckboxGroup: typeof import("@vant/weapp/lib/checkbox-group/index.js") & WeappComponent<ComponentProp<"van-checkbox-group">>;
    'van-checkbox-group': typeof import("@vant/weapp/lib/checkbox-group/index.js") & WeappComponent<ComponentProp<"van-checkbox-group">>;
    VanCircle: typeof import("@vant/weapp/lib/circle/index.js") & WeappComponent<ComponentProp<"van-circle">>;
    'van-circle': typeof import("@vant/weapp/lib/circle/index.js") & WeappComponent<ComponentProp<"van-circle">>;
    VanCol: typeof import("@vant/weapp/lib/col/index.js") & WeappComponent<ComponentProp<"van-col">>;
    'van-col': typeof import("@vant/weapp/lib/col/index.js") & WeappComponent<ComponentProp<"van-col">>;
    VanCollapse: typeof import("@vant/weapp/lib/collapse/index.js") & WeappComponent<ComponentProp<"van-collapse">>;
    'van-collapse': typeof import("@vant/weapp/lib/collapse/index.js") & WeappComponent<ComponentProp<"van-collapse">>;
    VanCollapseItem: typeof import("@vant/weapp/lib/collapse-item/index.js") & WeappComponent<ComponentProp<"van-collapse-item">>;
    'van-collapse-item': typeof import("@vant/weapp/lib/collapse-item/index.js") & WeappComponent<ComponentProp<"van-collapse-item">>;
    VanConfigProvider: typeof import("@vant/weapp/lib/config-provider/index.js") & WeappComponent<ComponentProp<"van-config-provider">>;
    'van-config-provider': typeof import("@vant/weapp/lib/config-provider/index.js") & WeappComponent<ComponentProp<"van-config-provider">>;
    VanCountDown: typeof import("@vant/weapp/lib/count-down/index.js") & WeappComponent<ComponentProp<"van-count-down">>;
    'van-count-down': typeof import("@vant/weapp/lib/count-down/index.js") & WeappComponent<ComponentProp<"van-count-down">>;
    VanDatetimePicker: typeof import("@vant/weapp/lib/datetime-picker/index.js") & WeappComponent<ComponentProp<"van-datetime-picker">>;
    'van-datetime-picker': typeof import("@vant/weapp/lib/datetime-picker/index.js") & WeappComponent<ComponentProp<"van-datetime-picker">>;
    VanDefinitions: typeof import("@vant/weapp/lib/definitions/index.js") & WeappComponent<ComponentProp<"van-definitions">>;
    'van-definitions': typeof import("@vant/weapp/lib/definitions/index.js") & WeappComponent<ComponentProp<"van-definitions">>;
    VanDialog: typeof import("@vant/weapp/lib/dialog/index.js") & WeappComponent<ComponentProp<"van-dialog">>;
    'van-dialog': typeof import("@vant/weapp/lib/dialog/index.js") & WeappComponent<ComponentProp<"van-dialog">>;
    VanDivider: typeof import("@vant/weapp/lib/divider/index.js") & WeappComponent<ComponentProp<"van-divider">>;
    'van-divider': typeof import("@vant/weapp/lib/divider/index.js") & WeappComponent<ComponentProp<"van-divider">>;
    VanDropdownItem: typeof import("@vant/weapp/lib/dropdown-item/index.js") & WeappComponent<ComponentProp<"van-dropdown-item">>;
    'van-dropdown-item': typeof import("@vant/weapp/lib/dropdown-item/index.js") & WeappComponent<ComponentProp<"van-dropdown-item">>;
    VanDropdownMenu: typeof import("@vant/weapp/lib/dropdown-menu/index.js") & WeappComponent<ComponentProp<"van-dropdown-menu">>;
    'van-dropdown-menu': typeof import("@vant/weapp/lib/dropdown-menu/index.js") & WeappComponent<ComponentProp<"van-dropdown-menu">>;
    VanEmpty: typeof import("@vant/weapp/lib/empty/index.js") & WeappComponent<ComponentProp<"van-empty">>;
    'van-empty': typeof import("@vant/weapp/lib/empty/index.js") & WeappComponent<ComponentProp<"van-empty">>;
    VanField: typeof import("@vant/weapp/lib/field/index.js") & WeappComponent<ComponentProp<"van-field">>;
    'van-field': typeof import("@vant/weapp/lib/field/index.js") & WeappComponent<ComponentProp<"van-field">>;
    VanGoodsAction: typeof import("@vant/weapp/lib/goods-action/index.js") & WeappComponent<ComponentProp<"van-goods-action">>;
    'van-goods-action': typeof import("@vant/weapp/lib/goods-action/index.js") & WeappComponent<ComponentProp<"van-goods-action">>;
    VanGoodsActionButton: typeof import("@vant/weapp/lib/goods-action-button/index.js") & WeappComponent<ComponentProp<"van-goods-action-button">>;
    'van-goods-action-button': typeof import("@vant/weapp/lib/goods-action-button/index.js") & WeappComponent<ComponentProp<"van-goods-action-button">>;
    VanGoodsActionIcon: typeof import("@vant/weapp/lib/goods-action-icon/index.js") & WeappComponent<ComponentProp<"van-goods-action-icon">>;
    'van-goods-action-icon': typeof import("@vant/weapp/lib/goods-action-icon/index.js") & WeappComponent<ComponentProp<"van-goods-action-icon">>;
    VanGrid: typeof import("@vant/weapp/lib/grid/index.js") & WeappComponent<ComponentProp<"van-grid">>;
    'van-grid': typeof import("@vant/weapp/lib/grid/index.js") & WeappComponent<ComponentProp<"van-grid">>;
    VanGridItem: typeof import("@vant/weapp/lib/grid-item/index.js") & WeappComponent<ComponentProp<"van-grid-item">>;
    'van-grid-item': typeof import("@vant/weapp/lib/grid-item/index.js") & WeappComponent<ComponentProp<"van-grid-item">>;
    VanIcon: typeof import("@vant/weapp/lib/icon/index.js") & WeappComponent<ComponentProp<"van-icon">>;
    'van-icon': typeof import("@vant/weapp/lib/icon/index.js") & WeappComponent<ComponentProp<"van-icon">>;
    VanImage: typeof import("@vant/weapp/lib/image/index.js") & WeappComponent<ComponentProp<"van-image">>;
    'van-image': typeof import("@vant/weapp/lib/image/index.js") & WeappComponent<ComponentProp<"van-image">>;
    VanIndexAnchor: typeof import("@vant/weapp/lib/index-anchor/index.js") & WeappComponent<ComponentProp<"van-index-anchor">>;
    'van-index-anchor': typeof import("@vant/weapp/lib/index-anchor/index.js") & WeappComponent<ComponentProp<"van-index-anchor">>;
    VanIndexBar: typeof import("@vant/weapp/lib/index-bar/index.js") & WeappComponent<ComponentProp<"van-index-bar">>;
    'van-index-bar': typeof import("@vant/weapp/lib/index-bar/index.js") & WeappComponent<ComponentProp<"van-index-bar">>;
    VanInfo: typeof import("@vant/weapp/lib/info/index.js") & WeappComponent<ComponentProp<"van-info">>;
    'van-info': typeof import("@vant/weapp/lib/info/index.js") & WeappComponent<ComponentProp<"van-info">>;
    VanLoading: typeof import("@vant/weapp/lib/loading/index.js") & WeappComponent<ComponentProp<"van-loading">>;
    'van-loading': typeof import("@vant/weapp/lib/loading/index.js") & WeappComponent<ComponentProp<"van-loading">>;
    VanNavBar: typeof import("@vant/weapp/lib/nav-bar/index.js") & WeappComponent<ComponentProp<"van-nav-bar">>;
    'van-nav-bar': typeof import("@vant/weapp/lib/nav-bar/index.js") & WeappComponent<ComponentProp<"van-nav-bar">>;
    VanNoticeBar: typeof import("@vant/weapp/lib/notice-bar/index.js") & WeappComponent<ComponentProp<"van-notice-bar">>;
    'van-notice-bar': typeof import("@vant/weapp/lib/notice-bar/index.js") & WeappComponent<ComponentProp<"van-notice-bar">>;
    VanNotify: typeof import("@vant/weapp/lib/notify/index.js") & WeappComponent<ComponentProp<"van-notify">>;
    'van-notify': typeof import("@vant/weapp/lib/notify/index.js") & WeappComponent<ComponentProp<"van-notify">>;
    VanOverlay: typeof import("@vant/weapp/lib/overlay/index.js") & WeappComponent<ComponentProp<"van-overlay">>;
    'van-overlay': typeof import("@vant/weapp/lib/overlay/index.js") & WeappComponent<ComponentProp<"van-overlay">>;
    VanPanel: typeof import("@vant/weapp/lib/panel/index.js") & WeappComponent<ComponentProp<"van-panel">>;
    'van-panel': typeof import("@vant/weapp/lib/panel/index.js") & WeappComponent<ComponentProp<"van-panel">>;
    VanPicker: typeof import("@vant/weapp/lib/picker/index.js") & WeappComponent<ComponentProp<"van-picker">>;
    'van-picker': typeof import("@vant/weapp/lib/picker/index.js") & WeappComponent<ComponentProp<"van-picker">>;
    VanPickerColumn: typeof import("@vant/weapp/lib/picker-column/index.js") & WeappComponent<ComponentProp<"van-picker-column">>;
    'van-picker-column': typeof import("@vant/weapp/lib/picker-column/index.js") & WeappComponent<ComponentProp<"van-picker-column">>;
    VanPopup: typeof import("@vant/weapp/lib/popup/index.js") & WeappComponent<ComponentProp<"van-popup">>;
    'van-popup': typeof import("@vant/weapp/lib/popup/index.js") & WeappComponent<ComponentProp<"van-popup">>;
    VanProgress: typeof import("@vant/weapp/lib/progress/index.js") & WeappComponent<ComponentProp<"van-progress">>;
    'van-progress': typeof import("@vant/weapp/lib/progress/index.js") & WeappComponent<ComponentProp<"van-progress">>;
    VanRadio: typeof import("@vant/weapp/lib/radio/index.js") & WeappComponent<ComponentProp<"van-radio">>;
    'van-radio': typeof import("@vant/weapp/lib/radio/index.js") & WeappComponent<ComponentProp<"van-radio">>;
    VanRadioGroup: typeof import("@vant/weapp/lib/radio-group/index.js") & WeappComponent<ComponentProp<"van-radio-group">>;
    'van-radio-group': typeof import("@vant/weapp/lib/radio-group/index.js") & WeappComponent<ComponentProp<"van-radio-group">>;
    VanRate: typeof import("@vant/weapp/lib/rate/index.js") & WeappComponent<ComponentProp<"van-rate">>;
    'van-rate': typeof import("@vant/weapp/lib/rate/index.js") & WeappComponent<ComponentProp<"van-rate">>;
    VanRow: typeof import("@vant/weapp/lib/row/index.js") & WeappComponent<ComponentProp<"van-row">>;
    'van-row': typeof import("@vant/weapp/lib/row/index.js") & WeappComponent<ComponentProp<"van-row">>;
    VanSearch: typeof import("@vant/weapp/lib/search/index.js") & WeappComponent<ComponentProp<"van-search">>;
    'van-search': typeof import("@vant/weapp/lib/search/index.js") & WeappComponent<ComponentProp<"van-search">>;
    VanShareSheet: typeof import("@vant/weapp/lib/share-sheet/index.js") & WeappComponent<ComponentProp<"van-share-sheet">>;
    'van-share-sheet': typeof import("@vant/weapp/lib/share-sheet/index.js") & WeappComponent<ComponentProp<"van-share-sheet">>;
    VanSidebar: typeof import("@vant/weapp/lib/sidebar/index.js") & WeappComponent<ComponentProp<"van-sidebar">>;
    'van-sidebar': typeof import("@vant/weapp/lib/sidebar/index.js") & WeappComponent<ComponentProp<"van-sidebar">>;
    VanSidebarItem: typeof import("@vant/weapp/lib/sidebar-item/index.js") & WeappComponent<ComponentProp<"van-sidebar-item">>;
    'van-sidebar-item': typeof import("@vant/weapp/lib/sidebar-item/index.js") & WeappComponent<ComponentProp<"van-sidebar-item">>;
    VanSkeleton: typeof import("@vant/weapp/lib/skeleton/index.js") & WeappComponent<ComponentProp<"van-skeleton">>;
    'van-skeleton': typeof import("@vant/weapp/lib/skeleton/index.js") & WeappComponent<ComponentProp<"van-skeleton">>;
    VanSlider: typeof import("@vant/weapp/lib/slider/index.js") & WeappComponent<ComponentProp<"van-slider">>;
    'van-slider': typeof import("@vant/weapp/lib/slider/index.js") & WeappComponent<ComponentProp<"van-slider">>;
    VanStepper: typeof import("@vant/weapp/lib/stepper/index.js") & WeappComponent<ComponentProp<"van-stepper">>;
    'van-stepper': typeof import("@vant/weapp/lib/stepper/index.js") & WeappComponent<ComponentProp<"van-stepper">>;
    VanSteps: typeof import("@vant/weapp/lib/steps/index.js") & WeappComponent<ComponentProp<"van-steps">>;
    'van-steps': typeof import("@vant/weapp/lib/steps/index.js") & WeappComponent<ComponentProp<"van-steps">>;
    VanSticky: typeof import("@vant/weapp/lib/sticky/index.js") & WeappComponent<ComponentProp<"van-sticky">>;
    'van-sticky': typeof import("@vant/weapp/lib/sticky/index.js") & WeappComponent<ComponentProp<"van-sticky">>;
    VanSubmitBar: typeof import("@vant/weapp/lib/submit-bar/index.js") & WeappComponent<ComponentProp<"van-submit-bar">>;
    'van-submit-bar': typeof import("@vant/weapp/lib/submit-bar/index.js") & WeappComponent<ComponentProp<"van-submit-bar">>;
    VanSwipeCell: typeof import("@vant/weapp/lib/swipe-cell/index.js") & WeappComponent<ComponentProp<"van-swipe-cell">>;
    'van-swipe-cell': typeof import("@vant/weapp/lib/swipe-cell/index.js") & WeappComponent<ComponentProp<"van-swipe-cell">>;
    VanSwitch: typeof import("@vant/weapp/lib/switch/index.js") & WeappComponent<ComponentProp<"van-switch">>;
    'van-switch': typeof import("@vant/weapp/lib/switch/index.js") & WeappComponent<ComponentProp<"van-switch">>;
    VanTab: typeof import("@vant/weapp/lib/tab/index.js") & WeappComponent<ComponentProp<"van-tab">>;
    'van-tab': typeof import("@vant/weapp/lib/tab/index.js") & WeappComponent<ComponentProp<"van-tab">>;
    VanTabbar: typeof import("@vant/weapp/lib/tabbar/index.js") & WeappComponent<ComponentProp<"van-tabbar">>;
    'van-tabbar': typeof import("@vant/weapp/lib/tabbar/index.js") & WeappComponent<ComponentProp<"van-tabbar">>;
    VanTabbarItem: typeof import("@vant/weapp/lib/tabbar-item/index.js") & WeappComponent<ComponentProp<"van-tabbar-item">>;
    'van-tabbar-item': typeof import("@vant/weapp/lib/tabbar-item/index.js") & WeappComponent<ComponentProp<"van-tabbar-item">>;
    VanTabs: typeof import("@vant/weapp/lib/tabs/index.js") & WeappComponent<ComponentProp<"van-tabs">>;
    'van-tabs': typeof import("@vant/weapp/lib/tabs/index.js") & WeappComponent<ComponentProp<"van-tabs">>;
    VanTag: typeof import("@vant/weapp/lib/tag/index.js") & WeappComponent<ComponentProp<"van-tag">>;
    'van-tag': typeof import("@vant/weapp/lib/tag/index.js") & WeappComponent<ComponentProp<"van-tag">>;
    VanToast: typeof import("@vant/weapp/lib/toast/index.js") & WeappComponent<ComponentProp<"van-toast">>;
    'van-toast': typeof import("@vant/weapp/lib/toast/index.js") & WeappComponent<ComponentProp<"van-toast">>;
    VanTransition: typeof import("@vant/weapp/lib/transition/index.js") & WeappComponent<ComponentProp<"van-transition">>;
    'van-transition': typeof import("@vant/weapp/lib/transition/index.js") & WeappComponent<ComponentProp<"van-transition">>;
    VanTreeSelect: typeof import("@vant/weapp/lib/tree-select/index.js") & WeappComponent<ComponentProp<"van-tree-select">>;
    'van-tree-select': typeof import("@vant/weapp/lib/tree-select/index.js") & WeappComponent<ComponentProp<"van-tree-select">>;
    VanUploader: typeof import("@vant/weapp/lib/uploader/index.js") & WeappComponent<ComponentProp<"van-uploader">>;
    'van-uploader': typeof import("@vant/weapp/lib/uploader/index.js") & WeappComponent<ComponentProp<"van-uploader">>;
    [component: string]: WeappComponent;
  }
}

// For TSX support
declare global {
  const TActionSheet: typeof import("tdesign-miniprogram/miniprogram_dist/action-sheet/action-sheet.js") & WeappComponent<ComponentProp<"t-action-sheet">>
  const TAvatar: typeof import("tdesign-miniprogram/miniprogram_dist/avatar/avatar.js") & WeappComponent<ComponentProp<"t-avatar">>
  const TAvatarGroup: typeof import("tdesign-miniprogram/miniprogram_dist/avatar-group/avatar-group.js") & WeappComponent<ComponentProp<"t-avatar-group">>
  const TBackTop: typeof import("tdesign-miniprogram/miniprogram_dist/back-top/back-top.js") & WeappComponent<ComponentProp<"t-back-top">>
  const TBadge: typeof import("tdesign-miniprogram/miniprogram_dist/badge/badge.js") & WeappComponent<ComponentProp<"t-badge">>
  const TButton: typeof import("tdesign-miniprogram/miniprogram_dist/button/button.js") & WeappComponent<ComponentProp<"t-button">>
  const TCalendar: typeof import("tdesign-miniprogram/miniprogram_dist/calendar/calendar.js") & WeappComponent<ComponentProp<"t-calendar">>
  const TCascader: typeof import("tdesign-miniprogram/miniprogram_dist/cascader/cascader.js") & WeappComponent<ComponentProp<"t-cascader">>
  const TCell: typeof import("tdesign-miniprogram/miniprogram_dist/cell/cell.js") & WeappComponent<ComponentProp<"t-cell">>
  const TCellGroup: typeof import("tdesign-miniprogram/miniprogram_dist/cell-group/cell-group.js") & WeappComponent<ComponentProp<"t-cell-group">>
  const TCheckTag: typeof import("tdesign-miniprogram/miniprogram_dist/check-tag/check-tag.js") & WeappComponent<ComponentProp<"t-check-tag">>
  const TCheckbox: typeof import("tdesign-miniprogram/miniprogram_dist/checkbox/checkbox.js") & WeappComponent<ComponentProp<"t-checkbox">>
  const TCheckboxGroup: typeof import("tdesign-miniprogram/miniprogram_dist/checkbox-group/checkbox-group.js") & WeappComponent<ComponentProp<"t-checkbox-group">>
  const TCol: typeof import("tdesign-miniprogram/miniprogram_dist/col/col.js") & WeappComponent<ComponentProp<"t-col">>
  const TCollapse: typeof import("tdesign-miniprogram/miniprogram_dist/collapse/collapse.js") & WeappComponent<ComponentProp<"t-collapse">>
  const TCollapsePanel: typeof import("tdesign-miniprogram/miniprogram_dist/collapse-panel/collapse-panel.js") & WeappComponent<ComponentProp<"t-collapse-panel">>
  const TColorPicker: typeof import("tdesign-miniprogram/miniprogram_dist/color-picker/color-picker.js") & WeappComponent<ComponentProp<"t-color-picker">>
  const TCountDown: typeof import("tdesign-miniprogram/miniprogram_dist/count-down/count-down.js") & WeappComponent<ComponentProp<"t-count-down">>
  const TDateTimePicker: typeof import("tdesign-miniprogram/miniprogram_dist/date-time-picker/date-time-picker.js") & WeappComponent<ComponentProp<"t-date-time-picker">>
  const TDialog: typeof import("tdesign-miniprogram/miniprogram_dist/dialog/dialog.js") & WeappComponent<ComponentProp<"t-dialog">>
  const TDivider: typeof import("tdesign-miniprogram/miniprogram_dist/divider/divider.js") & WeappComponent<ComponentProp<"t-divider">>
  const TDrawer: typeof import("tdesign-miniprogram/miniprogram_dist/drawer/drawer.js") & WeappComponent<ComponentProp<"t-drawer">>
  const TDropdownItem: typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-item/dropdown-item.js") & WeappComponent<ComponentProp<"t-dropdown-item">>
  const TDropdownMenu: typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-menu/dropdown-menu.js") & WeappComponent<ComponentProp<"t-dropdown-menu">>
  const TEmpty: typeof import("tdesign-miniprogram/miniprogram_dist/empty/empty.js") & WeappComponent<ComponentProp<"t-empty">>
  const TFab: typeof import("tdesign-miniprogram/miniprogram_dist/fab/fab.js") & WeappComponent<ComponentProp<"t-fab">>
  const TFooter: typeof import("tdesign-miniprogram/miniprogram_dist/footer/footer.js") & WeappComponent<ComponentProp<"t-footer">>
  const TForm: WeappComponent<ComponentProp<"t-form">>
  const TFormItem: WeappComponent<ComponentProp<"t-form-item">>
  const TGrid: typeof import("tdesign-miniprogram/miniprogram_dist/grid/grid.js") & WeappComponent<ComponentProp<"t-grid">>
  const TGridItem: typeof import("tdesign-miniprogram/miniprogram_dist/grid-item/grid-item.js") & WeappComponent<ComponentProp<"t-grid-item">>
  const TGuide: typeof import("tdesign-miniprogram/miniprogram_dist/guide/guide.js") & WeappComponent<ComponentProp<"t-guide">>
  const TIcon: typeof import("tdesign-miniprogram/miniprogram_dist/icon/icon.js") & WeappComponent<ComponentProp<"t-icon">>
  const TImage: typeof import("tdesign-miniprogram/miniprogram_dist/image/image.js") & WeappComponent<ComponentProp<"t-image">>
  const TImageViewer: typeof import("tdesign-miniprogram/miniprogram_dist/image-viewer/image-viewer.js") & WeappComponent<ComponentProp<"t-image-viewer">>
  const TIndexes: typeof import("tdesign-miniprogram/miniprogram_dist/indexes/indexes.js") & WeappComponent<ComponentProp<"t-indexes">>
  const TIndexesAnchor: typeof import("tdesign-miniprogram/miniprogram_dist/indexes-anchor/indexes-anchor.js") & WeappComponent<ComponentProp<"t-indexes-anchor">>
  const TInput: typeof import("tdesign-miniprogram/miniprogram_dist/input/input.js") & WeappComponent<ComponentProp<"t-input">>
  const TLink: typeof import("tdesign-miniprogram/miniprogram_dist/link/link.js") & WeappComponent<ComponentProp<"t-link">>
  const TLoading: typeof import("tdesign-miniprogram/miniprogram_dist/loading/loading.js") & WeappComponent<ComponentProp<"t-loading">>
  const TMessage: typeof import("tdesign-miniprogram/miniprogram_dist/message/message.js") & WeappComponent<ComponentProp<"t-message">>
  const TMessageItem: typeof import("tdesign-miniprogram/miniprogram_dist/message-item/message-item.js") & WeappComponent<ComponentProp<"t-message-item">>
  const TNavbar: typeof import("tdesign-miniprogram/miniprogram_dist/navbar/navbar.js") & WeappComponent<ComponentProp<"t-navbar">>
  const TNoticeBar: typeof import("tdesign-miniprogram/miniprogram_dist/notice-bar/notice-bar.js") & WeappComponent<ComponentProp<"t-notice-bar">>
  const TOverlay: typeof import("tdesign-miniprogram/miniprogram_dist/overlay/overlay.js") & WeappComponent<ComponentProp<"t-overlay">>
  const TPicker: typeof import("tdesign-miniprogram/miniprogram_dist/picker/picker.js") & WeappComponent<ComponentProp<"t-picker">>
  const TPickerItem: typeof import("tdesign-miniprogram/miniprogram_dist/picker-item/picker-item.js") & WeappComponent<ComponentProp<"t-picker-item">>
  const TPopup: typeof import("tdesign-miniprogram/miniprogram_dist/popup/popup.js") & WeappComponent<ComponentProp<"t-popup">>
  const TProgress: typeof import("tdesign-miniprogram/miniprogram_dist/progress/progress.js") & WeappComponent<ComponentProp<"t-progress">>
  const TPullDownRefresh: typeof import("tdesign-miniprogram/miniprogram_dist/pull-down-refresh/pull-down-refresh.js") & WeappComponent<ComponentProp<"t-pull-down-refresh">>
  const TQrcode: typeof import("tdesign-miniprogram/miniprogram_dist/qrcode/qrcode.js") & WeappComponent<ComponentProp<"t-qrcode">>
  const TRadio: typeof import("tdesign-miniprogram/miniprogram_dist/radio/radio.js") & WeappComponent<ComponentProp<"t-radio">>
  const TRadioGroup: typeof import("tdesign-miniprogram/miniprogram_dist/radio-group/radio-group.js") & WeappComponent<ComponentProp<"t-radio-group">>
  const TRate: typeof import("tdesign-miniprogram/miniprogram_dist/rate/rate.js") & WeappComponent<ComponentProp<"t-rate">>
  const TResult: typeof import("tdesign-miniprogram/miniprogram_dist/result/result.js") & WeappComponent<ComponentProp<"t-result">>
  const TRow: typeof import("tdesign-miniprogram/miniprogram_dist/row/row.js") & WeappComponent<ComponentProp<"t-row">>
  const TScrollView: typeof import("tdesign-miniprogram/miniprogram_dist/scroll-view/scroll-view.js") & WeappComponent<ComponentProp<"t-scroll-view">>
  const TSearch: typeof import("tdesign-miniprogram/miniprogram_dist/search/search.js") & WeappComponent<ComponentProp<"t-search">>
  const TSideBar: typeof import("tdesign-miniprogram/miniprogram_dist/side-bar/side-bar.js") & WeappComponent<ComponentProp<"t-side-bar">>
  const TSideBarItem: typeof import("tdesign-miniprogram/miniprogram_dist/side-bar-item/side-bar-item.js") & WeappComponent<ComponentProp<"t-side-bar-item">>
  const TSkeleton: typeof import("tdesign-miniprogram/miniprogram_dist/skeleton/skeleton.js") & WeappComponent<ComponentProp<"t-skeleton">>
  const TSlider: typeof import("tdesign-miniprogram/miniprogram_dist/slider/slider.js") & WeappComponent<ComponentProp<"t-slider">>
  const TStepItem: typeof import("tdesign-miniprogram/miniprogram_dist/step-item/step-item.js") & WeappComponent<ComponentProp<"t-step-item">>
  const TStepper: typeof import("tdesign-miniprogram/miniprogram_dist/stepper/stepper.js") & WeappComponent<ComponentProp<"t-stepper">>
  const TSteps: typeof import("tdesign-miniprogram/miniprogram_dist/steps/steps.js") & WeappComponent<ComponentProp<"t-steps">>
  const TSticky: typeof import("tdesign-miniprogram/miniprogram_dist/sticky/sticky.js") & WeappComponent<ComponentProp<"t-sticky">>
  const TSwipeCell: typeof import("tdesign-miniprogram/miniprogram_dist/swipe-cell/swipe-cell.js") & WeappComponent<ComponentProp<"t-swipe-cell">>
  const TSwiper: typeof import("tdesign-miniprogram/miniprogram_dist/swiper/swiper.js") & WeappComponent<ComponentProp<"t-swiper">>
  const TSwiperNav: typeof import("tdesign-miniprogram/miniprogram_dist/swiper-nav/swiper-nav.js") & WeappComponent<ComponentProp<"t-swiper-nav">>
  const TSwitch: typeof import("tdesign-miniprogram/miniprogram_dist/switch/switch.js") & WeappComponent<ComponentProp<"t-switch">>
  const TTabBar: typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar/tab-bar.js") & WeappComponent<ComponentProp<"t-tab-bar">>
  const TTabBarItem: typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar-item/tab-bar-item.js") & WeappComponent<ComponentProp<"t-tab-bar-item">>
  const TTabPanel: typeof import("tdesign-miniprogram/miniprogram_dist/tab-panel/tab-panel.js") & WeappComponent<ComponentProp<"t-tab-panel">>
  const TTabs: typeof import("tdesign-miniprogram/miniprogram_dist/tabs/tabs.js") & WeappComponent<ComponentProp<"t-tabs">>
  const TTag: typeof import("tdesign-miniprogram/miniprogram_dist/tag/tag.js") & WeappComponent<ComponentProp<"t-tag">>
  const TTextarea: typeof import("tdesign-miniprogram/miniprogram_dist/textarea/textarea.js") & WeappComponent<ComponentProp<"t-textarea">>
  const TToast: typeof import("tdesign-miniprogram/miniprogram_dist/toast/toast.js") & WeappComponent<ComponentProp<"t-toast">>
  const TTransition: typeof import("tdesign-miniprogram/miniprogram_dist/transition/transition.js") & WeappComponent<ComponentProp<"t-transition">>
  const TTreeSelect: typeof import("tdesign-miniprogram/miniprogram_dist/tree-select/tree-select.js") & WeappComponent<ComponentProp<"t-tree-select">>
  const TUpload: typeof import("tdesign-miniprogram/miniprogram_dist/upload/upload.js") & WeappComponent<ComponentProp<"t-upload">>
  const TWatermark: typeof import("tdesign-miniprogram/miniprogram_dist/watermark/watermark.js") & WeappComponent<ComponentProp<"t-watermark">>
  const VanActionSheet: typeof import("@vant/weapp/lib/action-sheet/index.js") & WeappComponent<ComponentProp<"van-action-sheet">>
  const VanArea: typeof import("@vant/weapp/lib/area/index.js") & WeappComponent<ComponentProp<"van-area">>
  const VanButton: typeof import("@vant/weapp/lib/button/index.js") & WeappComponent<ComponentProp<"van-button">>
  const VanCalendar: typeof import("@vant/weapp/lib/calendar/index.js") & WeappComponent<ComponentProp<"van-calendar">>
  const VanCard: typeof import("@vant/weapp/lib/card/index.js") & WeappComponent<ComponentProp<"van-card">>
  const VanCascader: typeof import("@vant/weapp/lib/cascader/index.js") & WeappComponent<ComponentProp<"van-cascader">>
  const VanCell: typeof import("@vant/weapp/lib/cell/index.js") & WeappComponent<ComponentProp<"van-cell">>
  const VanCellGroup: typeof import("@vant/weapp/lib/cell-group/index.js") & WeappComponent<ComponentProp<"van-cell-group">>
  const VanCheckbox: typeof import("@vant/weapp/lib/checkbox/index.js") & WeappComponent<ComponentProp<"van-checkbox">>
  const VanCheckboxGroup: typeof import("@vant/weapp/lib/checkbox-group/index.js") & WeappComponent<ComponentProp<"van-checkbox-group">>
  const VanCircle: typeof import("@vant/weapp/lib/circle/index.js") & WeappComponent<ComponentProp<"van-circle">>
  const VanCol: typeof import("@vant/weapp/lib/col/index.js") & WeappComponent<ComponentProp<"van-col">>
  const VanCollapse: typeof import("@vant/weapp/lib/collapse/index.js") & WeappComponent<ComponentProp<"van-collapse">>
  const VanCollapseItem: typeof import("@vant/weapp/lib/collapse-item/index.js") & WeappComponent<ComponentProp<"van-collapse-item">>
  const VanConfigProvider: typeof import("@vant/weapp/lib/config-provider/index.js") & WeappComponent<ComponentProp<"van-config-provider">>
  const VanCountDown: typeof import("@vant/weapp/lib/count-down/index.js") & WeappComponent<ComponentProp<"van-count-down">>
  const VanDatetimePicker: typeof import("@vant/weapp/lib/datetime-picker/index.js") & WeappComponent<ComponentProp<"van-datetime-picker">>
  const VanDefinitions: typeof import("@vant/weapp/lib/definitions/index.js") & WeappComponent<ComponentProp<"van-definitions">>
  const VanDialog: typeof import("@vant/weapp/lib/dialog/index.js") & WeappComponent<ComponentProp<"van-dialog">>
  const VanDivider: typeof import("@vant/weapp/lib/divider/index.js") & WeappComponent<ComponentProp<"van-divider">>
  const VanDropdownItem: typeof import("@vant/weapp/lib/dropdown-item/index.js") & WeappComponent<ComponentProp<"van-dropdown-item">>
  const VanDropdownMenu: typeof import("@vant/weapp/lib/dropdown-menu/index.js") & WeappComponent<ComponentProp<"van-dropdown-menu">>
  const VanEmpty: typeof import("@vant/weapp/lib/empty/index.js") & WeappComponent<ComponentProp<"van-empty">>
  const VanField: typeof import("@vant/weapp/lib/field/index.js") & WeappComponent<ComponentProp<"van-field">>
  const VanGoodsAction: typeof import("@vant/weapp/lib/goods-action/index.js") & WeappComponent<ComponentProp<"van-goods-action">>
  const VanGoodsActionButton: typeof import("@vant/weapp/lib/goods-action-button/index.js") & WeappComponent<ComponentProp<"van-goods-action-button">>
  const VanGoodsActionIcon: typeof import("@vant/weapp/lib/goods-action-icon/index.js") & WeappComponent<ComponentProp<"van-goods-action-icon">>
  const VanGrid: typeof import("@vant/weapp/lib/grid/index.js") & WeappComponent<ComponentProp<"van-grid">>
  const VanGridItem: typeof import("@vant/weapp/lib/grid-item/index.js") & WeappComponent<ComponentProp<"van-grid-item">>
  const VanIcon: typeof import("@vant/weapp/lib/icon/index.js") & WeappComponent<ComponentProp<"van-icon">>
  const VanImage: typeof import("@vant/weapp/lib/image/index.js") & WeappComponent<ComponentProp<"van-image">>
  const VanIndexAnchor: typeof import("@vant/weapp/lib/index-anchor/index.js") & WeappComponent<ComponentProp<"van-index-anchor">>
  const VanIndexBar: typeof import("@vant/weapp/lib/index-bar/index.js") & WeappComponent<ComponentProp<"van-index-bar">>
  const VanInfo: typeof import("@vant/weapp/lib/info/index.js") & WeappComponent<ComponentProp<"van-info">>
  const VanLoading: typeof import("@vant/weapp/lib/loading/index.js") & WeappComponent<ComponentProp<"van-loading">>
  const VanNavBar: typeof import("@vant/weapp/lib/nav-bar/index.js") & WeappComponent<ComponentProp<"van-nav-bar">>
  const VanNoticeBar: typeof import("@vant/weapp/lib/notice-bar/index.js") & WeappComponent<ComponentProp<"van-notice-bar">>
  const VanNotify: typeof import("@vant/weapp/lib/notify/index.js") & WeappComponent<ComponentProp<"van-notify">>
  const VanOverlay: typeof import("@vant/weapp/lib/overlay/index.js") & WeappComponent<ComponentProp<"van-overlay">>
  const VanPanel: typeof import("@vant/weapp/lib/panel/index.js") & WeappComponent<ComponentProp<"van-panel">>
  const VanPicker: typeof import("@vant/weapp/lib/picker/index.js") & WeappComponent<ComponentProp<"van-picker">>
  const VanPickerColumn: typeof import("@vant/weapp/lib/picker-column/index.js") & WeappComponent<ComponentProp<"van-picker-column">>
  const VanPopup: typeof import("@vant/weapp/lib/popup/index.js") & WeappComponent<ComponentProp<"van-popup">>
  const VanProgress: typeof import("@vant/weapp/lib/progress/index.js") & WeappComponent<ComponentProp<"van-progress">>
  const VanRadio: typeof import("@vant/weapp/lib/radio/index.js") & WeappComponent<ComponentProp<"van-radio">>
  const VanRadioGroup: typeof import("@vant/weapp/lib/radio-group/index.js") & WeappComponent<ComponentProp<"van-radio-group">>
  const VanRate: typeof import("@vant/weapp/lib/rate/index.js") & WeappComponent<ComponentProp<"van-rate">>
  const VanRow: typeof import("@vant/weapp/lib/row/index.js") & WeappComponent<ComponentProp<"van-row">>
  const VanSearch: typeof import("@vant/weapp/lib/search/index.js") & WeappComponent<ComponentProp<"van-search">>
  const VanShareSheet: typeof import("@vant/weapp/lib/share-sheet/index.js") & WeappComponent<ComponentProp<"van-share-sheet">>
  const VanSidebar: typeof import("@vant/weapp/lib/sidebar/index.js") & WeappComponent<ComponentProp<"van-sidebar">>
  const VanSidebarItem: typeof import("@vant/weapp/lib/sidebar-item/index.js") & WeappComponent<ComponentProp<"van-sidebar-item">>
  const VanSkeleton: typeof import("@vant/weapp/lib/skeleton/index.js") & WeappComponent<ComponentProp<"van-skeleton">>
  const VanSlider: typeof import("@vant/weapp/lib/slider/index.js") & WeappComponent<ComponentProp<"van-slider">>
  const VanStepper: typeof import("@vant/weapp/lib/stepper/index.js") & WeappComponent<ComponentProp<"van-stepper">>
  const VanSteps: typeof import("@vant/weapp/lib/steps/index.js") & WeappComponent<ComponentProp<"van-steps">>
  const VanSticky: typeof import("@vant/weapp/lib/sticky/index.js") & WeappComponent<ComponentProp<"van-sticky">>
  const VanSubmitBar: typeof import("@vant/weapp/lib/submit-bar/index.js") & WeappComponent<ComponentProp<"van-submit-bar">>
  const VanSwipeCell: typeof import("@vant/weapp/lib/swipe-cell/index.js") & WeappComponent<ComponentProp<"van-swipe-cell">>
  const VanSwitch: typeof import("@vant/weapp/lib/switch/index.js") & WeappComponent<ComponentProp<"van-switch">>
  const VanTab: typeof import("@vant/weapp/lib/tab/index.js") & WeappComponent<ComponentProp<"van-tab">>
  const VanTabbar: typeof import("@vant/weapp/lib/tabbar/index.js") & WeappComponent<ComponentProp<"van-tabbar">>
  const VanTabbarItem: typeof import("@vant/weapp/lib/tabbar-item/index.js") & WeappComponent<ComponentProp<"van-tabbar-item">>
  const VanTabs: typeof import("@vant/weapp/lib/tabs/index.js") & WeappComponent<ComponentProp<"van-tabs">>
  const VanTag: typeof import("@vant/weapp/lib/tag/index.js") & WeappComponent<ComponentProp<"van-tag">>
  const VanToast: typeof import("@vant/weapp/lib/toast/index.js") & WeappComponent<ComponentProp<"van-toast">>
  const VanTransition: typeof import("@vant/weapp/lib/transition/index.js") & WeappComponent<ComponentProp<"van-transition">>
  const VanTreeSelect: typeof import("@vant/weapp/lib/tree-select/index.js") & WeappComponent<ComponentProp<"van-tree-select">>
  const VanUploader: typeof import("@vant/weapp/lib/uploader/index.js") & WeappComponent<ComponentProp<"van-uploader">>
}
