/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// 由 weapp-vite 自动生成，请勿编辑。
declare module 'weapp-vite/typed-components' {
  export interface ComponentProps {
    't-action-sheet': {
      readonly align?: 'center' | 'left';
      readonly cancelText?: string;
      readonly count?: number;
      readonly defaultVisible?: boolean;
      readonly description?: string;
      readonly items?: Array<string | ActionSheetItem>;
      readonly popupProps?: PopupProps;
      readonly showCancel?: boolean;
      readonly showOverlay?: boolean;
      readonly theme?: 'list' | 'grid';
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
    };
    't-avatar': {
      readonly alt?: string;
      readonly badgeProps?: BadgeProps;
      readonly bordered?: boolean;
      readonly hideOnLoadFailed?: boolean;
      readonly icon?: string | object;
      readonly image?: string;
      readonly imageProps?: ImageProps;
      readonly shape?: ShapeEnum;
      readonly size?: string;
    };
    't-avatar-group': {
      readonly cascading?: CascadingValue;
      readonly collapseAvatar?: string;
      readonly max?: number;
      readonly shape?: ShapeEnum;
      readonly size?: string;
    };
    't-back-top': {
      readonly fixed?: boolean;
      readonly icon?: string | boolean | object;
      readonly scrollTop?: number;
      readonly text?: string;
      readonly theme?: 'round' | 'half-round' | 'round-dark' | 'half-round-dark';
      readonly visibilityHeight?: number;
    };
    't-badge': {
      readonly color?: string;
      readonly content?: string;
      readonly count?: string | number;
      readonly dot?: boolean;
      readonly maxCount?: number;
      readonly offset?: Array<string | number>;
      readonly shape?: 'circle' | 'square' | 'bubble' | 'ribbon' | 'ribbon-right' | 'ribbon-left' | 'triangle-right' | 'triangle-left';
      readonly showZero?: boolean;
      readonly size?: 'medium' | 'large';
    };
    't-button': {
      readonly appParameter?: string;
      readonly block?: boolean;
      readonly content?: string;
      readonly customDataset?: null;
      readonly disabled?: boolean;
      readonly ghost?: boolean;
      readonly hoverClass?: string;
      readonly hoverStartTime?: number;
      readonly hoverStayTime?: number;
      readonly hoverStopPropagation?: boolean;
      readonly icon?: string | object;
      readonly lang?: 'en' | 'zh_CN' | 'zh_TW';
      readonly loading?: boolean;
      readonly loadingProps?: LoadingProps;
      readonly openType?: 'contact' | 'share' | 'getPhoneNumber' | 'getUserInfo' | 'launchApp' | 'openSetting' | 'feedback' | 'chooseAvatar' | 'agreePrivacyAuthorization';
      readonly phoneNumberNoQuotaToast?: boolean;
      readonly sendMessageImg?: string;
      readonly sendMessagePath?: string;
      readonly sendMessageTitle?: string;
      readonly sessionFrom?: string;
      readonly shape?: 'rectangle' | 'square' | 'round' | 'circle';
      readonly showMessageCard?: boolean;
      readonly size?: 'extra-small' | 'small' | 'medium' | 'large';
      readonly theme?: 'default' | 'primary' | 'danger' | 'light';
      readonly tId?: string;
      readonly type?: 'submit' | 'reset';
      readonly variant?: 'base' | 'outline' | 'dashed' | 'text';
    };
    't-calendar': {
      readonly allowSameDay?: boolean;
      readonly autoClose?: boolean;
      readonly confirmBtn?: string | ButtonProps | null;
      readonly defaultValue?: number | number[];
      readonly firstDayOfWeek?: number;
      readonly format?: CalendarFormatType;
      readonly localeText?: CalendarLocaleText;
      readonly maxDate?: number;
      readonly minDate?: number;
      readonly readonly?: boolean;
      readonly switchMode?: 'none' | 'month' | 'year-month';
      readonly title?: string;
      readonly type?: 'single' | 'multiple' | 'range';
      readonly usePopup?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly value?: number | number[];
      readonly visible?: boolean;
    };
    't-cascader': {
      readonly checkStrictly?: boolean;
      readonly closeBtn?: boolean;
      readonly defaultValue?: string | number;
      readonly keys?: CascaderKeysType;
      readonly options?: Array<CascaderOption>;
      readonly placeholder?: string;
      readonly subTitles?: Array<string>;
      readonly theme?: 'step' | 'tab';
      readonly title?: string;
      readonly value?: string | number;
      readonly visible?: boolean;
    };
    't-cell': {
      readonly align?: 'top' | 'middle' | 'bottom';
      readonly arrow?: boolean | object;
      readonly bordered?: boolean;
      readonly description?: string;
      readonly hover?: boolean;
      readonly image?: string;
      readonly jumpType?: 'switchTab' | 'reLaunch' | 'redirectTo' | 'navigateTo';
      readonly leftIcon?: string | object;
      readonly note?: string;
      readonly required?: boolean;
      readonly rightIcon?: string | object;
      readonly title?: string;
      readonly url?: string;
    };
    't-cell-group': {
      readonly bordered?: boolean;
      readonly theme?: 'default' | 'card';
      readonly title?: string;
    };
    't-check-tag': {
      readonly checked?: boolean;
      readonly closable?: boolean;
      readonly content?: string | number | string[];
      readonly defaultChecked?: boolean;
      readonly disabled?: boolean;
      readonly icon?: string | object;
      readonly shape?: 'square' | 'round' | 'mark';
      readonly size?: SizeEnum;
      readonly variant?: 'dark' | 'light' | 'outline' | 'light-outline';
    };
    't-checkbox': {
      readonly block?: boolean;
      readonly borderless?: boolean;
      readonly checkAll?: boolean;
      readonly checked?: boolean;
      readonly content?: string;
      readonly contentDisabled?: boolean;
      readonly defaultChecked?: boolean;
      readonly disabled?: boolean;
      readonly icon?: 'circle' | 'line' | 'rectangle' | string[];
      readonly indeterminate?: boolean;
      readonly label?: string;
      readonly maxContentRow?: number;
      readonly maxLabelRow?: number;
      readonly name?: string;
      readonly placement?: 'left' | 'right';
      readonly readonly?: boolean;
      readonly value?: string | number | boolean;
    };
    't-checkbox-group': {
      readonly borderless?: boolean;
      readonly defaultValue?: T;
      readonly disabled?: boolean;
      readonly keys?: KeysType;
      readonly max?: number;
      readonly name?: string;
      readonly options?: Array<CheckboxOption>;
      readonly readonly?: boolean;
      readonly value?: T;
    };
    't-col': {
      readonly offset?: string | number;
      readonly span?: string | number;
    };
    't-collapse': {
      readonly defaultExpandAll?: boolean;
      readonly defaultValue?: CollapseValue;
      readonly disabled?: boolean;
      readonly expandIcon?: boolean;
      readonly expandMutex?: boolean;
      readonly theme?: 'default' | 'card';
      readonly value?: CollapseValue;
    };
    't-collapse-panel': {
      readonly content?: string;
      readonly disabled?: boolean;
      readonly expandIcon?: boolean;
      readonly header?: string;
      readonly headerLeftIcon?: string;
      readonly headerRightContent?: string;
      readonly placement?: 'bottom' | 'top';
      readonly value?: string | number;
    };
    't-color-picker': {
      readonly autoClose?: boolean;
      readonly colorModes?: colorModesEnum | colorModesEnum[];
      readonly defaultValue?: string;
      readonly enableAlpha?: boolean;
      readonly enableMultipleGradient?: boolean;
      readonly fixed?: boolean;
      readonly format?: 'HEX' | 'HEX8' | 'RGB' | 'RGBA' | 'HSL' | 'HSLA' | 'HSV' | 'HSVA' | 'CMYK' | 'CSS';
      readonly popupProps?: PopupProps;
      readonly swatchColors?: Array<string> | null | undefined;
      readonly type?: TypeEnum;
      readonly usePopup?: boolean;
      readonly value?: string;
      readonly visible?: boolean;
    };
    't-count-down': {
      readonly autoStart?: boolean;
      readonly content?: string;
      readonly format?: string;
      readonly millisecond?: boolean;
      readonly size?: 'small' | 'medium' | 'large';
      readonly splitWithUnit?: boolean;
      readonly theme?: 'default' | 'round' | 'square';
      readonly time?: number;
    };
    't-date-time-picker': {
      readonly autoClose?: boolean;
      readonly cancelBtn?: string;
      readonly confirmBtn?: string;
      readonly customLocale?: string;
      readonly defaultValue?: DateValue;
      readonly end?: string | number;
      readonly filter?: (type: TimeModeValues, columns: DateTimePickerColumn) => DateTimePickerColumn;
      readonly format?: string;
      readonly formatter?: (option: DateTimePickerColumnItem, columnIndex: number) => DateTimePickerColumnItem;
      readonly header?: boolean;
      readonly mode?: DateTimePickerMode;
      readonly popupProps?: PopupProps;
      readonly showWeek?: boolean;
      readonly start?: string | number;
      readonly steps?: { [key in TimeModeValues]?: number };
      readonly title?: string;
      readonly usePopup?: boolean;
      readonly value?: DateValue;
      readonly visible?: boolean;
    };
    't-dialog': {
      readonly actions?: Array<ButtonProps>;
      readonly buttonLayout?: 'horizontal' | 'vertical';
      readonly cancelBtn?: string | ButtonProps | null;
      readonly closeBtn?: boolean | ButtonProps | null;
      readonly closeOnOverlayClick?: boolean;
      readonly confirmBtn?: string | ButtonProps | null;
      readonly content?: string;
      readonly overlayProps?: OverlayProps;
      readonly preventScrollThrough?: boolean;
      readonly showOverlay?: boolean;
      readonly title?: string;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-divider': {
      readonly align?: 'left' | 'right' | 'center';
      readonly content?: string;
      readonly dashed?: boolean;
      readonly layout?: 'horizontal' | 'vertical';
    };
    't-drawer': {
      readonly closeOnOverlayClick?: boolean;
      readonly destroyOnClose?: boolean;
      readonly items?: DrawerItem[];
      readonly overlayProps?: OverlayProps;
      readonly placement?: 'left' | 'right';
      readonly showOverlay?: boolean;
      readonly title?: string;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-dropdown-item': {
      readonly defaultValue?: DropdownValue;
      readonly disabled?: boolean;
      readonly keys?: KeysType;
      readonly label?: string;
      readonly multiple?: boolean;
      readonly options?: Array<DropdownOption>;
      readonly optionsColumns?: string | number;
      readonly placement?: 'left' | 'right';
      readonly value?: DropdownValue;
    };
    't-dropdown-menu': {
      readonly arrowIcon?: string | object;
      readonly closeOnClickOverlay?: boolean;
      readonly duration?: string | number;
      readonly showOverlay?: boolean;
      readonly zIndex?: number;
    };
    't-empty': {
      readonly description?: string;
      readonly icon?: string | object;
      readonly image?: string;
    };
    't-fab': {
      readonly buttonProps?: ButtonProps;
      readonly draggable?: boolean | FabDirectionEnum;
      readonly icon?: string;
      readonly style?: string;
      readonly text?: string;
      readonly usingCustomNavbar?: boolean;
      readonly yBounds?: Array<string | number>;
    };
    't-footer': {
      readonly links?: Array<LinkObj>;
      readonly logo?: FooterLogo;
      readonly text?: string;
    };
    't-form': Record<string, any>;
    't-form-item': Record<string, any>;
    't-grid': {
      readonly align?: 'left' | 'center';
      readonly border?: boolean | { color?: string; width?: string; style?: 'solid' | 'dashed' | 'dotted' | 'double' | 'groove' | 'inset' | 'outset'; };
      readonly column?: number;
      readonly gutter?: number;
      readonly hover?: boolean;
      readonly theme?: 'default' | 'card';
    };
    't-grid-item': {
      readonly badgeProps?: BadgeProps;
      readonly description?: string;
      readonly icon?: string | object;
      readonly image?: string;
      readonly imageProps?: ImageProps;
      readonly jumpType?: 'redirect-to' | 'switch-tab' | 'relaunch' | 'navigate-to';
      readonly layout?: 'vertical' | 'horizontal';
      readonly text?: string;
      readonly url?: string;
    };
    't-guide': {
      readonly backButtonProps?: ButtonProps;
      readonly counter?: string | ((params: { total: number; current: number; }) => string);
      readonly current?: number;
      readonly defaultCurrent?: number;
      readonly finishButtonProps?: ButtonProps;
      readonly hideBack?: boolean;
      readonly hideCounter?: boolean;
      readonly hideSkip?: boolean;
      readonly highlightPadding?: number;
      readonly mode?: 'popover' | 'dialog';
      readonly nextButtonProps?: ButtonProps;
      readonly showOverlay?: boolean;
      readonly skipButtonProps?: ButtonProps;
      readonly steps?: Array<GuideStep>;
      readonly usingCustomNavbar?: boolean;
      readonly zIndex?: number;
    };
    't-icon': {
      readonly color?: string;
      readonly name?: string;
      readonly prefix?: string;
      readonly size?: string | number;
    };
    't-image': {
      readonly error?: string;
      readonly height?: string | number;
      readonly lazy?: boolean;
      readonly loading?: string;
      readonly mode?: 'scaleToFill' | 'aspectFit' | 'aspectFill' | 'widthFix' | 'heightFix' | 'top' | 'bottom' | 'center' | 'left' | 'right' | 'top left' | 'top right' | 'bottom left' | 'bottom right';
      readonly shape?: 'circle' | 'round' | 'square';
      readonly showMenuByLongpress?: boolean;
      readonly src?: string;
      readonly tId?: string;
      readonly webp?: boolean;
      readonly width?: string | number;
    };
    't-image-viewer': {
      readonly backgroundColor?: string;
      readonly closeBtn?: string | boolean | object;
      readonly defaultVisible?: boolean;
      readonly deleteBtn?: string | boolean | object;
      readonly imageProps?: ImageProps;
      readonly images?: Array<string>;
      readonly initialIndex?: Number;
      readonly lazy?: boolean;
      readonly showIndex?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
    };
    't-indexes': {
      readonly current?: string | number;
      readonly defaultCurrent?: string | number;
      readonly indexList?: Array<string | number>;
      readonly sticky?: Boolean;
      readonly stickyOffset?: number;
    };
    't-indexes-anchor': {
      readonly index?: string | number;
    };
    't-input': {
      readonly adjustPosition?: boolean;
      readonly align?: 'left' | 'center' | 'right';
      readonly allowInputOverMax?: boolean;
      readonly alwaysEmbed?: boolean;
      readonly autoFocus?: boolean;
      readonly borderless?: boolean;
      readonly clearable?: boolean | object;
      readonly clearTrigger?: 'always' | 'focus';
      readonly confirmHold?: boolean;
      readonly confirmType?: 'send' | 'search' | 'next' | 'go' | 'done';
      readonly cursor?: number;
      readonly cursorColor?: string;
      readonly cursorSpacing?: number;
      readonly disabled?: boolean;
      readonly focus?: boolean;
      readonly format?: InputFormatType;
      readonly holdKeyboard?: boolean;
      readonly label?: string;
      readonly layout?: 'vertical' | 'horizontal';
      readonly maxcharacter?: number;
      readonly maxlength?: number;
      readonly placeholder?: string;
      readonly placeholderClass?: string;
      readonly placeholderStyle?: string;
      readonly prefixIcon?: string | object;
      readonly readonly?: boolean;
      readonly safePasswordCertPath?: string;
      readonly safePasswordCustomHash?: string;
      readonly safePasswordLength?: number;
      readonly safePasswordNonce?: string;
      readonly safePasswordSalt?: string;
      readonly safePasswordTimeStamp?: number;
      readonly selectionEnd?: number;
      readonly selectionStart?: number;
      readonly status?: 'default' | 'success' | 'warning' | 'error';
      readonly suffix?: string;
      readonly suffixIcon?: string | object;
      readonly tips?: string;
      readonly type?: 'text' | 'number' | 'idcard' | 'digit' | 'safe-password' | 'password' | 'nickname';
      readonly value?: InputValue;
    };
    't-link': {
      readonly content?: string;
      readonly disabled?: boolean;
      readonly hover?: boolean;
      readonly navigatorProps?: object;
      readonly prefixIcon?: string | object;
      readonly size?: SizeEnum;
      readonly suffixIcon?: string | object;
      readonly theme?: 'default' | 'primary' | 'danger' | 'warning' | 'success';
      readonly underline?: boolean;
    };
    't-loading': {
      readonly delay?: number;
      readonly duration?: number;
      readonly fullscreen?: boolean;
      readonly indicator?: boolean;
      readonly inheritColor?: boolean;
      readonly layout?: 'horizontal' | 'vertical';
      readonly loading?: boolean;
      readonly pause?: boolean;
      readonly progress?: number;
      readonly reverse?: boolean;
      readonly size?: string;
      readonly text?: string;
      readonly theme?: 'circular' | 'spinner' | 'dots';
    };
    't-message': {
      readonly align?: MessageAlignType;
      readonly closeBtn?: string | boolean | object;
      readonly content?: string;
      readonly defaultVisible?: boolean;
      readonly duration?: number;
      readonly gap?: string | number | boolean;
      readonly icon?: string | boolean | object;
      readonly link?: string | object;
      readonly marquee?: boolean | MessageMarquee;
      readonly offset?: Array<string | number>;
      readonly single?: boolean;
      readonly theme?: MessageThemeList;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-message-item': Record<string, any>;
    't-navbar': {
      readonly animation?: boolean;
      readonly delta?: number;
      readonly fixed?: boolean;
      readonly leftArrow?: boolean;
      readonly placeholder?: boolean;
      readonly safeAreaInsetTop?: boolean;
      readonly title?: string;
      readonly titleMaxLength?: number;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-notice-bar': {
      readonly content?: string | string[];
      readonly defaultVisible?: boolean;
      readonly direction?: 'horizontal' | 'vertical';
      readonly interval?: number;
      readonly marquee?: boolean | NoticeBarMarquee;
      readonly operation?: string;
      readonly prefixIcon?: string | boolean | object;
      readonly suffixIcon?: string | object;
      readonly theme?: 'info' | 'success' | 'warning' | 'error';
      readonly visible?: boolean;
    };
    't-overlay': {
      readonly backgroundColor?: string;
      readonly duration?: number;
      readonly preventScrollThrough?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-picker': {
      readonly autoClose?: boolean;
      readonly cancelBtn?: boolean | string;
      readonly confirmBtn?: boolean | string;
      readonly defaultValue?: Array<PickerValue>;
      readonly header?: boolean;
      readonly itemHeight?: number;
      readonly keys?: KeysType;
      readonly popupProps?: PopupProps;
      readonly title?: string;
      readonly usePopup?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly value?: Array<PickerValue>;
      readonly visible?: boolean;
      readonly visibleItemCount?: number;
    };
    't-picker-item': {
      readonly format?: (option: PickerItemOption, columnIndex: number) => PickerItemOption;
      readonly options?: PickerItemOption[];
    };
    't-popover': {
      readonly closeOnClickOutside?: boolean;
      readonly content?: string;
      readonly defaultVisible?: boolean;
      readonly fixed?: boolean;
      readonly placement?: 'top' | 'left' | 'right' | 'bottom' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'left-top' | 'left-bottom' | 'right-top' | 'right-bottom';
      readonly showArrow?: boolean;
      readonly theme?: 'dark' | 'light' | 'brand' | 'success' | 'warning' | 'error';
      readonly visible?: boolean;
    };
    't-popup': {
      readonly closeBtn?: boolean;
      readonly closeOnOverlayClick?: boolean;
      readonly content?: string;
      readonly defaultVisible?: boolean;
      readonly duration?: number;
      readonly overlayProps?: OverlayProps;
      readonly placement?: 'top' | 'left' | 'right' | 'bottom' | 'center';
      readonly preventScrollThrough?: boolean;
      readonly showOverlay?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-progress': {
      readonly color?: string | Array<string> | Record<string, string>;
      readonly label?: string | boolean;
      readonly percentage?: number;
      readonly size?: string | number;
      readonly status?: ProgressStatus;
      readonly strokeWidth?: string | number;
      readonly theme?: ProgressTheme;
      readonly trackColor?: string;
    };
    't-pull-down-refresh': {
      readonly defaultValue?: boolean;
      readonly disabled?: boolean;
      readonly enableBackToTop?: boolean;
      readonly enablePassive?: boolean;
      readonly loadingBarHeight?: string | number;
      readonly loadingProps?: LoadingProps;
      readonly loadingTexts?: string[];
      readonly lowerThreshold?: string | number;
      readonly maxBarHeight?: string | number;
      readonly refreshTimeout?: number;
      readonly scrollIntoView?: string;
      readonly showScrollbar?: boolean;
      readonly successDuration?: string | number;
      readonly upperThreshold?: string | number;
      readonly usingCustomNavbar?: boolean;
      readonly value?: boolean;
    };
    't-qrcode': {
      readonly bgColor?: string;
      readonly borderless?: boolean;
      readonly color?: string;
      readonly icon?: string;
      readonly iconSize?: number | { width: number; height: number; };
      readonly level?: 'L' | 'M' | 'Q' | 'H';
      readonly size?: number;
      readonly status?: QRStatus;
      readonly value?: string;
    };
    't-radio': {
      readonly allowUncheck?: boolean;
      readonly block?: boolean;
      readonly checked?: boolean;
      readonly content?: string;
      readonly contentDisabled?: boolean;
      readonly defaultChecked?: boolean;
      readonly disabled?: boolean;
      readonly icon?: 'circle' | 'line' | 'dot' | Array<string>;
      readonly label?: string;
      readonly maxContentRow?: number;
      readonly maxLabelRow?: number;
      readonly name?: string;
      readonly placement?: 'left' | 'right';
      readonly readonly?: boolean;
      readonly value?: T;
    };
    't-radio-group': {
      readonly allowUncheck?: boolean;
      readonly borderless?: boolean;
      readonly defaultValue?: T;
      readonly disabled?: boolean;
      readonly icon?: 'circle' | 'line' | 'dot' | Array<string>;
      readonly keys?: KeysType;
      readonly name?: string;
      readonly options?: Array<RadioOption>;
      readonly placement?: 'left' | 'right';
      readonly readonly?: boolean;
      readonly value?: T;
    };
    't-rate': {
      readonly allowHalf?: boolean;
      readonly color?: string | Array<string>;
      readonly count?: number;
      readonly defaultValue?: number;
      readonly disabled?: boolean;
      readonly gap?: string | number;
      readonly icon?: string | string[];
      readonly iconPrefix?: string;
      readonly placement?: 'top' | 'bottom' | '';
      readonly showText?: boolean;
      readonly size?: string;
      readonly texts?: Array<string>;
      readonly value?: number;
      readonly variant?: 'outline' | 'filled';
    };
    't-result': {
      readonly description?: string;
      readonly icon?: string | boolean | object;
      readonly image?: string;
      readonly theme?: 'default' | 'success' | 'warning' | 'error';
      readonly title?: string;
    };
    't-row': {
      readonly gutter?: string | number;
    };
    't-scroll-view': {
      readonly scrollIntoView?: string;
    };
    't-search': {
      readonly action?: string;
      readonly adjustPosition?: boolean;
      readonly alwaysEmbed?: boolean;
      readonly center?: boolean;
      readonly clearable?: boolean;
      readonly clearTrigger?: 'always' | 'focus';
      readonly confirmHold?: boolean;
      readonly confirmType?: 'send' | 'search' | 'next' | 'go' | 'done';
      readonly cursor?: number;
      readonly cursorColor?: string;
      readonly cursorSpacing?: number;
      readonly disabled?: boolean;
      readonly focus?: boolean;
      readonly holdKeyboard?: boolean;
      readonly leftIcon?: string;
      readonly maxcharacter?: number;
      readonly maxlength?: number;
      readonly placeholder?: string;
      readonly placeholderClass?: string;
      readonly placeholderStyle?: string;
      readonly readonly?: boolean;
      readonly resultList?: Array<string>;
      readonly selectionEnd?: number;
      readonly selectionStart?: number;
      readonly shape?: 'square' | 'round';
      readonly type?: 'text' | 'number' | 'idcard' | 'digit' | 'nickname';
      readonly value?: string;
    };
    't-side-bar': {
      readonly defaultValue?: string | number;
      readonly value?: string | number;
    };
    't-side-bar-item': {
      readonly badgeProps?: BadgeProps;
      readonly disabled?: boolean;
      readonly icon?: string | object;
      readonly label?: string;
      readonly value?: string | number;
    };
    't-skeleton': {
      readonly animation?: 'gradient' | 'flashed' | 'none';
      readonly delay?: number;
      readonly loading?: boolean;
      readonly rowCol?: SkeletonRowCol;
      readonly theme?: 'avatar' | 'image' | 'text' | 'paragraph';
    };
    't-slider': {
      readonly defaultValue?: SliderValue;
      readonly disabled?: boolean;
      readonly label?: string | boolean;
      readonly marks?: Record<number, string> | Array<number>;
      readonly max?: number;
      readonly min?: number;
      readonly range?: boolean;
      readonly showExtremeValue?: boolean;
      readonly step?: number;
      readonly theme?: 'default' | 'capsule';
      readonly value?: SliderValue;
      readonly vertical?: boolean;
    };
    't-step-item': {
      readonly content?: string;
      readonly extra?: string;
      readonly icon?: string;
      readonly status?: StepStatus;
      readonly title?: string;
    };
    't-stepper': {
      readonly defaultValue?: string | number;
      readonly disabled?: boolean;
      readonly disableInput?: boolean;
      readonly inputWidth?: number;
      readonly integer?: boolean;
      readonly max?: number;
      readonly min?: number;
      readonly size?: SizeEnum;
      readonly step?: number;
      readonly theme?: 'normal' | 'filled' | 'outline';
      readonly value?: string | number;
    };
    't-steps': {
      readonly current?: string | number;
      readonly currentStatus?: 'default' | 'process' | 'finish' | 'error';
      readonly defaultCurrent?: string | number;
      readonly layout?: 'horizontal' | 'vertical';
      readonly readonly?: boolean;
      readonly sequence?: 'positive' | 'reverse';
      readonly theme?: 'default' | 'dot';
    };
    't-sticky': {
      readonly container?: null;
      readonly disabled?: boolean;
      readonly offsetTop?: string | number;
      readonly zIndex?: number;
    };
    't-swipe-cell': {
      readonly disabled?: boolean;
      readonly left?: Array<SwipeActionItem>;
      readonly opened?: boolean | Array<boolean>;
      readonly right?: Array<SwipeActionItem>;
    };
    't-swiper': {
      readonly autoplay?: boolean;
      readonly current?: number;
      readonly direction?: 'horizontal' | 'vertical';
      readonly displayMultipleItems?: number;
      readonly duration?: number;
      readonly easingFunction?: 'default' | 'linear' | 'easeInCubic' | 'easeOutCubic' | 'easeInOutCubic';
      readonly height?: string | number;
      readonly imageProps?: object;
      readonly interval?: number;
      readonly list?: string[] | SwiperList[];
      readonly loop?: boolean;
      readonly navigation?: SwiperNavProps | boolean;
      readonly nextMargin?: string | number;
      readonly paginationPosition?: 'top-left' | 'top' | 'top-right' | 'bottom-left' | 'bottom' | 'bottom-right';
      readonly previousMargin?: string | number;
      readonly snapToEdge?: boolean;
    };
    't-swiper-nav': {
      readonly current?: number;
      readonly direction?: 'horizontal' | 'vertical';
      readonly minShowNum?: number;
      readonly paginationPosition?: 'top-left' | 'top' | 'top-right' | 'bottom-left' | 'bottom' | 'bottom-right';
      readonly showControls?: boolean;
      readonly total?: number;
      readonly type?: SwiperNavigationType;
    };
    't-switch': {
      readonly customValue?: Array<SwitchValue>;
      readonly defaultValue?: SwitchValue;
      readonly disabled?: boolean;
      readonly icon?: string[];
      readonly label?: string[];
      readonly loading?: boolean;
      readonly size?: 'small' | 'medium' | 'large';
      readonly value?: SwitchValue;
    };
    't-tab-bar': {
      readonly bordered?: boolean;
      readonly defaultValue?: string | number | Array<string | number>;
      readonly fixed?: boolean;
      readonly placeholder?: boolean;
      readonly safeAreaInsetBottom?: boolean;
      readonly shape?: 'normal' | 'round';
      readonly split?: boolean;
      readonly theme?: 'normal' | 'tag';
      readonly value?: string | number | Array<string | number>;
      readonly zIndex?: number;
    };
    't-tab-bar-item': {
      readonly badgeProps?: BadgeProps;
      readonly icon?: string | object;
      readonly subTabBar?: SubTabBarItem[];
      readonly value?: string | number;
    };
    't-tab-panel': {
      readonly badgeProps?: object;
      readonly disabled?: boolean;
      readonly icon?: string | object;
      readonly label?: string;
      readonly lazy?: boolean;
      readonly panel?: string;
      readonly value?: TabValue;
    };
    't-tabs': {
      readonly animation?: TabAnimation;
      readonly bottomLineMode?: 'fixed' | 'auto' | 'full';
      readonly defaultValue?: TabValue;
      readonly showBottomLine?: boolean;
      readonly spaceEvenly?: boolean;
      readonly split?: boolean;
      readonly sticky?: boolean;
      readonly stickyProps?: StickyProps;
      readonly swipeable?: boolean;
      readonly theme?: 'line' | 'tag' | 'card';
      readonly value?: TabValue;
    };
    't-tag': {
      readonly closable?: boolean | object;
      readonly disabled?: boolean;
      readonly icon?: string | object;
      readonly maxWidth?: string | number;
      readonly shape?: 'square' | 'round' | 'mark';
      readonly size?: 'small' | 'medium' | 'large' | 'extra-large';
      readonly theme?: 'default' | 'primary' | 'warning' | 'danger' | 'success';
      readonly variant?: 'dark' | 'light' | 'outline' | 'light-outline';
    };
    't-textarea': {
      readonly adjustPosition?: boolean;
      readonly allowInputOverMax?: boolean;
      readonly autofocus?: boolean;
      readonly autosize?: boolean | { maxHeight?: number; minHeight?: number; };
      readonly bordered?: boolean;
      readonly confirmHold?: boolean;
      readonly confirmType?: 'return' | 'send' | 'search' | 'next' | 'go' | 'done';
      readonly cursor?: number;
      readonly cursorColor?: string;
      readonly cursorSpacing?: number;
      readonly defaultValue?: TextareaValue;
      readonly disabled?: boolean;
      readonly disableDefaultPadding?: boolean;
      readonly fixed?: boolean;
      readonly focus?: boolean;
      readonly holdKeyboard?: boolean;
      readonly indicator?: boolean;
      readonly label?: string;
      readonly maxcharacter?: number;
      readonly maxlength?: number;
      readonly placeholder?: string;
      readonly placeholderClass?: string;
      readonly placeholderStyle?: string;
      readonly readonly?: boolean;
      readonly selectionEnd?: number;
      readonly selectionStart?: number;
      readonly showConfirmBar?: boolean;
      readonly value?: TextareaValue;
    };
    't-toast': {
      readonly direction?: 'row' | 'column';
      readonly duration?: number;
      readonly icon?: string | object;
      readonly message?: string;
      readonly overlayProps?: OverlayProps;
      readonly placement?: 'top' | 'middle' | 'bottom';
      readonly preventScrollThrough?: boolean;
      readonly showOverlay?: boolean;
      readonly theme?: 'loading' | 'success' | 'warning' | 'error';
      readonly usingCustomNavbar?: boolean;
    };
    't-transition': {
      readonly appear?: boolean;
      readonly destoryOnHide?: boolean;
      readonly durations?: number | number[];
      readonly name?: string;
      readonly visible?: boolean;
    };
    't-tree-select': {
      readonly customValue?: TreeSelectValue;
      readonly defaultValue?: TreeSelectValue;
      readonly height?: string | number;
      readonly keys?: TreeKeysType;
      readonly multiple?: boolean;
      readonly options?: Array<DataOption>;
      readonly value?: TreeSelectValue;
    };
    't-upload': {
      readonly addBtn?: boolean;
      readonly addContent?: string;
      readonly allowUploadDuplicateFile?: boolean;
      readonly config?: UploadMpConfig;
      readonly defaultFiles?: Array<UploadFile>;
      readonly disabled?: boolean;
      readonly draggable?: boolean | { vibrate?: boolean; collisionVibrate?: boolean; };
      readonly files?: Array<UploadFile>;
      readonly gridConfig?: { column?: number; width?: number; height?: number; };
      readonly gutter?: number;
      readonly imageProps?: ImageProps;
      readonly max?: number;
      readonly mediaType?: Array<MediaType>;
      readonly preview?: boolean;
      readonly removeBtn?: boolean;
      readonly requestMethod?: null;
      readonly sizeLimit?: number | SizeLimitObj;
      readonly source?: 'media' | 'messageFile';
      readonly transition?: Transition;
    };
    't-watermark': {
      readonly alpha?: number;
      readonly content?: string;
      readonly height?: number;
      readonly isRepeat?: boolean;
      readonly layout?: 'rectangular' | 'hexagonal';
      readonly lineSpace?: number;
      readonly movable?: boolean;
      readonly moveInterval?: number;
      readonly offset?: Array<number>;
      readonly removable?: boolean;
      readonly rotate?: number;
      readonly watermarkContent?: WatermarkText | WatermarkImage | Array<WatermarkText | WatermarkImage>;
      readonly width?: number;
      readonly x?: number;
      readonly y?: number;
      readonly zIndex?: number;
    };
    'van-action-sheet': {
      readonly actions?: any[];
      readonly cancelText?: string;
      readonly closeOnClickAction?: boolean;
      readonly closeOnClickOverlay?: boolean;
      readonly description?: string;
      readonly overlay?: boolean;
      readonly rootPortal?: boolean;
      readonly round?: boolean;
      readonly safeAreaInsetBottom?: boolean;
      readonly show?: boolean;
      readonly title?: string;
      readonly zIndex?: number;
    };
    'van-area': Record<string, any>;
    'van-button': {
      readonly block?: boolean;
      readonly classPrefix?: string;
      readonly color?: string;
      readonly customStyle?: string;
      readonly dataset?: any;
      readonly disabled?: boolean;
      readonly formType?: string;
      readonly hairline?: boolean;
      readonly icon?: string;
      readonly loading?: boolean;
      readonly loadingSize?: string;
      readonly loadingText?: string;
      readonly loadingType?: string;
      readonly plain?: boolean;
      readonly round?: boolean;
      readonly size?: string;
      readonly square?: boolean;
      readonly type?: string;
    };
    'van-calendar': {
      readonly allowSameDay?: boolean;
      readonly closeOnClickOverlay?: boolean;
      readonly color?: string;
      readonly confirmDisabledText?: string;
      readonly confirmText?: string;
      readonly defaultDate?: any;
      readonly firstDayOfWeek?: number;
      readonly formatter?: any;
      readonly maxDate?: number;
      readonly maxRange?: any;
      readonly minDate?: number;
      readonly minRange?: number;
      readonly poppable?: boolean;
      readonly position?: string;
      readonly rangePrompt?: string;
      readonly readonly?: boolean;
      readonly rootPortal?: boolean;
      readonly round?: boolean;
      readonly rowHeight?: any;
      readonly safeAreaInsetBottom?: boolean;
      readonly show?: boolean;
      readonly showConfirm?: boolean;
      readonly showMark?: boolean;
      readonly showRangePrompt?: boolean;
      readonly showSubtitle?: boolean;
      readonly showTitle?: boolean;
      readonly title?: string;
      readonly type?: string;
    };
    'van-card': {
      readonly centered?: boolean;
      readonly currency?: string;
      readonly desc?: string;
      readonly lazyLoad?: boolean;
      readonly num?: string;
      readonly originPrice?: string;
      readonly price?: string;
      readonly tag?: string;
      readonly thumb?: string;
      readonly thumbLink?: string;
      readonly thumbMode?: string;
      readonly title?: string;
    };
    'van-cascader': {
      readonly activeColor?: string;
      readonly closeable?: boolean;
      readonly closeIcon?: string;
      readonly ellipsis?: boolean;
      readonly fieldNames?: Record<string, any>;
      readonly options?: any[];
      readonly placeholder?: string;
      readonly showHeader?: boolean;
      readonly swipeable?: boolean;
      readonly title?: string;
      readonly useTitleSlot?: boolean;
      readonly value?: string;
    };
    'van-cell': {
      readonly arrowDirection?: string;
      readonly border?: boolean;
      readonly center?: boolean;
      readonly clickable?: boolean;
      readonly customStyle?: string;
      readonly icon?: string;
      readonly isLink?: boolean;
      readonly label?: string;
      readonly required?: boolean;
      readonly size?: string;
      readonly title?: any;
      readonly titleStyle?: string;
      readonly titleWidth?: string;
      readonly useLabelSlot?: boolean;
      readonly value?: any;
    };
    'van-cell-group': {
      readonly border?: boolean;
      readonly inset?: boolean;
      readonly title?: string;
    };
    'van-checkbox': {
      readonly checkedColor?: string;
      readonly disabled?: boolean;
      readonly iconSize?: any;
      readonly labelDisabled?: boolean;
      readonly labelPosition?: string;
      readonly shape?: string;
      readonly useIconSlot?: boolean;
      readonly value?: boolean;
    };
    'van-checkbox-group': {
      readonly direction?: string;
      readonly disabled?: boolean;
      readonly max?: number;
      readonly value?: any[];
    };
    'van-circle': {
      readonly clockwise?: boolean;
      readonly color?: any;
      readonly fill?: string;
      readonly layerColor?: string;
      readonly lineCap?: string;
      readonly size?: number;
      readonly speed?: number;
      readonly strokeWidth?: number;
      readonly text?: string;
      readonly type?: string;
      readonly value?: number;
    };
    'van-col': {
      readonly offset?: number;
      readonly span?: number;
    };
    'van-collapse': {
      readonly accordion?: boolean;
      readonly border?: boolean;
      readonly value?: any;
    };
    'van-collapse-item': {
      readonly border?: boolean;
      readonly clickable?: boolean;
      readonly disabled?: boolean;
      readonly icon?: string;
      readonly isLink?: boolean;
      readonly label?: string;
      readonly name?: any;
      readonly size?: string;
      readonly title?: any;
      readonly value?: any;
    };
    'van-config-provider': {
      readonly themeVars?: Record<string, any>;
    };
    'van-count-down': {
      readonly autoStart?: boolean;
      readonly format?: string;
      readonly millisecond?: boolean;
      readonly time?: number;
      readonly useSlot?: boolean;
    };
    'van-datetime-picker': Record<string, any>;
    'van-definitions': Record<string, any>;
    'van-dialog': {
      readonly asyncClose?: boolean;
      readonly beforeClose?: any;
      readonly cancelButtonColor?: string;
      readonly cancelButtonText?: string;
      readonly className?: string;
      readonly closeOnClickOverlay?: boolean;
      readonly confirmButtonColor?: string;
      readonly confirmButtonId?: string;
      readonly confirmButtonOpenType?: string;
      readonly confirmButtonText?: string;
      readonly customStyle?: string;
      readonly message?: string;
      readonly messageAlign?: string;
      readonly overlay?: boolean;
      readonly overlayStyle?: string;
      readonly rootPortal?: boolean;
      readonly show?: boolean;
      readonly showCancelButton?: boolean;
      readonly showConfirmButton?: boolean;
      readonly theme?: string;
      readonly title?: string;
      readonly transition?: string;
      readonly useCancelButtonSlot?: boolean;
      readonly useConfirmButtonSlot?: boolean;
      readonly useSlot?: boolean;
      readonly useTitleSlot?: boolean;
      readonly width?: any;
      readonly zIndex?: number;
    };
    'van-divider': {
      readonly borderColor?: string;
      readonly contentPosition?: string;
      readonly customStyle?: string;
      readonly dashed?: boolean;
      readonly fontSize?: string;
      readonly hairline?: boolean;
      readonly textColor?: string;
    };
    'van-dropdown-item': {
      readonly disabled?: boolean;
      readonly options?: any[];
      readonly popupStyle?: string;
      readonly rootPortal?: boolean;
      readonly title?: string;
      readonly titleClass?: string;
      readonly useBeforeToggle?: boolean;
      readonly value?: any;
    };
    'van-dropdown-menu': {
      readonly activeColor?: string;
      readonly closeOnClickOutside?: boolean;
      readonly closeOnClickOverlay?: boolean;
      readonly direction?: string;
      readonly duration?: number;
      readonly overlay?: boolean;
      readonly safeAreaTabBar?: boolean;
      readonly zIndex?: number;
    };
    'van-empty': {
      readonly description?: string;
      readonly image?: string;
    };
    'van-field': Record<string, any>;
    'van-goods-action': {
      readonly safeAreaInsetBottom?: boolean;
    };
    'van-goods-action-button': {
      readonly color?: string;
      readonly customStyle?: string;
      readonly disabled?: boolean;
      readonly loading?: boolean;
      readonly plain?: boolean;
      readonly size?: string;
      readonly text?: string;
      readonly type?: string;
    };
    'van-goods-action-icon': {
      readonly classPrefix?: string;
      readonly color?: string;
      readonly disabled?: boolean;
      readonly dot?: boolean;
      readonly icon?: string;
      readonly info?: string;
      readonly loading?: boolean;
      readonly size?: string;
      readonly text?: string;
    };
    'van-grid': {
      readonly border?: boolean;
      readonly center?: boolean;
      readonly clickable?: boolean;
      readonly columnNum?: number;
      readonly direction?: string;
      readonly gutter?: any;
      readonly iconSize?: string;
      readonly reverse?: boolean;
      readonly square?: boolean;
    };
    'van-grid-item': {
      readonly badge?: any;
      readonly dot?: boolean;
      readonly icon?: string;
      readonly iconColor?: string;
      readonly iconPrefix?: string;
      readonly info?: any;
      readonly text?: string;
      readonly useSlot?: boolean;
    };
    'van-icon': {
      readonly classPrefix?: string;
      readonly color?: string;
      readonly customStyle?: string;
      readonly dot?: boolean;
      readonly info?: any;
      readonly name?: string;
      readonly size?: any;
    };
    'van-image': {
      readonly fit?: string;
      readonly height?: any;
      readonly lazyLoad?: boolean;
      readonly radius?: any;
      readonly round?: boolean;
      readonly showError?: boolean;
      readonly showLoading?: boolean;
      readonly showMenuByLongpress?: boolean;
      readonly src?: string;
      readonly useErrorSlot?: boolean;
      readonly useLoadingSlot?: boolean;
      readonly webp?: boolean;
      readonly width?: any;
    };
    'van-index-anchor': {
      readonly index?: any;
      readonly useSlot?: boolean;
    };
    'van-index-bar': {
      readonly highlightColor?: string;
      readonly indexList?: any[];
      readonly sticky?: boolean;
      readonly stickyOffsetTop?: number;
      readonly zIndex?: number;
    };
    'van-info': {
      readonly customStyle?: string;
      readonly dot?: boolean;
      readonly info?: any;
    };
    'van-loading': {
      readonly color?: string;
      readonly size?: string;
      readonly textSize?: string;
      readonly type?: string;
      readonly vertical?: boolean;
    };
    'van-nav-bar': {
      readonly border?: boolean;
      readonly customStyle?: string;
      readonly fixed?: boolean;
      readonly leftArrow?: boolean;
      readonly leftText?: string;
      readonly placeholder?: boolean;
      readonly rightText?: string;
      readonly safeAreaInsetTop?: boolean;
      readonly title?: string;
      readonly zIndex?: number;
    };
    'van-notice-bar': {
      readonly background?: string;
      readonly backgroundColor?: string;
      readonly color?: string;
      readonly delay?: number;
      readonly leftIcon?: string;
      readonly mode?: string;
      readonly openType?: string;
      readonly scrollable?: any;
      readonly speed?: number;
      readonly text?: string;
      readonly url?: string;
      readonly wrapable?: boolean;
    };
    'van-notify': {
      readonly background?: string;
      readonly color?: string;
      readonly duration?: number;
      readonly message?: string;
      readonly safeAreaInsetTop?: boolean;
      readonly top?: any;
      readonly type?: string;
      readonly zIndex?: number;
    };
    'van-overlay': {
      readonly customStyle?: string;
      readonly duration?: any;
      readonly lockScroll?: boolean;
      readonly rootPortal?: boolean;
      readonly show?: boolean;
      readonly zIndex?: number;
    };
    'van-panel': {
      readonly desc?: string;
      readonly status?: string;
      readonly title?: string;
    };
    'van-picker': Record<string, any>;
    'van-picker-column': {
      readonly className?: string;
      readonly defaultIndex?: number;
      readonly initialOptions?: any[];
      readonly itemHeight?: number;
      readonly valueKey?: string;
      readonly visibleItemCount?: number;
    };
    'van-popup': {
      readonly closeable?: boolean;
      readonly closeIcon?: string;
      readonly closeIconPosition?: string;
      readonly closeOnClickOverlay?: boolean;
      readonly customStyle?: string;
      readonly lockScroll?: boolean;
      readonly overlay?: boolean;
      readonly overlayStyle?: string;
      readonly position?: string;
      readonly rootPortal?: boolean;
      readonly round?: boolean;
      readonly safeAreaInsetBottom?: boolean;
      readonly safeAreaInsetTop?: boolean;
      readonly safeAreaTabBar?: boolean;
      readonly transition?: string;
      readonly zIndex?: number;
    };
    'van-progress': {
      readonly color?: string;
      readonly inactive?: boolean;
      readonly percentage?: number;
      readonly pivotColor?: string;
      readonly pivotText?: string;
      readonly showPivot?: boolean;
      readonly strokeWidth?: any;
      readonly textColor?: string;
      readonly trackColor?: string;
    };
    'van-radio': {
      readonly checkedColor?: string;
      readonly disabled?: boolean;
      readonly iconSize?: any;
      readonly labelDisabled?: boolean;
      readonly labelPosition?: string;
      readonly name?: any;
      readonly shape?: string;
      readonly useIconSlot?: boolean;
      readonly value?: any;
    };
    'van-radio-group': {
      readonly direction?: string;
      readonly disabled?: boolean;
      readonly value?: any;
    };
    'van-rate': {
      readonly allowHalf?: boolean;
      readonly color?: string;
      readonly count?: number;
      readonly disabled?: boolean;
      readonly disabledColor?: string;
      readonly gutter?: any;
      readonly icon?: string;
      readonly readonly?: boolean;
      readonly size?: any;
      readonly touchable?: boolean;
      readonly value?: number;
      readonly voidColor?: string;
      readonly voidIcon?: string;
    };
    'van-row': {
      readonly gutter?: number;
    };
    'van-search': {
      readonly actionText?: string;
      readonly background?: string;
      readonly clearable?: boolean;
      readonly clearIcon?: string;
      readonly clearTrigger?: string;
      readonly cursorSpacing?: number;
      readonly disabled?: boolean;
      readonly error?: boolean;
      readonly focus?: boolean;
      readonly inputAlign?: string;
      readonly label?: string;
      readonly leftIcon?: string;
      readonly maxlength?: number;
      readonly placeholder?: string;
      readonly placeholderStyle?: string;
      readonly readonly?: boolean;
      readonly rightIcon?: string;
      readonly shape?: string;
      readonly showAction?: boolean;
      readonly useActionSlot?: boolean;
      readonly useLeftIconSlot?: boolean;
      readonly useRightIconSlot?: boolean;
      readonly value?: string;
    };
    'van-share-sheet': {
      readonly cancelText?: string;
      readonly closeOnClickOverlay?: boolean;
      readonly description?: string;
      readonly duration?: any;
      readonly options?: any[];
      readonly overlay?: boolean;
      readonly overlayStyle?: string;
      readonly rootPortal?: boolean;
      readonly safeAreaInsetBottom?: boolean;
      readonly show?: boolean;
      readonly title?: string;
      readonly zIndex?: number;
    };
    'van-sidebar': {
      readonly activeKey?: number;
    };
    'van-sidebar-item': {
      readonly badge?: any;
      readonly disabled?: boolean;
      readonly dot?: boolean;
      readonly info?: any;
      readonly title?: string;
    };
    'van-skeleton': {
      readonly animate?: boolean;
      readonly avatar?: boolean;
      readonly avatarShape?: string;
      readonly avatarSize?: string;
      readonly loading?: boolean;
      readonly row?: number;
      readonly rowWidth?: any;
      readonly title?: boolean;
      readonly titleWidth?: string;
    };
    'van-slider': {
      readonly activeColor?: string;
      readonly barHeight?: any;
      readonly disabled?: boolean;
      readonly inactiveColor?: string;
      readonly max?: number;
      readonly min?: number;
      readonly range?: boolean;
      readonly step?: number;
      readonly useButtonSlot?: boolean;
      readonly value?: any;
      readonly vertical?: boolean;
    };
    'van-stepper': {
      readonly alwaysEmbed?: boolean;
      readonly asyncChange?: boolean;
      readonly buttonSize?: string;
      readonly decimalLength?: number;
      readonly disabled?: boolean;
      readonly disableInput?: boolean;
      readonly disableMinus?: boolean;
      readonly disablePlus?: boolean;
      readonly inputWidth?: string;
      readonly integer?: boolean;
      readonly longPress?: boolean;
      readonly max?: any;
      readonly min?: any;
      readonly showMinus?: boolean;
      readonly showPlus?: boolean;
      readonly step?: any;
      readonly theme?: string;
      readonly value?: any;
    };
    'van-steps': {
      readonly active?: number;
      readonly activeColor?: string;
      readonly activeIcon?: string;
      readonly direction?: string;
      readonly icon?: string;
      readonly inactiveColor?: string;
      readonly inactiveIcon?: string;
      readonly steps?: any[];
    };
    'van-sticky': {
      readonly container?: any;
      readonly disabled?: boolean;
      readonly offsetTop?: number;
      readonly scrollTop?: any;
      readonly zIndex?: number;
    };
    'van-submit-bar': {
      readonly buttonText?: string;
      readonly buttonType?: string;
      readonly currency?: string;
      readonly decimalLength?: number;
      readonly disabled?: boolean;
      readonly label?: string;
      readonly loading?: boolean;
      readonly price?: any;
      readonly safeAreaInsetBottom?: boolean;
      readonly suffixLabel?: string;
      readonly tip?: any;
      readonly tipIcon?: string;
      readonly type?: number;
    };
    'van-swipe-cell': {
      readonly asyncClose?: boolean;
      readonly disabled?: boolean;
      readonly leftWidth?: number;
      readonly name?: any;
      readonly rightWidth?: number;
    };
    'van-switch': {
      readonly activeColor?: string;
      readonly activeValue?: any;
      readonly checked?: any;
      readonly disabled?: boolean;
      readonly inactiveColor?: string;
      readonly inactiveValue?: any;
      readonly loading?: boolean;
      readonly size?: string;
    };
    'van-tab': {
      readonly disabled?: boolean;
      readonly dot?: boolean;
      readonly info?: any;
      readonly name?: any;
      readonly title?: string;
      readonly titleStyle?: string;
    };
    'van-tabbar': {
      readonly active?: any;
      readonly activeColor?: string;
      readonly border?: boolean;
      readonly fixed?: boolean;
      readonly inactiveColor?: string;
      readonly placeholder?: boolean;
      readonly safeAreaInsetBottom?: boolean;
      readonly zIndex?: number;
    };
    'van-tabbar-item': {
      readonly dot?: boolean;
      readonly icon?: string;
      readonly iconPrefix?: string;
      readonly info?: any;
      readonly linkType?: string;
      readonly name?: any;
      readonly url?: string;
    };
    'van-tabs': {
      readonly active?: any;
      readonly animated?: boolean;
      readonly border?: boolean;
      readonly color?: string;
      readonly duration?: number;
      readonly ellipsis?: boolean;
      readonly lazyRender?: boolean;
      readonly lineHeight?: any;
      readonly lineWidth?: any;
      readonly offsetTop?: number;
      readonly sticky?: boolean;
      readonly swipeable?: boolean;
      readonly swipeThreshold?: number;
      readonly titleActiveColor?: string;
      readonly titleInactiveColor?: string;
      readonly type?: string;
      readonly useBeforeChange?: boolean;
      readonly zIndex?: number;
    };
    'van-tag': {
      readonly closeable?: boolean;
      readonly color?: string;
      readonly mark?: boolean;
      readonly plain?: boolean;
      readonly round?: boolean;
      readonly size?: string;
      readonly textColor?: string;
      readonly type?: string;
    };
    'van-toast': {
      readonly forbidClick?: boolean;
      readonly loadingType?: string;
      readonly mask?: boolean;
      readonly message?: string;
      readonly position?: string;
      readonly show?: boolean;
      readonly type?: string;
      readonly zIndex?: number;
    };
    'van-transition': Record<string, any>;
    'van-tree-select': {
      readonly activeId?: any;
      readonly height?: any;
      readonly items?: any[];
      readonly mainActiveIndex?: number;
      readonly max?: number;
      readonly selectedIcon?: string;
    };
    'van-uploader': Record<string, any>;
  }
  export type ComponentPropName = keyof ComponentProps;
  export type ComponentProp<Name extends string> = Name extends ComponentPropName ? ComponentProps[Name] : Record<string, any>;
  export const componentProps: ComponentProps;
}
