import { describe, expect, it } from 'vitest'
import { definePage } from '@/router'

describe('router compiler-owned entries', () => {
  it('fails clearly when definePage reaches runtime uncompiled', () => {
    expect(() => definePage({ name: 'home' })).toThrow(
      'definePage() is a compiler macro and must be compiled by weapp-vite.',
    )
  })

  it('fails clearly when auto-routes is loaded outside weapp-vite', async () => {
    await expect(import('@/router/auto-routes')).rejects.toThrow(
      'wevu/router/auto-routes is generated by weapp-vite and is unavailable outside a weapp-vite build.',
    )
  })
})
