import { describe, expect, it } from 'vitest'

describe('router compiler-owned entries', () => {
  it('fails clearly when auto-routes is loaded outside weapp-vite', async () => {
    await expect(import('@/router/auto-routes')).rejects.toThrow(
      'wevu/router/auto-routes is generated by weapp-vite and is unavailable outside a weapp-vite build.',
    )
  })
})
