import { describe, expect, it } from 'vitest'
import { createStatefulHmrControlSource, statefulHmrRolldownRuntimeSource } from './runtimeSource'

describe('stateful hmr runtime source', () => {
  it('uses static runtime hooks without dynamic evaluation', () => {
    expect(statefulHmrRolldownRuntimeSource).toContain('class WeappViteDevRuntime extends BaseDevRuntime')
    expect(statefulHmrRolldownRuntimeSource).toContain('Page(definition) { return registerDefinition(\'Page\', definition); }')
    expect(statefulHmrRolldownRuntimeSource).not.toContain('globalThis[name] = function')
    expect(statefulHmrRolldownRuntimeSource).toContain('!runtime.applyingPatch && runtime.patchedModules.has(moduleId)')
    expect(statefulHmrRolldownRuntimeSource).not.toContain('!this.applyingPatch && this.patchedModules.has(id)')
    expect(statefulHmrRolldownRuntimeSource).toContain('installNative(name, registration)')
    expect(statefulHmrRolldownRuntimeSource).toContain('takeNativeDefinitions(name)')
    expect(statefulHmrRolldownRuntimeSource).toContain('if (name === \'Component\')')
    expect(statefulHmrRolldownRuntimeSource).toContain('this.registrationModuleId = id')
    expect(statefulHmrRolldownRuntimeSource).toContain('this.registrationModuleId = moduleId')
    expect(statefulHmrRolldownRuntimeSource).toContain('initModule(id)')
    expect(statefulHmrRolldownRuntimeSource).toContain('this.currentModuleId = id')
    expect(statefulHmrRolldownRuntimeSource).toContain('if (this.applyingPatch) this.patchedModules.add(id)')
    expect(statefulHmrRolldownRuntimeSource).toContain('runtime.currentModuleId || runtime.registrationModuleId || name')
    expect(statefulHmrRolldownRuntimeSource).toContain('if (!wevuRefreshes.has(moduleId)) definitions.set(moduleId, definition)')
    expect(statefulHmrRolldownRuntimeSource).toContain('const callLatestWevuFunction = (instance, path, fallback, args) =>')
    expect(statefulHmrRolldownRuntimeSource).toContain('const pageHookNames = [\'onLoad\', \'onShow\', \'onReady\', \'onHide\', \'onResize\', \'onUnload\'')
    expect(statefulHmrRolldownRuntimeSource).toContain('methods[name] = function (...args)')
    expect(statefulHmrRolldownRuntimeSource).toContain('callLatestWevuFunction(this, \'methods.\' + name, fallback, args)')
    expect(statefulHmrRolldownRuntimeSource).toContain('callLatestWevuFunction(this, \'lifetimes.\' + name, fallback, args)')
    expect(statefulHmrRolldownRuntimeSource).toContain('callLatestWevuFunction(this, \'pageLifetimes.\' + name, fallback, args)')
    expect(statefulHmrRolldownRuntimeSource).toContain('refreshWevuInstance(this, moduleId)')
    expect(statefulHmrRolldownRuntimeSource).toContain('const instanceSnapshots = new WeakMap()')
    expect(statefulHmrRolldownRuntimeSource).toContain('const moduleSnapshots = new Map()')
    expect(statefulHmrRolldownRuntimeSource).toContain('restoreInstanceState(instance, moduleId)')
    expect(statefulHmrRolldownRuntimeSource).toContain('if ((wevuRefreshGenerations.get(moduleId) || 0) > 0)')
    expect(statefulHmrRolldownRuntimeSource).toContain('wevuInstanceGenerations.get(instance)?.get(moduleId) === generation')
    expect(statefulHmrRolldownRuntimeSource).toContain('if (!suppressLifecycles) moduleSnapshots.delete(moduleId)')
    expect(statefulHmrRolldownRuntimeSource).toContain('pending.push(decorateObject(definition, moduleId, \'\', true))')
    expect(statefulHmrRolldownRuntimeSource).toContain('restoreTrackedInstances()')
    expect(statefulHmrRolldownRuntimeSource).toContain('wevuRefreshGenerations.set(moduleId')
    expect(statefulHmrRolldownRuntimeSource).toContain('runtime.currentModuleId || runtime.registrationModuleId || \'Component\'')
    expect(statefulHmrRolldownRuntimeSource).toContain('return decorateWevuComponent(definition, moduleId)')
    expect(statefulHmrRolldownRuntimeSource).toContain('getDebugSnapshot()')
    expect(statefulHmrRolldownRuntimeSource).toContain('runtimeGlobal && !runtimeGlobal[bridgeKey]')
    expect(statefulHmrRolldownRuntimeSource.indexOf('!runtime.applyingPatch && runtime.patchedModules.has(moduleId)')).toBeLessThan(
      statefulHmrRolldownRuntimeSource.indexOf('wevuRefreshes.set(moduleId, refresh)'),
    )
    expect(statefulHmrRolldownRuntimeSource).toContain('original.call(globalThis, decorateObject(definition, moduleId))')
    expect(statefulHmrRolldownRuntimeSource).not.toMatch(/\beval\s*\(|new\s+Function|\bFunction\s*\(/)
  })

  it('renders authenticated metadata transport without executable HTTP payloads', () => {
    const source = createStatefulHmrControlSource({
      buildId: 'build-a',
      token: 'token-a',
      url: 'http://localhost:1234/__weapp_vite_stateful_hmr__',
    })
    expect(source).toContain('build-a')
    expect(source).toContain('token-a')
    expect(source).toContain('send(\'register\')')
    expect(source).toContain('send(\'rebuild\')')
    expect(source).toContain('getVersion() { return version; }')
    expect(source).toContain('getLastApply() { return this.lastApply; }')
    expect(source).toContain('getTransportState()')
    expect(source).toContain('lastRequestError')
    expect(source).toContain('?.stop?.()')
    expect(source).toContain('stop() {')
    expect(source).not.toContain(']) return;')
    expect(source).toContain('applyChangedModules(changedIds)')
    expect(source).toContain('applyChangedModules(meta.changedIds)')
    expect(source).toContain('runtime.removeModuleCache.call(runtime, id)')
    expect(source).toContain('runtime.initModule.call(runtime, id)')
    expect(source).not.toMatch(/\beval\s*\(|new\s+Function|\bFunction\s*\(/)
  })
})
