// Auto-generated by weapp-vite. Do not edit.
declare module 'weapp-vite/typed-components' {
  export interface ComponentProps {
    HelloWorld: {
      readonly description?: string;
      readonly docs?: string;
      readonly links?: any[];
      readonly title?: string;
    };
    [component: string]: Record<string, any>;
  }
  export type ComponentPropName = keyof ComponentProps;
  export type ComponentProp<Name extends ComponentPropName> = ComponentProps[Name];
  export const componentProps: ComponentProps;
}
