/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_MY_METHODS_PART_1 } from './myMethodsAddPhoneContactToOnGyroscopeChange'
import { WEAPI_MY_METHODS_PART_2 } from './myMethodsOnLocatedCompleteToWriteBLECharacteristicValue'

export const WEAPI_MY_METHODS = [
  ...WEAPI_MY_METHODS_PART_1,
  ...WEAPI_MY_METHODS_PART_2,
] as const
