/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
export const WEAPI_MY_NON_FUNCTION_MEMBERS = [
  'ap',
  'cloud',
  'env',
  'isIDE',
  'SDKVersion',
] as const
