/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_TT_METHODS_PART_1 } from './ttMethodsPart1'
import { WEAPI_TT_METHODS_PART_2 } from './ttMethodsPart2'

export const WEAPI_TT_METHODS = [
  ...WEAPI_TT_METHODS_PART_1,
  ...WEAPI_TT_METHODS_PART_2,
] as const
