/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
export const WEAPI_TYPE_SOURCES = {
  wx: {
    package: 'miniprogram-api-typings',
    version: '5.1.2',
  },
  my: {
    package: '@mini-types/alipay',
    version: '3.0.14',
  },
  tt: {
    package: '@douyin-microapp/typings',
    version: '1.3.1',
  },
} as const
