/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_WX_METHODS_ADD_CARD_TO_JOIN_VO_IPCHAT } from './wxMethodsAddCardToJoinVoIPChat'
import { WEAPI_WX_METHODS_LOAD_BUILT_IN_FONT_FACE_TO_POST_MESSAGE_TO_REFERRER_PAGE } from './wxMethodsLoadBuiltInFontFaceToPostMessageToReferrerPage'
import { WEAPI_WX_METHODS_PRE_DOWNLOAD_SUBPACKAGE_TO_WRITE_BLECHARACTERISTIC_VALUE } from './wxMethodsPreDownloadSubpackageToWriteBLECharacteristicValue'

export const WEAPI_WX_METHODS = [
  ...WEAPI_WX_METHODS_ADD_CARD_TO_JOIN_VO_IPCHAT,
  ...WEAPI_WX_METHODS_LOAD_BUILT_IN_FONT_FACE_TO_POST_MESSAGE_TO_REFERRER_PAGE,
  ...WEAPI_WX_METHODS_PRE_DOWNLOAD_SUBPACKAGE_TO_WRITE_BLECHARACTERISTIC_VALUE,
] as const
