/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_WX_METHODS_PART_1 } from './wxMethodsAddCardToJoinVoIPChat'
import { WEAPI_WX_METHODS_PART_2 } from './wxMethodsLoadBuiltInFontFaceToPreloadAssets'
import { WEAPI_WX_METHODS_PART_3 } from './wxMethodsPreloadSkylineViewToWriteBLECharacteristicValue'

export const WEAPI_WX_METHODS = [
  ...WEAPI_WX_METHODS_PART_1,
  ...WEAPI_WX_METHODS_PART_2,
  ...WEAPI_WX_METHODS_PART_3,
] as const
