export { BABEL_TS_MODULE_PARSER_OPTIONS, BABEL_TS_MODULE_PLUGINS, generate, getVisitorKeys, parse, parseJsLike, traverse } from './babel'
export { parseJsLikeWithEngine } from './engine'
export { babelAstEngine } from './engines/babel'
export { oxcAstEngine } from './engines/oxc'
export { mayContainPlatformApiAccess, platformApiIdentifiers } from './operations/platformApi'
export { collectRequireTokens, mayContainStaticRequireLiteral } from './operations/require'
export type { RequireToken } from './operations/require'
export { collectScriptSetupImportsFromCode } from './operations/scriptSetupImports'
export type { ScriptSetupImport } from './operations/scriptSetupImports'
export type { AstEngineName, AstParserLike, WeappAstConfig } from './types'
