export { resolveAstEngine } from './config'
export { collectComponentPropsFromCode } from './operations/componentProps'
export { collectOnPageScrollPerformanceWarnings } from './operations/onPageScroll'
export { mayContainPlatformApiAccess } from './operations/platformApi'
export { collectRequireTokens, mayContainStaticRequireLiteral } from './operations/require'
export type { RequireToken } from './operations/require'
export { collectScriptSetupImportsFromCode } from './operations/scriptSetupImports'
export { collectSetDataPickKeysFromTemplateCode } from './operations/setDataPick'
export { parseJsLikeWithEngine } from '@weapp-vite/ast'
export type { AstEngineName, AstParserLike, WeappAstConfig } from '@weapp-vite/ast'
