import type { WeapiMethodSupportMatrixItem, WeapiPlatformSupportMatrixItem } from './types'

export const WEAPI_PLATFORM_SUPPORT_MATRIX: readonly WeapiPlatformSupportMatrixItem[] = [
  {
    platform: '微信小程序',
    globalObject: '`wx`',
    typeSource: '`miniprogram-api-typings`',
    support: '✅ 全量',
  },
  {
    platform: '支付宝小程序',
    globalObject: '`my`',
    typeSource: '`@mini-types/alipay`',
    support: '✅ 全量',
  },
  {
    platform: '抖音小程序',
    globalObject: '`tt`',
    typeSource: '`@douyin-microapp/typings`',
    support: '✅ 全量',
  },
  {
    platform: '其他平台（swan/jd/xhs 等）',
    globalObject: '运行时宿主对象',
    typeSource: '运行时透传',
    support: '⚠️ 按宿主能力支持',
  },
]

export const WEAPI_METHOD_SUPPORT_MATRIX: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'showToast',
    description: '显示消息提示框。',
    wxStrategy: '直连 `wx.showToast`',
    alipayStrategy: '`title/icon` 映射到 `content/type` 后调用 `my.showToast`',
    douyinStrategy: '`icon=error` 映射为 `fail` 后调用 `tt.showToast`',
    support: '✅',
  },
  {
    method: 'showLoading',
    description: '显示 loading 提示框。',
    wxStrategy: '直连 `wx.showLoading`',
    alipayStrategy: '`title` 映射到 `content` 后调用 `my.showLoading`',
    douyinStrategy: '直连 `tt.showLoading`',
    support: '✅',
  },
  {
    method: 'showActionSheet',
    description: '显示操作菜单。',
    wxStrategy: '直连 `wx.showActionSheet`',
    alipayStrategy: '`itemList` ↔ `items`、`index` ↔ `tapIndex` 双向对齐',
    douyinStrategy: '直连 `tt.showActionSheet`；缺失时按 unsupported 报错',
    support: '✅',
  },
  {
    method: 'showModal',
    description: '显示模态弹窗。',
    wxStrategy: '直连 `wx.showModal`',
    alipayStrategy: '调用 `my.confirm` 并对齐按钮字段与 `cancel/content`；`showCancel=false`、`editable` 等场景按 unsupported 报错',
    douyinStrategy: '直连 `tt.showModal`',
    support: '⚠️',
  },
  {
    method: 'chooseImage',
    description: '选择图片。',
    wxStrategy: '直连 `wx.chooseImage`',
    alipayStrategy: '返回值 `apFilePaths` 映射到 `tempFilePaths`',
    douyinStrategy: '`tempFilePaths` 字符串转数组，缺失时从 `tempFiles.path` 兜底',
    support: '✅',
  },
  {
    method: 'chooseMedia',
    description: '选择图片或视频。',
    wxStrategy: '直连 `wx.chooseMedia`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.chooseMedia`，并补齐 `tempFiles[].tempFilePath/fileType`',
    support: '⚠️',
  },
  {
    method: 'chooseMessageFile',
    description: '选择会话文件。',
    wxStrategy: '直连 `wx.chooseMessageFile`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getFuzzyLocation',
    description: '获取模糊地理位置。',
    wxStrategy: '直连 `wx.getFuzzyLocation`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'previewMedia',
    description: '预览图片和视频。',
    wxStrategy: '直连 `wx.previewMedia`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createInterstitialAd',
    description: '创建插屏广告实例。',
    wxStrategy: '直连 `wx.createInterstitialAd`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.createInterstitialAd`',
    support: '⚠️',
  },
  {
    method: 'createRewardedVideoAd',
    description: '创建激励视频广告实例。',
    wxStrategy: '直连 `wx.createRewardedVideoAd`',
    alipayStrategy: '映射到 `my.createRewardedAd`，并将 `load/show/destroy` 参数对齐为微信调用方式',
    douyinStrategy: '直连 `tt.createRewardedVideoAd`',
    support: '⚠️',
  },
  {
    method: 'createLivePlayerContext',
    description: '创建直播播放器上下文。',
    wxStrategy: '直连 `wx.createLivePlayerContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.createLivePlayerContext`',
    support: '⚠️',
  },
  {
    method: 'createLivePusherContext',
    description: '创建直播推流上下文。',
    wxStrategy: '直连 `wx.createLivePusherContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getVideoInfo',
    description: '获取视频详细信息。',
    wxStrategy: '直连 `wx.getVideoInfo`',
    alipayStrategy: '直连 `my.getVideoInfo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'saveFile',
    description: '保存文件（跨端扩展，微信 typings 未声明同名 API）。',
    wxStrategy: '微信当前 typings 未声明同名 API，保留为跨端扩展能力',
    alipayStrategy: '请求参数 `tempFilePath` ↔ `apFilePath`、结果映射为 `savedFilePath`',
    douyinStrategy: '直连 `tt.saveFile`，并在缺失时用 `filePath` 兜底 `savedFilePath`',
    support: '⚠️',
  },
  {
    method: 'setClipboardData',
    description: '设置剪贴板内容。',
    wxStrategy: '直连 `wx.setClipboardData`',
    alipayStrategy: '转调 `my.setClipboard` 并映射 `data` → `text`',
    douyinStrategy: '直连 `tt.setClipboardData`',
    support: '✅',
  },
  {
    method: 'getClipboardData',
    description: '获取剪贴板内容。',
    wxStrategy: '直连 `wx.getClipboardData`',
    alipayStrategy: '转调 `my.getClipboard` 并映射 `text` → `data`',
    douyinStrategy: '直连 `tt.getClipboardData`',
    support: '✅',
  },
  {
    method: 'chooseAddress',
    description: '选择收货地址。',
    wxStrategy: '直连 `wx.chooseAddress`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.chooseAddress`',
    support: '⚠️',
  },
  {
    method: 'createAudioContext',
    description: '创建音频上下文。',
    wxStrategy: '直连 `wx.createAudioContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createWebAudioContext',
    description: '创建 WebAudio 上下文。',
    wxStrategy: '直连 `wx.createWebAudioContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSystemInfoAsync',
    description: '异步获取系统信息。',
    wxStrategy: '直连 `wx.getSystemInfoAsync`',
    alipayStrategy: '映射到 `my.getSystemInfo`',
    douyinStrategy: '映射到 `tt.getSystemInfo`',
    support: '⚠️',
  },
  {
    method: 'openAppAuthorizeSetting',
    description: '打开小程序授权设置页。',
    wxStrategy: '直连 `wx.openAppAuthorizeSetting`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'pluginLogin',
    description: '插件登录。',
    wxStrategy: '直连 `wx.pluginLogin`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'login',
    description: '登录。',
    wxStrategy: '直连 `wx.login`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.login`',
    support: '⚠️',
  },
  {
    method: 'authorize',
    description: '提前向用户发起授权请求。',
    wxStrategy: '直连 `wx.authorize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.authorize`',
    support: '⚠️',
  },
  {
    method: 'checkSession',
    description: '检查登录态是否过期。',
    wxStrategy: '直连 `wx.checkSession`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.checkSession`',
    support: '⚠️',
  },
  {
    method: 'requestSubscribeDeviceMessage',
    description: '请求订阅设备消息。',
    wxStrategy: '直连 `wx.requestSubscribeDeviceMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestSubscribeEmployeeMessage',
    description: '请求订阅员工消息。',
    wxStrategy: '直连 `wx.requestSubscribeEmployeeMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'restartMiniProgram',
    description: '重启小程序。',
    wxStrategy: '直连 `wx.restartMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'scanCode',
    description: '扫码。',
    wxStrategy: '直连 `wx.scanCode`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.scanCode`',
    support: '⚠️',
  },
  {
    method: 'requestPayment',
    description: '发起支付。',
    wxStrategy: '直连 `wx.requestPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestOrderPayment',
    description: '发起订单支付。',
    wxStrategy: '直连 `wx.requestOrderPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestPluginPayment',
    description: '发起插件支付。',
    wxStrategy: '直连 `wx.requestPluginPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestVirtualPayment',
    description: '发起虚拟支付。',
    wxStrategy: '直连 `wx.requestVirtualPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'showShareImageMenu',
    description: '显示分享图片菜单。',
    wxStrategy: '直连 `wx.showShareImageMenu`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'updateShareMenu',
    description: '更新分享菜单配置。',
    wxStrategy: '直连 `wx.updateShareMenu`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openEmbeddedMiniProgram',
    description: '打开嵌入式小程序。',
    wxStrategy: '直连 `wx.openEmbeddedMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'saveFileToDisk',
    description: '保存文件到磁盘。',
    wxStrategy: '直连 `wx.saveFileToDisk`',
    alipayStrategy: '直连 `my.saveFileToDisk`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getEnterOptionsSync',
    description: '获取启动参数（同步）。',
    wxStrategy: '直连 `wx.getEnterOptionsSync`',
    alipayStrategy: '直连 `my.getEnterOptionsSync`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSystemSetting',
    description: '获取系统设置。',
    wxStrategy: '直连 `wx.getSystemSetting`',
    alipayStrategy: '直连 `my.getSystemSetting`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getUserProfile',
    description: '获取用户资料。',
    wxStrategy: '直连 `wx.getUserProfile`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.getUserProfile`',
    support: '⚠️',
  },
  {
    method: 'getUserInfo',
    description: '获取用户信息。',
    wxStrategy: '直连 `wx.getUserInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.getUserInfo`',
    support: '⚠️',
  },
  {
    method: 'getAppAuthorizeSetting',
    description: '获取 App 授权设置。',
    wxStrategy: '直连 `wx.getAppAuthorizeSetting`',
    alipayStrategy: '直连 `my.getAppAuthorizeSetting`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getAppBaseInfo',
    description: '获取 App 基础信息。',
    wxStrategy: '直连 `wx.getAppBaseInfo`',
    alipayStrategy: '直连 `my.getAppBaseInfo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'chooseVideo',
    description: '选择视频。',
    wxStrategy: '直连 `wx.chooseVideo`',
    alipayStrategy: '直连 `my.chooseVideo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'hideHomeButton',
    description: '隐藏返回首页按钮。',
    wxStrategy: '直连 `wx.hideHomeButton`',
    alipayStrategy: '映射到 `my.hideBackHome`',
    douyinStrategy: '直连 `tt.hideHomeButton`',
    support: '✅',
  },
  {
    method: 'getWindowInfo',
    description: '获取窗口信息。',
    wxStrategy: '直连 `wx.getWindowInfo`',
    alipayStrategy: '直连 `my.getWindowInfo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getDeviceInfo',
    description: '获取设备基础信息。',
    wxStrategy: '直连 `wx.getDeviceInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getAccountInfoSync',
    description: '同步获取当前账号信息。',
    wxStrategy: '直连 `wx.getAccountInfoSync`',
    alipayStrategy: '直连 `my.getAccountInfoSync`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setBackgroundColor',
    description: '动态设置窗口背景色。',
    wxStrategy: '直连 `wx.setBackgroundColor`',
    alipayStrategy: '直连 `my.setBackgroundColor`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setBackgroundTextStyle',
    description: '动态设置下拉背景字体样式。',
    wxStrategy: '直连 `wx.setBackgroundTextStyle`',
    alipayStrategy: '直连 `my.setBackgroundTextStyle`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getNetworkType',
    description: '获取网络类型。',
    wxStrategy: '直连 `wx.getNetworkType`',
    alipayStrategy: '直连 `my.getNetworkType`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getBatteryInfo',
    description: '异步获取电量信息。',
    wxStrategy: '直连 `wx.getBatteryInfo`',
    alipayStrategy: '直连 `my.getBatteryInfo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getBatteryInfoSync',
    description: '同步获取电量信息。',
    wxStrategy: '直连 `wx.getBatteryInfoSync`',
    alipayStrategy: '直连 `my.getBatteryInfoSync`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getLogManager',
    description: '获取日志管理器实例。',
    wxStrategy: '直连 `wx.getLogManager`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'nextTick',
    description: '延迟到下一个 UI 更新时机执行回调。',
    wxStrategy: '直连 `wx.nextTick`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'onWindowResize',
    description: '监听窗口尺寸变化事件。',
    wxStrategy: '直连 `wx.onWindowResize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.onWindowResize`',
    support: '⚠️',
  },
  {
    method: 'offWindowResize',
    description: '取消监听窗口尺寸变化事件。',
    wxStrategy: '直连 `wx.offWindowResize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.offWindowResize`',
    support: '⚠️',
  },
  {
    method: 'reportAnalytics',
    description: '上报分析数据。',
    wxStrategy: '直连 `wx.reportAnalytics`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.reportAnalytics`',
    support: '⚠️',
  },
  {
    method: 'openCustomerServiceChat',
    description: '打开客服会话。',
    wxStrategy: '直连 `wx.openCustomerServiceChat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createVKSession',
    description: '创建视觉识别会话。',
    wxStrategy: '直连 `wx.createVKSession`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'compressVideo',
    description: '压缩视频文件。',
    wxStrategy: '直连 `wx.compressVideo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openVideoEditor',
    description: '打开视频编辑器。',
    wxStrategy: '直连 `wx.openVideoEditor`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getShareInfo',
    description: '获取转发详细信息。',
    wxStrategy: '直连 `wx.getShareInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'joinVoIPChat',
    description: '加入音视频通话。',
    wxStrategy: '直连 `wx.joinVoIPChat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openDocument',
    description: '打开文档。',
    wxStrategy: '直连 `wx.openDocument`',
    alipayStrategy: '直连 `my.openDocument`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'saveVideoToPhotosAlbum',
    description: '保存视频到系统相册。',
    wxStrategy: '直连 `wx.saveVideoToPhotosAlbum`',
    alipayStrategy: '直连 `my.saveVideoToPhotosAlbum`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'batchSetStorage',
    description: '批量异步写入缓存。',
    wxStrategy: '直连 `wx.batchSetStorage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'batchGetStorage',
    description: '批量异步读取缓存。',
    wxStrategy: '直连 `wx.batchGetStorage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'batchSetStorageSync',
    description: '批量同步写入缓存。',
    wxStrategy: '直连 `wx.batchSetStorageSync`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'batchGetStorageSync',
    description: '批量同步读取缓存。',
    wxStrategy: '直连 `wx.batchGetStorageSync`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createCameraContext',
    description: '创建相机上下文对象。',
    wxStrategy: '直连 `wx.createCameraContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'offMemoryWarning',
    description: '取消内存不足告警监听。',
    wxStrategy: '直连 `wx.offMemoryWarning`',
    alipayStrategy: '直连 `my.offMemoryWarning`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'cancelIdleCallback',
    description: '取消空闲回调。',
    wxStrategy: '直连 `wx.cancelIdleCallback`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'onBLEConnectionStateChange',
    description: '监听 BLE 连接状态变化。',
    wxStrategy: '直连 `wx.onBLEConnectionStateChange`',
    alipayStrategy: '映射到 `my.onBLEConnectionStateChanged`',
    douyinStrategy: '抖音无同等 API，调用时报 not supported',
    support: '⚠️',
  },
  {
    method: 'offBLEConnectionStateChange',
    description: '取消监听 BLE 连接状态变化。',
    wxStrategy: '直连 `wx.offBLEConnectionStateChange`',
    alipayStrategy: '映射到 `my.offBLEConnectionStateChanged`',
    douyinStrategy: '抖音无同等 API，调用时报 not supported',
    support: '⚠️',
  },
  {
    method: 'addCard',
    description: '添加微信卡券。',
    wxStrategy: '直连 `wx.addCard`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addFileToFavorites',
    description: '添加文件到收藏。',
    wxStrategy: '直连 `wx.addFileToFavorites`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPaymentPassFinish',
    description: '添加支付 pass 完成回调。',
    wxStrategy: '直连 `wx.addPaymentPassFinish`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPaymentPassGetCertificateData',
    description: '添加支付 pass 证书数据回调。',
    wxStrategy: '直连 `wx.addPaymentPassGetCertificateData`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPhoneCalendar',
    description: '添加日历事件。',
    wxStrategy: '直连 `wx.addPhoneCalendar`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPhoneContact',
    description: '添加手机联系人。',
    wxStrategy: '直连 `wx.addPhoneContact`',
    alipayStrategy: '直连 `my.addPhoneContact`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPhoneRepeatCalendar',
    description: '添加重复日历事件。',
    wxStrategy: '直连 `wx.addPhoneRepeatCalendar`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addVideoToFavorites',
    description: '添加视频到收藏。',
    wxStrategy: '直连 `wx.addVideoToFavorites`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'authorizeForMiniProgram',
    description: '获取小程序授权码。',
    wxStrategy: '直连 `wx.authorizeForMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'authPrivateMessage',
    description: '校验私密消息。',
    wxStrategy: '直连 `wx.authPrivateMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'bindEmployeeRelation',
    description: '绑定员工关系。',
    wxStrategy: '直连 `wx.bindEmployeeRelation`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'canAddSecureElementPass',
    description: '检测是否可添加安全元素卡片。',
    wxStrategy: '直连 `wx.canAddSecureElementPass`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'canvasGetImageData',
    description: '获取 canvas 区域像素数据。',
    wxStrategy: '直连 `wx.canvasGetImageData`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'canvasPutImageData',
    description: '将像素数据绘制到 canvas。',
    wxStrategy: '直连 `wx.canvasPutImageData`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkDeviceSupportHevc',
    description: '检测设备是否支持 HEVC 解码。',
    wxStrategy: '直连 `wx.checkDeviceSupportHevc`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkEmployeeRelation',
    description: '查询员工关系绑定状态。',
    wxStrategy: '直连 `wx.checkEmployeeRelation`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsAddedToMyMiniProgram',
    description: '检测是否已添加到我的小程序。',
    wxStrategy: '直连 `wx.checkIsAddedToMyMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsOpenAccessibility',
    description: '检测系统无障碍是否开启。',
    wxStrategy: '直连 `wx.checkIsOpenAccessibility`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsPictureInPictureActive',
    description: '检测是否处于画中画状态。',
    wxStrategy: '直连 `wx.checkIsPictureInPictureActive`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsSoterEnrolledInDevice',
    description: '检测设备是否录入 SOTER 信息。',
    wxStrategy: '直连 `wx.checkIsSoterEnrolledInDevice`',
    alipayStrategy: '映射到 `my.checkIsIfaaEnrolledInDevice`，`speech` 模式按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'checkIsSupportSoterAuthentication',
    description: '检测设备是否支持 SOTER 生物认证。',
    wxStrategy: '直连 `wx.checkIsSupportSoterAuthentication`',
    alipayStrategy: '映射到 `my.checkIsSupportIfaaAuthentication`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openCard',
    description: '打开卡券详情。',
    wxStrategy: '直连 `wx.openCard`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsActivity',
    description: '打开视频号活动页。',
    wxStrategy: '直连 `wx.openChannelsActivity`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsEvent',
    description: '打开视频号活动详情。',
    wxStrategy: '直连 `wx.openChannelsEvent`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsLive',
    description: '打开视频号直播。',
    wxStrategy: '直连 `wx.openChannelsLive`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsLiveNoticeInfo',
    description: '打开视频号直播预告详情。',
    wxStrategy: '直连 `wx.openChannelsLiveNoticeInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChannelsUserProfile',
    description: '打开视频号用户主页。',
    wxStrategy: '直连 `wx.openChannelsUserProfile`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openChatTool',
    description: '打开客服工具页。',
    wxStrategy: '直连 `wx.openChatTool`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openHKOfflinePayView',
    description: '打开香港线下支付视图。',
    wxStrategy: '直连 `wx.openHKOfflinePayView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openInquiriesTopic',
    description: '打开询价话题。',
    wxStrategy: '直连 `wx.openInquiriesTopic`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openOfficialAccountArticle',
    description: '打开公众号文章。',
    wxStrategy: '直连 `wx.openOfficialAccountArticle`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openOfficialAccountChat',
    description: '打开公众号会话。',
    wxStrategy: '直连 `wx.openOfficialAccountChat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openOfficialAccountProfile',
    description: '打开公众号主页。',
    wxStrategy: '直连 `wx.openOfficialAccountProfile`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openPrivacyContract',
    description: '打开隐私协议页面。',
    wxStrategy: '直连 `wx.openPrivacyContract`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openSystemBluetoothSetting',
    description: '打开系统蓝牙设置页面。',
    wxStrategy: '直连 `wx.openSystemBluetoothSetting`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'reportEvent',
    description: '上报事件埋点。',
    wxStrategy: '直连 `wx.reportEvent`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'reportMonitor',
    description: '上报监控数据。',
    wxStrategy: '直连 `wx.reportMonitor`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'reportPerformance',
    description: '上报性能数据。',
    wxStrategy: '直连 `wx.reportPerformance`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openSingleStickerView',
    description: '打开单个表情贴纸详情。',
    wxStrategy: '直连 `wx.openSingleStickerView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openStickerIPView',
    description: '打开表情 IP 页面。',
    wxStrategy: '直连 `wx.openStickerIPView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openStickerSetView',
    description: '打开表情包详情页。',
    wxStrategy: '直连 `wx.openStickerSetView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openStoreCouponDetail',
    description: '打开小店优惠券详情。',
    wxStrategy: '直连 `wx.openStoreCouponDetail`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openStoreOrderDetail',
    description: '打开小店订单详情。',
    wxStrategy: '直连 `wx.openStoreOrderDetail`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'pauseBackgroundAudio',
    description: '暂停后台音频。',
    wxStrategy: '直连 `wx.pauseBackgroundAudio`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'pauseVoice',
    description: '暂停播放语音。',
    wxStrategy: '直连 `wx.pauseVoice`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'playBackgroundAudio',
    description: '播放后台音频。',
    wxStrategy: '直连 `wx.playBackgroundAudio`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'playVoice',
    description: '播放语音。',
    wxStrategy: '直连 `wx.playVoice`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'postMessageToReferrerMiniProgram',
    description: '向来源小程序发送消息。',
    wxStrategy: '直连 `wx.postMessageToReferrerMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'postMessageToReferrerPage',
    description: '向来源页面发送消息。',
    wxStrategy: '直连 `wx.postMessageToReferrerPage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'preDownloadSubpackage',
    description: '预下载分包。',
    wxStrategy: '直连 `wx.preDownloadSubpackage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'preloadAssets',
    description: '预加载资源。',
    wxStrategy: '直连 `wx.preloadAssets`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'preloadSkylineView',
    description: '预加载 Skyline 视图。',
    wxStrategy: '直连 `wx.preloadSkylineView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'preloadWebview',
    description: '预加载 WebView 页面。',
    wxStrategy: '直连 `wx.preloadWebview`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'removeSecureElementPass',
    description: '移除安全元素卡片。',
    wxStrategy: '直连 `wx.removeSecureElementPass`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'chooseInvoiceTitle',
    description: '选择发票抬头。',
    wxStrategy: '直连 `wx.chooseInvoiceTitle`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'chooseLicensePlate',
    description: '选择车牌号。',
    wxStrategy: '直连 `wx.chooseLicensePlate`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'choosePoi',
    description: '选择兴趣点 POI。',
    wxStrategy: '直连 `wx.choosePoi`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'closeBLEConnection',
    description: '断开低功耗蓝牙连接。',
    wxStrategy: '直连 `wx.closeBLEConnection`',
    alipayStrategy: '`deviceId` 对齐后映射到 `my.disconnectBLEDevice`，并将 `errorCode/errorMessage` 映射为 `errCode/errMsg`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createBLEConnection',
    description: '创建低功耗蓝牙连接。',
    wxStrategy: '直连 `wx.createBLEConnection`',
    alipayStrategy: '`deviceId/timeout` 对齐后映射到 `my.connectBLEDevice`，并将 `error/errorMessage` 映射为 `errCode/errMsg`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'cropImage',
    description: '裁剪图片。',
    wxStrategy: '直连 `wx.cropImage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'editImage',
    description: '编辑图片。',
    wxStrategy: '直连 `wx.editImage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'exitVoIPChat',
    description: '退出音视频通话。',
    wxStrategy: '直连 `wx.exitVoIPChat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'faceDetect',
    description: '人脸检测。',
    wxStrategy: '直连 `wx.faceDetect`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getApiCategory',
    description: '获取 API 分类信息。',
    wxStrategy: '直连 `wx.getApiCategory`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getBackgroundFetchToken',
    description: '获取后台拉取 token。',
    wxStrategy: '直连 `wx.getBackgroundFetchToken`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getChannelsLiveInfo',
    description: '获取视频号直播信息。',
    wxStrategy: '直连 `wx.getChannelsLiveInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getChannelsLiveNoticeInfo',
    description: '获取视频号直播预告信息。',
    wxStrategy: '直连 `wx.getChannelsLiveNoticeInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getChannelsShareKey',
    description: '获取视频号分享 key。',
    wxStrategy: '直连 `wx.getChannelsShareKey`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getChatToolInfo',
    description: '获取客服工具信息。',
    wxStrategy: '直连 `wx.getChatToolInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getCommonConfig',
    description: '获取通用配置。',
    wxStrategy: '直连 `wx.getCommonConfig`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getGroupEnterInfo',
    description: '获取群聊进入信息。',
    wxStrategy: '直连 `wx.getGroupEnterInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getPrivacySetting',
    description: '获取隐私设置。',
    wxStrategy: '直连 `wx.getPrivacySetting`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'initFaceDetect',
    description: '初始化人脸检测。',
    wxStrategy: '直连 `wx.initFaceDetect`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'join1v1Chat',
    description: '发起 1v1 通话。',
    wxStrategy: '直连 `wx.join1v1Chat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareAppMessageToGroup',
    description: '分享到群聊会话。',
    wxStrategy: '直连 `wx.shareAppMessageToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareEmojiToGroup',
    description: '分享到群聊表情。',
    wxStrategy: '直连 `wx.shareEmojiToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareFileMessage',
    description: '分享文件消息。',
    wxStrategy: '直连 `wx.shareFileMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareFileToGroup',
    description: '分享文件到群。',
    wxStrategy: '直连 `wx.shareFileToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareImageToGroup',
    description: '分享图片到群。',
    wxStrategy: '直连 `wx.shareImageToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareToOfficialAccount',
    description: '分享至公众号。',
    wxStrategy: '直连 `wx.shareToOfficialAccount`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareToWeRun',
    description: '分享至微信运动。',
    wxStrategy: '直连 `wx.shareToWeRun`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareVideoMessage',
    description: '分享视频消息。',
    wxStrategy: '直连 `wx.shareVideoMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'shareVideoToGroup',
    description: '分享视频到群。',
    wxStrategy: '直连 `wx.shareVideoToGroup`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'showRedPackage',
    description: '展示红包组件。',
    wxStrategy: '直连 `wx.showRedPackage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startDeviceMotionListening',
    description: '开始监听设备方向变化。',
    wxStrategy: '直连 `wx.startDeviceMotionListening`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startHCE',
    description: '启动 HCE 功能。',
    wxStrategy: '直连 `wx.startHCE`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startLocalServiceDiscovery',
    description: '开始本地服务发现。',
    wxStrategy: '直连 `wx.startLocalServiceDiscovery`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startLocationUpdate',
    description: '开始持续定位。',
    wxStrategy: '直连 `wx.startLocationUpdate`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startLocationUpdateBackground',
    description: '开始后台持续定位。',
    wxStrategy: '直连 `wx.startLocationUpdateBackground`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startRecord',
    description: '开始录音。',
    wxStrategy: '直连 `wx.startRecord`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'startSoterAuthentication',
    description: '开始 SOTER 认证。',
    wxStrategy: '直连 `wx.startSoterAuthentication`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopBackgroundAudio',
    description: '停止后台音频。',
    wxStrategy: '直连 `wx.stopBackgroundAudio`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopDeviceMotionListening',
    description: '停止监听设备方向变化。',
    wxStrategy: '直连 `wx.stopDeviceMotionListening`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopFaceDetect',
    description: '停止人脸检测。',
    wxStrategy: '直连 `wx.stopFaceDetect`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestCommonPayment',
    description: '发起通用支付请求。',
    wxStrategy: '直连 `wx.requestCommonPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestDeviceVoIP',
    description: '请求设备 VoIP 能力。',
    wxStrategy: '直连 `wx.requestDeviceVoIP`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestMerchantTransfer',
    description: '发起商家转账请求。',
    wxStrategy: '直连 `wx.requestMerchantTransfer`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requirePrivacyAuthorize',
    description: '请求隐私授权。',
    wxStrategy: '直连 `wx.requirePrivacyAuthorize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'reserveChannelsLive',
    description: '预约视频号直播。',
    wxStrategy: '直连 `wx.reserveChannelsLive`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'selectGroupMembers',
    description: '选择群成员。',
    wxStrategy: '直连 `wx.selectGroupMembers`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'sendHCEMessage',
    description: '发送 HCE 消息。',
    wxStrategy: '直连 `wx.sendHCEMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'sendSms',
    description: '发送短信。',
    wxStrategy: '直连 `wx.sendSms`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setBackgroundFetchToken',
    description: '设置后台拉取 token。',
    wxStrategy: '直连 `wx.setBackgroundFetchToken`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setEnable1v1Chat',
    description: '设置 1v1 通话可用状态。',
    wxStrategy: '直连 `wx.setEnable1v1Chat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setTopBarText',
    description: '设置顶栏文本。',
    wxStrategy: '直连 `wx.setTopBarText`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setWindowSize',
    description: '设置窗口尺寸。',
    wxStrategy: '直连 `wx.setWindowSize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopHCE',
    description: '停止 HCE 功能。',
    wxStrategy: '直连 `wx.stopHCE`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopLocalServiceDiscovery',
    description: '停止本地服务发现。',
    wxStrategy: '直连 `wx.stopLocalServiceDiscovery`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopLocationUpdate',
    description: '停止持续定位。',
    wxStrategy: '直连 `wx.stopLocationUpdate`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopRecord',
    description: '停止录音。',
    wxStrategy: '直连 `wx.stopRecord`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'stopVoice',
    description: '停止播放语音。',
    wxStrategy: '直连 `wx.stopVoice`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'subscribeVoIPVideoMembers',
    description: '订阅 VoIP 视频成员变化。',
    wxStrategy: '直连 `wx.subscribeVoIPVideoMembers`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'updateVoIPChatMuteConfig',
    description: '更新 VoIP 静音配置。',
    wxStrategy: '直连 `wx.updateVoIPChatMuteConfig`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'updateWeChatApp',
    description: '拉起微信升级流程。',
    wxStrategy: '直连 `wx.updateWeChatApp`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getBackgroundAudioPlayerState',
    description: '获取后台音频播放状态。',
    wxStrategy: '直连 `wx.getBackgroundAudioPlayerState`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getDeviceBenchmarkInfo',
    description: '获取设备性能评估信息。',
    wxStrategy: '直连 `wx.getDeviceBenchmarkInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getDeviceVoIPList',
    description: '获取设备 VoIP 列表。',
    wxStrategy: '直连 `wx.getDeviceVoIPList`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getHCEState',
    description: '获取 HCE 状态。',
    wxStrategy: '直连 `wx.getHCEState`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getInferenceEnvInfo',
    description: '获取推理环境信息。',
    wxStrategy: '直连 `wx.getInferenceEnvInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getNFCAdapter',
    description: '获取 NFC 适配器。',
    wxStrategy: '直连 `wx.getNFCAdapter`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getPerformance',
    description: '获取性能对象。',
    wxStrategy: '直连 `wx.getPerformance`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getRandomValues',
    description: '获取随机值。',
    wxStrategy: '直连 `wx.getRandomValues`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getRealtimeLogManager',
    description: '获取实时日志管理器。',
    wxStrategy: '直连 `wx.getRealtimeLogManager`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getRendererUserAgent',
    description: '获取渲染层 UserAgent。',
    wxStrategy: '直连 `wx.getRendererUserAgent`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getScreenRecordingState',
    description: '获取录屏状态。',
    wxStrategy: '直连 `wx.getScreenRecordingState`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSecureElementPasses',
    description: '获取安全元素卡片列表。',
    wxStrategy: '直连 `wx.getSecureElementPasses`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSelectedTextRange',
    description: '获取已选中文本范围。',
    wxStrategy: '直连 `wx.getSelectedTextRange`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getShowSplashAdStatus',
    description: '获取开屏广告展示状态。',
    wxStrategy: '直连 `wx.getShowSplashAdStatus`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSkylineInfo',
    description: '获取 Skyline 信息。',
    wxStrategy: '直连 `wx.getSkylineInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getUserCryptoManager',
    description: '获取用户加密管理器。',
    wxStrategy: '直连 `wx.getUserCryptoManager`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getWeRunData',
    description: '获取微信运动数据。',
    wxStrategy: '直连 `wx.getWeRunData`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getXrFrameSystem',
    description: '获取 XR 框架系统对象。',
    wxStrategy: '直连 `wx.getXrFrameSystem`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'isBluetoothDevicePaired',
    description: '判断蓝牙设备是否已配对。',
    wxStrategy: '直连 `wx.isBluetoothDevicePaired`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'isVKSupport',
    description: '判断是否支持视觉识别能力。',
    wxStrategy: '直连 `wx.isVKSupport`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createBLEPeripheralServer',
    description: '创建 BLE 外设服务实例。',
    wxStrategy: '直连 `wx.createBLEPeripheralServer`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createBufferURL',
    description: '创建缓冲区 URL。',
    wxStrategy: '直连 `wx.createBufferURL`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createCacheManager',
    description: '创建缓存管理器。',
    wxStrategy: '直连 `wx.createCacheManager`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createGlobalPayment',
    description: '创建全局支付对象。',
    wxStrategy: '直连 `wx.createGlobalPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createInferenceSession',
    description: '创建推理会话。',
    wxStrategy: '直连 `wx.createInferenceSession`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createMediaAudioPlayer',
    description: '创建媒体音频播放器。',
    wxStrategy: '直连 `wx.createMediaAudioPlayer`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createMediaContainer',
    description: '创建媒体容器实例。',
    wxStrategy: '直连 `wx.createMediaContainer`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createMediaRecorder',
    description: '创建媒体录制器。',
    wxStrategy: '直连 `wx.createMediaRecorder`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.createMediaRecorder`',
    support: '⚠️',
  },
  {
    method: 'createTCPSocket',
    description: '创建 TCP Socket。',
    wxStrategy: '直连 `wx.createTCPSocket`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createUDPSocket',
    description: '创建 UDP Socket。',
    wxStrategy: '直连 `wx.createUDPSocket`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createVideoDecoder',
    description: '创建视频解码器。',
    wxStrategy: '直连 `wx.createVideoDecoder`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'loadBuiltInFontFace',
    description: '加载内置字体。',
    wxStrategy: '直连 `wx.loadBuiltInFontFace`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'notifyGroupMembers',
    description: '通知群成员。',
    wxStrategy: '直连 `wx.notifyGroupMembers`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestIdleCallback',
    description: '空闲时回调请求。',
    wxStrategy: '直连 `wx.requestIdleCallback`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'revokeBufferURL',
    description: '释放缓冲区 URL。',
    wxStrategy: '直连 `wx.revokeBufferURL`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'rewriteRoute',
    description: '重写路由规则。',
    wxStrategy: '直连 `wx.rewriteRoute`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'seekBackgroundAudio',
    description: '调整后台音频播放进度。',
    wxStrategy: '直连 `wx.seekBackgroundAudio`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setEnableDebug',
    description: '设置调试开关。',
    wxStrategy: '直连 `wx.setEnableDebug`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setInnerAudioOption',
    description: '设置内部音频选项。',
    wxStrategy: '直连 `wx.setInnerAudioOption`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
] as const
