/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_MY_NON_FUNCTION_MEMBERS } from './myMembers'
import { WEAPI_MY_METHODS } from './myMethods'
import { WEAPI_TT_NON_FUNCTION_MEMBERS } from './ttMembers'
import { WEAPI_TT_METHODS } from './ttMethods'
import {
  WEAPI_PLATFORM_TYPE_SOURCES,
  WEAPI_RUNTIME_TYPE_SOURCES,
  WEAPI_TYPE_SOURCES,
} from './typeSources'
import { WEAPI_WX_NON_FUNCTION_MEMBERS } from './wxMembers'
import { WEAPI_WX_METHODS } from './wxMethods'

export const WEAPI_WECHAT_METHODS = WEAPI_WX_METHODS
export const WEAPI_WECHAT_NON_FUNCTION_MEMBERS = WEAPI_WX_NON_FUNCTION_MEMBERS
export const WEAPI_ALIPAY_METHODS = WEAPI_MY_METHODS
export const WEAPI_ALIPAY_NON_FUNCTION_MEMBERS = WEAPI_MY_NON_FUNCTION_MEMBERS
export const WEAPI_DOUYIN_METHODS = WEAPI_TT_METHODS
export const WEAPI_DOUYIN_NON_FUNCTION_MEMBERS = WEAPI_TT_NON_FUNCTION_MEMBERS

export {
  WEAPI_MY_METHODS,
  WEAPI_MY_NON_FUNCTION_MEMBERS,
  WEAPI_PLATFORM_TYPE_SOURCES,
  WEAPI_RUNTIME_TYPE_SOURCES,
  WEAPI_TT_METHODS,
  WEAPI_TT_NON_FUNCTION_MEMBERS,
  WEAPI_TYPE_SOURCES,
  WEAPI_WX_METHODS,
  WEAPI_WX_NON_FUNCTION_MEMBERS,
}

export const WEAPI_MINIPROGRAM_METHODS = WEAPI_WECHAT_METHODS
export const WEAPI_MINIPROGRAM_WECHAT_METHODS = WEAPI_WECHAT_METHODS
export const WEAPI_MINIPROGRAM_ALIPAY_METHODS = WEAPI_ALIPAY_METHODS
export const WEAPI_MINIPROGRAM_DOUYIN_METHODS = WEAPI_DOUYIN_METHODS
export type WeapiMiniProgramMethodName = (typeof WEAPI_MINIPROGRAM_METHODS)[number]
export type WeapiPlatformTypeSourceName = 'default' | 'wechat' | 'alipay' | 'douyin'
export type WeapiRuntimeTypeSourceName = 'wx' | 'my' | 'tt'
export type WeapiTypeSourceName = WeapiPlatformTypeSourceName | WeapiRuntimeTypeSourceName
export type WeapiMiniProgramWechatMethodName = (typeof WEAPI_MINIPROGRAM_WECHAT_METHODS)[number]
export type WeapiMiniProgramWxMethodName = WeapiMiniProgramMethodName
export type WeapiWechatMethodName = WeapiMiniProgramWechatMethodName
export type WeapiWxMethodName = (typeof WEAPI_WECHAT_METHODS)[number]
export type WeapiMiniProgramAlipayMethodName = (typeof WEAPI_ALIPAY_METHODS)[number]
export type WeapiAlipayMethodName = WeapiMiniProgramAlipayMethodName
export type WeapiMyMethodName = (typeof WEAPI_ALIPAY_METHODS)[number]
export type WeapiMiniProgramDouyinMethodName = (typeof WEAPI_DOUYIN_METHODS)[number]
export type WeapiDouyinMethodName = WeapiMiniProgramDouyinMethodName
export type WeapiTtMethodName = (typeof WEAPI_TT_METHODS)[number]
