/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_MY_NON_FUNCTION_MEMBERS } from './myMembers'
import { WEAPI_MY_METHODS } from './myMethods'
import { WEAPI_TT_NON_FUNCTION_MEMBERS } from './ttMembers'
import { WEAPI_TT_METHODS } from './ttMethods'
import { WEAPI_TYPE_SOURCES } from './typeSources'
import { WEAPI_WX_NON_FUNCTION_MEMBERS } from './wxMembers'
import { WEAPI_WX_METHODS } from './wxMethods'

export {
  WEAPI_MY_METHODS,
  WEAPI_MY_NON_FUNCTION_MEMBERS,
  WEAPI_TT_METHODS,
  WEAPI_TT_NON_FUNCTION_MEMBERS,
  WEAPI_TYPE_SOURCES,
  WEAPI_WX_METHODS,
  WEAPI_WX_NON_FUNCTION_MEMBERS,
}

export const WEAPI_MINIPROGRAM_METHODS = WEAPI_WX_METHODS
export type WeapiMiniProgramMethodName = (typeof WEAPI_WX_METHODS)[number]
export type WeapiWxMethodName = (typeof WEAPI_WX_METHODS)[number]
export type WeapiMyMethodName = (typeof WEAPI_MY_METHODS)[number]
export type WeapiTtMethodName = (typeof WEAPI_TT_METHODS)[number]
