/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
export const WEAPI_TYPE_SOURCES = {
  default: {
    package: 'miniprogram-api-typings',
    version: '5.1.3',
  },
  wechat: {
    package: 'miniprogram-api-typings',
    version: '5.1.3',
  },
  alipay: {
    package: '@mini-types/alipay',
    version: '3.0.14',
  },
  douyin: {
    package: '@douyin-microapp/typings',
    version: '1.3.1',
  },
  wx: {
    package: 'miniprogram-api-typings',
    version: '5.1.3',
  },
  my: {
    package: '@mini-types/alipay',
    version: '3.0.14',
  },
  tt: {
    package: '@douyin-microapp/typings',
    version: '1.3.1',
  },
} as const

export const WEAPI_PLATFORM_TYPE_SOURCES = {
  default: WEAPI_TYPE_SOURCES.default,
  wechat: WEAPI_TYPE_SOURCES.wechat,
  alipay: WEAPI_TYPE_SOURCES.alipay,
  douyin: WEAPI_TYPE_SOURCES.douyin,
} as const

export const WEAPI_RUNTIME_TYPE_SOURCES = {
  wx: WEAPI_TYPE_SOURCES.wx,
  my: WEAPI_TYPE_SOURCES.my,
  tt: WEAPI_TYPE_SOURCES.tt,
} as const
