/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_WX_METHODS_ADD_CARD_TO_IS_VKSUPPORT } from './wxMethodsAddCardToIsVKSupport'
import { WEAPI_WX_METHODS_JOIN1V1_CHAT_TO_PLUGIN_LOGIN } from './wxMethodsJoin1v1ChatToPluginLogin'
import { WEAPI_WX_METHODS_POST_MESSAGE_TO_REFERRER_MINI_PROGRAM_TO_WRITE_BLECHARACTERISTIC_VALUE } from './wxMethodsPostMessageToReferrerMiniProgramToWriteBLECharacteristicValue'

export const WEAPI_WX_METHODS = [
  ...WEAPI_WX_METHODS_ADD_CARD_TO_IS_VKSUPPORT,
  ...WEAPI_WX_METHODS_JOIN1V1_CHAT_TO_PLUGIN_LOGIN,
  ...WEAPI_WX_METHODS_POST_MESSAGE_TO_REFERRER_MINI_PROGRAM_TO_WRITE_BLECHARACTERISTIC_VALUE,
] as const
