/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_WX_METHODS_ADD_CARD_TO_HIDE_SHARE_MENU } from './wxMethodsAddCardToHideShareMenu'
import { WEAPI_WX_METHODS_HIDE_TAB_BAR_TO_OPEN_STORE_COUPON_DETAIL } from './wxMethodsHideTabBarToOpenStoreCouponDetail'
import { WEAPI_WX_METHODS_OPEN_STORE_ORDER_DETAIL_TO_WRITE_BLECHARACTERISTIC_VALUE } from './wxMethodsOpenStoreOrderDetailToWriteBLECharacteristicValue'

export const WEAPI_WX_METHODS = [
  ...WEAPI_WX_METHODS_ADD_CARD_TO_HIDE_SHARE_MENU,
  ...WEAPI_WX_METHODS_HIDE_TAB_BAR_TO_OPEN_STORE_COUPON_DETAIL,
  ...WEAPI_WX_METHODS_OPEN_STORE_ORDER_DETAIL_TO_WRITE_BLECHARACTERISTIC_VALUE,
] as const
