export const CLASS_STYLE_WXS_MODULE = '__weapp_vite'
export const CLASS_STYLE_WXS_FILE = '__weapp_vite_class_style'

export function buildClassStyleWxsTag(extension: string) {
  const normalized = extension.startsWith('.') ? extension.slice(1) : extension
  return `<wxs module="${CLASS_STYLE_WXS_MODULE}" src="./${CLASS_STYLE_WXS_FILE}.${normalized}"/>`
}

export function getClassStyleWxsSource() {
  return [
    'var hasOwn = Object.prototype.hasOwnProperty',
    '',
    'function isWordCharCode(code) {',
    '  return (code >= 48 && code <= 57)',
    '    || (code >= 65 && code <= 90)',
    '    || (code >= 97 && code <= 122)',
    '    || code === 95',
    '}',
    '',
    'function isUpperCaseCode(code) {',
    '  return code >= 65 && code <= 90',
    '}',
    '',
    'function hyphenate(str) {',
    '  if (!str) {',
    '    return \'\'',
    '  }',
    '  if (str.indexOf(\'--\') === 0) {',
    '    return str',
    '  }',
    '  var res = \'\'',
    '  for (var i = 0; i < str.length; i++) {',
    '    var code = str.charCodeAt(i)',
    '    if (isUpperCaseCode(code)) {',
    '      if (i > 0 && isWordCharCode(str.charCodeAt(i - 1))) {',
    '        res += \'-\'',
    '      }',
    '      res += String.fromCharCode(code + 32)',
    '      continue',
    '    }',
    '    res += str.charAt(i)',
    '  }',
    '  return res',
    '}',
    '',
    'function appendStyle(base, part) {',
    '  if (!part) {',
    '    return base || \'\'',
    '  }',
    '  if (!base) {',
    '    return part',
    '  }',
    '  if (base.charAt(base.length - 1) !== \';\') {',
    '    base += \';\'',
    '  }',
    '  if (part.charAt(0) === \';\') {',
    '    part = part.slice(1)',
    '  }',
    '  return base + part',
    '}',
    '',
    'function normalizeClass(value) {',
    '  var res = \'\'',
    '  if (!value) {',
    '    return res',
    '  }',
    '  if (typeof value === \'string\') {',
    '    return value',
    '  }',
    '  if (Array.isArray(value)) {',
    '    for (var i = 0; i < value.length; i++) {',
    '      var normalized = normalizeClass(value[i])',
    '      if (normalized) {',
    '        res += normalized + \' \'',
    '      }',
    '    }',
    '    return res.trim()',
    '  }',
    '  if (typeof value === \'object\') {',
    '    for (var key in value) {',
    '      if (hasOwn.call(value, key) && value[key]) {',
    '        res += key + \' \'',
    '      }',
    '    }',
    '    return res.trim()',
    '  }',
    '  return res',
    '}',
    '',
    'function stringifyStyle(obj) {',
    '  var res = \'\'',
    '  for (var key in obj) {',
    '    if (!hasOwn.call(obj, key)) {',
    '      continue',
    '    }',
    '    var val = obj[key]',
    '    if (val == null) {',
    '      continue',
    '    }',
    '    var name = hyphenate(key)',
    '    if (Array.isArray(val)) {',
    '      for (var i = 0; i < val.length; i++) {',
    '        var item = val[i]',
    '        if (item == null) {',
    '          continue',
    '        }',
    '        res = appendStyle(res, name + \':\' + item)',
    '      }',
    '    }',
    '    else {',
    '      res = appendStyle(res, name + \':\' + val)',
    '    }',
    '  }',
    '  return res',
    '}',
    '',
    'function normalizeStyle(value) {',
    '  if (value == null) {',
    '    return \'\'',
    '  }',
    '  if (typeof value === \'string\') {',
    '    return value',
    '  }',
    '  if (Array.isArray(value)) {',
    '    var res = \'\'',
    '    for (var i = 0; i < value.length; i++) {',
    '      var normalized = normalizeStyle(value[i])',
    '      if (normalized) {',
    '        res = appendStyle(res, normalized)',
    '      }',
    '    }',
    '    return res',
    '  }',
    '  if (typeof value === \'object\') {',
    '    return stringifyStyle(value)',
    '  }',
    '  return \'\'',
    '}',
    '',
    'module.exports = {',
    '  cls: normalizeClass,',
    '  style: normalizeStyle,',
    '}',
    '',
  ].join('\n')
}
