import { describe, expect, it } from 'vitest'
import * as api from '@/api'
import * as root from '@/index'
import * as reactivity from '@/reactivity'
import * as router from '@/router'
import * as runtime from '@/runtime'
import * as store from '@/store'

const ROOT_RUNTIME_EXPORTS = [
  'addMutationRecorder',
  'batch',
  'callHookList',
  'callHookReturn',
  'callUpdateHooks',
  'computed',
  'createApp',
  'createStore',
  'createWevuComponent',
  'createWevuScopedSlotComponent',
  'customRef',
  'defineComponent',
  'defineStore',
  'effect',
  'effectScope',
  'endBatch',
  'getCurrentInstance',
  'getCurrentScope',
  'getCurrentSetupContext',
  'getDeepWatchStrategy',
  'getReactiveVersion',
  'hasInjectionContext',
  'inject',
  'injectGlobal',
  'isNoSetData',
  'isRaw',
  'isReactive',
  'isRef',
  'isShallowReactive',
  'isShallowRef',
  'markNoSetData',
  'markRaw',
  'mergeModels',
  'mountRuntimeInstance',
  'nextTick',
  'normalizeClass',
  'normalizeStyle',
  'onActivated',
  'onAddToFavorites',
  'onAttached',
  'onBeforeMount',
  'onBeforeUnmount',
  'onBeforeUpdate',
  'onDeactivated',
  'onDetached',
  'onError',
  'onErrorCaptured',
  'onHide',
  'onLaunch',
  'onLoad',
  'onMemoryWarning',
  'onMounted',
  'onMoved',
  'onPageNotFound',
  'onPageScroll',
  'onPullDownRefresh',
  'onReachBottom',
  'onReady',
  'onResize',
  'onRouteDone',
  'onSaveExitState',
  'onScopeDispose',
  'onServerPrefetch',
  'onShareAppMessage',
  'onShareTimeline',
  'onShow',
  'onTabItemTap',
  'onThemeChange',
  'onUnhandledRejection',
  'onUnload',
  'onUnmounted',
  'onUpdated',
  'prelinkReactiveTree',
  'provide',
  'provideGlobal',
  'reactive',
  'readonly',
  'ref',
  'registerApp',
  'registerComponent',
  'registerPageFeedbackHost',
  'removeMutationRecorder',
  'resetWevuDefaults',
  'resolvePageFeedbackHost',
  'resolveRuntimePageLayoutName',
  'runSetupFunction',
  'setCurrentInstance',
  'setCurrentSetupContext',
  'setDeepWatchStrategy',
  'setPageLayout',
  'setRuntimeSetDataVisibility',
  'setWevuDefaults',
  'shallowReactive',
  'shallowReadonly',
  'shallowRef',
  'startBatch',
  'stop',
  'storeToRefs',
  'syncRuntimePageLayoutState',
  'syncRuntimePageLayoutStateFromRuntime',
  'teardownRuntimeInstance',
  'toRaw',
  'toRef',
  'toRefs',
  'toValue',
  'touchReactive',
  'traverse',
  'triggerRef',
  'unref',
  'unregisterPageFeedbackHost',
  'useAttrs',
  'useBindModel',
  'useDisposables',
  'useIntersectionObserver',
  'useModel',
  'useNativeInstance',
  'useNativePageRouter',
  'useNativeRouter',
  'usePageFeedbackHost',
  'usePageLayout',
  'usePageScrollThrottle',
  'useSlots',
  'useTemplateRef',
  'useUpdatePerformanceListener',
  'watch',
  'watchEffect',
] as const

describe('export barrels', () => {
  it('loads public exports', () => {
    expect(api).toMatchObject({
      createWeapi: expect.any(Function),
      wpi: expect.any(Object),
    })
    expect(router).toMatchObject({
      NavigationFailureType: expect.any(Object),
      createRouter: expect.any(Function),
      createNavigationFailure: expect.any(Function),
      isNavigationFailure: expect.any(Function),
      parseQuery: expect.any(Function),
      resolveRouteLocation: expect.any(Function),
      stringifyQuery: expect.any(Function),
      useNativePageRouter: expect.any(Function),
      useNativeRouter: expect.any(Function),
      useRoute: expect.any(Function),
      useRouter: expect.any(Function),
    })
    expect(reactivity).toBeTruthy()
    expect(runtime).toBeTruthy()
    expect(store).toBeTruthy()
    expect(root).toBeTruthy()
  })

  it('covers all runtime exports of root entry', () => {
    const keys = Object.keys(root).sort()
    expect(keys).toEqual(ROOT_RUNTIME_EXPORTS)
  })
})
