/**
 * @description 三端 API 名单（由 typings 自动提取，请勿手工修改）
 * @generated by scripts/sync-api-catalog.mjs
 */
import { WEAPI_TT_METHODS_APPLY_EC_COUPON_TO_UNSUBSCRIBE_ALL_SPECIFIED_USER_COMMENT } from './ttMethodsApplyEcCouponToUnsubscribeAllSpecifiedUserComment'
import { WEAPI_TT_METHODS_UNSUBSCRIBE_AUDIENCES_FOLLOW_ACTION_TO_VIBRATE_SHORT } from './ttMethodsUnsubscribeAudiencesFollowActionToVibrateShort'

export const WEAPI_TT_METHODS = [
  ...WEAPI_TT_METHODS_APPLY_EC_COUPON_TO_UNSUBSCRIBE_ALL_SPECIFIED_USER_COMMENT,
  ...WEAPI_TT_METHODS_UNSUBSCRIBE_AUDIENCES_FOLLOW_ACTION_TO_VIBRATE_SHORT,
] as const
