import type { ComponentMarkup } from '../../../e2e/component-library/generator'

const TEXT_MODEL = `const modelValue = ref('Ready')`
const BOOLEAN_MODEL = `const modelValue = ref(false)`
const LIST = `const list = [
  { name: 'Alpha', value: 'alpha' },
  { name: 'Beta', value: 'beta' },
]`
const SAMPLE_IMAGE_IMPORT = { name: 'sampleImage', source: '../../../assets/sample.png' } as const
const SAMPLE_ALT_IMAGE_IMPORT = { name: 'sampleAltImage', source: '../../../assets/sample-alt.png' } as const
const SAMPLE_VIDEO_IMPORT = { name: 'sampleVideo', source: '../../../assets/sample.mp4' } as const

const overrides: Record<string, ComponentMarkup> = {
  'up-action-sheet': {
    setup: `const actionSheetVisible = ref(true)
const actions = [{ name: 'Alpha' }, { name: 'Beta' }]`,
    parent: 'up-action-sheet',
    markup: '<up-action-sheet :show="actionSheetVisible" :actions="actions" title="Actions"><up-action-sheet-data :show="false" /></up-action-sheet>',
  },
  'up-agreement': { setup: BOOLEAN_MODEL, markup: '<up-agreement v-model="modelValue" text="I accept the compatibility terms" />' },
  'up-album': { imports: [SAMPLE_IMAGE_IMPORT, SAMPLE_ALT_IMAGE_IMPORT], setup: `const urls = [sampleImage, sampleAltImage]`, markup: '<up-album :urls="urls" :row-count="2" />' },
  'up-alert': { markup: '<up-alert title="Compatibility alert" description="Stable local content" type="success" />' },
  'up-avatar': { markup: '<up-avatar text="UP" size="52" />' },
  'up-avatar-group': { parent: 'up-avatar-group', markup: '<up-avatar-group><up-avatar text="A" /><up-avatar text="B" /></up-avatar-group>' },
  'up-back-top': { markup: '<up-back-top :scroll-top="800" mode="square" />' },
  'up-badge': { markup: '<up-badge :value="8"><view class="badge-anchor">Badge</view></up-badge>' },
  'up-barcode': { markup: '<up-barcode value="123456789012" :width="280" :height="90" />' },
  'up-box': { markup: '<up-box text="Stable box content" />' },
  'up-button': { interaction: { type: 'command', method: 'clickHandler', event: 'click' }, markup: '<up-button type="primary" text="Primary button" />' },
  'up-calendar': { setup: `const calendarVisible = ref(true)`, markup: '<up-calendar :show="calendarVisible" :min-date="1735689600000" :max-date="1738281600000" />' },
  'up-calendar-strip': { setup: `const selectedDate = ref('2025-01-15')`, markup: '<up-calendar-strip v-model="selectedDate" />' },
  'up-car-keyboard': { setup: BOOLEAN_MODEL, markup: '<up-car-keyboard v-model="modelValue" />' },
  'up-card': { markup: '<up-card title="Compatibility card"><view>Stable card content</view></up-card>' },
  'up-cascader': { setup: `${TEXT_MODEL}\n${LIST}`, markup: '<up-cascader v-model="modelValue" :options="list" />' },
  'up-cate-tab': { setup: `const categories = [{ name: 'Alpha', children: [{ name: 'Item' }] }]`, markup: '<up-cate-tab :list="categories" />' },
  'up-cell': { markup: '<up-cell title="Status" value="Ready" label="Representative cell" />' },
  'up-cell-group': { parent: 'up-cell-group', markup: '<up-cell-group title="Group"><up-cell title="Status" value="Ready" /></up-cell-group>' },
  'up-checkbox': { setup: BOOLEAN_MODEL, markup: '<up-checkbox v-model="modelValue" label="Accepted" name="accepted" used-alone />' },
  'up-checkbox-group': { setup: `const modelValue = ref<string[]>(['alpha'])`, parent: 'up-checkbox-group', markup: '<up-checkbox-group v-model="modelValue"><up-checkbox name="alpha" label="Alpha" /></up-checkbox-group>' },
  'up-choose': { setup: LIST, markup: '<up-choose :list="list" />' },
  'up-city-locate': { markup: '<up-city-locate city="Shanghai" />' },
  'up-code': { markup: '<up-code :seconds="60" />' },
  'up-code-input': { setup: `const modelValue = ref('1234')`, markup: '<up-code-input v-model="modelValue" :maxlength="6" />' },
  'up-col': { parent: 'up-row', markup: '<up-row :gutter="12"><up-col :span="12"><view class="grid-block">Column</view></up-col></up-row>' },
  'up-collapse': { setup: `const modelValue = ref<string[]>(['item'])`, parent: 'up-collapse', markup: '<up-collapse v-model="modelValue"><up-collapse-item name="item" title="Item">Expanded content</up-collapse-item></up-collapse>' },
  'up-collapse-item': { setup: `const modelValue = ref<string[]>(['item'])`, parent: 'up-collapse', markup: '<up-collapse v-model="modelValue"><up-collapse-item name="item" title="Item">Expanded content</up-collapse-item></up-collapse>' },
  'up-color-picker': { setup: `const modelValue = ref('#3c9cff')`, markup: '<up-color-picker v-model="modelValue" />' },
  'up-copy': { markup: '<up-copy content="Stable local text" />' },
  'up-count-down': { markup: '<up-count-down :time="65000" format="mm:ss" :auto-start="false" />' },
  'up-count-to': { markup: '<up-count-to :start-val="0" :end-val="128" :duration="0" />' },
  'up-coupon': { setup: `const coupons = [{ title: 'Stable coupon', amount: 8 }]`, markup: '<up-coupon :list="coupons" />' },
  'up-datetime-picker': { setup: `const pickerVisible = ref(true)\nconst modelValue = ref(1736928000000)`, markup: '<up-datetime-picker v-model="modelValue" :show="pickerVisible" mode="datetime" />' },
  'up-divider': { markup: '<up-divider text="Divider label" />' },
  'up-dragsort': { setup: `const dragList = ref([{ id: 1, name: 'Alpha' }, { id: 2, name: 'Beta' }])`, markup: '<up-dragsort v-model="dragList" key-name="id" />' },
  'up-dropdown': { setup: `const dropdownValue = ref('alpha')\n${LIST}`, parent: 'up-dropdown', markup: '<up-dropdown><up-dropdown-item v-model="dropdownValue" :options="list" /></up-dropdown>' },
  'up-dropdown-item': { setup: `const dropdownValue = ref('alpha')\n${LIST}`, parent: 'up-dropdown', markup: '<up-dropdown><up-dropdown-item v-model="dropdownValue" :options="list" /></up-dropdown>' },
  'up-empty': { markup: '<up-empty text="No data" mode="data" />' },
  'up-form': { setup: `const formModel = { name: 'uview-plus' }`, parent: 'up-form', markup: '<up-form :model="formModel"><up-form-item label="Name" prop="name"><up-input v-model="formModel.name" /></up-form-item></up-form>' },
  'up-form-item': { setup: `const formModel = { name: 'uview-plus' }`, parent: 'up-form', markup: '<up-form :model="formModel"><up-form-item label="Name" prop="name"><up-input v-model="formModel.name" /></up-form-item></up-form>' },
  'up-goods-sku': {
    setup: `const goodsInfo = { title: 'Stable product', price: 88, stock: 5 }
const skuTree = [{ name: 'Color', children: [{ id: 'blue', name: 'Blue' }] }]
const skuList = [{ Color: 'blue', price: 88, stock: 5 }]`,
    markup: '<up-goods-sku :goods-info="goodsInfo" :sku-tree="skuTree" :sku-list="skuList" page-inline />',
  },
  'up-grid': { parent: 'up-grid', markup: '<up-grid :col="2"><up-grid-item bg-color="#eef3fa" :custom-style="{ minHeight: \'80rpx\' }"><view class="grid-block">Home</view></up-grid-item><up-grid-item bg-color="#e8f5ec" :custom-style="{ minHeight: \'80rpx\' }"><view class="grid-block">Profile</view></up-grid-item></up-grid>' },
  'up-grid-item': { parent: 'up-grid', markup: '<up-grid :col="1"><up-grid-item bg-color="#eef3fa" :custom-style="{ minHeight: \'80rpx\' }"><view class="grid-block">Grid item</view></up-grid-item></up-grid>' },
  'up-guide': { setup: `const guideVisible = ref(false)\nconst guideSteps = [{ element: '#e2e-target', text: 'Target' }]`, markup: '<up-guide v-model="guideVisible" :steps="guideSteps" />' },
  'up-icon': { markup: '<up-icon name="checkmark-circle" size="28" color="#16a34a" />' },
  'up-image': { imports: [SAMPLE_IMAGE_IMPORT], markup: '<up-image width="120" height="80" :src="sampleImage" mode="aspectFill" />' },
  'up-index-anchor': { parent: 'up-index-list', markup: '<up-index-list :index-list="[\'A\']"><up-index-item><up-index-anchor index="A" /><up-cell title="Alpha" /></up-index-item></up-index-list>' },
  'up-index-item': { parent: 'up-index-list', markup: '<up-index-list :index-list="[\'A\']"><up-index-item><up-index-anchor index="A" /><up-cell title="Alpha" /></up-index-item></up-index-list>' },
  'up-index-list': { parent: 'up-index-list', markup: '<up-index-list :index-list="[\'A\']"><up-index-item><up-index-anchor index="A" /><up-cell title="Alpha" /></up-index-item></up-index-list>' },
  'up-input': { setup: TEXT_MODEL, interaction: { type: 'model', model: 'modelValue', value: 'Changed' }, markup: '<up-input v-model="modelValue" placeholder="Input" />' },
  'up-keyboard': { setup: BOOLEAN_MODEL, markup: '<up-keyboard v-model="modelValue" mode="number" />' },
  'up-link': { markup: '<up-link href="/" text="Stable link" :under-line="true" />' },
  'up-list': { parent: 'up-list', markup: '<up-list height="180"><up-list-item><up-cell title="List item" /></up-list-item></up-list>' },
  'up-list-item': { parent: 'up-list', markup: '<up-list height="180"><up-list-item><up-cell title="List item" /></up-list-item></up-list>' },
  'up-loading-page': { markup: '<up-loading-page :loading="false" loading-text="Ready" />' },
  'up-loadmore': { markup: '<up-loadmore status="nomore" nomore-text="No more data" />' },
  'up-markdown': { markup: '<up-markdown content="# Stable markdown" />' },
  'up-message-input': { setup: `const modelValue = ref('1234')`, markup: '<up-message-input v-model="modelValue" :maxlength="6" />' },
  'up-modal': { setup: `const modalVisible = ref(true)`, markup: '<up-modal :show="modalVisible" title="Modal" content="Stable modal content" />' },
  'up-navbar': { markup: '<up-navbar title="Navigation" :auto-back="false" />' },
  'up-navbar-mini': { markup: '<up-navbar-mini title="Mini navigation" />' },
  'up-no-network': { markup: '<up-no-network />' },
  'up-novel-reader': {
    setup: `const novelChapters = [
  { id: 'chapter-1', index: 0, title: 'Compatibility Chapter', content: ['The reader renders deterministic local content.', 'A second paragraph exercises nested reader components and layout measurement.'] },
]
const novelChapter = novelChapters[0]`,
    markup: '<view style="height: 280px"><up-novel-reader :chapters="novelChapters" :current-chapter="novelChapter" book-id="compatibility-book" :persist="false" :safe-area-inset-top="false" :safe-area-inset-bottom="false" :page-animation="false" /></view>',
  },
  'up-notice-bar': { markup: '<up-notice-bar :text="[\'Alpha notice\', \'Beta notice\']" direction="column" :duration="60000" />' },
  'up-number-box': { setup: `const modelValue = ref(2)`, markup: '<up-number-box v-model="modelValue" :min="0" :max="5" />' },
  'up-number-keyboard': { setup: BOOLEAN_MODEL, markup: '<up-number-keyboard v-model="modelValue" />' },
  'up-pagination': { setup: `const modelValue = ref(2)`, markup: '<up-pagination v-model="modelValue" :total="60" :page-size="10" />' },
  'up-parse': { markup: '<up-parse content="<p><strong>Stable</strong> parsed content</p>" />' },
  'up-picker': { setup: `const pickerVisible = ref(true)\nconst columns = [[\'Alpha\', \'Beta\']]`, markup: '<up-picker :show="pickerVisible" :columns="columns" />' },
  'up-picker-column': { setup: `const columns = ['Alpha', 'Beta']`, markup: '<up-picker-column :item-height="44" :default-index="0" :props="{ values: columns }" />' },
  'up-picker-data': { setup: `const pickerData = [{ label: 'Alpha', value: 'alpha' }]`, markup: '<up-picker-data :columns="pickerData" />' },
  'up-popover': { setup: `const popoverVisible = ref(true)\n${LIST}`, markup: '<up-popover v-model="popoverVisible" :list="list"><up-button text="Popover" /></up-popover>' },
  'up-popup': { setup: `const popupVisible = ref(true)`, markup: '<up-popup :show="popupVisible" mode="center"><view class="transition-content">Popup content</view></up-popup>' },
  'up-poster': { imports: [SAMPLE_IMAGE_IMPORT], markup: '<up-poster title="Stable poster" :image="sampleImage" />' },
  'up-pull-refresh': { setup: BOOLEAN_MODEL, markup: '<up-pull-refresh v-model="modelValue"><view>Pull refresh content</view></up-pull-refresh>' },
  'up-qrcode': { markup: '<up-qrcode value="uview-plus-3.8.108" :size="128" />' },
  'up-radio': { setup: `const modelValue = ref('alpha')`, parent: 'up-radio-group', markup: '<up-radio-group v-model="modelValue"><up-radio name="alpha" label="Alpha" /></up-radio-group>' },
  'up-radio-group': { setup: `const modelValue = ref('alpha')`, parent: 'up-radio-group', markup: '<up-radio-group v-model="modelValue"><up-radio name="alpha" label="Alpha" /><up-radio name="beta" label="Beta" /></up-radio-group>' },
  'up-rate': { setup: `const modelValue = ref(4)`, interaction: { type: 'model', model: 'modelValue', value: 3 }, markup: '<up-rate v-model="modelValue" :count="5" />' },
  'up-read-more': { markup: '<up-read-more :show-height="60"><view>Stable long content. Stable long content. Stable long content.</view></up-read-more>' },
  'up-row': { parent: 'up-row', markup: '<up-row :gutter="12"><up-col :span="12"><view class="grid-block">Left</view></up-col><up-col :span="12"><view class="grid-block">Right</view></up-col></up-row>' },
  'up-row-notice': { markup: '<up-row-notice text="Stable notice" :speed="0" />' },
  'up-scroll-list': { markup: '<up-scroll-list><view class="grid-block">Scrollable content</view></up-scroll-list>' },
  'up-search': { setup: TEXT_MODEL, markup: '<up-search v-model="modelValue" placeholder="Search" :show-action="false" />' },
  'up-select': { setup: `${TEXT_MODEL}\n${LIST}`, markup: '<up-select v-model="modelValue" :list="list" />' },
  'up-short-video': { imports: [SAMPLE_IMAGE_IMPORT, SAMPLE_VIDEO_IMPORT], setup: `const videos = [{ videoUrl: sampleVideo, author: { avatar: sampleImage, name: 'Tester', desc: 'Local fixture' }, playbackRate: 1, isLiked: false, likeCount: 0, commentCount: 0, shareCount: 0, isCollected: false, collectCount: 0, progress: 0 }]`, markup: '<up-short-video :video-list="videos" />' },
  'up-skeleton': { markup: '<up-skeleton :loading="false"><view>Loaded content</view></up-skeleton>' },
  'up-slider': { setup: `const modelValue = ref(40)`, interaction: { type: 'model', model: 'modelValue', value: 60 }, markup: '<up-slider v-model="modelValue" />' },
  'up-steps': { parent: 'up-steps', markup: '<up-steps :current="1"><up-steps-item title="First" /><up-steps-item title="Second" /></up-steps>' },
  'up-steps-item': { parent: 'up-steps', markup: '<up-steps :current="1"><up-steps-item title="First" /><up-steps-item title="Second" /></up-steps>' },
  'up-subsection': { setup: `const modelValue = ref(0)\nconst sections = [{ name: 'Alpha' }, { name: 'Beta' }]`, markup: '<up-subsection v-model="modelValue" :list="sections" />' },
  'up-swipe-action': { parent: 'up-swipe-action', markup: '<up-swipe-action><up-swipe-action-item :options="[{ text: \'Delete\' }]"><up-cell title="Swipe item" /></up-swipe-action-item></up-swipe-action>' },
  'up-swipe-action-item': { parent: 'up-swipe-action', markup: '<up-swipe-action><up-swipe-action-item :options="[{ text: \'Delete\' }]"><up-cell title="Swipe item" /></up-swipe-action-item></up-swipe-action>' },
  'up-swiper': { imports: [SAMPLE_IMAGE_IMPORT, SAMPLE_ALT_IMAGE_IMPORT], setup: `const swiperList = [{ image: sampleImage, title: 'Alpha' }, { image: sampleAltImage, title: 'Beta' }]`, parent: 'up-swiper', markup: '<up-swiper :list="swiperList" :autoplay="false"><up-swiper-indicator :current="0" :length="2" /></up-swiper>' },
  'up-swiper-indicator': { imports: [SAMPLE_IMAGE_IMPORT, SAMPLE_ALT_IMAGE_IMPORT], setup: `const swiperList = [sampleImage, sampleAltImage]`, parent: 'up-swiper', markup: '<up-swiper :list="swiperList" :autoplay="false"><up-swiper-indicator :current="0" :length="2" /></up-swiper>' },
  'up-switch': { setup: BOOLEAN_MODEL, interaction: { type: 'model', model: 'modelValue', value: true }, markup: '<up-switch v-model="modelValue" />' },
  'up-tabbar': { setup: `const modelValue = ref(0)`, parent: 'up-tabbar', markup: '<up-tabbar v-model="modelValue" :fixed="false"><up-tabbar-item text="Home" icon="home" /><up-tabbar-item text="Profile" icon="account" /></up-tabbar>' },
  'up-tabbar-item': { setup: `const modelValue = ref(0)`, parent: 'up-tabbar', markup: '<up-tabbar v-model="modelValue" :fixed="false"><up-tabbar-item text="Home" icon="home" /><up-tabbar-item text="Profile" icon="account" /></up-tabbar>' },
  'up-table': { parent: 'up-table', markup: '<up-table><up-tr><up-th>Key</up-th><up-th>Value</up-th></up-tr><up-tr><up-td>Status</up-td><up-td>Ready</up-td></up-tr></up-table>' },
  'up-tabs': { setup: `const modelValue = ref(0)\nconst tabs = [{ name: 'Alpha' }, { name: 'Beta' }]`, parent: 'up-tabs', markup: '<up-tabs v-model="modelValue" :list="tabs"><up-tabs-item name="alpha">Alpha content</up-tabs-item></up-tabs>' },
  'up-tabs-item': { setup: `const modelValue = ref(0)\nconst tabs = [{ name: 'Alpha' }]`, parent: 'up-tabs', markup: '<up-tabs v-model="modelValue" :list="tabs"><up-tabs-item name="alpha">Alpha content</up-tabs-item></up-tabs>' },
  'up-tabs-pro': { setup: `const modelValue = ref(0)\nconst tabs = [{ name: 'Alpha' }, { name: 'Beta' }]`, interaction: { type: 'model', model: 'modelValue', value: 1 }, markup: '<up-tabs-pro v-model:current="modelValue" :list="tabs"><view>Stable tab content</view></up-tabs-pro>' },
  'up-td': { parent: 'up-table', markup: '<up-table><up-tr><up-th>Key</up-th><up-td>Value</up-td></up-tr></up-table>' },
  'up-text': { markup: '<up-text text="Stable text" type="primary" />' },
  'up-textarea': { setup: TEXT_MODEL, markup: '<up-textarea v-model="modelValue" placeholder="Textarea" />' },
  'up-th': { parent: 'up-table', markup: '<up-table><up-tr><up-th>Header</up-th></up-tr></up-table>' },
  'up-title': { markup: '<up-title title="Stable title" subtitle="Compatibility" />' },
  'up-toast': { markup: '<up-toast />' },
  'up-tooltip': { markup: '<up-tooltip text="Tooltip content"><up-button text="Tooltip" /></up-tooltip>' },
  'up-tr': { parent: 'up-table', markup: '<up-table><up-tr><up-td>Row</up-td></up-tr></up-table>' },
  'up-transition': { setup: `const transitionVisible = ref(true)`, markup: '<up-transition :show="transitionVisible"><view class="transition-content">Transition content</view></up-transition>' },
  'up-tree': { setup: `const treeData = [{ id: 1, label: 'Alpha', children: [{ id: 2, label: 'Beta' }] }]`, markup: '<up-tree :data="treeData" node-key="id" />' },
  'up-upload': { imports: [SAMPLE_IMAGE_IMPORT], setup: `const fileList = ref([{ url: sampleImage, status: 'success' }])`, markup: '<up-upload :file-list="fileList" :max-count="1" />' },
  'up-view': { markup: '<up-view text="Stable view content" />' },
  'up-waterfall': { setup: `const waterfallList = ref([{ id: 1, title: 'Alpha' }, { id: 2, title: 'Beta' }])`, markup: '<up-waterfall v-model="waterfallList"><template #left="{ leftList }"><view v-for="item in leftList" :key="item.id">{{ item.title }}</view></template><template #right="{ rightList }"><view v-for="item in rightList" :key="item.id">{{ item.title }}</view></template></up-waterfall>' },
}

export function getComponentMarkup(component: string): ComponentMarkup {
  return overrides[component] ?? { markup: `<${component} />` }
}
