// 此文件由 scripts/generate-intrinsic-elements.mjs 自动生成，请勿直接修改。 来源：components.weapp.json、components.alipay.json、components.tt.json。
/* eslint-disable style/quote-props -- 生成的组件名需要保留宿主拼写。 */

export const WEAPP_JSX_EVENT_NAME_ALIASES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  ad: {
    close: 'bindclose',
    error: 'binderror',
    load: 'bindload',
  },
  'ad-custom': {
    error: 'binderror',
    load: 'bindload',
  },
  audio: {
    ended: 'bindended',
    error: 'binderror',
    pause: 'bindpause',
    play: 'bindplay',
    timeUpdate: 'bindtimeupdate',
  },
  button: {
    agreePrivacyAuthorization: 'bindagreeprivacyauthorization',
    chooseAvatar: 'bindchooseavatar',
    contact: 'bindcontact',
    createLiveActivity: 'createliveactivity',
    error: 'binderror',
    getPhoneNumber: 'bindgetphonenumber',
    getRealtimePhoneNumber: 'bindgetrealtimephonenumber',
    getUserInfo: 'bindgetuserinfo',
    launchApp: 'bindlaunchapp',
    openSetting: 'bindopensetting',
    tap: 'bindtap',
  },
  camera: {
    error: 'binderror',
    initdone: 'bindinitdone',
    scanCode: 'bindscancode',
    stop: 'bindstop',
  },
  canvas: {
    error: 'binderror',
    longTap: 'bindlongtap',
    touchCancel: 'bindtouchcancel',
    touchEnd: 'bindtouchend',
    touchMove: 'bindtouchmove',
    touchStart: 'bindtouchstart',
  },
  'checkbox-group': {
    change: 'bind:change',
  },
  'cover-image': {
    error: 'bind:error',
    load: 'bind:load',
  },
  editor: {
    blur: 'bindblur',
    focus: 'bindfocus',
    input: 'bindinput',
    ready: 'bindready',
    statuschange: 'bindstatuschange',
  },
  form: {
    reset: 'bindreset',
    submit: 'bindsubmit',
    submitToGroup: 'bindsubmitToGroup',
  },
  'functional-page-navigator': {
    cancel: 'bindcancel',
    fail: 'bindfail',
    success: 'bindsuccess',
  },
  image: {
    error: 'binderror',
    load: 'bindload',
  },
  input: {
    blur: 'bindblur',
    change: 'bindchange',
    confirm: 'bindconfirm',
    focus: 'bindfocus',
    input: 'bindinput',
    keyboardHeightChange: 'bindkeyboardheightchange',
    keyboardcompositionend: 'bind:keyboardcompositionend',
    keyboardcompositionstart: 'bind:keyboardcompositionstart',
    keyboardcompositionupdate: 'bind:keyboardcompositionupdate',
    nicknameReview: 'bindnicknamereview',
    selectionchange: 'bind:selectionchange',
    workletOnkeyboardheightchange: 'worklet:onkeyboardheightchange',
  },
  'live-player': {
    audiovolumenotify: 'bindaudiovolumenotify',
    castinginterrupt: 'bindcastinginterrupt',
    castingstatechange: 'bindcastingstatechange',
    castinguserselect: 'bindcastinguserselect',
    enterpictureinpicture: 'bindenterpictureinpicture',
    fullScreenChange: 'bindfullscreenchange',
    leavepictureinpicture: 'bindleavepictureinpicture',
    netstatus: 'bindnetstatus',
    statechange: 'bindstatechange',
  },
  'live-pusher': {
    audiovolumenotify: 'bindaudiovolumenotify',
    bgmcomplete: 'bindbgmcomplete',
    bgmprogress: 'bindbgmprogress',
    bgmstart: 'bindbgmstart',
    enterpictureinpicture: 'bindenterpictureinpicture',
    error: 'binderror',
    leavepictureinpicture: 'bindleavepictureinpicture',
    netstatus: 'bindnetstatus',
    statechange: 'bindstatechange',
  },
  map: {
    abilityfail: 'bindabilityfail',
    abilitysuccess: 'bindabilitysuccess',
    authsuccess: 'bindauthsuccess',
    calloutTap: 'bindcallouttap',
    controlTap: 'bindcontroltap',
    error: 'binderror',
    interpolatepoint: 'bindinterpolatepoint',
    labeltap: 'bindlabeltap',
    markerTap: 'bindmarkertap',
    poitap: 'bindpoitap',
    polylinetap: 'bindpolylinetap',
    regionChange: 'bindregionchange',
    tap: 'bindtap',
    updated: 'bindupdated',
  },
  'movable-area': {
    change: 'bindchange',
    htouchmove: 'htouchmove',
    scale: 'bindscale',
    vtouchmove: 'vtouchmove',
  },
  'movable-view': {
    change: 'bindchange',
    htouchmove: 'htouchmove',
    scale: 'bindscale',
    vtouchmove: 'vtouchmove',
  },
  navigator: {
    complete: 'bindcomplete',
    fail: 'bindfail',
    success: 'bindsuccess',
  },
  'official-account': {
    error: 'binderror',
    load: 'bindload',
  },
  'open-data': {
    error: 'binderror',
  },
  'page-container': {
    afterEnter: 'bind:afterenter',
    afterLeave: 'bind:afterleave',
    beforeEnter: 'bind:beforeenter',
    beforeLeave: 'bind:beforeleave',
    clickOverlay: 'bind:clickoverlay',
    enter: 'bind:enter',
    leave: 'bind:leave',
  },
  'page-meta': {
    resize: 'bindresize',
    scroll: 'bindscroll',
    scrolldone: 'bindscrolldone',
  },
  picker: {
    cancel: 'bindcancel',
    change: 'bindchange',
    columnchange: 'bindcolumnchange',
  },
  'picker-view': {
    change: 'bindchange',
    pickEnd: 'bindpickend',
    pickStart: 'bindpickstart',
  },
  'picker-view-column': {
    change: 'bindchange',
    pickEnd: 'bindpickend',
    pickStart: 'bindpickstart',
  },
  progress: {
    activeend: 'bindactiveend',
  },
  'radio-group': {
    change: 'bind:change',
  },
  'scroll-view': {
    dragend: 'binddragend',
    dragging: 'binddragging',
    dragstart: 'binddragstart',
    refresherabort: 'bindrefresherabort',
    refresherpulling: 'bindrefresherpulling',
    refresherrefresh: 'bindrefresherrefresh',
    refresherrestore: 'bindrefresherrestore',
    refresherstatuschange: 'bind:refresherstatuschange',
    refresherwillrefresh: 'bind:refresherwillrefresh',
    scroll: 'bindscroll',
    scrollToLower: 'bindscrolltolower',
    scrollToUpper: 'bindscrolltoupper',
    scrollend: 'bind:scrollend',
    scrollstart: 'bind:scrollstart',
    workletAdjustDecelerationVelocity: 'worklet:adjust-deceleration-velocity',
    workletOnscrollend: 'worklet:onscrollend',
    workletOnscrollstart: 'worklet:onscrollstart',
    workletOnscrollupdate: 'worklet:onscrollupdate',
  },
  'share-element': {
    workletOnframe: 'worklet:onframe',
  },
  slider: {
    change: 'bindchange',
    changing: 'bindchanging',
  },
  swiper: {
    animationfinish: 'bindanimationfinish',
    change: 'bindchange',
    transition: 'bindtransition',
    workletOnscrollend: 'worklet:onscrollend',
    workletOnscrollstart: 'worklet:onscrollstart',
    workletOnscrollupdate: 'worklet:onscrollupdate',
  },
  switch: {
    change: 'bindchange',
  },
  textarea: {
    blur: 'bindblur',
    confirm: 'bindconfirm',
    focus: 'bindfocus',
    input: 'bindinput',
    keyboardHeightChange: 'bindkeyboardheightchange',
    keyboardcompositionend: 'bind:keyboardcompositionend',
    keyboardcompositionstart: 'bind:keyboardcompositionstart',
    keyboardcompositionupdate: 'bind:keyboardcompositionupdate',
    linechange: 'bindlinechange',
    selectionchange: 'bind:selectionchange',
  },
  video: {
    castinginterrupt: 'bindcastinginterrupt',
    castingstatechange: 'bindcastingstatechange',
    castinguserselect: 'bindcastinguserselect',
    controlstoggle: 'bindcontrolstoggle',
    ended: 'bindended',
    enterpictureinpicture: 'bindenterpictureinpicture',
    error: 'binderror',
    fullScreenChange: 'bindfullscreenchange',
    leavepictureinpicture: 'bindleavepictureinpicture',
    loadedmetadata: 'bindloadedmetadata',
    pause: 'bindpause',
    play: 'bindplay',
    progress: 'bindprogress',
    seekcomplete: 'bindseekcomplete',
    timeUpdate: 'bindtimeupdate',
    waiting: 'bindwaiting',
  },
  view: {
    tap: 'bindtap',
  },
  'voip-room': {
    error: 'binderror',
  },
  'web-view': {
    error: 'binderror',
    load: 'bindload',
    message: 'bindmessage',
  },
}

export const ALIPAY_JSX_EVENT_NAME_ALIASES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  button: {
    chooseAvatar: 'onChooseAvatar',
    error: 'onError',
    followLifestyle: 'onFollowLifestyle',
    getAuthorize: 'onGetAuthorize',
    getPhoneNumber: 'onGetPhoneNumber',
    getUserInfo: 'onGetUserInfo',
    tap: 'onTap',
  },
  camera: {
    error: 'onError',
    ready: 'onReady',
    scanCode: 'onScanCode',
    stop: 'onStop',
  },
  canvas: {
    longTap: 'onLongTap',
    ready: 'onReady',
    tap: 'onTap',
    touchCancel: 'onTouchCancel',
    touchEnd: 'onTouchEnd',
    touchMove: 'onTouchMove',
    touchStart: 'onTouchStart',
  },
  checkbox: {
    change: 'onChange',
  },
  'checkbox-group': {
    change: 'onChange',
  },
  'cover-image': {
    tap: 'onTap',
  },
  'cover-view': {
    tap: 'onTap',
  },
  form: {
    reset: 'onReset',
    submit: 'onSubmit',
  },
  image: {
    error: 'onError',
    load: 'onLoad',
    tap: 'onTap',
  },
  input: {
    blur: 'onBlur',
    confirm: 'onConfirm',
    focus: 'onFocus',
    input: 'onInput',
  },
  lifestyle: {
    follow: 'onFollow',
  },
  lottie: {
    animationCancel: 'onAnimationCancel',
    animationEnd: 'onAnimationEnd',
    animationRepeat: 'onAnimationRepeat',
    animationStart: 'onAnimationStart',
    dataFailed: 'onDataFailed',
    dataLoadReady: 'onDataLoadReady',
    dataReady: 'onDataReady',
  },
  map: {
    calloutTap: 'onCalloutTap',
    controlTap: 'onControlTap',
    initComplete: 'onInitComplete',
    markerTap: 'onMarkerTap',
    panelTap: 'onPanelTap',
    regionChange: 'onRegionChange',
    tap: 'onTap',
  },
  'movable-view': {
    change: 'onChange',
    changeEnd: 'onChangeEnd',
    scale: 'onScale',
    touchCancel: 'onTouchCancel',
    touchEnd: 'onTouchEnd',
    touchMove: 'onTouchMove',
    touchStart: 'onTouchStart',
  },
  'page-container': {
    afterEnter: 'onAfterEnter',
    afterLeave: 'onAfterLeave',
    beforeEnter: 'onBeforeEnter',
    beforeLeave: 'onBeforeLeave',
    clickOverlay: 'onClickOverlay',
    enter: 'onEnter',
    enterCancelled: 'onEnterCancelled',
    leave: 'onLeave',
    leaveCancelled: 'onLeaveCancelled',
  },
  'page-meta': {
    scroll: 'onScroll',
  },
  picker: {
    change: 'onChange',
  },
  'picker-view': {
    change: 'onChange',
    pickEnd: 'onPickEnd',
    pickStart: 'onPickStart',
  },
  'radio-group': {
    change: 'onChange',
  },
  'rich-text': {
    longTap: 'onLongtap',
    tap: 'onTap',
    touchCancel: 'onTouchcancel',
    touchEnd: 'onTouchend',
    touchMove: 'onTouchmove',
    touchStart: 'onTouchstart',
  },
  'scroll-view': {
    scroll: 'onScroll',
    scrollToLower: 'onScrollToLower',
    scrollToUpper: 'onScrollToUpper',
    touchCancel: 'onTouchCancel',
    touchEnd: 'onTouchEnd',
    touchMove: 'onTouchMove',
    touchStart: 'onTouchStart',
  },
  slider: {
    change: 'onChange',
    changing: 'onChanging',
  },
  'subscribe-message': {
    complete: 'onComplete',
  },
  swiper: {
    animationEnd: 'onAnimationEnd',
    change: 'onChange',
    transition: 'onTransition',
  },
  switch: {
    change: 'onChange',
  },
  textarea: {
    blur: 'onBlur',
    confirm: 'onConfirm',
    focus: 'onFocus',
    input: 'onInput',
  },
  video: {
    ended: 'onEnded',
    error: 'onError',
    fullScreenChange: 'onFullScreenChange',
    loading: 'onLoading',
    pause: 'onPause',
    play: 'onPlay',
    renderStart: 'onRenderStart',
    stop: 'onStop',
    tap: 'onTap',
    timeUpdate: 'onTimeUpdate',
    userAction: 'onUserAction',
  },
  view: {
    animationEnd: 'onAnimationEnd',
    animationIteration: 'onAnimationIteration',
    animationStart: 'onAnimationStart',
    appear: 'onAppear',
    disappear: 'onDisappear',
    firstAppear: 'onFirstAppear',
    longTap: 'onLongTap',
    tap: 'onTap',
    touchCancel: 'onTouchCancel',
    touchEnd: 'onTouchEnd',
    touchMove: 'onTouchMove',
    touchStart: 'onTouchStart',
    transitionEnd: 'onTransitionEnd',
  },
  'web-view': {
    error: 'onError',
    load: 'onLoad',
    message: 'onMessage',
  },
}

export const TT_JSX_EVENT_NAME_ALIASES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  'aweme-data': {
    error: 'binderror',
  },
  'aweme-user-card': {
    error: 'binderror',
  },
  button: {
    agreePrivacyAuthorization: 'bindagreeprivacyauthorization',
    getPhoneNumber: 'bindgetphonenumber',
    tap: 'bindtap',
  },
  camera: {
    error: 'binderror',
    initdone: 'bindinitdone',
    scanCode: 'bindscancode',
    stop: 'bindstop',
  },
  canvas: {
    touchCancel: 'bindtouchcancel',
    touchEnd: 'bindtouchend',
    touchMove: 'bindtouchmove',
    touchStart: 'bindtouchstart',
  },
  'checkbox-group': {
    change: 'bindchange',
  },
  'draw-ad': {
    error: 'binderror',
    play: 'bindplay',
    stop: 'bindstop',
  },
  form: {
    reset: 'bindreset',
    submit: 'bindsubmit',
  },
  image: {
    error: 'binderror',
    load: 'bindload',
  },
  input: {
    blur: 'bindblur',
    confirm: 'bindconfirm',
    focus: 'bindfocus',
    input: 'bindinput',
    keyboardHeightChange: 'bindkeyboardheightchange',
  },
  'live-player': {
    error: 'binderror',
    fullScreenChange: 'bindfullscreenchange',
    statechange: 'bindstatechange',
  },
  map: {
    anchorpointtap: 'bindanchorpointtap',
    calloutTap: 'bindcallouttap',
    labeltap: 'bindlabeltap',
    markerTap: 'bindmarkertap',
    regionChange: 'bindregionchange',
    tap: 'bindtap',
    updated: 'bindupdated',
  },
  'movable-view': {
    change: 'bindchange',
    htouchmove: 'bindhtouchmove',
    scale: 'bindscale',
    vtouchmove: 'bindvtouchmove',
  },
  'open-data': {
    error: 'binderror',
  },
  picker: {
    cancel: 'bindcancel',
  },
  'picker-view': {
    change: 'bindchange',
    pickEnd: 'bindpickend',
    pickStart: 'bindpickstart',
  },
  progress: {
    activeend: 'bindactiveend',
  },
  'radio-group': {
    change: 'bindchange',
  },
  'rtc-room': {
    error: 'binderror',
  },
  'scroll-view': {
    refresherabort: 'bindrefresherabort',
    refresherpulling: 'bindrefresherpulling',
    refresherrefresh: 'bindrefresherrefresh',
    refresherrestore: 'bindrefresherrestore',
    scroll: 'bindscroll',
    scrollToLower: 'bindscrolltolower',
    scrollToUpper: 'bindscrolltoupper',
  },
  slider: {
    change: 'bindchange',
    changing: 'bindchanging',
  },
  swiper: {
    animationfinish: 'bindanimationfinish',
    change: 'bindchange',
    transition: 'bindtransition',
  },
  switch: {
    change: 'bindchange',
  },
  textarea: {
    blur: 'bindblur',
    confirm: 'bindconfirm',
    focus: 'bindfocus',
    input: 'bindinput',
    keyboardHeightChange: 'bindkeyboardheightchange',
    linechange: 'bindlinechange',
  },
  video: {
    closebackground: 'bindclosebackground',
    controlTap: 'bindcontroltap',
    controlstoggle: 'bindcontrolstoggle',
    ended: 'bindended',
    enterbackground: 'bindenterbackground',
    error: 'binderror',
    fullScreenChange: 'bindfullscreenchange',
    leavebackground: 'bindleavebackground',
    loadedmetadata: 'bindloadedmetadata',
    mutechange: 'bindmutechange',
    pause: 'bindpause',
    play: 'bindplay',
    playbackratechange: 'bindplaybackratechange',
    playbackratelistchange: 'bindplaybackratelistchange',
    progress: 'bindprogress',
    seekcomplete: 'bindseekcomplete',
    timeUpdate: 'bindtimeupdate',
    waiting: 'bindwaiting',
  },
  view: {
    tap: 'bindtap',
  },
  'web-view': {
    error: 'binderror',
    load: 'bindload',
    message: 'bindmessage',
  },
}
