export { createVueTransformPlugin } from './transform/plugin'
export type { AutoUsingComponentsOptions, VueTransformResult } from 'wevu/compiler'
export { compileVueFile } from 'wevu/compiler'
export { compileConfigBlocks, evaluateJsLikeConfig, isJsonLikeLang, normalizeConfigLang, resolveJsLikeLang } from 'wevu/compiler'
export type { JsLikeLang } from 'wevu/compiler'
export { generateScopedId } from 'wevu/compiler'
export type { TransformResult, TransformScriptOptions } from 'wevu/compiler'
export { transformScript } from 'wevu/compiler'
