import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_REQUEST_SUBSCRIBE_EMPLOYEE_MESSAGE_TO_GET_BATTERY_INFO_SYNC: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'requestSubscribeEmployeeMessage',
    description: '请求订阅员工消息。',
    wxStrategy: '直连 `wx.requestSubscribeEmployeeMessage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'restartMiniProgram',
    description: '重启小程序。',
    wxStrategy: '直连 `wx.restartMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'scanCode',
    description: '扫码。',
    wxStrategy: '直连 `wx.scanCode`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.scanCode`',
    support: '⚠️',
  },
  {
    method: 'requestPayment',
    description: '发起支付。',
    wxStrategy: '直连 `wx.requestPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestOrderPayment',
    description: '发起订单支付。',
    wxStrategy: '直连 `wx.requestOrderPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestPluginPayment',
    description: '发起插件支付。',
    wxStrategy: '直连 `wx.requestPluginPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'requestVirtualPayment',
    description: '发起虚拟支付。',
    wxStrategy: '直连 `wx.requestVirtualPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'showShareImageMenu',
    description: '显示分享图片菜单。',
    wxStrategy: '直连 `wx.showShareImageMenu`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'updateShareMenu',
    description: '更新分享菜单配置。',
    wxStrategy: '直连 `wx.updateShareMenu`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openEmbeddedMiniProgram',
    description: '打开嵌入式小程序。',
    wxStrategy: '直连 `wx.openEmbeddedMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'saveFileToDisk',
    description: '保存文件到磁盘。',
    wxStrategy: '直连 `wx.saveFileToDisk`',
    alipayStrategy: '直连 `my.saveFileToDisk`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getEnterOptionsSync',
    description: '获取启动参数（同步）。',
    wxStrategy: '直连 `wx.getEnterOptionsSync`',
    alipayStrategy: '直连 `my.getEnterOptionsSync`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSystemSetting',
    description: '获取系统设置。',
    wxStrategy: '直连 `wx.getSystemSetting`',
    alipayStrategy: '直连 `my.getSystemSetting`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getUserProfile',
    description: '获取用户资料。',
    wxStrategy: '直连 `wx.getUserProfile`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.getUserProfile`',
    support: '⚠️',
  },
  {
    method: 'getUserInfo',
    description: '获取用户信息。',
    wxStrategy: '直连 `wx.getUserInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.getUserInfo`',
    support: '⚠️',
  },
  {
    method: 'getAppAuthorizeSetting',
    description: '获取 App 授权设置。',
    wxStrategy: '直连 `wx.getAppAuthorizeSetting`',
    alipayStrategy: '直连 `my.getAppAuthorizeSetting`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getAppBaseInfo',
    description: '获取 App 基础信息。',
    wxStrategy: '直连 `wx.getAppBaseInfo`',
    alipayStrategy: '直连 `my.getAppBaseInfo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'chooseVideo',
    description: '选择视频。',
    wxStrategy: '直连 `wx.chooseVideo`',
    alipayStrategy: '直连 `my.chooseVideo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'hideHomeButton',
    description: '隐藏返回首页按钮。',
    wxStrategy: '直连 `wx.hideHomeButton`',
    alipayStrategy: '映射到 `my.hideBackHome`',
    douyinStrategy: '直连 `tt.hideHomeButton`',
    support: '✅',
  },
  {
    method: 'getWindowInfo',
    description: '获取窗口信息。',
    wxStrategy: '直连 `wx.getWindowInfo`',
    alipayStrategy: '直连 `my.getWindowInfo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getDeviceInfo',
    description: '获取设备基础信息。',
    wxStrategy: '直连 `wx.getDeviceInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getAccountInfoSync',
    description: '同步获取当前账号信息。',
    wxStrategy: '直连 `wx.getAccountInfoSync`',
    alipayStrategy: '直连 `my.getAccountInfoSync`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setBackgroundColor',
    description: '动态设置窗口背景色。',
    wxStrategy: '直连 `wx.setBackgroundColor`',
    alipayStrategy: '直连 `my.setBackgroundColor`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'setBackgroundTextStyle',
    description: '动态设置下拉背景字体样式。',
    wxStrategy: '直连 `wx.setBackgroundTextStyle`',
    alipayStrategy: '直连 `my.setBackgroundTextStyle`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getNetworkType',
    description: '获取网络类型。',
    wxStrategy: '直连 `wx.getNetworkType`',
    alipayStrategy: '直连 `my.getNetworkType`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getBatteryInfo',
    description: '异步获取电量信息。',
    wxStrategy: '直连 `wx.getBatteryInfo`',
    alipayStrategy: '直连 `my.getBatteryInfo`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getBatteryInfoSync',
    description: '同步获取电量信息。',
    wxStrategy: '直连 `wx.getBatteryInfoSync`',
    alipayStrategy: '直连 `my.getBatteryInfoSync`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
