import { DefaultMiniProgramHostNamespace } from './miniprogramHostSources'

export {
  AlipayMiniProgramHostNamespace,
  DefaultMiniProgramHostNamespace,
  TtMiniProgramHostNamespace,
  WechatMiniProgramHostNamespace,
} from './miniprogramHostSources'
export type { MiniProgramHostSourceName } from './miniprogramHostSources'

/* eslint-disable ts/no-namespace -- 通过单点 namespace 别名集中宿主类型入口，避免文件内重复散落宿主底座类型引用。 */
export declare namespace MiniProgramHostNamespace {
  export import App = DefaultMiniProgramHostNamespace.App
  export import Behavior = DefaultMiniProgramHostNamespace.Behavior
  export import Component = DefaultMiniProgramHostNamespace.Component
  export import Page = DefaultMiniProgramHostNamespace.Page
  export import BoundingClientRectCallbackResult = DefaultMiniProgramHostNamespace.BoundingClientRectCallbackResult
  export import ScrollOffsetCallbackResult = DefaultMiniProgramHostNamespace.ScrollOffsetCallbackResult
  export import NodesRef = DefaultMiniProgramHostNamespace.NodesRef
  export import SelectorQuery = DefaultMiniProgramHostNamespace.SelectorQuery
  export import CreateIntersectionObserverOption = DefaultMiniProgramHostNamespace.CreateIntersectionObserverOption
  export import IntersectionObserver = DefaultMiniProgramHostNamespace.IntersectionObserver
  export import OnUnhandledRejectionListenerResult = DefaultMiniProgramHostNamespace.OnUnhandledRejectionListenerResult
  export import OnThemeChangeListenerResult = DefaultMiniProgramHostNamespace.OnThemeChangeListenerResult
  export import OnMemoryWarningListenerResult = DefaultMiniProgramHostNamespace.OnMemoryWarningListenerResult
  export import SwitchTabOption = DefaultMiniProgramHostNamespace.SwitchTabOption
  export import ReLaunchOption = DefaultMiniProgramHostNamespace.ReLaunchOption
  export import RedirectToOption = DefaultMiniProgramHostNamespace.RedirectToOption
  export import NavigateToOption = DefaultMiniProgramHostNamespace.NavigateToOption
}

export type HostMiniProgramComponentBehaviorOptions = MiniProgramHostNamespace.Component.ComponentOptions
export type HostMiniProgramComponentTrivialOption = MiniProgramHostNamespace.Component.TrivialOption
export type HostMiniProgramBehaviorIdentifier = MiniProgramHostNamespace.Behavior.Identifier
export type HostMiniProgramLaunchOptions = MiniProgramHostNamespace.App.LaunchShowOption
export type HostMiniProgramPageNotFoundOptions = MiniProgramHostNamespace.App.PageNotFoundOption
export type HostMiniProgramUnhandledRejectionResult = MiniProgramHostNamespace.OnUnhandledRejectionListenerResult
export type HostMiniProgramThemeChangeResult = MiniProgramHostNamespace.OnThemeChangeListenerResult
export type HostMiniProgramMemoryWarningResult = MiniProgramHostNamespace.OnMemoryWarningListenerResult
export type HostMiniProgramPageScrollOption = MiniProgramHostNamespace.Page.IPageScrollOption
export type HostMiniProgramTabItemTapOption = MiniProgramHostNamespace.Page.ITabItemTapOption
export type HostMiniProgramPageResizeOption = MiniProgramHostNamespace.Page.IResizeOption
export type HostMiniProgramShareAppMessageOption = MiniProgramHostNamespace.Page.IShareAppMessageOption
export type HostMiniProgramAddToFavoritesOption = MiniProgramHostNamespace.Page.IAddToFavoritesOption
export type HostMiniProgramSaveExitState = MiniProgramHostNamespace.Page.ISaveExitState
export type HostMiniProgramRouter = MiniProgramHostNamespace.Component.Router
export type HostMiniProgramSwitchTabOption = MiniProgramHostNamespace.SwitchTabOption
export type HostMiniProgramReLaunchOption = MiniProgramHostNamespace.ReLaunchOption
export type HostMiniProgramRedirectToOption = MiniProgramHostNamespace.RedirectToOption
export type HostMiniProgramNavigateToOption = MiniProgramHostNamespace.NavigateToOption
export type HostMiniProgramPageLifetime = MiniProgramHostNamespace.Page.ILifetime
export type HostMiniProgramNodesRef = MiniProgramHostNamespace.NodesRef
export type HostMiniProgramNodesRefFields = Parameters<HostMiniProgramNodesRef['fields']>[0]
export type HostMiniProgramBoundingClientRectResult = MiniProgramHostNamespace.BoundingClientRectCallbackResult
export type HostMiniProgramScrollOffsetResult = MiniProgramHostNamespace.ScrollOffsetCallbackResult
export type HostMiniProgramSelectorQuery = MiniProgramHostNamespace.SelectorQuery
export type HostMiniProgramIntersectionObserverOptions = MiniProgramHostNamespace.CreateIntersectionObserverOption
export type HostMiniProgramIntersectionObserver = MiniProgramHostNamespace.IntersectionObserver
export type HostMiniProgramComponentPropertyOption = MiniProgramHostNamespace.Component.PropertyOption
export type HostMiniProgramComponentMethodOption = MiniProgramHostNamespace.Component.MethodOption
export type HostMiniProgramComponentEmptyArray = MiniProgramHostNamespace.Component.IEmptyArray
export type HostMiniProgramComponentAllProperty = MiniProgramHostNamespace.Component.AllProperty
export type HostMiniProgramComponentAllFullProperty = MiniProgramHostNamespace.Component.AllFullProperty
export type HostMiniProgramComponentShortProperty = MiniProgramHostNamespace.Component.ShortProperty
export type HostMiniProgramComponentPropertyValue<TProperty extends HostMiniProgramComponentAllFullProperty>
  = MiniProgramHostNamespace.Component.PropertyToData<TProperty>
export type HostMiniProgramComponentInstance<
  D extends object,
  P extends HostMiniProgramComponentPropertyOption,
  M extends HostMiniProgramComponentMethodOption,
  B extends HostMiniProgramComponentEmptyArray = HostMiniProgramComponentEmptyArray,
> = MiniProgramHostNamespace.Component.Instance<D, P, M, B>
export type HostMiniProgramTriggerEventOptions = MiniProgramHostNamespace.Component.TriggerEventOption
export type HostMiniProgramAppOptions<T extends Record<string, any>> = MiniProgramHostNamespace.App.Options<T>
export type HostMiniProgramComponentTrivialInstance = MiniProgramHostNamespace.Component.TrivialInstance
export type HostMiniProgramPageTrivialInstance = MiniProgramHostNamespace.Page.TrivialInstance
export type HostMiniProgramAppTrivialInstance = MiniProgramHostNamespace.App.TrivialInstance
