import type {
  HostMiniProgramComponentAllFullProperty,
  HostMiniProgramComponentEmptyArray,
  HostMiniProgramComponentInstance,
  HostMiniProgramComponentMethodOption,
  HostMiniProgramComponentPropertyOption,
  HostMiniProgramComponentPropertyValue,
} from './miniprogramHost'

export type {
  HostMiniProgramAddToFavoritesOption as NativeMiniProgramAddToFavoritesOption,
  HostMiniProgramAppOptions as NativeMiniProgramAppOptions,
  HostMiniProgramAppTrivialInstance as NativeMiniProgramAppTrivialInstance,
  HostMiniProgramBehaviorIdentifier as NativeMiniProgramBehaviorIdentifier,
  HostMiniProgramBoundingClientRectResult as NativeMiniProgramBoundingClientRectResult,
  HostMiniProgramComponentAllFullProperty as NativeMiniProgramComponentAllFullProperty,
  HostMiniProgramComponentAllProperty as NativeMiniProgramComponentAllProperty,
  HostMiniProgramComponentBehaviorOptions as NativeMiniProgramComponentBehaviorOptions,
  HostMiniProgramComponentEmptyArray as NativeMiniProgramComponentEmptyArray,
  HostMiniProgramComponentMethodOption as NativeMiniProgramComponentMethodOption,
  HostMiniProgramComponentPropertyOption as NativeMiniProgramComponentPropertyOption,
  HostMiniProgramComponentShortProperty as NativeMiniProgramComponentShortProperty,
  HostMiniProgramComponentTrivialInstance as NativeMiniProgramComponentTrivialInstance,
  HostMiniProgramComponentTrivialOption as NativeMiniProgramComponentTrivialOption,
  HostMiniProgramIntersectionObserver as NativeMiniProgramIntersectionObserver,
  HostMiniProgramIntersectionObserverOptions as NativeMiniProgramIntersectionObserverOptions,
  HostMiniProgramLaunchOptions as NativeMiniProgramLaunchOptions,
  HostMiniProgramMemoryWarningResult as NativeMiniProgramMemoryWarningResult,
  HostMiniProgramNavigateToOption as NativeMiniProgramNavigateToOption,
  HostMiniProgramNodesRef as NativeMiniProgramNodesRef,
  HostMiniProgramNodesRefFields as NativeMiniProgramNodesRefFields,
  HostMiniProgramPageLifetime as NativeMiniProgramPageLifetime,
  HostMiniProgramPageNotFoundOptions as NativeMiniProgramPageNotFoundOptions,
  HostMiniProgramPageResizeOption as NativeMiniProgramPageResizeOption,
  HostMiniProgramPageScrollOption as NativeMiniProgramPageScrollOption,
  HostMiniProgramPageTrivialInstance as NativeMiniProgramPageTrivialInstance,
  HostMiniProgramRedirectToOption as NativeMiniProgramRedirectToOption,
  HostMiniProgramReLaunchOption as NativeMiniProgramReLaunchOption,
  HostMiniProgramRouter as NativeMiniProgramRouter,
  HostMiniProgramSaveExitState as NativeMiniProgramSaveExitState,
  HostMiniProgramScrollOffsetResult as NativeMiniProgramScrollOffsetResult,
  HostMiniProgramSelectorQuery as NativeMiniProgramSelectorQuery,
  HostMiniProgramShareAppMessageOption as NativeMiniProgramShareAppMessageOption,
  HostMiniProgramSwitchTabOption as NativeMiniProgramSwitchTabOption,
  HostMiniProgramTabItemTapOption as NativeMiniProgramTabItemTapOption,
  HostMiniProgramThemeChangeResult as NativeMiniProgramThemeChangeResult,
  HostMiniProgramTriggerEventOptions as NativeMiniProgramTriggerEventOptions,
  HostMiniProgramUnhandledRejectionResult as NativeMiniProgramUnhandledRejectionResult,
} from './miniprogramHost'

export type NativeMiniProgramComponentPropertyValue<TProperty extends HostMiniProgramComponentAllFullProperty>
  = HostMiniProgramComponentPropertyValue<TProperty>

export type NativeMiniProgramComponentInstance<
  D extends object,
  P extends HostMiniProgramComponentPropertyOption,
  M extends HostMiniProgramComponentMethodOption,
  B extends HostMiniProgramComponentEmptyArray = HostMiniProgramComponentEmptyArray,
> = HostMiniProgramComponentInstance<D, P, M, B>
