import type { WeapiCrossPlatformMethodDocsMissingMethodsArrayBufferToBase64ToCreateCanvasContext } from './arrayBufferToBase64ToCreateCanvasContext'
import type { WeapiCrossPlatformMethodDocsMissingMethodsCreateInnerAudioContextToGetBLEMTU } from './createInnerAudioContextToGetBLEMTU'
import type { WeapiCrossPlatformMethodDocsMissingMethodsGetBackgroundAudioManagerToGetMenuButtonBoundingClientRect } from './getBackgroundAudioManagerToGetMenuButtonBoundingClientRect'
import type { WeapiCrossPlatformMethodDocsMissingMethodsGetRecorderManagerToHideShareMenu } from './getRecorderManagerToHideShareMenu'
import type { WeapiCrossPlatformMethodDocsMissingMethodsHideTabBarToOffAppHide } from './hideTabBarToOffAppHide'
import type { WeapiCrossPlatformMethodDocsMissingMethodsOffAppRouteToOffBluetoothDeviceFound } from './offAppRouteToOffBluetoothDeviceFound'
import type { WeapiCrossPlatformMethodDocsMissingMethodsOffCompassChangeToOffLocalServiceLost } from './offCompassChangeToOffLocalServiceLost'
import type { WeapiCrossPlatformMethodDocsMissingMethodsOffLocalServiceResolveFailToOffVoIPChatInterrupted } from './offLocalServiceResolveFailToOffVoIPChatInterrupted'
import type { WeapiCrossPlatformMethodDocsMissingMethodsOffVoIPChatMembersChangedToOnAudioInterruptionBegin } from './offVoIPChatMembersChangedToOnAudioInterruptionBegin'
import type { WeapiCrossPlatformMethodDocsMissingMethodsOnAudioInterruptionEndToOnBluetoothDeviceFound } from './onAudioInterruptionEndToOnBluetoothDeviceFound'
import type { WeapiCrossPlatformMethodDocsMissingMethodsOnCompassChangeToOnLocalServiceLost } from './onCompassChangeToOnLocalServiceLost'
import type { WeapiCrossPlatformMethodDocsMissingMethodsOnLocalServiceResolveFailToOnSocketOpen } from './onLocalServiceResolveFailToOnSocketOpen'
import type { WeapiCrossPlatformMethodDocsMissingMethodsOnThemeChangeToOpenSetting } from './onThemeChangeToOpenSetting'
import type { WeapiCrossPlatformMethodDocsMissingMethodsPageScrollToToSetNavigationBarTitle } from './pageScrollToToSetNavigationBarTitle'
import type { WeapiCrossPlatformMethodDocsMissingMethodsSetScreenBrightnessToStartCompass } from './setScreenBrightnessToStartCompass'
import type { WeapiCrossPlatformMethodDocsMissingMethodsStartGyroscopeToWriteBLECharacteristicValue } from './startGyroscopeToWriteBLECharacteristicValue'

export type WeapiCrossPlatformMethodDocsMissingMethods
  = WeapiCrossPlatformMethodDocsMissingMethodsArrayBufferToBase64ToCreateCanvasContext
    & WeapiCrossPlatformMethodDocsMissingMethodsCreateInnerAudioContextToGetBLEMTU
    & WeapiCrossPlatformMethodDocsMissingMethodsGetBackgroundAudioManagerToGetMenuButtonBoundingClientRect
    & WeapiCrossPlatformMethodDocsMissingMethodsGetRecorderManagerToHideShareMenu
    & WeapiCrossPlatformMethodDocsMissingMethodsHideTabBarToOffAppHide
    & WeapiCrossPlatformMethodDocsMissingMethodsOffAppRouteToOffBluetoothDeviceFound
    & WeapiCrossPlatformMethodDocsMissingMethodsOffCompassChangeToOffLocalServiceLost
    & WeapiCrossPlatformMethodDocsMissingMethodsOffLocalServiceResolveFailToOffVoIPChatInterrupted
    & WeapiCrossPlatformMethodDocsMissingMethodsOffVoIPChatMembersChangedToOnAudioInterruptionBegin
    & WeapiCrossPlatformMethodDocsMissingMethodsOnAudioInterruptionEndToOnBluetoothDeviceFound
    & WeapiCrossPlatformMethodDocsMissingMethodsOnCompassChangeToOnLocalServiceLost
    & WeapiCrossPlatformMethodDocsMissingMethodsOnLocalServiceResolveFailToOnSocketOpen
    & WeapiCrossPlatformMethodDocsMissingMethodsOnThemeChangeToOpenSetting
    & WeapiCrossPlatformMethodDocsMissingMethodsPageScrollToToSetNavigationBarTitle
    & WeapiCrossPlatformMethodDocsMissingMethodsSetScreenBrightnessToStartCompass
    & WeapiCrossPlatformMethodDocsMissingMethodsStartGyroscopeToWriteBLECharacteristicValue
