/* eslint-disable no-console */
import autoRoutes from 'weapp-vite/auto-routes'
import { createRouter } from 'wevu/router'
import { ROUTER_COVERAGE_PATHS } from './routerCoverage'

let wevuFeaturesRouterCreated = false

function normalizeGuardPath(path: string | undefined) {
  if (!path) {
    return ''
  }
  return path.startsWith('/') ? path.slice(1) : path
}

function mergeRoutesByPath(...groups: Array<Array<{ path: string } & Record<string, any>>>) {
  const merged: Array<{ path: string } & Record<string, any>> = []
  const seen = new Set<string>()

  for (const group of groups) {
    for (const route of group) {
      if (!route?.path || seen.has(route.path)) {
        continue
      }
      seen.add(route.path)
      merged.push(route)
    }
  }

  return merged
}

/**
 * @description 初始化 wevu-features 应用唯一的 router 实例。
 */
export function ensureWevuFeaturesRouter() {
  if (wevuFeaturesRouterCreated) {
    return
  }

  const autoGeneratedRoutes = autoRoutes.entries.map(path => ({
    path: `/${path}`,
  }))

  const routerCoverageRoutes = [
    {
      path: ROUTER_COVERAGE_PATHS.mainTarget,
      beforeEnter(to, from) {
        console.log('[router-coverage] beforeEnter main-target', {
          to: to?.fullPath,
          from: from.fullPath,
        })
        return true
      },
    },
    {
      path: ROUTER_COVERAGE_PATHS.normalSubpackageTarget,
      beforeEnter(to, from) {
        console.log('[router-coverage] beforeEnter normal-subpackage-target', {
          to: to?.fullPath,
          from: from.fullPath,
        })
        return true
      },
    },
    {
      path: ROUTER_COVERAGE_PATHS.independentSubpackageTarget,
      beforeEnter(to, from) {
        console.log('[router-coverage] beforeEnter independent-subpackage-target', {
          to: to?.fullPath,
          from: from.fullPath,
        })
        return true
      },
    },
  ]

  const router = createRouter({
    rejectOnError: false,
    routes: mergeRoutesByPath(
      autoGeneratedRoutes,
      routerCoverageRoutes,
      [
        {
          path: '/pages/router-showcase/profile/:id',
          alias: '/router-profile/:id',
          meta: {
            zone: 'profile',
          },
          children: [
            {
              path: 'detail/:tab',
              alias: 'detail-alias/:tab',
              meta: {
                zone: 'profile-detail',
              },
            },
          ],
        },
        {
          path: '/router-guard/block',
        },
        {
          path: '/router-guard/error',
        },
        {
          path: ROUTER_COVERAGE_PATHS.blocked,
        },
        {
          path: ROUTER_COVERAGE_PATHS.error,
        },
        {
          path: '/components/router-origin-probe/target/index',
        },
      ],
    ),
  })

  router.beforeEach((to, from) => {
    console.log('[router-coverage] beforeEach', {
      to: to?.fullPath,
      from: from.fullPath,
    })

    if (normalizeGuardPath(to?.path) === normalizeGuardPath(ROUTER_COVERAGE_PATHS.blocked)) {
      console.log('[router-coverage] beforeEach blocked navigation', {
        to: to?.fullPath,
      })
      return false
    }

    return true
  })

  router.beforeResolve((to, from) => {
    console.log('[router-coverage] beforeResolve', {
      to: to?.fullPath,
      from: from.fullPath,
    })

    if (normalizeGuardPath(to?.path) === normalizeGuardPath(ROUTER_COVERAGE_PATHS.error)) {
      throw new Error('router-coverage-beforeResolve-error')
    }

    return true
  })

  router.afterEach((to, from, failure) => {
    console.log('[router-coverage] afterEach', {
      to: to?.fullPath,
      from: from.fullPath,
      failureType: failure?.type,
      failureMessage: failure?.message,
    })
  })

  router.onError((error, context) => {
    console.log('[router-coverage] onError', {
      error: error instanceof Error ? error.message : String(error),
      mode: context.mode,
      to: context.to?.fullPath,
      from: context.from.fullPath,
      failureType: context.failure.type,
    })
  })

  wevuFeaturesRouterCreated = true
}
