/* eslint-disable */
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by weapp-vite autoImportComponents
import type { ComponentOptionsMixin, DefineComponent, PublicProps } from 'vue'
import type { ComponentProp } from 'weapp-vite/typed-components'

export {}

type WeappComponent<Props = Record<string, any>> = DefineComponent<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, PublicProps, Props, {}>

declare module 'vue' {
  export interface GlobalComponents {
    TActionSheet: typeof import("tdesign-miniprogram/miniprogram_dist/action-sheet/action-sheet.js") & WeappComponent<ComponentProp<"t-action-sheet">>;
    't-action-sheet': typeof import("tdesign-miniprogram/miniprogram_dist/action-sheet/action-sheet.js") & WeappComponent<ComponentProp<"t-action-sheet">>;
    TAvatar: typeof import("tdesign-miniprogram/miniprogram_dist/avatar/avatar.js") & WeappComponent<ComponentProp<"t-avatar">>;
    't-avatar': typeof import("tdesign-miniprogram/miniprogram_dist/avatar/avatar.js") & WeappComponent<ComponentProp<"t-avatar">>;
    TAvatarGroup: typeof import("tdesign-miniprogram/miniprogram_dist/avatar-group/avatar-group.js") & WeappComponent<ComponentProp<"t-avatar-group">>;
    't-avatar-group': typeof import("tdesign-miniprogram/miniprogram_dist/avatar-group/avatar-group.js") & WeappComponent<ComponentProp<"t-avatar-group">>;
    TBackTop: typeof import("tdesign-miniprogram/miniprogram_dist/back-top/back-top.js") & WeappComponent<ComponentProp<"t-back-top">>;
    't-back-top': typeof import("tdesign-miniprogram/miniprogram_dist/back-top/back-top.js") & WeappComponent<ComponentProp<"t-back-top">>;
    TBadge: typeof import("tdesign-miniprogram/miniprogram_dist/badge/badge.js") & WeappComponent<ComponentProp<"t-badge">>;
    't-badge': typeof import("tdesign-miniprogram/miniprogram_dist/badge/badge.js") & WeappComponent<ComponentProp<"t-badge">>;
    TButton: typeof import("tdesign-miniprogram/miniprogram_dist/button/button.js") & WeappComponent<ComponentProp<"t-button">>;
    't-button': typeof import("tdesign-miniprogram/miniprogram_dist/button/button.js") & WeappComponent<ComponentProp<"t-button">>;
    TCalendar: typeof import("tdesign-miniprogram/miniprogram_dist/calendar/calendar.js") & WeappComponent<ComponentProp<"t-calendar">>;
    't-calendar': typeof import("tdesign-miniprogram/miniprogram_dist/calendar/calendar.js") & WeappComponent<ComponentProp<"t-calendar">>;
    TCascader: typeof import("tdesign-miniprogram/miniprogram_dist/cascader/cascader.js") & WeappComponent<ComponentProp<"t-cascader">>;
    't-cascader': typeof import("tdesign-miniprogram/miniprogram_dist/cascader/cascader.js") & WeappComponent<ComponentProp<"t-cascader">>;
    TCell: typeof import("tdesign-miniprogram/miniprogram_dist/cell/cell.js") & WeappComponent<ComponentProp<"t-cell">>;
    't-cell': typeof import("tdesign-miniprogram/miniprogram_dist/cell/cell.js") & WeappComponent<ComponentProp<"t-cell">>;
    TCellGroup: typeof import("tdesign-miniprogram/miniprogram_dist/cell-group/cell-group.js") & WeappComponent<ComponentProp<"t-cell-group">>;
    't-cell-group': typeof import("tdesign-miniprogram/miniprogram_dist/cell-group/cell-group.js") & WeappComponent<ComponentProp<"t-cell-group">>;
    TCheckTag: typeof import("tdesign-miniprogram/miniprogram_dist/check-tag/check-tag.js") & WeappComponent<ComponentProp<"t-check-tag">>;
    't-check-tag': typeof import("tdesign-miniprogram/miniprogram_dist/check-tag/check-tag.js") & WeappComponent<ComponentProp<"t-check-tag">>;
    TCheckbox: typeof import("tdesign-miniprogram/miniprogram_dist/checkbox/checkbox.js") & WeappComponent<ComponentProp<"t-checkbox">>;
    't-checkbox': typeof import("tdesign-miniprogram/miniprogram_dist/checkbox/checkbox.js") & WeappComponent<ComponentProp<"t-checkbox">>;
    TCheckboxGroup: typeof import("tdesign-miniprogram/miniprogram_dist/checkbox-group/checkbox-group.js") & WeappComponent<ComponentProp<"t-checkbox-group">>;
    't-checkbox-group': typeof import("tdesign-miniprogram/miniprogram_dist/checkbox-group/checkbox-group.js") & WeappComponent<ComponentProp<"t-checkbox-group">>;
    TCol: typeof import("tdesign-miniprogram/miniprogram_dist/col/col.js") & WeappComponent<ComponentProp<"t-col">>;
    't-col': typeof import("tdesign-miniprogram/miniprogram_dist/col/col.js") & WeappComponent<ComponentProp<"t-col">>;
    TCollapse: typeof import("tdesign-miniprogram/miniprogram_dist/collapse/collapse.js") & WeappComponent<ComponentProp<"t-collapse">>;
    't-collapse': typeof import("tdesign-miniprogram/miniprogram_dist/collapse/collapse.js") & WeappComponent<ComponentProp<"t-collapse">>;
    TCollapsePanel: typeof import("tdesign-miniprogram/miniprogram_dist/collapse-panel/collapse-panel.js") & WeappComponent<ComponentProp<"t-collapse-panel">>;
    't-collapse-panel': typeof import("tdesign-miniprogram/miniprogram_dist/collapse-panel/collapse-panel.js") & WeappComponent<ComponentProp<"t-collapse-panel">>;
    TColorPicker: typeof import("tdesign-miniprogram/miniprogram_dist/color-picker/color-picker.js") & WeappComponent<ComponentProp<"t-color-picker">>;
    't-color-picker': typeof import("tdesign-miniprogram/miniprogram_dist/color-picker/color-picker.js") & WeappComponent<ComponentProp<"t-color-picker">>;
    TCountDown: typeof import("tdesign-miniprogram/miniprogram_dist/count-down/count-down.js") & WeappComponent<ComponentProp<"t-count-down">>;
    't-count-down': typeof import("tdesign-miniprogram/miniprogram_dist/count-down/count-down.js") & WeappComponent<ComponentProp<"t-count-down">>;
    TDateTimePicker: typeof import("tdesign-miniprogram/miniprogram_dist/date-time-picker/date-time-picker.js") & WeappComponent<ComponentProp<"t-date-time-picker">>;
    't-date-time-picker': typeof import("tdesign-miniprogram/miniprogram_dist/date-time-picker/date-time-picker.js") & WeappComponent<ComponentProp<"t-date-time-picker">>;
    TDialog: typeof import("tdesign-miniprogram/miniprogram_dist/dialog/dialog.js") & WeappComponent<ComponentProp<"t-dialog">>;
    't-dialog': typeof import("tdesign-miniprogram/miniprogram_dist/dialog/dialog.js") & WeappComponent<ComponentProp<"t-dialog">>;
    TDivider: typeof import("tdesign-miniprogram/miniprogram_dist/divider/divider.js") & WeappComponent<ComponentProp<"t-divider">>;
    't-divider': typeof import("tdesign-miniprogram/miniprogram_dist/divider/divider.js") & WeappComponent<ComponentProp<"t-divider">>;
    TDrawer: typeof import("tdesign-miniprogram/miniprogram_dist/drawer/drawer.js") & WeappComponent<ComponentProp<"t-drawer">>;
    't-drawer': typeof import("tdesign-miniprogram/miniprogram_dist/drawer/drawer.js") & WeappComponent<ComponentProp<"t-drawer">>;
    TDropdownItem: typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-item/dropdown-item.js") & WeappComponent<ComponentProp<"t-dropdown-item">>;
    't-dropdown-item': typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-item/dropdown-item.js") & WeappComponent<ComponentProp<"t-dropdown-item">>;
    TDropdownMenu: typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-menu/dropdown-menu.js") & WeappComponent<ComponentProp<"t-dropdown-menu">>;
    't-dropdown-menu': typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-menu/dropdown-menu.js") & WeappComponent<ComponentProp<"t-dropdown-menu">>;
    TEmpty: typeof import("tdesign-miniprogram/miniprogram_dist/empty/empty.js") & WeappComponent<ComponentProp<"t-empty">>;
    't-empty': typeof import("tdesign-miniprogram/miniprogram_dist/empty/empty.js") & WeappComponent<ComponentProp<"t-empty">>;
    TFab: typeof import("tdesign-miniprogram/miniprogram_dist/fab/fab.js") & WeappComponent<ComponentProp<"t-fab">>;
    't-fab': typeof import("tdesign-miniprogram/miniprogram_dist/fab/fab.js") & WeappComponent<ComponentProp<"t-fab">>;
    TFooter: typeof import("tdesign-miniprogram/miniprogram_dist/footer/footer.js") & WeappComponent<ComponentProp<"t-footer">>;
    't-footer': typeof import("tdesign-miniprogram/miniprogram_dist/footer/footer.js") & WeappComponent<ComponentProp<"t-footer">>;
    TForm: WeappComponent<ComponentProp<"t-form">>;
    't-form': WeappComponent<ComponentProp<"t-form">>;
    TFormItem: WeappComponent<ComponentProp<"t-form-item">>;
    't-form-item': WeappComponent<ComponentProp<"t-form-item">>;
    TGrid: typeof import("tdesign-miniprogram/miniprogram_dist/grid/grid.js") & WeappComponent<ComponentProp<"t-grid">>;
    't-grid': typeof import("tdesign-miniprogram/miniprogram_dist/grid/grid.js") & WeappComponent<ComponentProp<"t-grid">>;
    TGridItem: typeof import("tdesign-miniprogram/miniprogram_dist/grid-item/grid-item.js") & WeappComponent<ComponentProp<"t-grid-item">>;
    't-grid-item': typeof import("tdesign-miniprogram/miniprogram_dist/grid-item/grid-item.js") & WeappComponent<ComponentProp<"t-grid-item">>;
    TGuide: typeof import("tdesign-miniprogram/miniprogram_dist/guide/guide.js") & WeappComponent<ComponentProp<"t-guide">>;
    't-guide': typeof import("tdesign-miniprogram/miniprogram_dist/guide/guide.js") & WeappComponent<ComponentProp<"t-guide">>;
    TIcon: typeof import("tdesign-miniprogram/miniprogram_dist/icon/icon.js") & WeappComponent<ComponentProp<"t-icon">>;
    't-icon': typeof import("tdesign-miniprogram/miniprogram_dist/icon/icon.js") & WeappComponent<ComponentProp<"t-icon">>;
    TImage: typeof import("tdesign-miniprogram/miniprogram_dist/image/image.js") & WeappComponent<ComponentProp<"t-image">>;
    't-image': typeof import("tdesign-miniprogram/miniprogram_dist/image/image.js") & WeappComponent<ComponentProp<"t-image">>;
    TImageViewer: typeof import("tdesign-miniprogram/miniprogram_dist/image-viewer/image-viewer.js") & WeappComponent<ComponentProp<"t-image-viewer">>;
    't-image-viewer': typeof import("tdesign-miniprogram/miniprogram_dist/image-viewer/image-viewer.js") & WeappComponent<ComponentProp<"t-image-viewer">>;
    TIndexes: typeof import("tdesign-miniprogram/miniprogram_dist/indexes/indexes.js") & WeappComponent<ComponentProp<"t-indexes">>;
    't-indexes': typeof import("tdesign-miniprogram/miniprogram_dist/indexes/indexes.js") & WeappComponent<ComponentProp<"t-indexes">>;
    TIndexesAnchor: typeof import("tdesign-miniprogram/miniprogram_dist/indexes-anchor/indexes-anchor.js") & WeappComponent<ComponentProp<"t-indexes-anchor">>;
    't-indexes-anchor': typeof import("tdesign-miniprogram/miniprogram_dist/indexes-anchor/indexes-anchor.js") & WeappComponent<ComponentProp<"t-indexes-anchor">>;
    TInput: typeof import("tdesign-miniprogram/miniprogram_dist/input/input.js") & WeappComponent<ComponentProp<"t-input">>;
    't-input': typeof import("tdesign-miniprogram/miniprogram_dist/input/input.js") & WeappComponent<ComponentProp<"t-input">>;
    TLink: typeof import("tdesign-miniprogram/miniprogram_dist/link/link.js") & WeappComponent<ComponentProp<"t-link">>;
    't-link': typeof import("tdesign-miniprogram/miniprogram_dist/link/link.js") & WeappComponent<ComponentProp<"t-link">>;
    TLoading: typeof import("tdesign-miniprogram/miniprogram_dist/loading/loading.js") & WeappComponent<ComponentProp<"t-loading">>;
    't-loading': typeof import("tdesign-miniprogram/miniprogram_dist/loading/loading.js") & WeappComponent<ComponentProp<"t-loading">>;
    TMessage: typeof import("tdesign-miniprogram/miniprogram_dist/message/message.js") & WeappComponent<ComponentProp<"t-message">>;
    't-message': typeof import("tdesign-miniprogram/miniprogram_dist/message/message.js") & WeappComponent<ComponentProp<"t-message">>;
    TMessageItem: typeof import("tdesign-miniprogram/miniprogram_dist/message-item/message-item.js") & WeappComponent<ComponentProp<"t-message-item">>;
    't-message-item': typeof import("tdesign-miniprogram/miniprogram_dist/message-item/message-item.js") & WeappComponent<ComponentProp<"t-message-item">>;
    TNavbar: typeof import("tdesign-miniprogram/miniprogram_dist/navbar/navbar.js") & WeappComponent<ComponentProp<"t-navbar">>;
    't-navbar': typeof import("tdesign-miniprogram/miniprogram_dist/navbar/navbar.js") & WeappComponent<ComponentProp<"t-navbar">>;
    TNoticeBar: typeof import("tdesign-miniprogram/miniprogram_dist/notice-bar/notice-bar.js") & WeappComponent<ComponentProp<"t-notice-bar">>;
    't-notice-bar': typeof import("tdesign-miniprogram/miniprogram_dist/notice-bar/notice-bar.js") & WeappComponent<ComponentProp<"t-notice-bar">>;
    TOverlay: typeof import("tdesign-miniprogram/miniprogram_dist/overlay/overlay.js") & WeappComponent<ComponentProp<"t-overlay">>;
    't-overlay': typeof import("tdesign-miniprogram/miniprogram_dist/overlay/overlay.js") & WeappComponent<ComponentProp<"t-overlay">>;
    TPicker: typeof import("tdesign-miniprogram/miniprogram_dist/picker/picker.js") & WeappComponent<ComponentProp<"t-picker">>;
    't-picker': typeof import("tdesign-miniprogram/miniprogram_dist/picker/picker.js") & WeappComponent<ComponentProp<"t-picker">>;
    TPickerItem: typeof import("tdesign-miniprogram/miniprogram_dist/picker-item/picker-item.js") & WeappComponent<ComponentProp<"t-picker-item">>;
    't-picker-item': typeof import("tdesign-miniprogram/miniprogram_dist/picker-item/picker-item.js") & WeappComponent<ComponentProp<"t-picker-item">>;
    TPopup: typeof import("tdesign-miniprogram/miniprogram_dist/popup/popup.js") & WeappComponent<ComponentProp<"t-popup">>;
    't-popup': typeof import("tdesign-miniprogram/miniprogram_dist/popup/popup.js") & WeappComponent<ComponentProp<"t-popup">>;
    TProgress: typeof import("tdesign-miniprogram/miniprogram_dist/progress/progress.js") & WeappComponent<ComponentProp<"t-progress">>;
    't-progress': typeof import("tdesign-miniprogram/miniprogram_dist/progress/progress.js") & WeappComponent<ComponentProp<"t-progress">>;
    TPullDownRefresh: typeof import("tdesign-miniprogram/miniprogram_dist/pull-down-refresh/pull-down-refresh.js") & WeappComponent<ComponentProp<"t-pull-down-refresh">>;
    't-pull-down-refresh': typeof import("tdesign-miniprogram/miniprogram_dist/pull-down-refresh/pull-down-refresh.js") & WeappComponent<ComponentProp<"t-pull-down-refresh">>;
    TQrcode: typeof import("tdesign-miniprogram/miniprogram_dist/qrcode/qrcode.js") & WeappComponent<ComponentProp<"t-qrcode">>;
    't-qrcode': typeof import("tdesign-miniprogram/miniprogram_dist/qrcode/qrcode.js") & WeappComponent<ComponentProp<"t-qrcode">>;
    TRadio: typeof import("tdesign-miniprogram/miniprogram_dist/radio/radio.js") & WeappComponent<ComponentProp<"t-radio">>;
    't-radio': typeof import("tdesign-miniprogram/miniprogram_dist/radio/radio.js") & WeappComponent<ComponentProp<"t-radio">>;
    TRadioGroup: typeof import("tdesign-miniprogram/miniprogram_dist/radio-group/radio-group.js") & WeappComponent<ComponentProp<"t-radio-group">>;
    't-radio-group': typeof import("tdesign-miniprogram/miniprogram_dist/radio-group/radio-group.js") & WeappComponent<ComponentProp<"t-radio-group">>;
    TRate: typeof import("tdesign-miniprogram/miniprogram_dist/rate/rate.js") & WeappComponent<ComponentProp<"t-rate">>;
    't-rate': typeof import("tdesign-miniprogram/miniprogram_dist/rate/rate.js") & WeappComponent<ComponentProp<"t-rate">>;
    TResult: typeof import("tdesign-miniprogram/miniprogram_dist/result/result.js") & WeappComponent<ComponentProp<"t-result">>;
    't-result': typeof import("tdesign-miniprogram/miniprogram_dist/result/result.js") & WeappComponent<ComponentProp<"t-result">>;
    TRow: typeof import("tdesign-miniprogram/miniprogram_dist/row/row.js") & WeappComponent<ComponentProp<"t-row">>;
    't-row': typeof import("tdesign-miniprogram/miniprogram_dist/row/row.js") & WeappComponent<ComponentProp<"t-row">>;
    TScrollView: typeof import("tdesign-miniprogram/miniprogram_dist/scroll-view/scroll-view.js") & WeappComponent<ComponentProp<"t-scroll-view">>;
    't-scroll-view': typeof import("tdesign-miniprogram/miniprogram_dist/scroll-view/scroll-view.js") & WeappComponent<ComponentProp<"t-scroll-view">>;
    TSearch: typeof import("tdesign-miniprogram/miniprogram_dist/search/search.js") & WeappComponent<ComponentProp<"t-search">>;
    't-search': typeof import("tdesign-miniprogram/miniprogram_dist/search/search.js") & WeappComponent<ComponentProp<"t-search">>;
    TSideBar: typeof import("tdesign-miniprogram/miniprogram_dist/side-bar/side-bar.js") & WeappComponent<ComponentProp<"t-side-bar">>;
    't-side-bar': typeof import("tdesign-miniprogram/miniprogram_dist/side-bar/side-bar.js") & WeappComponent<ComponentProp<"t-side-bar">>;
    TSideBarItem: typeof import("tdesign-miniprogram/miniprogram_dist/side-bar-item/side-bar-item.js") & WeappComponent<ComponentProp<"t-side-bar-item">>;
    't-side-bar-item': typeof import("tdesign-miniprogram/miniprogram_dist/side-bar-item/side-bar-item.js") & WeappComponent<ComponentProp<"t-side-bar-item">>;
    TSkeleton: typeof import("tdesign-miniprogram/miniprogram_dist/skeleton/skeleton.js") & WeappComponent<ComponentProp<"t-skeleton">>;
    't-skeleton': typeof import("tdesign-miniprogram/miniprogram_dist/skeleton/skeleton.js") & WeappComponent<ComponentProp<"t-skeleton">>;
    TSlider: typeof import("tdesign-miniprogram/miniprogram_dist/slider/slider.js") & WeappComponent<ComponentProp<"t-slider">>;
    't-slider': typeof import("tdesign-miniprogram/miniprogram_dist/slider/slider.js") & WeappComponent<ComponentProp<"t-slider">>;
    TStepItem: typeof import("tdesign-miniprogram/miniprogram_dist/step-item/step-item.js") & WeappComponent<ComponentProp<"t-step-item">>;
    't-step-item': typeof import("tdesign-miniprogram/miniprogram_dist/step-item/step-item.js") & WeappComponent<ComponentProp<"t-step-item">>;
    TStepper: typeof import("tdesign-miniprogram/miniprogram_dist/stepper/stepper.js") & WeappComponent<ComponentProp<"t-stepper">>;
    't-stepper': typeof import("tdesign-miniprogram/miniprogram_dist/stepper/stepper.js") & WeappComponent<ComponentProp<"t-stepper">>;
    TSteps: typeof import("tdesign-miniprogram/miniprogram_dist/steps/steps.js") & WeappComponent<ComponentProp<"t-steps">>;
    't-steps': typeof import("tdesign-miniprogram/miniprogram_dist/steps/steps.js") & WeappComponent<ComponentProp<"t-steps">>;
    TSticky: typeof import("tdesign-miniprogram/miniprogram_dist/sticky/sticky.js") & WeappComponent<ComponentProp<"t-sticky">>;
    't-sticky': typeof import("tdesign-miniprogram/miniprogram_dist/sticky/sticky.js") & WeappComponent<ComponentProp<"t-sticky">>;
    TSwipeCell: typeof import("tdesign-miniprogram/miniprogram_dist/swipe-cell/swipe-cell.js") & WeappComponent<ComponentProp<"t-swipe-cell">>;
    't-swipe-cell': typeof import("tdesign-miniprogram/miniprogram_dist/swipe-cell/swipe-cell.js") & WeappComponent<ComponentProp<"t-swipe-cell">>;
    TSwiper: typeof import("tdesign-miniprogram/miniprogram_dist/swiper/swiper.js") & WeappComponent<ComponentProp<"t-swiper">>;
    't-swiper': typeof import("tdesign-miniprogram/miniprogram_dist/swiper/swiper.js") & WeappComponent<ComponentProp<"t-swiper">>;
    TSwiperNav: typeof import("tdesign-miniprogram/miniprogram_dist/swiper-nav/swiper-nav.js") & WeappComponent<ComponentProp<"t-swiper-nav">>;
    't-swiper-nav': typeof import("tdesign-miniprogram/miniprogram_dist/swiper-nav/swiper-nav.js") & WeappComponent<ComponentProp<"t-swiper-nav">>;
    TSwitch: typeof import("tdesign-miniprogram/miniprogram_dist/switch/switch.js") & WeappComponent<ComponentProp<"t-switch">>;
    't-switch': typeof import("tdesign-miniprogram/miniprogram_dist/switch/switch.js") & WeappComponent<ComponentProp<"t-switch">>;
    TTabBar: typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar/tab-bar.js") & WeappComponent<ComponentProp<"t-tab-bar">>;
    't-tab-bar': typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar/tab-bar.js") & WeappComponent<ComponentProp<"t-tab-bar">>;
    TTabBarItem: typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar-item/tab-bar-item.js") & WeappComponent<ComponentProp<"t-tab-bar-item">>;
    't-tab-bar-item': typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar-item/tab-bar-item.js") & WeappComponent<ComponentProp<"t-tab-bar-item">>;
    TTabPanel: typeof import("tdesign-miniprogram/miniprogram_dist/tab-panel/tab-panel.js") & WeappComponent<ComponentProp<"t-tab-panel">>;
    't-tab-panel': typeof import("tdesign-miniprogram/miniprogram_dist/tab-panel/tab-panel.js") & WeappComponent<ComponentProp<"t-tab-panel">>;
    TTabs: typeof import("tdesign-miniprogram/miniprogram_dist/tabs/tabs.js") & WeappComponent<ComponentProp<"t-tabs">>;
    't-tabs': typeof import("tdesign-miniprogram/miniprogram_dist/tabs/tabs.js") & WeappComponent<ComponentProp<"t-tabs">>;
    TTag: typeof import("tdesign-miniprogram/miniprogram_dist/tag/tag.js") & WeappComponent<ComponentProp<"t-tag">>;
    't-tag': typeof import("tdesign-miniprogram/miniprogram_dist/tag/tag.js") & WeappComponent<ComponentProp<"t-tag">>;
    TTextarea: typeof import("tdesign-miniprogram/miniprogram_dist/textarea/textarea.js") & WeappComponent<ComponentProp<"t-textarea">>;
    't-textarea': typeof import("tdesign-miniprogram/miniprogram_dist/textarea/textarea.js") & WeappComponent<ComponentProp<"t-textarea">>;
    TToast: typeof import("tdesign-miniprogram/miniprogram_dist/toast/toast.js") & WeappComponent<ComponentProp<"t-toast">>;
    't-toast': typeof import("tdesign-miniprogram/miniprogram_dist/toast/toast.js") & WeappComponent<ComponentProp<"t-toast">>;
    TTransition: typeof import("tdesign-miniprogram/miniprogram_dist/transition/transition.js") & WeappComponent<ComponentProp<"t-transition">>;
    't-transition': typeof import("tdesign-miniprogram/miniprogram_dist/transition/transition.js") & WeappComponent<ComponentProp<"t-transition">>;
    TTreeSelect: typeof import("tdesign-miniprogram/miniprogram_dist/tree-select/tree-select.js") & WeappComponent<ComponentProp<"t-tree-select">>;
    't-tree-select': typeof import("tdesign-miniprogram/miniprogram_dist/tree-select/tree-select.js") & WeappComponent<ComponentProp<"t-tree-select">>;
    TUpload: typeof import("tdesign-miniprogram/miniprogram_dist/upload/upload.js") & WeappComponent<ComponentProp<"t-upload">>;
    't-upload': typeof import("tdesign-miniprogram/miniprogram_dist/upload/upload.js") & WeappComponent<ComponentProp<"t-upload">>;
    TWatermark: typeof import("tdesign-miniprogram/miniprogram_dist/watermark/watermark.js") & WeappComponent<ComponentProp<"t-watermark">>;
    't-watermark': typeof import("tdesign-miniprogram/miniprogram_dist/watermark/watermark.js") & WeappComponent<ComponentProp<"t-watermark">>;
    [component: string]: WeappComponent;
  }
}

// For TSX support
declare global {
  const TActionSheet: typeof import("tdesign-miniprogram/miniprogram_dist/action-sheet/action-sheet.js") & WeappComponent<ComponentProp<"t-action-sheet">>
  const TAvatar: typeof import("tdesign-miniprogram/miniprogram_dist/avatar/avatar.js") & WeappComponent<ComponentProp<"t-avatar">>
  const TAvatarGroup: typeof import("tdesign-miniprogram/miniprogram_dist/avatar-group/avatar-group.js") & WeappComponent<ComponentProp<"t-avatar-group">>
  const TBackTop: typeof import("tdesign-miniprogram/miniprogram_dist/back-top/back-top.js") & WeappComponent<ComponentProp<"t-back-top">>
  const TBadge: typeof import("tdesign-miniprogram/miniprogram_dist/badge/badge.js") & WeappComponent<ComponentProp<"t-badge">>
  const TButton: typeof import("tdesign-miniprogram/miniprogram_dist/button/button.js") & WeappComponent<ComponentProp<"t-button">>
  const TCalendar: typeof import("tdesign-miniprogram/miniprogram_dist/calendar/calendar.js") & WeappComponent<ComponentProp<"t-calendar">>
  const TCascader: typeof import("tdesign-miniprogram/miniprogram_dist/cascader/cascader.js") & WeappComponent<ComponentProp<"t-cascader">>
  const TCell: typeof import("tdesign-miniprogram/miniprogram_dist/cell/cell.js") & WeappComponent<ComponentProp<"t-cell">>
  const TCellGroup: typeof import("tdesign-miniprogram/miniprogram_dist/cell-group/cell-group.js") & WeappComponent<ComponentProp<"t-cell-group">>
  const TCheckTag: typeof import("tdesign-miniprogram/miniprogram_dist/check-tag/check-tag.js") & WeappComponent<ComponentProp<"t-check-tag">>
  const TCheckbox: typeof import("tdesign-miniprogram/miniprogram_dist/checkbox/checkbox.js") & WeappComponent<ComponentProp<"t-checkbox">>
  const TCheckboxGroup: typeof import("tdesign-miniprogram/miniprogram_dist/checkbox-group/checkbox-group.js") & WeappComponent<ComponentProp<"t-checkbox-group">>
  const TCol: typeof import("tdesign-miniprogram/miniprogram_dist/col/col.js") & WeappComponent<ComponentProp<"t-col">>
  const TCollapse: typeof import("tdesign-miniprogram/miniprogram_dist/collapse/collapse.js") & WeappComponent<ComponentProp<"t-collapse">>
  const TCollapsePanel: typeof import("tdesign-miniprogram/miniprogram_dist/collapse-panel/collapse-panel.js") & WeappComponent<ComponentProp<"t-collapse-panel">>
  const TColorPicker: typeof import("tdesign-miniprogram/miniprogram_dist/color-picker/color-picker.js") & WeappComponent<ComponentProp<"t-color-picker">>
  const TCountDown: typeof import("tdesign-miniprogram/miniprogram_dist/count-down/count-down.js") & WeappComponent<ComponentProp<"t-count-down">>
  const TDateTimePicker: typeof import("tdesign-miniprogram/miniprogram_dist/date-time-picker/date-time-picker.js") & WeappComponent<ComponentProp<"t-date-time-picker">>
  const TDialog: typeof import("tdesign-miniprogram/miniprogram_dist/dialog/dialog.js") & WeappComponent<ComponentProp<"t-dialog">>
  const TDivider: typeof import("tdesign-miniprogram/miniprogram_dist/divider/divider.js") & WeappComponent<ComponentProp<"t-divider">>
  const TDrawer: typeof import("tdesign-miniprogram/miniprogram_dist/drawer/drawer.js") & WeappComponent<ComponentProp<"t-drawer">>
  const TDropdownItem: typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-item/dropdown-item.js") & WeappComponent<ComponentProp<"t-dropdown-item">>
  const TDropdownMenu: typeof import("tdesign-miniprogram/miniprogram_dist/dropdown-menu/dropdown-menu.js") & WeappComponent<ComponentProp<"t-dropdown-menu">>
  const TEmpty: typeof import("tdesign-miniprogram/miniprogram_dist/empty/empty.js") & WeappComponent<ComponentProp<"t-empty">>
  const TFab: typeof import("tdesign-miniprogram/miniprogram_dist/fab/fab.js") & WeappComponent<ComponentProp<"t-fab">>
  const TFooter: typeof import("tdesign-miniprogram/miniprogram_dist/footer/footer.js") & WeappComponent<ComponentProp<"t-footer">>
  const TForm: WeappComponent<ComponentProp<"t-form">>
  const TFormItem: WeappComponent<ComponentProp<"t-form-item">>
  const TGrid: typeof import("tdesign-miniprogram/miniprogram_dist/grid/grid.js") & WeappComponent<ComponentProp<"t-grid">>
  const TGridItem: typeof import("tdesign-miniprogram/miniprogram_dist/grid-item/grid-item.js") & WeappComponent<ComponentProp<"t-grid-item">>
  const TGuide: typeof import("tdesign-miniprogram/miniprogram_dist/guide/guide.js") & WeappComponent<ComponentProp<"t-guide">>
  const TIcon: typeof import("tdesign-miniprogram/miniprogram_dist/icon/icon.js") & WeappComponent<ComponentProp<"t-icon">>
  const TImage: typeof import("tdesign-miniprogram/miniprogram_dist/image/image.js") & WeappComponent<ComponentProp<"t-image">>
  const TImageViewer: typeof import("tdesign-miniprogram/miniprogram_dist/image-viewer/image-viewer.js") & WeappComponent<ComponentProp<"t-image-viewer">>
  const TIndexes: typeof import("tdesign-miniprogram/miniprogram_dist/indexes/indexes.js") & WeappComponent<ComponentProp<"t-indexes">>
  const TIndexesAnchor: typeof import("tdesign-miniprogram/miniprogram_dist/indexes-anchor/indexes-anchor.js") & WeappComponent<ComponentProp<"t-indexes-anchor">>
  const TInput: typeof import("tdesign-miniprogram/miniprogram_dist/input/input.js") & WeappComponent<ComponentProp<"t-input">>
  const TLink: typeof import("tdesign-miniprogram/miniprogram_dist/link/link.js") & WeappComponent<ComponentProp<"t-link">>
  const TLoading: typeof import("tdesign-miniprogram/miniprogram_dist/loading/loading.js") & WeappComponent<ComponentProp<"t-loading">>
  const TMessage: typeof import("tdesign-miniprogram/miniprogram_dist/message/message.js") & WeappComponent<ComponentProp<"t-message">>
  const TMessageItem: typeof import("tdesign-miniprogram/miniprogram_dist/message-item/message-item.js") & WeappComponent<ComponentProp<"t-message-item">>
  const TNavbar: typeof import("tdesign-miniprogram/miniprogram_dist/navbar/navbar.js") & WeappComponent<ComponentProp<"t-navbar">>
  const TNoticeBar: typeof import("tdesign-miniprogram/miniprogram_dist/notice-bar/notice-bar.js") & WeappComponent<ComponentProp<"t-notice-bar">>
  const TOverlay: typeof import("tdesign-miniprogram/miniprogram_dist/overlay/overlay.js") & WeappComponent<ComponentProp<"t-overlay">>
  const TPicker: typeof import("tdesign-miniprogram/miniprogram_dist/picker/picker.js") & WeappComponent<ComponentProp<"t-picker">>
  const TPickerItem: typeof import("tdesign-miniprogram/miniprogram_dist/picker-item/picker-item.js") & WeappComponent<ComponentProp<"t-picker-item">>
  const TPopup: typeof import("tdesign-miniprogram/miniprogram_dist/popup/popup.js") & WeappComponent<ComponentProp<"t-popup">>
  const TProgress: typeof import("tdesign-miniprogram/miniprogram_dist/progress/progress.js") & WeappComponent<ComponentProp<"t-progress">>
  const TPullDownRefresh: typeof import("tdesign-miniprogram/miniprogram_dist/pull-down-refresh/pull-down-refresh.js") & WeappComponent<ComponentProp<"t-pull-down-refresh">>
  const TQrcode: typeof import("tdesign-miniprogram/miniprogram_dist/qrcode/qrcode.js") & WeappComponent<ComponentProp<"t-qrcode">>
  const TRadio: typeof import("tdesign-miniprogram/miniprogram_dist/radio/radio.js") & WeappComponent<ComponentProp<"t-radio">>
  const TRadioGroup: typeof import("tdesign-miniprogram/miniprogram_dist/radio-group/radio-group.js") & WeappComponent<ComponentProp<"t-radio-group">>
  const TRate: typeof import("tdesign-miniprogram/miniprogram_dist/rate/rate.js") & WeappComponent<ComponentProp<"t-rate">>
  const TResult: typeof import("tdesign-miniprogram/miniprogram_dist/result/result.js") & WeappComponent<ComponentProp<"t-result">>
  const TRow: typeof import("tdesign-miniprogram/miniprogram_dist/row/row.js") & WeappComponent<ComponentProp<"t-row">>
  const TScrollView: typeof import("tdesign-miniprogram/miniprogram_dist/scroll-view/scroll-view.js") & WeappComponent<ComponentProp<"t-scroll-view">>
  const TSearch: typeof import("tdesign-miniprogram/miniprogram_dist/search/search.js") & WeappComponent<ComponentProp<"t-search">>
  const TSideBar: typeof import("tdesign-miniprogram/miniprogram_dist/side-bar/side-bar.js") & WeappComponent<ComponentProp<"t-side-bar">>
  const TSideBarItem: typeof import("tdesign-miniprogram/miniprogram_dist/side-bar-item/side-bar-item.js") & WeappComponent<ComponentProp<"t-side-bar-item">>
  const TSkeleton: typeof import("tdesign-miniprogram/miniprogram_dist/skeleton/skeleton.js") & WeappComponent<ComponentProp<"t-skeleton">>
  const TSlider: typeof import("tdesign-miniprogram/miniprogram_dist/slider/slider.js") & WeappComponent<ComponentProp<"t-slider">>
  const TStepItem: typeof import("tdesign-miniprogram/miniprogram_dist/step-item/step-item.js") & WeappComponent<ComponentProp<"t-step-item">>
  const TStepper: typeof import("tdesign-miniprogram/miniprogram_dist/stepper/stepper.js") & WeappComponent<ComponentProp<"t-stepper">>
  const TSteps: typeof import("tdesign-miniprogram/miniprogram_dist/steps/steps.js") & WeappComponent<ComponentProp<"t-steps">>
  const TSticky: typeof import("tdesign-miniprogram/miniprogram_dist/sticky/sticky.js") & WeappComponent<ComponentProp<"t-sticky">>
  const TSwipeCell: typeof import("tdesign-miniprogram/miniprogram_dist/swipe-cell/swipe-cell.js") & WeappComponent<ComponentProp<"t-swipe-cell">>
  const TSwiper: typeof import("tdesign-miniprogram/miniprogram_dist/swiper/swiper.js") & WeappComponent<ComponentProp<"t-swiper">>
  const TSwiperNav: typeof import("tdesign-miniprogram/miniprogram_dist/swiper-nav/swiper-nav.js") & WeappComponent<ComponentProp<"t-swiper-nav">>
  const TSwitch: typeof import("tdesign-miniprogram/miniprogram_dist/switch/switch.js") & WeappComponent<ComponentProp<"t-switch">>
  const TTabBar: typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar/tab-bar.js") & WeappComponent<ComponentProp<"t-tab-bar">>
  const TTabBarItem: typeof import("tdesign-miniprogram/miniprogram_dist/tab-bar-item/tab-bar-item.js") & WeappComponent<ComponentProp<"t-tab-bar-item">>
  const TTabPanel: typeof import("tdesign-miniprogram/miniprogram_dist/tab-panel/tab-panel.js") & WeappComponent<ComponentProp<"t-tab-panel">>
  const TTabs: typeof import("tdesign-miniprogram/miniprogram_dist/tabs/tabs.js") & WeappComponent<ComponentProp<"t-tabs">>
  const TTag: typeof import("tdesign-miniprogram/miniprogram_dist/tag/tag.js") & WeappComponent<ComponentProp<"t-tag">>
  const TTextarea: typeof import("tdesign-miniprogram/miniprogram_dist/textarea/textarea.js") & WeappComponent<ComponentProp<"t-textarea">>
  const TToast: typeof import("tdesign-miniprogram/miniprogram_dist/toast/toast.js") & WeappComponent<ComponentProp<"t-toast">>
  const TTransition: typeof import("tdesign-miniprogram/miniprogram_dist/transition/transition.js") & WeappComponent<ComponentProp<"t-transition">>
  const TTreeSelect: typeof import("tdesign-miniprogram/miniprogram_dist/tree-select/tree-select.js") & WeappComponent<ComponentProp<"t-tree-select">>
  const TUpload: typeof import("tdesign-miniprogram/miniprogram_dist/upload/upload.js") & WeappComponent<ComponentProp<"t-upload">>
  const TWatermark: typeof import("tdesign-miniprogram/miniprogram_dist/watermark/watermark.js") & WeappComponent<ComponentProp<"t-watermark">>
}
