/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// 由 weapp-vite 自动生成，请勿编辑。
declare module 'weapp-vite/typed-components' {
  export interface ComponentProps {
    't-action-sheet': {
      readonly align?: 'center' | 'left';
      readonly cancelText?: string;
      readonly count?: number;
      readonly defaultVisible?: boolean;
      readonly description?: string;
      readonly items?: Array<string | ActionSheetItem>;
      readonly popupProps?: PopupProps;
      readonly showCancel?: boolean;
      readonly showOverlay?: boolean;
      readonly theme?: 'list' | 'grid';
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
    };
    't-avatar': {
      readonly alt?: string;
      readonly badgeProps?: BadgeProps;
      readonly bordered?: boolean;
      readonly hideOnLoadFailed?: boolean;
      readonly icon?: string | object;
      readonly image?: string;
      readonly imageProps?: ImageProps;
      readonly shape?: ShapeEnum;
      readonly size?: string;
    };
    't-avatar-group': {
      readonly cascading?: CascadingValue;
      readonly collapseAvatar?: string;
      readonly max?: number;
      readonly shape?: ShapeEnum;
      readonly size?: string;
    };
    't-back-top': {
      readonly fixed?: boolean;
      readonly icon?: string | boolean | object;
      readonly scrollTop?: number;
      readonly text?: string;
      readonly theme?: 'round' | 'half-round' | 'round-dark' | 'half-round-dark';
      readonly visibilityHeight?: number;
    };
    't-badge': {
      readonly color?: string;
      readonly content?: string;
      readonly count?: string | number;
      readonly dot?: boolean;
      readonly maxCount?: number;
      readonly offset?: Array<string | number>;
      readonly shape?: 'circle' | 'square' | 'bubble' | 'ribbon' | 'ribbon-right' | 'ribbon-left' | 'triangle-right' | 'triangle-left';
      readonly showZero?: boolean;
      readonly size?: 'medium' | 'large';
    };
    't-button': {
      readonly appParameter?: string;
      readonly block?: boolean;
      readonly content?: string;
      readonly customDataset?: null;
      readonly disabled?: boolean;
      readonly ghost?: boolean;
      readonly hoverClass?: string;
      readonly hoverStartTime?: number;
      readonly hoverStayTime?: number;
      readonly hoverStopPropagation?: boolean;
      readonly icon?: string | object;
      readonly lang?: 'en' | 'zh_CN' | 'zh_TW';
      readonly loading?: boolean;
      readonly loadingProps?: LoadingProps;
      readonly openType?: 'contact' | 'share' | 'getPhoneNumber' | 'getUserInfo' | 'launchApp' | 'openSetting' | 'feedback' | 'chooseAvatar' | 'agreePrivacyAuthorization';
      readonly phoneNumberNoQuotaToast?: boolean;
      readonly sendMessageImg?: string;
      readonly sendMessagePath?: string;
      readonly sendMessageTitle?: string;
      readonly sessionFrom?: string;
      readonly shape?: 'rectangle' | 'square' | 'round' | 'circle';
      readonly showMessageCard?: boolean;
      readonly size?: 'extra-small' | 'small' | 'medium' | 'large';
      readonly theme?: 'default' | 'primary' | 'danger' | 'light';
      readonly tId?: string;
      readonly type?: 'submit' | 'reset';
      readonly variant?: 'base' | 'outline' | 'dashed' | 'text';
    };
    't-calendar': {
      readonly allowSameDay?: boolean;
      readonly autoClose?: boolean;
      readonly confirmBtn?: string | ButtonProps | null;
      readonly defaultValue?: number | number[];
      readonly firstDayOfWeek?: number;
      readonly format?: CalendarFormatType;
      readonly localeText?: CalendarLocaleText;
      readonly maxDate?: number;
      readonly minDate?: number;
      readonly readonly?: boolean;
      readonly switchMode?: 'none' | 'month' | 'year-month';
      readonly title?: string;
      readonly type?: 'single' | 'multiple' | 'range';
      readonly usePopup?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly value?: number | number[];
      readonly visible?: boolean;
    };
    't-cascader': {
      readonly checkStrictly?: boolean;
      readonly closeBtn?: boolean;
      readonly defaultValue?: string | number;
      readonly keys?: CascaderKeysType;
      readonly options?: Array<CascaderOption>;
      readonly placeholder?: string;
      readonly subTitles?: Array<string>;
      readonly theme?: 'step' | 'tab';
      readonly title?: string;
      readonly value?: string | number;
      readonly visible?: boolean;
    };
    't-cell': {
      readonly align?: 'top' | 'middle' | 'bottom';
      readonly arrow?: boolean | object;
      readonly bordered?: boolean;
      readonly description?: string;
      readonly hover?: boolean;
      readonly image?: string;
      readonly jumpType?: 'switchTab' | 'reLaunch' | 'redirectTo' | 'navigateTo';
      readonly leftIcon?: string | object;
      readonly note?: string;
      readonly required?: boolean;
      readonly rightIcon?: string | object;
      readonly title?: string;
      readonly url?: string;
    };
    't-cell-group': {
      readonly bordered?: boolean;
      readonly theme?: 'default' | 'card';
      readonly title?: string;
    };
    't-check-tag': {
      readonly checked?: boolean;
      readonly closable?: boolean;
      readonly content?: string | number | string[];
      readonly defaultChecked?: boolean;
      readonly disabled?: boolean;
      readonly icon?: string | object;
      readonly shape?: 'square' | 'round' | 'mark';
      readonly size?: SizeEnum;
      readonly variant?: 'dark' | 'light' | 'outline' | 'light-outline';
    };
    't-checkbox': {
      readonly block?: boolean;
      readonly borderless?: boolean;
      readonly checkAll?: boolean;
      readonly checked?: boolean;
      readonly content?: string;
      readonly contentDisabled?: boolean;
      readonly defaultChecked?: boolean;
      readonly disabled?: boolean;
      readonly icon?: 'circle' | 'line' | 'rectangle' | string[];
      readonly indeterminate?: boolean;
      readonly label?: string;
      readonly maxContentRow?: number;
      readonly maxLabelRow?: number;
      readonly name?: string;
      readonly placement?: 'left' | 'right';
      readonly readonly?: boolean;
      readonly value?: string | number | boolean;
    };
    't-checkbox-group': {
      readonly borderless?: boolean;
      readonly defaultValue?: T;
      readonly disabled?: boolean;
      readonly keys?: KeysType;
      readonly max?: number;
      readonly name?: string;
      readonly options?: Array<CheckboxOption>;
      readonly readonly?: boolean;
      readonly value?: T;
    };
    't-col': {
      readonly offset?: string | number;
      readonly span?: string | number;
    };
    't-collapse': {
      readonly defaultExpandAll?: boolean;
      readonly defaultValue?: CollapseValue;
      readonly disabled?: boolean;
      readonly expandIcon?: boolean;
      readonly expandMutex?: boolean;
      readonly theme?: 'default' | 'card';
      readonly value?: CollapseValue;
    };
    't-collapse-panel': {
      readonly content?: string;
      readonly disabled?: boolean;
      readonly expandIcon?: boolean;
      readonly header?: string;
      readonly headerLeftIcon?: string;
      readonly headerRightContent?: string;
      readonly placement?: 'bottom' | 'top';
      readonly value?: string | number;
    };
    't-color-picker': {
      readonly autoClose?: boolean;
      readonly colorModes?: colorModesEnum | colorModesEnum[];
      readonly defaultValue?: string;
      readonly enableAlpha?: boolean;
      readonly enableMultipleGradient?: boolean;
      readonly fixed?: boolean;
      readonly format?: 'HEX' | 'HEX8' | 'RGB' | 'RGBA' | 'HSL' | 'HSLA' | 'HSV' | 'HSVA' | 'CMYK' | 'CSS';
      readonly popupProps?: PopupProps;
      readonly swatchColors?: Array<string> | null | undefined;
      readonly type?: TypeEnum;
      readonly usePopup?: boolean;
      readonly value?: string;
      readonly visible?: boolean;
    };
    't-count-down': {
      readonly autoStart?: boolean;
      readonly content?: string;
      readonly format?: string;
      readonly millisecond?: boolean;
      readonly size?: 'small' | 'medium' | 'large';
      readonly splitWithUnit?: boolean;
      readonly theme?: 'default' | 'round' | 'square';
      readonly time?: number;
    };
    't-date-time-picker': {
      readonly autoClose?: boolean;
      readonly cancelBtn?: string;
      readonly confirmBtn?: string;
      readonly customLocale?: string;
      readonly defaultValue?: DateValue;
      readonly end?: string | number;
      readonly filter?: (type: TimeModeValues, columns: DateTimePickerColumn) => DateTimePickerColumn;
      readonly format?: string;
      readonly formatter?: (option: DateTimePickerColumnItem, columnIndex: number) => DateTimePickerColumnItem;
      readonly header?: boolean;
      readonly mode?: DateTimePickerMode;
      readonly popupProps?: PopupProps;
      readonly showWeek?: boolean;
      readonly start?: string | number;
      readonly steps?: { [key in TimeModeValues]?: number };
      readonly title?: string;
      readonly usePopup?: boolean;
      readonly value?: DateValue;
      readonly visible?: boolean;
    };
    't-dialog': {
      readonly actions?: Array<ButtonProps>;
      readonly buttonLayout?: 'horizontal' | 'vertical';
      readonly cancelBtn?: string | ButtonProps | null;
      readonly closeBtn?: boolean | ButtonProps | null;
      readonly closeOnOverlayClick?: boolean;
      readonly confirmBtn?: string | ButtonProps | null;
      readonly content?: string;
      readonly overlayProps?: OverlayProps;
      readonly preventScrollThrough?: boolean;
      readonly showOverlay?: boolean;
      readonly title?: string;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-divider': {
      readonly align?: 'left' | 'right' | 'center';
      readonly content?: string;
      readonly dashed?: boolean;
      readonly layout?: 'horizontal' | 'vertical';
    };
    't-drawer': {
      readonly closeOnOverlayClick?: boolean;
      readonly destroyOnClose?: boolean;
      readonly items?: DrawerItem[];
      readonly overlayProps?: OverlayProps;
      readonly placement?: 'left' | 'right';
      readonly showOverlay?: boolean;
      readonly title?: string;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-dropdown-item': {
      readonly defaultValue?: DropdownValue;
      readonly disabled?: boolean;
      readonly keys?: KeysType;
      readonly label?: string;
      readonly multiple?: boolean;
      readonly options?: Array<DropdownOption>;
      readonly optionsColumns?: string | number;
      readonly placement?: 'left' | 'right';
      readonly value?: DropdownValue;
    };
    't-dropdown-menu': {
      readonly arrowIcon?: string | object;
      readonly closeOnClickOverlay?: boolean;
      readonly duration?: string | number;
      readonly showOverlay?: boolean;
      readonly zIndex?: number;
    };
    't-empty': {
      readonly description?: string;
      readonly icon?: string | object;
      readonly image?: string;
    };
    't-fab': {
      readonly buttonProps?: ButtonProps;
      readonly draggable?: boolean | FabDirectionEnum;
      readonly icon?: string;
      readonly style?: string;
      readonly text?: string;
      readonly usingCustomNavbar?: boolean;
      readonly yBounds?: Array<string | number>;
    };
    't-footer': {
      readonly links?: Array<LinkObj>;
      readonly logo?: FooterLogo;
      readonly text?: string;
    };
    't-form': Record<string, any>;
    't-form-item': Record<string, any>;
    't-grid': {
      readonly align?: 'left' | 'center';
      readonly border?: boolean | { color?: string; width?: string; style?: 'solid' | 'dashed' | 'dotted' | 'double' | 'groove' | 'inset' | 'outset'; };
      readonly column?: number;
      readonly gutter?: number;
      readonly hover?: boolean;
      readonly theme?: 'default' | 'card';
    };
    't-grid-item': {
      readonly badgeProps?: BadgeProps;
      readonly description?: string;
      readonly icon?: string | object;
      readonly image?: string;
      readonly imageProps?: ImageProps;
      readonly jumpType?: 'redirect-to' | 'switch-tab' | 'relaunch' | 'navigate-to';
      readonly layout?: 'vertical' | 'horizontal';
      readonly text?: string;
      readonly url?: string;
    };
    't-guide': {
      readonly backButtonProps?: ButtonProps;
      readonly counter?: string | ((params: { total: number; current: number; }) => string);
      readonly current?: number;
      readonly defaultCurrent?: number;
      readonly finishButtonProps?: ButtonProps;
      readonly hideBack?: boolean;
      readonly hideCounter?: boolean;
      readonly hideSkip?: boolean;
      readonly highlightPadding?: number;
      readonly mode?: 'popover' | 'dialog';
      readonly nextButtonProps?: ButtonProps;
      readonly showOverlay?: boolean;
      readonly skipButtonProps?: ButtonProps;
      readonly steps?: Array<GuideStep>;
      readonly usingCustomNavbar?: boolean;
      readonly zIndex?: number;
    };
    't-icon': {
      readonly color?: string;
      readonly name?: string;
      readonly prefix?: string;
      readonly size?: string | number;
    };
    't-image': {
      readonly error?: string;
      readonly height?: string | number;
      readonly lazy?: boolean;
      readonly loading?: string;
      readonly mode?: 'scaleToFill' | 'aspectFit' | 'aspectFill' | 'widthFix' | 'heightFix' | 'top' | 'bottom' | 'center' | 'left' | 'right' | 'top left' | 'top right' | 'bottom left' | 'bottom right';
      readonly shape?: 'circle' | 'round' | 'square';
      readonly showMenuByLongpress?: boolean;
      readonly src?: string;
      readonly tId?: string;
      readonly webp?: boolean;
      readonly width?: string | number;
    };
    't-image-viewer': {
      readonly backgroundColor?: string;
      readonly closeBtn?: string | boolean | object;
      readonly defaultVisible?: boolean;
      readonly deleteBtn?: string | boolean | object;
      readonly imageProps?: ImageProps;
      readonly images?: Array<string>;
      readonly initialIndex?: Number;
      readonly lazy?: boolean;
      readonly showIndex?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
    };
    't-indexes': {
      readonly current?: string | number;
      readonly defaultCurrent?: string | number;
      readonly indexList?: Array<string | number>;
      readonly sticky?: Boolean;
      readonly stickyOffset?: number;
    };
    't-indexes-anchor': {
      readonly index?: string | number;
    };
    't-input': {
      readonly adjustPosition?: boolean;
      readonly align?: 'left' | 'center' | 'right';
      readonly allowInputOverMax?: boolean;
      readonly alwaysEmbed?: boolean;
      readonly autoFocus?: boolean;
      readonly borderless?: boolean;
      readonly clearable?: boolean | object;
      readonly clearTrigger?: 'always' | 'focus';
      readonly confirmHold?: boolean;
      readonly confirmType?: 'send' | 'search' | 'next' | 'go' | 'done';
      readonly cursor?: number;
      readonly cursorColor?: string;
      readonly cursorSpacing?: number;
      readonly disabled?: boolean;
      readonly focus?: boolean;
      readonly format?: InputFormatType;
      readonly holdKeyboard?: boolean;
      readonly label?: string;
      readonly layout?: 'vertical' | 'horizontal';
      readonly maxcharacter?: number;
      readonly maxlength?: number;
      readonly placeholder?: string;
      readonly placeholderClass?: string;
      readonly placeholderStyle?: string;
      readonly prefixIcon?: string | object;
      readonly readonly?: boolean;
      readonly safePasswordCertPath?: string;
      readonly safePasswordCustomHash?: string;
      readonly safePasswordLength?: number;
      readonly safePasswordNonce?: string;
      readonly safePasswordSalt?: string;
      readonly safePasswordTimeStamp?: number;
      readonly selectionEnd?: number;
      readonly selectionStart?: number;
      readonly status?: 'default' | 'success' | 'warning' | 'error';
      readonly suffix?: string;
      readonly suffixIcon?: string | object;
      readonly tips?: string;
      readonly type?: 'text' | 'number' | 'idcard' | 'digit' | 'safe-password' | 'password' | 'nickname';
      readonly value?: InputValue;
    };
    't-link': {
      readonly content?: string;
      readonly disabled?: boolean;
      readonly hover?: boolean;
      readonly navigatorProps?: object;
      readonly prefixIcon?: string | object;
      readonly size?: SizeEnum;
      readonly suffixIcon?: string | object;
      readonly theme?: 'default' | 'primary' | 'danger' | 'warning' | 'success';
      readonly underline?: boolean;
    };
    't-loading': {
      readonly delay?: number;
      readonly duration?: number;
      readonly fullscreen?: boolean;
      readonly indicator?: boolean;
      readonly inheritColor?: boolean;
      readonly layout?: 'horizontal' | 'vertical';
      readonly loading?: boolean;
      readonly pause?: boolean;
      readonly progress?: number;
      readonly reverse?: boolean;
      readonly size?: string;
      readonly text?: string;
      readonly theme?: 'circular' | 'spinner' | 'dots';
    };
    't-message': {
      readonly align?: MessageAlignType;
      readonly closeBtn?: string | boolean | object;
      readonly content?: string;
      readonly defaultVisible?: boolean;
      readonly duration?: number;
      readonly gap?: string | number | boolean;
      readonly icon?: string | boolean | object;
      readonly link?: string | object;
      readonly marquee?: boolean | MessageMarquee;
      readonly offset?: Array<string | number>;
      readonly single?: boolean;
      readonly theme?: MessageThemeList;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-message-item': Record<string, any>;
    't-navbar': {
      readonly animation?: boolean;
      readonly delta?: number;
      readonly fixed?: boolean;
      readonly leftArrow?: boolean;
      readonly placeholder?: boolean;
      readonly safeAreaInsetTop?: boolean;
      readonly title?: string;
      readonly titleMaxLength?: number;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-notice-bar': {
      readonly content?: string | string[];
      readonly defaultVisible?: boolean;
      readonly direction?: 'horizontal' | 'vertical';
      readonly interval?: number;
      readonly marquee?: boolean | NoticeBarMarquee;
      readonly operation?: string;
      readonly prefixIcon?: string | boolean | object;
      readonly suffixIcon?: string | object;
      readonly theme?: 'info' | 'success' | 'warning' | 'error';
      readonly visible?: boolean;
    };
    't-overlay': {
      readonly backgroundColor?: string;
      readonly duration?: number;
      readonly preventScrollThrough?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-picker': {
      readonly autoClose?: boolean;
      readonly cancelBtn?: boolean | string;
      readonly confirmBtn?: boolean | string;
      readonly defaultValue?: Array<PickerValue>;
      readonly header?: boolean;
      readonly itemHeight?: number;
      readonly keys?: KeysType;
      readonly popupProps?: PopupProps;
      readonly title?: string;
      readonly usePopup?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly value?: Array<PickerValue>;
      readonly visible?: boolean;
      readonly visibleItemCount?: number;
    };
    't-picker-item': {
      readonly format?: (option: PickerItemOption, columnIndex: number) => PickerItemOption;
      readonly options?: PickerItemOption[];
    };
    't-popup': {
      readonly closeBtn?: boolean;
      readonly closeOnOverlayClick?: boolean;
      readonly content?: string;
      readonly defaultVisible?: boolean;
      readonly duration?: number;
      readonly overlayProps?: OverlayProps;
      readonly placement?: 'top' | 'left' | 'right' | 'bottom' | 'center';
      readonly preventScrollThrough?: boolean;
      readonly showOverlay?: boolean;
      readonly usingCustomNavbar?: boolean;
      readonly visible?: boolean;
      readonly zIndex?: number;
    };
    't-progress': {
      readonly color?: string | Array<string> | Record<string, string>;
      readonly label?: string | boolean;
      readonly percentage?: number;
      readonly size?: string | number;
      readonly status?: ProgressStatus;
      readonly strokeWidth?: string | number;
      readonly theme?: ProgressTheme;
      readonly trackColor?: string;
    };
    't-pull-down-refresh': {
      readonly defaultValue?: boolean;
      readonly disabled?: boolean;
      readonly enableBackToTop?: boolean;
      readonly enablePassive?: boolean;
      readonly loadingBarHeight?: string | number;
      readonly loadingProps?: LoadingProps;
      readonly loadingTexts?: string[];
      readonly lowerThreshold?: string | number;
      readonly maxBarHeight?: string | number;
      readonly refreshTimeout?: number;
      readonly scrollIntoView?: string;
      readonly showScrollbar?: boolean;
      readonly successDuration?: string | number;
      readonly upperThreshold?: string | number;
      readonly usingCustomNavbar?: boolean;
      readonly value?: boolean;
    };
    't-qrcode': {
      readonly bgColor?: string;
      readonly borderless?: boolean;
      readonly color?: string;
      readonly icon?: string;
      readonly iconSize?: number | { width: number; height: number; };
      readonly level?: 'L' | 'M' | 'Q' | 'H';
      readonly size?: number;
      readonly status?: QRStatus;
      readonly value?: string;
    };
    't-radio': {
      readonly allowUncheck?: boolean;
      readonly block?: boolean;
      readonly checked?: boolean;
      readonly content?: string;
      readonly contentDisabled?: boolean;
      readonly defaultChecked?: boolean;
      readonly disabled?: boolean;
      readonly icon?: 'circle' | 'line' | 'dot' | Array<string>;
      readonly label?: string;
      readonly maxContentRow?: number;
      readonly maxLabelRow?: number;
      readonly name?: string;
      readonly placement?: 'left' | 'right';
      readonly readonly?: boolean;
      readonly value?: T;
    };
    't-radio-group': {
      readonly allowUncheck?: boolean;
      readonly borderless?: boolean;
      readonly defaultValue?: T;
      readonly disabled?: boolean;
      readonly icon?: 'circle' | 'line' | 'dot' | Array<string>;
      readonly keys?: KeysType;
      readonly name?: string;
      readonly options?: Array<RadioOption>;
      readonly placement?: 'left' | 'right';
      readonly readonly?: boolean;
      readonly value?: T;
    };
    't-rate': {
      readonly allowHalf?: boolean;
      readonly color?: string | Array<string>;
      readonly count?: number;
      readonly defaultValue?: number;
      readonly disabled?: boolean;
      readonly gap?: string | number;
      readonly icon?: string | string[];
      readonly iconPrefix?: string;
      readonly placement?: 'top' | 'bottom' | '';
      readonly showText?: boolean;
      readonly size?: string;
      readonly texts?: Array<string>;
      readonly value?: number;
      readonly variant?: 'outline' | 'filled';
    };
    't-result': {
      readonly description?: string;
      readonly icon?: string | boolean | object;
      readonly image?: string;
      readonly theme?: 'default' | 'success' | 'warning' | 'error';
      readonly title?: string;
    };
    't-row': {
      readonly gutter?: string | number;
    };
    't-scroll-view': {
      readonly scrollIntoView?: string;
    };
    't-search': {
      readonly action?: string;
      readonly adjustPosition?: boolean;
      readonly alwaysEmbed?: boolean;
      readonly center?: boolean;
      readonly clearable?: boolean;
      readonly clearTrigger?: 'always' | 'focus';
      readonly confirmHold?: boolean;
      readonly confirmType?: 'send' | 'search' | 'next' | 'go' | 'done';
      readonly cursor?: number;
      readonly cursorColor?: string;
      readonly cursorSpacing?: number;
      readonly disabled?: boolean;
      readonly focus?: boolean;
      readonly holdKeyboard?: boolean;
      readonly leftIcon?: string;
      readonly maxcharacter?: number;
      readonly maxlength?: number;
      readonly placeholder?: string;
      readonly placeholderClass?: string;
      readonly placeholderStyle?: string;
      readonly readonly?: boolean;
      readonly resultList?: Array<string>;
      readonly selectionEnd?: number;
      readonly selectionStart?: number;
      readonly shape?: 'square' | 'round';
      readonly type?: 'text' | 'number' | 'idcard' | 'digit' | 'nickname';
      readonly value?: string;
    };
    't-side-bar': {
      readonly defaultValue?: string | number;
      readonly value?: string | number;
    };
    't-side-bar-item': {
      readonly badgeProps?: BadgeProps;
      readonly disabled?: boolean;
      readonly icon?: string | object;
      readonly label?: string;
      readonly value?: string | number;
    };
    't-skeleton': {
      readonly animation?: 'gradient' | 'flashed' | 'none';
      readonly delay?: number;
      readonly loading?: boolean;
      readonly rowCol?: SkeletonRowCol;
      readonly theme?: 'avatar' | 'image' | 'text' | 'paragraph';
    };
    't-slider': {
      readonly defaultValue?: SliderValue;
      readonly disabled?: boolean;
      readonly label?: string | boolean;
      readonly marks?: Record<number, string> | Array<number>;
      readonly max?: number;
      readonly min?: number;
      readonly range?: boolean;
      readonly showExtremeValue?: boolean;
      readonly step?: number;
      readonly theme?: 'default' | 'capsule';
      readonly value?: SliderValue;
      readonly vertical?: boolean;
    };
    't-step-item': {
      readonly content?: string;
      readonly extra?: string;
      readonly icon?: string;
      readonly status?: StepStatus;
      readonly title?: string;
    };
    't-stepper': {
      readonly defaultValue?: string | number;
      readonly disabled?: boolean;
      readonly disableInput?: boolean;
      readonly inputWidth?: number;
      readonly integer?: boolean;
      readonly max?: number;
      readonly min?: number;
      readonly size?: SizeEnum;
      readonly step?: number;
      readonly theme?: 'normal' | 'filled' | 'outline';
      readonly value?: string | number;
    };
    't-steps': {
      readonly current?: string | number;
      readonly currentStatus?: 'default' | 'process' | 'finish' | 'error';
      readonly defaultCurrent?: string | number;
      readonly layout?: 'horizontal' | 'vertical';
      readonly readonly?: boolean;
      readonly sequence?: 'positive' | 'reverse';
      readonly theme?: 'default' | 'dot';
    };
    't-sticky': {
      readonly container?: null;
      readonly disabled?: boolean;
      readonly offsetTop?: string | number;
      readonly zIndex?: number;
    };
    't-swipe-cell': {
      readonly disabled?: boolean;
      readonly left?: Array<SwipeActionItem>;
      readonly opened?: boolean | Array<boolean>;
      readonly right?: Array<SwipeActionItem>;
    };
    't-swiper': {
      readonly autoplay?: boolean;
      readonly current?: number;
      readonly direction?: 'horizontal' | 'vertical';
      readonly displayMultipleItems?: number;
      readonly duration?: number;
      readonly easingFunction?: 'default' | 'linear' | 'easeInCubic' | 'easeOutCubic' | 'easeInOutCubic';
      readonly height?: string | number;
      readonly imageProps?: object;
      readonly interval?: number;
      readonly list?: string[] | SwiperList[];
      readonly loop?: boolean;
      readonly navigation?: SwiperNavProps | boolean;
      readonly nextMargin?: string | number;
      readonly paginationPosition?: 'top-left' | 'top' | 'top-right' | 'bottom-left' | 'bottom' | 'bottom-right';
      readonly previousMargin?: string | number;
      readonly snapToEdge?: boolean;
    };
    't-swiper-nav': {
      readonly current?: number;
      readonly direction?: 'horizontal' | 'vertical';
      readonly minShowNum?: number;
      readonly paginationPosition?: 'top-left' | 'top' | 'top-right' | 'bottom-left' | 'bottom' | 'bottom-right';
      readonly showControls?: boolean;
      readonly total?: number;
      readonly type?: SwiperNavigationType;
    };
    't-switch': {
      readonly customValue?: Array<SwitchValue>;
      readonly defaultValue?: SwitchValue;
      readonly disabled?: boolean;
      readonly icon?: string[];
      readonly label?: string[];
      readonly loading?: boolean;
      readonly size?: 'small' | 'medium' | 'large';
      readonly value?: SwitchValue;
    };
    't-tab-bar': {
      readonly bordered?: boolean;
      readonly defaultValue?: string | number | Array<string | number>;
      readonly fixed?: boolean;
      readonly placeholder?: boolean;
      readonly safeAreaInsetBottom?: boolean;
      readonly shape?: 'normal' | 'round';
      readonly split?: boolean;
      readonly theme?: 'normal' | 'tag';
      readonly value?: string | number | Array<string | number>;
      readonly zIndex?: number;
    };
    't-tab-bar-item': {
      readonly badgeProps?: BadgeProps;
      readonly icon?: string | object;
      readonly subTabBar?: SubTabBarItem[];
      readonly value?: string | number;
    };
    't-tab-panel': {
      readonly badgeProps?: object;
      readonly disabled?: boolean;
      readonly icon?: string | object;
      readonly label?: string;
      readonly lazy?: boolean;
      readonly panel?: string;
      readonly value?: TabValue;
    };
    't-tabs': {
      readonly animation?: TabAnimation;
      readonly bottomLineMode?: 'fixed' | 'auto' | 'full';
      readonly defaultValue?: TabValue;
      readonly showBottomLine?: boolean;
      readonly spaceEvenly?: boolean;
      readonly split?: boolean;
      readonly sticky?: boolean;
      readonly stickyProps?: StickyProps;
      readonly swipeable?: boolean;
      readonly theme?: 'line' | 'tag' | 'card';
      readonly value?: TabValue;
    };
    't-tag': {
      readonly closable?: boolean | object;
      readonly disabled?: boolean;
      readonly icon?: string | object;
      readonly maxWidth?: string | number;
      readonly shape?: 'square' | 'round' | 'mark';
      readonly size?: 'small' | 'medium' | 'large' | 'extra-large';
      readonly theme?: 'default' | 'primary' | 'warning' | 'danger' | 'success';
      readonly variant?: 'dark' | 'light' | 'outline' | 'light-outline';
    };
    't-textarea': {
      readonly adjustPosition?: boolean;
      readonly allowInputOverMax?: boolean;
      readonly autofocus?: boolean;
      readonly autosize?: boolean | { maxHeight?: number; minHeight?: number; };
      readonly bordered?: boolean;
      readonly confirmHold?: boolean;
      readonly confirmType?: 'return' | 'send' | 'search' | 'next' | 'go' | 'done';
      readonly cursor?: number;
      readonly cursorColor?: string;
      readonly cursorSpacing?: number;
      readonly defaultValue?: TextareaValue;
      readonly disabled?: boolean;
      readonly disableDefaultPadding?: boolean;
      readonly fixed?: boolean;
      readonly focus?: boolean;
      readonly holdKeyboard?: boolean;
      readonly indicator?: boolean;
      readonly label?: string;
      readonly maxcharacter?: number;
      readonly maxlength?: number;
      readonly placeholder?: string;
      readonly placeholderClass?: string;
      readonly placeholderStyle?: string;
      readonly readonly?: boolean;
      readonly selectionEnd?: number;
      readonly selectionStart?: number;
      readonly showConfirmBar?: boolean;
      readonly value?: TextareaValue;
    };
    't-toast': {
      readonly direction?: 'row' | 'column';
      readonly duration?: number;
      readonly icon?: string | object;
      readonly message?: string;
      readonly overlayProps?: OverlayProps;
      readonly placement?: 'top' | 'middle' | 'bottom';
      readonly preventScrollThrough?: boolean;
      readonly showOverlay?: boolean;
      readonly theme?: 'loading' | 'success' | 'warning' | 'error';
      readonly usingCustomNavbar?: boolean;
    };
    't-transition': {
      readonly appear?: boolean;
      readonly destoryOnHide?: boolean;
      readonly durations?: number | number[];
      readonly name?: string;
      readonly visible?: boolean;
    };
    't-tree-select': {
      readonly customValue?: TreeSelectValue;
      readonly defaultValue?: TreeSelectValue;
      readonly height?: string | number;
      readonly keys?: TreeKeysType;
      readonly multiple?: boolean;
      readonly options?: Array<DataOption>;
      readonly value?: TreeSelectValue;
    };
    't-upload': {
      readonly addBtn?: boolean;
      readonly addContent?: string;
      readonly allowUploadDuplicateFile?: boolean;
      readonly config?: UploadMpConfig;
      readonly defaultFiles?: Array<UploadFile>;
      readonly disabled?: boolean;
      readonly draggable?: boolean | { vibrate?: boolean; collisionVibrate?: boolean; };
      readonly files?: Array<UploadFile>;
      readonly gridConfig?: { column?: number; width?: number; height?: number; };
      readonly gutter?: number;
      readonly imageProps?: ImageProps;
      readonly max?: number;
      readonly mediaType?: Array<MediaType>;
      readonly preview?: boolean;
      readonly removeBtn?: boolean;
      readonly requestMethod?: null;
      readonly sizeLimit?: number | SizeLimitObj;
      readonly source?: 'media' | 'messageFile';
      readonly transition?: Transition;
    };
    't-watermark': {
      readonly alpha?: number;
      readonly content?: string;
      readonly height?: number;
      readonly isRepeat?: boolean;
      readonly layout?: 'rectangular' | 'hexagonal';
      readonly lineSpace?: number;
      readonly movable?: boolean;
      readonly moveInterval?: number;
      readonly offset?: Array<number>;
      readonly removable?: boolean;
      readonly rotate?: number;
      readonly watermarkContent?: WatermarkText | WatermarkImage | Array<WatermarkText | WatermarkImage>;
      readonly width?: number;
      readonly x?: number;
      readonly y?: number;
      readonly zIndex?: number;
    };
  }
  export type ComponentPropName = keyof ComponentProps;
  export type ComponentProp<Name extends string> = Name extends ComponentPropName ? ComponentProps[Name] : Record<string, any>;
  export const componentProps: ComponentProps;
}
