export const APP_PRELUDE_CHUNK_MARKER = '__wvAPR__'
export const APP_PRELUDE_GUARD_KEY = '__ai'
export const APP_PRELUDE_REQUIRE_MARKER = '__wvAPQ__'

export const REQUEST_GLOBAL_PRELUDE_MARKER = '__wvRGP__'
export const REQUEST_GLOBAL_PRELUDE_GUARD_KEY = '__ri'
export const REQUEST_GLOBAL_PASSIVE_BINDINGS_MARKER = '__wvRGL__'
export const REQUEST_GLOBAL_LOCAL_BINDINGS_MARKER = '__wvRGC__'
export const REQUEST_GLOBAL_BUNDLE_MARKER = '__wvRGB__'
export const REQUEST_GLOBAL_ACTUALS_KEY = '__ra'
export const REQUEST_GLOBAL_PLACEHOLDER_KEY = '__rp'

export const REQUEST_GLOBAL_MARK_PLACEHOLDER_HELPER = '__rM'
export const REQUEST_GLOBAL_LAZY_FUNCTION_HELPER = '__rF'
export const REQUEST_GLOBAL_LAZY_CONSTRUCTOR_HELPER = '__rC'
export const REQUEST_GLOBAL_USABLE_CONSTRUCTOR_HELPER = '__rU'
export const REQUEST_GLOBAL_EXPOSE_HELPER = '__rE'

export const REQUEST_GLOBAL_INSTALLER_HOST_REF = '__rh'
export const REQUEST_GLOBAL_CHUNK_MODULE_REF = '__rm'
export const REQUEST_GLOBAL_CHUNK_HOST_REF = '__rc'
export const REQUEST_GLOBAL_BUNDLE_HOST_REF = '__rb'

export const WEVU_PAGE_LAYOUT_SETTER_KEY = '__wevuSetPageLayout'
export const WEVU_PAGE_LAYOUT_NONE = '__wv_no_layout'
export const WEVU_PAGE_LAYOUT_NAME_KEY = '__wv_page_layout_name'
export const WEVU_PAGE_LAYOUT_PROPS_KEY = '__wv_page_layout_props'

export const WEVU_INLINE_HANDLER = '__weapp_vite_inline'
export const WEVU_MODEL_HANDLER = '__weapp_vite_model'
export const WEVU_OWNER_HANDLER = '__weapp_vite_owner'
export const WEVU_RESERVED_METHOD_PREFIX = '__weapp_vite_'
export const WEVU_INLINE_MAP_KEY = '__weapp_vite_inline_map'
export const WEVU_SCOPED_SLOT_CREATOR_KEY = '__weapp_vite_createScopedSlotComponent'

export const WEVU_SLOT_OWNER_ID_KEY = '__wvOwnerId'
export const WEVU_SLOT_OWNER_ID_PROP = '__wvSlotOwnerId'
export const WEVU_SLOT_PROPS_KEY = '__wvSlotProps'
export const WEVU_SLOT_SCOPE_KEY = '__wvSlotScope'
export const WEVU_SLOT_OWNER_KEY = '__wvOwner'
export const WEVU_SLOT_PROPS_DATA_KEY = '__wvSlotPropsData'

export const WEVU_SLOT_OWNER_ATTR = '__wv-owner-id'
export const WEVU_SLOT_OWNER_ID_ATTR = '__wv-slot-owner-id'
export const WEVU_SLOT_PROPS_ATTR = '__wv-slot-props'
export const WEVU_SLOT_SCOPE_ATTR = '__wv-slot-scope'

export const WEVU_CLASS_STYLE_RUNTIME_MODULE = '__weapp_vite'
export const WEVU_CLASS_STYLE_RUNTIME_FILE = '__weapp_vite_class_style'
export const WEVU_LAYOUT_HOST_ID_PREFIX = '__wv-layout-host-'
export const WEVU_LAYOUT_HOST_REF_PREFIX = '__wevu_layout_host_'
export const WEVU_LAYOUT_BIND_PREFIX = '__wv_layout_bind_'
export const WEVU_EXPRESSION_ERROR_IDENTIFIER = '__wv_expr_err'
export const WEVU_PAGE_LAYOUT_NEXT_NAME_IDENTIFIER = '__wv_next_layout_name'
export const WEVU_PAGE_LAYOUT_NEXT_PROPS_IDENTIFIER = '__wv_next_layout_props'
export const WEVU_PAGE_LAYOUT_CURRENT_NAME_IDENTIFIER = '__wv_current_layout_name'
export const WEVU_PAGE_LAYOUT_CURRENT_PROPS_IDENTIFIER = '__wv_current_layout_props'
export const WEVU_INTERNAL_KEY_IDENTIFIER = '__wv_key'

export const WEVU_PROPS_KEY = '__wevuProps'
export const WEVU_ATTRS_KEY = '__wevuAttrs'
export const WEVU_NATIVE_INSTANCE_KEY = '__wevuNativeInstance'
export const WEVU_RUNTIME_KEY = '__wevuRuntime'
export const WEVU_TEMPLATE_REFS_KEY = '__wevuTemplateRefs'
export const WEVU_LAYOUT_HOSTS_KEY = '__wevuLayoutHosts'
export const WEVU_IS_PAGE_KEY = '__wevu_isPage'
export const WEVU_SETUP_CONTEXT_INSTANCE_KEY = '__wevuSetupContextInstance'
export const WEVU_PROP_KEYS_KEY = '__wevuPropKeys'
export const WEVU_READY_CALLED_KEY = '__wevuReadyCalled'
export const WEVU_TEMPLATE_REFS_CALLBACKS_KEY = '__wevuTemplateRefsCallbacks'
export const WEVU_TEMPLATE_REFS_PENDING_KEY = '__wevuTemplateRefsPending'
export const WEVU_PENDING_PROP_VALUES_KEY = '__wevuPendingPropValues'
export const WEVU_ON_LOAD_CALLED_KEY = '__wevuOnLoadCalled'
export const WEVU_ROUTE_DONE_CALLED_KEY = '__wevuRouteDoneCalled'
export const WEVU_ROUTE_DONE_IN_TICK_KEY = '__wevuRouteDoneInTick'
export const WEVU_PAGE_SCROLL_HOOK_DEPTH_KEY = '__wevuPageScrollHookDepth'
export const WEVU_ON_BEFORE_UPDATE_HOOK = '__wevuOnBeforeUpdate'
export const WEVU_ON_UPDATED_HOOK = '__wevuOnUpdated'
export const WEVU_HOOKS_KEY = '__wevuHooks'
export const WEVU_EXPOSED_KEY = '__wevuExposed'
export const WEVU_PUBLIC_RUNTIME_KEY = '$wevu'
export const WEVU_RUNTIME_APP_KEY = '__wevuRuntimeApp'
export const WEVU_IS_APP_INSTANCE_KEY = '__wevuIsAppInstance'
export const WEVU_WATCH_STOPS_KEY = '__wevuWatchStops'
export const WEVU_EFFECT_SCOPE_KEY = '__wevuEffectScope'
export const WEVU_TEMPLATE_REF_MAP_KEY = '__wevuTemplateRefMap'
export const WEVU_LAYOUT_HOST_BRIDGE_KEY = '__wevuLayoutHostBridge'
export const WEVU_LAYOUT_BRIDGE_PAGE_KEYS = '__wevuLayoutBridgePageKeys'

export const WEAPP_VITE_INJECTED_API_IDENTIFIER = '__weappViteInjectedApi__'
export const WEAPP_VITE_WEB_AUTHORIZE_DECISION_KEY = '__weappViteWebAuthorizeDecision'
export const WEAPP_VITE_WEB_OPEN_SETTING_AUTH_KEY = '__weappViteWebOpenSettingAuth'
export const WEAPP_VITE_WEB_OPEN_APP_AUTHORIZE_SETTING_KEY = '__weappViteWebOpenAppAuthorizeSetting'
export const WEAPP_VITE_WEB_USER_INFO_KEY = '__weappViteWebUserInfo'
export const WEAPP_VITE_WEB_USER_PROFILE_KEY = '__weappViteWebUserProfile'
export const WEAPP_VITE_WEB_CHECK_SESSION_KEY = '__weappViteWebCheckSession'
export const WEAPP_VITE_WEB_GET_USER_PROFILE_DECISION_KEY = '__weappViteWebGetUserProfileDecision'
