import type { WeapiCrossPlatformMethodDocsSaveVideoToPhotosAlbumToCanAddSecureElementPassAddFileToFavoritesToCanAddSecureElementPass } from './addFileToFavoritesToCanAddSecureElementPass'
import type { WeapiCrossPlatformMethodDocsSaveVideoToPhotosAlbumToCanAddSecureElementPassSaveVideoToPhotosAlbumToAddCard } from './saveVideoToPhotosAlbumToAddCard'

export type WeapiCrossPlatformMethodDocsSaveVideoToPhotosAlbumToCanAddSecureElementPass
  = WeapiCrossPlatformMethodDocsSaveVideoToPhotosAlbumToCanAddSecureElementPassSaveVideoToPhotosAlbumToAddCard
    & WeapiCrossPlatformMethodDocsSaveVideoToPhotosAlbumToCanAddSecureElementPassAddFileToFavoritesToCanAddSecureElementPass
