import type { WeapiCrossPlatformMethodDocsShareImageToGroupToSelectGroupMembersShareImageToGroupToStartLocationUpdateBackground } from './shareImageToGroupToStartLocationUpdateBackground'
import type { WeapiCrossPlatformMethodDocsShareImageToGroupToSelectGroupMembersStartRecordToSelectGroupMembers } from './startRecordToSelectGroupMembers'

export type WeapiCrossPlatformMethodDocsShareImageToGroupToSelectGroupMembers
  = WeapiCrossPlatformMethodDocsShareImageToGroupToSelectGroupMembersShareImageToGroupToStartLocationUpdateBackground
    & WeapiCrossPlatformMethodDocsShareImageToGroupToSelectGroupMembersStartRecordToSelectGroupMembers
