import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const REPO_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const WEVU_ENTRY_PATH = path.join(REPO_ROOT, 'packages-runtime/wevu/src/index.ts')
const OUTPUT_PATH = path.join(REPO_ROOT, 'e2e/generated/wevu-root-hmr-exports.ts')

function hasDeclareModifier(declaration: ts.Declaration) {
  if (declaration.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.DeclareKeyword)) {
    return true
  }

  if (ts.isVariableDeclaration(declaration)) {
    const variableStatement = declaration.parent.parent
    return ts.isVariableStatement(variableStatement)
      && Boolean(variableStatement.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.DeclareKeyword))
  }

  return false
}

function hasRuntimeValueDeclaration(symbol: ts.Symbol) {
  const declarations = symbol.getDeclarations() ?? []

  return declarations.some((declaration) => {
    if (hasDeclareModifier(declaration)) {
      return false
    }

    if (ts.isVariableDeclaration(declaration)
      || ts.isFunctionDeclaration(declaration)
      || ts.isClassDeclaration(declaration)
      || ts.isEnumDeclaration(declaration)) {
      return true
    }

    if (ts.isModuleDeclaration(declaration)) {
      return !declaration.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.DeclareKeyword)
    }

    return false
  })
}

function isValueExport(symbol: ts.Symbol, checker: ts.TypeChecker) {
  let target = symbol
  if (symbol.flags & ts.SymbolFlags.Alias) {
    target = checker.getAliasedSymbol(symbol)
  }

  return Boolean(target.flags & ts.SymbolFlags.Value) && hasRuntimeValueDeclaration(target)
}

export function collectWevuRootValueExports(entryPath = WEVU_ENTRY_PATH) {
  const program = ts.createProgram([entryPath], {
    allowJs: false,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    noEmit: true,
    skipLibCheck: true,
    strict: false,
    target: ts.ScriptTarget.ES2022,
    types: [],
  })
  const checker = program.getTypeChecker()
  const sourceFile = program.getSourceFile(entryPath)
  if (!sourceFile) {
    throw new Error(`Failed to load wevu root entry: ${entryPath}`)
  }

  const moduleSymbol = checker.getSymbolAtLocation(sourceFile)
  if (!moduleSymbol) {
    throw new Error(`Failed to resolve wevu root module symbol: ${entryPath}`)
  }

  return checker
    .getExportsOfModule(moduleSymbol)
    .filter(symbol => isValueExport(symbol, checker))
    .map(symbol => symbol.getName())
    .sort((left, right) => left.localeCompare(right))
}

export function quoteSingleStringLiteral(value: string) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll('\'', '\\\'')}'`
}

export function renderWevuRootHmrExports(exportNames: string[]) {
  return [
    '// Auto-generated by scripts/generate-wevu-root-hmr-exports.ts. Do not edit.',
    '// This manifest locks root `wevu` value exports covered by HMR runtime-import regression tests.',
    '',
    'export const WEVU_ROOT_HMR_EXPORTS = Object.freeze([',
    ...exportNames.map(exportName => `  ${quoteSingleStringLiteral(exportName)},`),
    '])',
    '',
  ].join('\n')
}

export function syncWevuRootHmrExports(options: { check?: boolean } = {}) {
  const next = renderWevuRootHmrExports(collectWevuRootValueExports())
  const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : ''

  if (current === next) {
    return false
  }

  if (options.check) {
    throw new Error(
      `Generated wevu root HMR export manifest is stale. Run: pnpm run sync:wevu-root-hmr-exports`,
    )
  }

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
  fs.writeFileSync(OUTPUT_PATH, next)
  return true
}

function isMainModule() {
  return process.argv[1] ? path.resolve(process.argv[1]) === fileURLToPath(import.meta.url) : false
}

if (isMainModule()) {
  syncWevuRootHmrExports({ check: process.argv.includes('--check') })
}
