import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { inspect } from 'node:util'
import { parse } from 'yaml'
import { syncRolldownCatalogReferences } from './print-rolldown-versions.mjs'

const ROOT_DIR = path.dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const WORKSPACE_PATH = path.resolve(ROOT_DIR, 'pnpm-workspace.yaml')
const GENERATED_CATALOG_PATH = path.resolve(ROOT_DIR, 'packages/create-weapp-vite/src/generated/catalog.ts')
const CHUNK_MODE_FAKE_PKG_FILES = [
  {
    filePath: path.resolve(ROOT_DIR, 'e2e-apps/chunk-modes/node_modules/fake-pkg/package.json'),
    content: `${JSON.stringify({
      name: 'fake-pkg',
      version: '0.0.0',
      type: 'module',
      main: 'index.js',
    }, null, 2)}\n`,
  },
  {
    filePath: path.resolve(ROOT_DIR, 'e2e-apps/chunk-modes/node_modules/fake-pkg/index.js'),
    content: `export const vendorMarker = '__VENDOR_MARKER__'\n`,
  },
  {
    filePath: path.resolve(ROOT_DIR, 'test/fixture-projects/weapp-vite/shared-chunk-modes/node_modules/fake-pkg/package.json'),
    content: `${JSON.stringify({
      name: 'fake-pkg',
      version: '0.0.0',
      type: 'module',
      main: 'index.js',
    }, null, 2)}\n`,
  },
  {
    filePath: path.resolve(ROOT_DIR, 'test/fixture-projects/weapp-vite/shared-chunk-modes/node_modules/fake-pkg/index.js'),
    content: `export const vendorMarker = '__VENDOR_MARKER__'\n`,
  },
]

function normalizeCatalog(catalog = {}) {
  const normalized = {}
  const sortedEntries = Object.entries(catalog).sort(([a], [b]) => a.localeCompare(b))

  for (const [name, version] of sortedEntries) {
    if (typeof version === 'string') {
      normalized[name] = version
    }
  }

  return normalized
}

function normalizeNamedCatalogs(catalogs = {}) {
  const normalized = {}
  const sortedCatalogNames = Object.keys(catalogs).sort((a, b) => a.localeCompare(b))

  for (const catalogName of sortedCatalogNames) {
    normalized[catalogName] = normalizeCatalog(catalogs[catalogName])
  }

  return normalized
}

function renderGeneratedCatalogFile(catalog, namedCatalogs) {
  const catalogLiteral = inspect(catalog, {
    depth: null,
    compact: false,
    sorted: true,
  })
  const namedCatalogLiteral = inspect(namedCatalogs, {
    depth: null,
    compact: false,
    sorted: true,
  })

  return `/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// Auto-generated by scripts/generate-template-catalog.ts. Do not edit.
export const TEMPLATE_CATALOG = ${catalogLiteral} as const

export const TEMPLATE_NAMED_CATALOG = ${namedCatalogLiteral} as const
`
}

async function syncTemplateCatalog() {
  const workspaceContent = await fs.readFile(WORKSPACE_PATH, 'utf8')
  const workspace = parse(workspaceContent) ?? {}
  const generated = renderGeneratedCatalogFile(
    normalizeCatalog(workspace.catalog),
    normalizeNamedCatalogs(workspace.catalogs),
  )
  const current = await fs.readFile(GENERATED_CATALOG_PATH, 'utf8').catch(() => '')

  if (current === generated) {
    return false
  }

  await fs.writeFile(GENERATED_CATALOG_PATH, generated, 'utf8')
  return true
}

async function fileChanged(filePath, runner) {
  const before = await fs.readFile(filePath, 'utf8').catch(() => '')
  await runner()
  const after = await fs.readFile(filePath, 'utf8').catch(() => '')
  return before !== after
}

async function ensureChunkModeFakePkg() {
  const changedFiles = []

  for (const entry of CHUNK_MODE_FAKE_PKG_FILES) {
    const current = await fs.readFile(entry.filePath, 'utf8').catch(() => '')
    if (current === entry.content) {
      continue
    }

    await fs.mkdir(path.dirname(entry.filePath), { recursive: true })
    await fs.writeFile(entry.filePath, entry.content, 'utf8')
    changedFiles.push(entry.filePath)
  }

  return changedFiles
}

async function main() {
  const changedFiles = []

  const catalogChanged = await fileChanged(GENERATED_CATALOG_PATH, async () => {
    await syncTemplateCatalog()
  })
  if (catalogChanged) {
    changedFiles.push(GENERATED_CATALOG_PATH)
  }

  changedFiles.push(...syncRolldownCatalogReferences(ROOT_DIR))
  changedFiles.push(...await ensureChunkModeFakePkg())

  if (changedFiles.length === 0) {
    return
  }

  console.log([
    '[workspace] synced postinstall artifacts',
    ...changedFiles.map(filePath => `- ${path.relative(ROOT_DIR, filePath)}`),
  ].join('\n'))
}

await main()
