import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { inspect } from 'node:util'
import { parse } from 'yaml'
import { syncRolldownCatalogReferences } from './print-rolldown-versions.mjs'

const ROOT_DIR = path.dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const MODES = new Set(['check', 'sync'])
const CHUNK_MODE_FAKE_PKG_FILES = [
  {
    filePath: path.resolve(ROOT_DIR, 'e2e-apps/chunk-modes/node_modules/fake-pkg/package.json'),
    content: `${JSON.stringify({
      name: 'fake-pkg',
      version: '0.0.0',
      type: 'module',
      main: 'index.js',
    }, null, 2)}\n`,
  },
  {
    filePath: path.resolve(ROOT_DIR, 'e2e-apps/chunk-modes/node_modules/fake-pkg/index.js'),
    content: `export const vendorMarker = '__VENDOR_MARKER__'\n`,
  },
  {
    filePath: path.resolve(ROOT_DIR, 'test/fixture-projects/weapp-vite/shared-chunk-modes/node_modules/fake-pkg/package.json'),
    content: `${JSON.stringify({
      name: 'fake-pkg',
      version: '0.0.0',
      type: 'module',
      main: 'index.js',
    }, null, 2)}\n`,
  },
  {
    filePath: path.resolve(ROOT_DIR, 'test/fixture-projects/weapp-vite/shared-chunk-modes/node_modules/fake-pkg/index.js'),
    content: `export const vendorMarker = '__VENDOR_MARKER__'\n`,
  },
]

function normalizeCatalog(catalog = {}) {
  const normalized = {}
  const sortedEntries = Object.entries(catalog).sort(([a], [b]) => a.localeCompare(b))

  for (const [name, version] of sortedEntries) {
    if (typeof version === 'string') {
      normalized[name] = version
    }
  }

  return normalized
}

function normalizeNamedCatalogs(catalogs = {}) {
  const normalized = {}
  const sortedCatalogNames = Object.keys(catalogs).sort((a, b) => a.localeCompare(b))

  for (const catalogName of sortedCatalogNames) {
    normalized[catalogName] = normalizeCatalog(catalogs[catalogName])
  }

  return normalized
}

export function renderGeneratedCatalogFile(catalog, namedCatalogs) {
  const catalogLiteral = inspect(catalog, {
    depth: null,
    compact: false,
    sorted: true,
  })
  const namedCatalogLiteral = inspect(namedCatalogs, {
    depth: null,
    compact: false,
    sorted: true,
  })

  return `/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// Auto-generated by scripts/generate-template-catalog.ts. Do not edit.
export const TEMPLATE_CATALOG = ${catalogLiteral} as const

export const TEMPLATE_NAMED_CATALOG = ${namedCatalogLiteral} as const
`
}

async function syncTemplateCatalog(rootDir = ROOT_DIR) {
  const workspacePath = path.resolve(rootDir, 'pnpm-workspace.yaml')
  const generatedCatalogPath = path.resolve(rootDir, 'packages/create-weapp-vite/src/generated/catalog.ts')
  const workspaceContent = await fs.readFile(workspacePath, 'utf8')
  const workspace = parse(workspaceContent) ?? {}
  const generated = renderGeneratedCatalogFile(
    normalizeCatalog(workspace.catalog),
    normalizeNamedCatalogs(workspace.catalogs),
  )
  const current = await fs.readFile(generatedCatalogPath, 'utf8').catch(() => '')

  if (current === generated) {
    return false
  }

  await fs.writeFile(generatedCatalogPath, generated, 'utf8')
  return true
}

async function hasTemplateCatalogDrift(rootDir = ROOT_DIR) {
  const workspacePath = path.resolve(rootDir, 'pnpm-workspace.yaml')
  const generatedCatalogPath = path.resolve(rootDir, 'packages/create-weapp-vite/src/generated/catalog.ts')
  const workspaceContent = await fs.readFile(workspacePath, 'utf8')
  const workspace = parse(workspaceContent) ?? {}
  const expected = renderGeneratedCatalogFile(
    normalizeCatalog(workspace.catalog),
    normalizeNamedCatalogs(workspace.catalogs),
  )
  const current = await fs.readFile(generatedCatalogPath, 'utf8').catch(() => '')
  return current !== expected
}

async function fileChanged(filePath, runner) {
  const before = await fs.readFile(filePath, 'utf8').catch(() => '')
  await runner()
  const after = await fs.readFile(filePath, 'utf8').catch(() => '')
  return before !== after
}

async function ensureChunkModeFakePkg(rootDir = ROOT_DIR) {
  const changedFiles = []

  for (const entry of CHUNK_MODE_FAKE_PKG_FILES.map(entry => ({
    ...entry,
    filePath: path.relative(ROOT_DIR, entry.filePath),
  })).map(entry => ({
    ...entry,
    filePath: path.resolve(rootDir, entry.filePath),
  }))) {
    const current = await fs.readFile(entry.filePath, 'utf8').catch(() => '')
    if (current === entry.content) {
      continue
    }

    await fs.mkdir(path.dirname(entry.filePath), { recursive: true })
    await fs.writeFile(entry.filePath, entry.content, 'utf8')
    changedFiles.push(entry.filePath)
  }

  return changedFiles
}

async function ensureRootWeappViteLink(rootDir = ROOT_DIR) {
  const rootLinkPath = path.resolve(rootDir, 'node_modules/weapp-vite')
  const targetPath = path.resolve(rootDir, 'packages/weapp-vite')
  const expectedRelativeTarget = path.relative(
    path.dirname(rootLinkPath),
    targetPath,
  )
  const currentTarget = await fs.readlink(rootLinkPath).catch(() => null)
  const resolvedTarget = currentTarget
    ? path.resolve(path.dirname(rootLinkPath), currentTarget)
    : null

  if (resolvedTarget === targetPath) {
    return false
  }

  const currentStat = await fs.lstat(rootLinkPath).catch(() => null)
  if (currentStat) {
    await fs.rm(rootLinkPath, { force: true, recursive: true })
  }

  await fs.mkdir(path.dirname(rootLinkPath), { recursive: true })
  await fs.symlink(expectedRelativeTarget, rootLinkPath, 'junction')
  return true
}

function resolveMode(argv = process.argv.slice(2)) {
  const mode = argv.find(arg => MODES.has(arg)) ?? 'check'
  return mode
}

async function collectRolldownDrift(rootDir = ROOT_DIR) {
  return syncRolldownCatalogReferences(rootDir, {
    writePackageJsonImpl() {},
  })
}

function formatChangedFiles(prefix, rootDir, files) {
  if (files.length === 0) {
    return ''
  }
  return [
    prefix,
    ...files.map(filePath => `- ${path.relative(rootDir, filePath)}`),
  ].join('\n')
}

export async function runPostinstall({ rootDir = ROOT_DIR, mode = 'check' } = {}) {
  if (!MODES.has(mode)) {
    throw new Error(`Unknown postinstall sync mode: ${mode}`)
  }

  const changedFiles = []

  if (mode === 'sync') {
    const generatedCatalogPath = path.resolve(rootDir, 'packages/create-weapp-vite/src/generated/catalog.ts')
    const catalogChanged = await fileChanged(generatedCatalogPath, async () => {
      await syncTemplateCatalog(rootDir)
    })
    if (catalogChanged) {
      changedFiles.push(generatedCatalogPath)
    }
    changedFiles.push(...syncRolldownCatalogReferences(rootDir))
  }
  else {
    if (await hasTemplateCatalogDrift(rootDir)) {
      changedFiles.push(path.resolve(rootDir, 'packages/create-weapp-vite/src/generated/catalog.ts'))
    }
    changedFiles.push(...await collectRolldownDrift(rootDir))
  }

  const ignoredFiles = []
  ignoredFiles.push(...await ensureChunkModeFakePkg(rootDir))

  if (await ensureRootWeappViteLink(rootDir)) {
    ignoredFiles.push(path.resolve(rootDir, 'node_modules/weapp-vite'))
  }

  if (mode === 'check' && changedFiles.length > 0) {
    console.warn(formatChangedFiles(
      '[workspace] install completed; tracked workspace artifacts need synchronization. Run `pnpm deps:up` or `pnpm run catalog:sync:workspace`.',
      rootDir,
      changedFiles,
    ))
  }
  else if (mode === 'sync' && changedFiles.length > 0) {
    console.log(formatChangedFiles('[workspace] synced tracked workspace artifacts', rootDir, changedFiles))
  }
  if (ignoredFiles.length > 0) {
    console.log(formatChangedFiles('[workspace] synced ignored install artifacts', rootDir, ignoredFiles))
  }

  return { changedFiles, ignoredFiles }
}

if (process.argv[1] && path.resolve(fileURLToPath(import.meta.url)) === path.resolve(process.argv[1])) {
  await runPostinstall({ mode: resolveMode() })
}
