import type { JSONSchema4 } from 'json-schema'
import fs from 'fs-extra'
import { compile } from 'json-schema-to-typescript'
import path from 'pathe'
import { JSON_SCHEMA_DEFINITIONS } from './json'

const websiteHostPath = path.resolve(import.meta.dirname, '../../../website/public')
const packageSchemaPath = path.resolve(import.meta.dirname, '../schemas')
const typeOutputPath = path.resolve(import.meta.dirname, '../src/type.auto.ts')

const BANNER_COMMENT = `/* eslint-disable */\n/**\n * This file was automatically generated by json-schema-to-typescript.\n * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n * and run json-schema-to-typescript to regenerate this file.\n */`

interface SchemaDefinition {
  filename: string
  typeName: string
  schema: JSONSchema4
}

function sortJsonKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortJsonKeysDeep)
  }

  if (value === null || typeof value !== 'object') {
    return value
  }

  const record = value as Record<string, unknown>
  const sortedKeys = Object.keys(record).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
  const result: Record<string, unknown> = {}

  for (const key of sortedKeys) {
    result[key] = sortJsonKeysDeep(record[key])
  }

  return result
}

function stableJsonStringify(value: unknown, spaces = 2) {
  return `${JSON.stringify(sortJsonKeysDeep(value), null, spaces)}\n`
}

function getSchemaDefinitions(): SchemaDefinition[] {
  return JSON_SCHEMA_DEFINITIONS.map(definition => ({
    filename: definition.filename,
    typeName: definition.typeName,
    schema: definition.schema as JSONSchema4,
  }))
}

async function writeSchemaJson(definition: SchemaDefinition) {
  const outputPaths = [
    path.resolve(websiteHostPath, definition.filename),
    path.resolve(packageSchemaPath, definition.filename),
  ]
  const json = stableJsonStringify(definition.schema, 2)
  await Promise.all(outputPaths.map(filepath => fs.outputFile(filepath, json, 'utf8')))
  return outputPaths[0]
}

function stripSchemaProperty(code: string) {
  return code
    .split('\n')
    .filter(line => !line.includes('$schema?: string;'))
    .join('\n')
}

async function generateTypeDeclaration(definition: SchemaDefinition) {
  const schema = sortJsonKeysDeep(definition.schema) as JSONSchema4
  const source = await compile(schema, definition.typeName, {
    bannerComment: BANNER_COMMENT,
    style: {
      singleQuote: false,
    },
  })
  return stripSchemaProperty(source.trim())
}

export async function buildSchemas() {
  const definitions = getSchemaDefinitions()

  await Promise.all(definitions.map(writeSchemaJson))

  const typeBlocks = await Promise.all(definitions.map(generateTypeDeclaration))
  const fileContents = `${typeBlocks.join('\n\n')}\n`

  await fs.writeFile(typeOutputPath, fileContents, 'utf8')
}
