import { execa } from 'execa'
import fs from 'fs-extra'
import path from 'pathe'
import { describe, expect, it } from 'vitest'

const CLI_PATH = path.resolve(import.meta.dirname, '../../packages/weapp-vite/bin/weapp-vite.js')
const APP_ROOT = path.resolve(import.meta.dirname, '../../e2e-apps/wevu-features')
const DIST_ROOT = path.join(APP_ROOT, 'dist')

async function runBuild() {
  await fs.remove(DIST_ROOT)
  await execa('node', [CLI_PATH, 'build', APP_ROOT, '--platform', 'weapp', '--skipNpm'], {
    cwd: APP_ROOT,
  })
}

describe.sequential('e2e app: wevu-features (build)', () => {
  it('builds useAttrs showcase app and emits expected outputs', async () => {
    await runBuild()

    const appJsonPath = path.join(DIST_ROOT, 'app.json')
    const indexWxmlPath = path.join(DIST_ROOT, 'pages/index/index.wxml')
    const indexJsPath = path.join(DIST_ROOT, 'pages/index/index.js')
    const useAttrsPageWxmlPath = path.join(DIST_ROOT, 'pages/use-attrs/index.wxml')
    const useAttrsPageJsPath = path.join(DIST_ROOT, 'pages/use-attrs/index.js')
    const useAttrsFeatureWxmlPath = path.join(DIST_ROOT, 'components/use-attrs-feature/index.wxml')

    expect(await fs.pathExists(appJsonPath)).toBe(true)
    expect(await fs.pathExists(indexWxmlPath)).toBe(true)
    expect(await fs.pathExists(indexJsPath)).toBe(true)
    expect(await fs.pathExists(useAttrsPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(useAttrsPageJsPath)).toBe(true)
    expect(await fs.pathExists(useAttrsFeatureWxmlPath)).toBe(true)

    const appJson = await fs.readJson(appJsonPath)
    const indexWxml = await fs.readFile(indexWxmlPath, 'utf8')
    const indexJs = await fs.readFile(indexJsPath, 'utf8')
    const useAttrsPageWxml = await fs.readFile(useAttrsPageWxmlPath, 'utf8')
    const useAttrsPageJs = await fs.readFile(useAttrsPageJsPath, 'utf8')
    const useAttrsFeatureWxml = await fs.readFile(useAttrsFeatureWxmlPath, 'utf8')

    expect(appJson.pages).toEqual([
      'pages/index/index',
      'pages/use-attrs/index',
      'pages/use-slots/index',
      'pages/use-model/index',
      'pages/use-provide-inject/index',
      'pages/use-store/index',
      'pages/subpath-entries/index',
      'pages/native-uses-vue/index',
      'pages/router-stability/index',
      'pages/router-stability/sub/index',
      'pages/router-stability/target/index',
      'pages/router-stability/sub/target/index',
      'components/router-origin-probe/target/index',
    ])

    expect(indexWxml).toContain('url="{{item.path}}"')
    expect(indexJs).toContain('/pages/use-attrs/index')
    expect(indexJs).toContain('/pages/use-slots/index')
    expect(indexJs).toContain('/pages/use-model/index')
    expect(indexJs).toContain('/pages/use-provide-inject/index')
    expect(indexJs).toContain('/pages/use-store/index')
    expect(indexJs).toContain('/pages/subpath-entries/index')
    expect(indexJs).toContain('/pages/native-uses-vue/index')
    expect(indexJs).toContain('/pages/router-stability/index')
    expect(indexJs).toContain('useAttrs')
    expect(indexJs).toContain('useSlots')
    expect(indexJs).toContain('useModel')
    expect(indexJs).toContain('provide / inject')
    expect(indexJs).toContain('store')
    expect(indexJs).toContain('subpath entries')
    expect(indexJs).toContain('native -> vue')
    expect(indexJs).toContain('router stability')

    expect(useAttrsPageWxml).toContain('<UseAttrsFeature')
    expect(useAttrsPageWxml).toContain('stateClass="{{currentToneClass}}"')
    expect(useAttrsPageWxml).toContain('visible="{{controlState.visible}}"')
    expect(useAttrsPageWxml).toContain('badgeStyle="{{currentBadgeStyle}}"')
    expect(useAttrsPageWxml).toContain('extraLabel="{{currentExtraLabel}}"')
    expect(useAttrsPageWxml).toContain('seedTag="{{controlState.seed}}"')
    expect(useAttrsPageWxml).toContain('bindtap="cycleToneClass"')
    expect(useAttrsPageWxml).toContain('bindtap="toggleVisible"')
    expect(useAttrsPageWxml).toContain('bindtap="toggleStrongBorder"')
    expect(useAttrsPageWxml).toContain('bindtap="bumpSeed"')

    expect(useAttrsPageJs).toContain('controlState')
    expect(useAttrsPageJs).toContain('runE2E')
    expect(useAttrsPageJs).toContain('_runE2E')

    expect(useAttrsFeatureWxml).toContain('wx:if="{{visible}}"')
    expect(useAttrsFeatureWxml).toContain('wx:for="{{attrRows}}"')
    expect(useAttrsFeatureWxml).toMatch(/class="\{\{__wv_cls_\d+\}\}"/)

    const useSlotsPageWxmlPath = path.join(DIST_ROOT, 'pages/use-slots/index.wxml')
    const useSlotsPageJsPath = path.join(DIST_ROOT, 'pages/use-slots/index.js')
    const useSlotsFeatureWxmlPath = path.join(DIST_ROOT, 'components/use-slots-feature/index.wxml')

    const useModelPageWxmlPath = path.join(DIST_ROOT, 'pages/use-model/index.wxml')
    const useModelPageJsPath = path.join(DIST_ROOT, 'pages/use-model/index.js')
    const useModelFeatureWxmlPath = path.join(DIST_ROOT, 'components/use-model-feature/index.wxml')
    const useProvideInjectPageWxmlPath = path.join(DIST_ROOT, 'pages/use-provide-inject/index.wxml')
    const useProvideInjectPageJsPath = path.join(DIST_ROOT, 'pages/use-provide-inject/index.js')
    const useProvideInjectFeatureWxmlPath = path.join(DIST_ROOT, 'components/use-provide-inject-feature/index.wxml')
    const useStorePageWxmlPath = path.join(DIST_ROOT, 'pages/use-store/index.wxml')
    const useStorePageJsPath = path.join(DIST_ROOT, 'pages/use-store/index.js')
    const subpathEntriesPageWxmlPath = path.join(DIST_ROOT, 'pages/subpath-entries/index.wxml')
    const subpathEntriesPageJsPath = path.join(DIST_ROOT, 'pages/subpath-entries/index.js')
    const nativeUsesVuePageWxmlPath = path.join(DIST_ROOT, 'pages/native-uses-vue/index.wxml')
    const nativeUsesVuePageJsPath = path.join(DIST_ROOT, 'pages/native-uses-vue/index.js')
    const nativeUsesVueComponentJsonPath = path.join(DIST_ROOT, 'native/native-uses-vue/index.json')
    const nativeUsesVueComponentWxmlPath = path.join(DIST_ROOT, 'native/native-uses-vue/index.wxml')
    const nativeCardComponentWxmlPath = path.join(DIST_ROOT, 'components/native-card/index.wxml')
    const routerStabilityPageWxmlPath = path.join(DIST_ROOT, 'pages/router-stability/index.wxml')
    const routerStabilityPageJsPath = path.join(DIST_ROOT, 'pages/router-stability/index.js')
    const routerStabilitySubPageWxmlPath = path.join(DIST_ROOT, 'pages/router-stability/sub/index.wxml')
    const routerStabilitySubPageJsPath = path.join(DIST_ROOT, 'pages/router-stability/sub/index.js')
    const routerStabilityTargetPageWxmlPath = path.join(DIST_ROOT, 'pages/router-stability/target/index.wxml')
    const routerStabilityTargetPageJsPath = path.join(DIST_ROOT, 'pages/router-stability/target/index.js')
    const routerStabilitySubTargetPageWxmlPath = path.join(DIST_ROOT, 'pages/router-stability/sub/target/index.wxml')
    const routerStabilitySubTargetPageJsPath = path.join(DIST_ROOT, 'pages/router-stability/sub/target/index.js')
    const routerOriginProbeWxmlPath = path.join(DIST_ROOT, 'components/router-origin-probe/index.wxml')
    const routerOriginProbeJsPath = path.join(DIST_ROOT, 'components/router-origin-probe/index.js')
    const routerOriginProbeTargetWxmlPath = path.join(DIST_ROOT, 'components/router-origin-probe/target/index.wxml')
    const routerOriginProbeTargetJsPath = path.join(DIST_ROOT, 'components/router-origin-probe/target/index.js')

    expect(await fs.pathExists(useSlotsPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(useSlotsPageJsPath)).toBe(true)
    expect(await fs.pathExists(useSlotsFeatureWxmlPath)).toBe(true)
    expect(await fs.pathExists(useModelPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(useModelPageJsPath)).toBe(true)
    expect(await fs.pathExists(useModelFeatureWxmlPath)).toBe(true)
    expect(await fs.pathExists(useProvideInjectPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(useProvideInjectPageJsPath)).toBe(true)
    expect(await fs.pathExists(useProvideInjectFeatureWxmlPath)).toBe(true)
    expect(await fs.pathExists(useStorePageWxmlPath)).toBe(true)
    expect(await fs.pathExists(useStorePageJsPath)).toBe(true)
    expect(await fs.pathExists(subpathEntriesPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(subpathEntriesPageJsPath)).toBe(true)
    expect(await fs.pathExists(nativeUsesVuePageWxmlPath)).toBe(true)
    expect(await fs.pathExists(nativeUsesVuePageJsPath)).toBe(true)
    expect(await fs.pathExists(nativeUsesVueComponentJsonPath)).toBe(true)
    expect(await fs.pathExists(nativeUsesVueComponentWxmlPath)).toBe(true)
    expect(await fs.pathExists(nativeCardComponentWxmlPath)).toBe(true)
    expect(await fs.pathExists(routerStabilityPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(routerStabilityPageJsPath)).toBe(true)
    expect(await fs.pathExists(routerStabilitySubPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(routerStabilitySubPageJsPath)).toBe(true)
    expect(await fs.pathExists(routerStabilityTargetPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(routerStabilityTargetPageJsPath)).toBe(true)
    expect(await fs.pathExists(routerStabilitySubTargetPageWxmlPath)).toBe(true)
    expect(await fs.pathExists(routerStabilitySubTargetPageJsPath)).toBe(true)
    expect(await fs.pathExists(routerOriginProbeWxmlPath)).toBe(true)
    expect(await fs.pathExists(routerOriginProbeJsPath)).toBe(true)
    expect(await fs.pathExists(routerOriginProbeTargetWxmlPath)).toBe(true)
    expect(await fs.pathExists(routerOriginProbeTargetJsPath)).toBe(true)

    const useSlotsPageWxml = await fs.readFile(useSlotsPageWxmlPath, 'utf8')
    const useSlotsPageJs = await fs.readFile(useSlotsPageJsPath, 'utf8')
    const useSlotsFeatureWxml = await fs.readFile(useSlotsFeatureWxmlPath, 'utf8')
    const useModelPageWxml = await fs.readFile(useModelPageWxmlPath, 'utf8')
    const useModelPageJs = await fs.readFile(useModelPageJsPath, 'utf8')
    const useModelFeatureWxml = await fs.readFile(useModelFeatureWxmlPath, 'utf8')
    const useProvideInjectPageWxml = await fs.readFile(useProvideInjectPageWxmlPath, 'utf8')
    const useProvideInjectPageJs = await fs.readFile(useProvideInjectPageJsPath, 'utf8')
    const useProvideInjectFeatureWxml = await fs.readFile(useProvideInjectFeatureWxmlPath, 'utf8')
    const useStorePageWxml = await fs.readFile(useStorePageWxmlPath, 'utf8')
    const useStorePageJs = await fs.readFile(useStorePageJsPath, 'utf8')
    const subpathEntriesPageWxml = await fs.readFile(subpathEntriesPageWxmlPath, 'utf8')
    const subpathEntriesPageJs = await fs.readFile(subpathEntriesPageJsPath, 'utf8')
    const nativeUsesVuePageWxml = await fs.readFile(nativeUsesVuePageWxmlPath, 'utf8')
    const nativeUsesVuePageJs = await fs.readFile(nativeUsesVuePageJsPath, 'utf8')
    const nativeUsesVueComponentJson = await fs.readJson(nativeUsesVueComponentJsonPath)
    const nativeUsesVueComponentWxml = await fs.readFile(nativeUsesVueComponentWxmlPath, 'utf8')
    const nativeCardComponentWxml = await fs.readFile(nativeCardComponentWxmlPath, 'utf8')
    const routerStabilityPageWxml = await fs.readFile(routerStabilityPageWxmlPath, 'utf8')
    const routerStabilityPageJs = await fs.readFile(routerStabilityPageJsPath, 'utf8')
    const routerStabilitySubPageWxml = await fs.readFile(routerStabilitySubPageWxmlPath, 'utf8')
    const routerStabilitySubPageJs = await fs.readFile(routerStabilitySubPageJsPath, 'utf8')
    const routerStabilityTargetPageWxml = await fs.readFile(routerStabilityTargetPageWxmlPath, 'utf8')
    const routerStabilityTargetPageJs = await fs.readFile(routerStabilityTargetPageJsPath, 'utf8')
    const routerStabilitySubTargetPageWxml = await fs.readFile(routerStabilitySubTargetPageWxmlPath, 'utf8')
    const routerStabilitySubTargetPageJs = await fs.readFile(routerStabilitySubTargetPageJsPath, 'utf8')
    const routerOriginProbeWxml = await fs.readFile(routerOriginProbeWxmlPath, 'utf8')
    const routerOriginProbeJs = await fs.readFile(routerOriginProbeJsPath, 'utf8')
    const routerOriginProbeTargetWxml = await fs.readFile(routerOriginProbeTargetWxmlPath, 'utf8')
    const routerOriginProbeTargetJs = await fs.readFile(routerOriginProbeTargetJsPath, 'utf8')

    expect(useSlotsPageWxml).toContain('<UseSlotsFeature')
    expect(useSlotsPageWxml).toContain('bindtap="toggleOpen"')
    expect(useSlotsPageWxml).toContain('bindtap="toggleHeader"')
    expect(useSlotsPageWxml).toContain('bindtap="bumpCount"')
    expect(useSlotsPageJs).toContain('_runE2E')
    expect(useSlotsFeatureWxml).toContain('id="slots-panel"')
    expect(useSlotsFeatureWxml).toContain('id="slots-summary"')

    expect(useModelPageWxml).toContain('<UseModelFeature')
    expect(useModelPageWxml).toContain('model-value="{{childModelValue}}"')
    expect(useModelPageWxml).toContain('bind:update:modelValue="__weapp_vite_inline"')
    expect(useModelPageWxml).toContain('bindtap="setParentAlpha"')
    expect(useModelPageWxml).toContain('bindtap="setParentBeta"')
    expect(useModelPageJs).toContain('_runE2E')
    expect(useModelPageJs).toContain('childModelValue')
    expect(useModelPageJs).toContain('normalizeModelValue')
    expect(useModelPageJs).toContain('_runNullGuardE2E')
    expect(useModelFeatureWxml).toContain('id="model-inner-value"')
    expect(useModelFeatureWxml).toContain('bindtap="__weapp_vite_inline"')

    expect(useProvideInjectPageWxml).toContain('<UseProvideInjectFeature')
    expect(useProvideInjectPageWxml).toContain('bindtap="providerIncrementTap"')
    expect(useProvideInjectPageWxml).toContain('bindtap="providerToggleThemeTap"')
    expect(useProvideInjectPageWxml).toContain('id="provide-inc"')
    expect(useProvideInjectPageWxml).toContain('id="provide-toggle-theme"')
    expect(useProvideInjectPageWxml).toContain('id="provide-state"')
    expect(useProvideInjectPageJs).toContain('_runE2E')
    expect(useProvideInjectFeatureWxml).toContain('id="inject-panel"')
    expect(useProvideInjectFeatureWxml).toContain('id="inject-inc"')
    expect(useProvideInjectFeatureWxml).toContain('id="inject-toggle-theme"')

    expect(useStorePageWxml).toContain('id="store-plugin-records"')
    expect(useStorePageWxml).toContain('id="store-subscribe-count"')
    expect(useStorePageWxml).toContain('id="store-subscribe-last"')
    expect(useStorePageWxml).toContain('id="store-action-counts"')
    expect(useStorePageWxml).toContain('id="store-action-last"')
    expect(useStorePageWxml).toContain('id="store-setup-inc"')
    expect(useStorePageWxml).toContain('id="store-setup-patch-object"')
    expect(useStorePageWxml).toContain('id="store-setup-ref-write"')
    expect(useStorePageWxml).toContain('id="store-options-inc"')
    expect(useStorePageWxml).toContain('id="store-options-patch-fn"')
    expect(useStorePageWxml).toContain('id="store-options-ref-write"')
    expect(useStorePageWxml).toContain('bindtap="setupInc"')
    expect(useStorePageWxml).toContain('bindtap="setupPatchObject"')
    expect(useStorePageWxml).toContain('bindtap="optionsPatchFunction"')
    expect(useStorePageWxml).toContain('bindtap="optionsRefWrite"')
    expect(useStorePageJs).toContain('featureSetupCounter')
    expect(useStorePageJs).toContain('featureOptionsCounter')
    expect(useStorePageJs).toContain('_runE2E')

    expect(subpathEntriesPageWxml).toContain('id="subpath-router-fullpath"')
    expect(subpathEntriesPageWxml).toContain('id="subpath-store-summary"')
    expect(subpathEntriesPageWxml).toContain('id="subpath-api-status"')
    expect(subpathEntriesPageWxml).toContain('id="subpath-fetch-status"')
    expect(subpathEntriesPageWxml).toContain('id="subpath-run-e2e"')
    expect(subpathEntriesPageJs).toContain('runE2E')
    expect(subpathEntriesPageJs).toContain('_runE2E')

    expect(nativeUsesVuePageWxml).toMatch(/<(native-uses-vue|NativeUsesVue)\b/)
    expect(nativeUsesVuePageWxml).toContain('id="native-interop-toggle"')
    expect(nativeUsesVuePageWxml).toContain('id="native-interop-count"')
    expect(nativeUsesVuePageJs).toContain('_runE2E')

    expect(nativeUsesVueComponentJson.usingComponents?.['native-card']).toBe('/components/native-card/index')
    expect(nativeUsesVueComponentWxml).toContain('<native-card')
    expect(nativeUsesVueComponentWxml).toContain('{{note}}')
    expect(nativeCardComponentWxml).toContain('badge:')
    expect(nativeCardComponentWxml).toContain('<slot')

    expect(routerStabilityPageWxml).toContain('id="router-open-sub"')
    expect(routerStabilityPageWxml).toContain('id="router-index-wx"')
    expect(routerStabilityPageWxml).toContain('id="router-index-page-router"')
    expect(routerStabilityPageWxml).toContain('bindtap="openSubPage"')
    expect(routerStabilityPageWxml).toContain('bindtap="triggerWxRelativeFromIndex"')
    expect(routerStabilityPageWxml).toContain('bindtap="triggerPageRouterRelativeFromIndex"')
    expect(routerStabilityPageJs).toContain('./target/index?source=wx-from-index')
    expect(routerStabilityPageJs).toContain('./target/index?source=page-router-from-index')
    expect(routerStabilityPageJs).toContain('pageRouter')

    expect(routerStabilitySubPageWxml).toContain('id="router-sub-call-prev-wx"')
    expect(routerStabilitySubPageWxml).toContain('id="router-sub-call-prev-page-router"')
    expect(routerStabilitySubPageWxml).toContain('id="router-sub-call-component-router"')
    expect(routerStabilitySubPageWxml).toContain('id="router-sub-call-component-page-router"')
    expect(routerStabilitySubPageWxml).toContain('bindtap="callPrevWxFromIndex"')
    expect(routerStabilitySubPageWxml).toContain('bindtap="callPrevPageRouterFromIndex"')
    expect(routerStabilitySubPageWxml).toContain('bindtap="runComponentRouterFromProbe"')
    expect(routerStabilitySubPageWxml).toContain('bindtap="runComponentPageRouterFromProbe"')
    expect(routerStabilitySubPageWxml).toContain('<RouterOriginProbe')
    expect(routerStabilitySubPageJs).toContain('getCurrentPages')
    expect(routerStabilitySubPageJs).toContain('triggerWxRelativeFromIndex')
    expect(routerStabilitySubPageJs).toContain('triggerPageRouterRelativeFromIndex')

    expect(routerOriginProbeWxml).toContain('id="cmp-router-nav"')
    expect(routerOriginProbeWxml).toContain('id="cmp-page-router-nav"')
    expect(routerOriginProbeWxml).toContain('bindtap="navByRouter"')
    expect(routerOriginProbeWxml).toContain('bindtap="navByPageRouter"')
    expect(routerOriginProbeJs).toContain('./target/index?source=component-router')
    expect(routerOriginProbeJs).toContain('./target/index?source=component-page-router')
    expect(routerOriginProbeJs).toContain('navByRouter')
    expect(routerOriginProbeJs).toContain('navByPageRouter')

    expect(routerStabilityTargetPageWxml).toContain('route=pages/router-stability/target/index source=')
    expect(routerStabilityTargetPageWxml).toContain('id="router-target-main-marker"')
    expect(routerStabilityTargetPageJs).toContain('navigateBack')
    expect(routerStabilitySubTargetPageWxml).toContain('route=pages/router-stability/sub/target/index source=')
    expect(routerStabilitySubTargetPageWxml).toContain('id="router-target-sub-marker"')
    expect(routerStabilitySubTargetPageJs).toContain('navigateBack')
    expect(routerOriginProbeTargetWxml).toContain('route=components/router-origin-probe/target/index source=')
    expect(routerOriginProbeTargetWxml).toContain('id="router-target-component-marker"')
    expect(routerOriginProbeTargetJs).toContain('navigateBack')
  })
})
