import { mkdir, readFile, writeFile } from 'node:fs/promises'
import nodePath from 'node:path'
import process from 'node:process'
import { pathToFileURL } from 'node:url'
import { inspect } from 'node:util'
import path from 'pathe'
import { parse } from 'yaml'

interface WorkspaceCatalog {
  catalog?: Record<string, unknown>
  catalogs?: Record<string, Record<string, unknown>>
}

function isCurrentModuleEntry(entryArg: string | undefined, moduleUrl: string) {
  if (!entryArg) {
    return false
  }

  const resolvedEntryPath = nodePath.isAbsolute(entryArg)
    ? entryArg
    : nodePath.resolve(entryArg)

  try {
    return moduleUrl === pathToFileURL(resolvedEntryPath).href
  }
  catch {
    return false
  }
}

function normalizeCatalog(catalog?: Record<string, unknown>): Record<string, string> {
  if (!catalog) {
    return {}
  }
  const normalized: Record<string, string> = {}
  const sortedEntries = Object.entries(catalog)
    .sort(([a], [b]) => a.localeCompare(b))

  for (const [name, version] of sortedEntries) {
    if (typeof version === 'string') {
      normalized[name] = version
    }
  }

  return normalized
}

function normalizeNamedCatalogs(
  catalogs?: Record<string, Record<string, unknown>>,
): Record<string, Record<string, string>> {
  if (!catalogs) {
    return {}
  }
  const normalized: Record<string, Record<string, string>> = {}
  const sortedCatalogNames = Object.keys(catalogs).sort((a, b) => a.localeCompare(b))

  for (const catalogName of sortedCatalogNames) {
    normalized[catalogName] = normalizeCatalog(catalogs[catalogName])
  }

  return normalized
}

function renderGeneratedFile(
  catalog: Record<string, string>,
  namedCatalogs: Record<string, Record<string, string>>,
) {
  const catalogLiteral = inspect(catalog, {
    depth: null,
    compact: false,
    sorted: true,
  })
  const namedCatalogLiteral = inspect(namedCatalogs, {
    depth: null,
    compact: false,
    sorted: true,
  })
  return `/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// Auto-generated by scripts/generate-template-catalog.ts. Do not edit.
export const TEMPLATE_CATALOG = ${catalogLiteral} as const

export const TEMPLATE_NAMED_CATALOG = ${namedCatalogLiteral} as const
`
}

/**
 * @description 基于 workspace catalog 生成 create-weapp-vite 模板依赖映射
 */
export async function main() {
  const workspacePath = path.resolve(import.meta.dirname, '../../../pnpm-workspace.yaml')
  const targetPath = path.resolve(import.meta.dirname, '../src/generated/catalog.ts')
  const content = await readFile(workspacePath, 'utf8')
  const workspace = parse(content) as WorkspaceCatalog
  const catalog = normalizeCatalog(workspace.catalog)
  const namedCatalogs = normalizeNamedCatalogs(workspace.catalogs)
  const generated = renderGeneratedFile(catalog, namedCatalogs)
  const current = await readFile(targetPath, 'utf8').catch(() => '')
  if (current === generated) {
    return false
  }
  await mkdir(path.dirname(targetPath), { recursive: true })
  await writeFile(targetPath, generated, 'utf8')
  return true
}

if (isCurrentModuleEntry(process.argv[1], import.meta.url)) {
  await main()
}
