import { registerWeapiIndexAliasPolicyAndMatrixConsistencyTests } from './aliasPolicyAndMatrixConsistency'
import { registerWeapiIndexAlipayClipboardAndAuthUnsupportedTests } from './alipayClipboardAndAuthUnsupported'
import { registerWeapiIndexAlipayModalAndBiometricMappingsTests } from './alipayModalAndBiometricMappings'
import { registerWeapiIndexAlipayUnsupportedAndBleMappingGuardsTests } from './alipayUnsupportedAndBleMappingGuards'
import { registerWeapiIndexCoreBehaviorAndAlipayUiBasicsTests } from './coreBehaviorAndAlipayUiBasics'
import { registerWeapiIndexCrossPlatformAliasAndSystemInfoMappingTests } from './crossPlatformAliasAndSystemInfoMapping'
import { registerWeapiIndexDouyinBaseInfoAndRewardedAdGuardsTests } from './douyinBaseInfoAndRewardedAdGuards'
import { registerWeapiIndexDouyinDocumentAndDeviceCapabilityGuardsTests } from './douyinDocumentAndDeviceCapabilityGuards'
import { registerWeapiIndexDouyinResultMappingAndCoverageTests } from './douyinResultMappingAndCoverage'
import { registerWeapiIndexDouyinStrictModeAndActionSheetCasesTests } from './douyinStrictModeAndActionSheetCases'
import { registerWeapiIndexMissingAdapterMethodUnsupportedCasesTests } from './missingAdapterMethodUnsupportedCases'
import { registerWeapiIndexRewardedAdAndCoreUnsupportedCapabilitiesTests } from './rewardedAdAndCoreUnsupportedCapabilities'
import { registerWeapiIndexStrictCompatibilityUnsupportedCasesTests } from './strictCompatibilityUnsupportedCases'
import { registerWeapiIndexUnsupportedPaymentsAndPreviewMediaTests } from './unsupportedPaymentsAndPreviewMedia'

export function registerWeapiIndexTests() {
  registerWeapiIndexCoreBehaviorAndAlipayUiBasicsTests()
  registerWeapiIndexAlipayModalAndBiometricMappingsTests()
  registerWeapiIndexAlipayUnsupportedAndBleMappingGuardsTests()
  registerWeapiIndexAlipayClipboardAndAuthUnsupportedTests()
  registerWeapiIndexCrossPlatformAliasAndSystemInfoMappingTests()
  registerWeapiIndexUnsupportedPaymentsAndPreviewMediaTests()
  registerWeapiIndexRewardedAdAndCoreUnsupportedCapabilitiesTests()
  registerWeapiIndexMissingAdapterMethodUnsupportedCasesTests()
  registerWeapiIndexStrictCompatibilityUnsupportedCasesTests()
  registerWeapiIndexDouyinStrictModeAndActionSheetCasesTests()
  registerWeapiIndexDouyinDocumentAndDeviceCapabilityGuardsTests()
  registerWeapiIndexDouyinBaseInfoAndRewardedAdGuardsTests()
  registerWeapiIndexDouyinResultMappingAndCoverageTests()
  registerWeapiIndexAliasPolicyAndMatrixConsistencyTests()
}
