import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { agentManifest } from './manifest'
import { renderAgentDocument } from './render'
import { resolveDocument, resolveLayer, validateManifest } from './resolve'

function parseArgs(argv: string[]) {
  const options: { check: boolean, write: boolean, target?: string, profile?: string } = { check: false, write: false }
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    if (arg === '--check') {
      options.check = true
    }
    if (arg === '--write') {
      options.write = true
    }
    if (arg === '--target') {
      options.target = argv[++index]
    }
    if (arg === '--profile') {
      options.profile = argv[++index]
    }
  }
  if (!options.check && !options.write) {
    options.check = true
  }
  if (options.check && options.write) {
    throw new Error('choose only one of --check or --write')
  }
  return options
}

function discoverAgentFiles() {
  const files: string[] = []
  const ignored = new Set([
    '.git',
    'node_modules',
    'dist',
    'coverage',
    'docs/reports',
    '.cache',
    '.codex-tmp',
    '.minidev',
    '.playwright',
    '.playwright-cli',
    '.pnpm-store',
    '.tmp',
    '.turbo',
    '.weapp-vite',
    '.wevu-config',
  ])
  function visit(directory: string) {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      if (ignored.has(entry.name)) {
        continue
      }
      const fullPath = path.join(directory, entry.name)
      const relativePath = path.relative(process.cwd(), fullPath)
      if (relativePath === 'docs/reports' || relativePath.startsWith('docs/reports/')) {
        continue
      }
      if (entry.isDirectory()) {
        visit(fullPath)
      }
      else if (entry.name === 'AGENTS.md') {
        files.push(path.relative(process.cwd(), fullPath))
      }
    }
  }
  visit(process.cwd())
  return files.sort()
}

function expectedFiles(options: { target?: string } = {}) {
  const files = agentManifest.documents.map(document => ({
    path: document.path,
    content: renderAgentDocument(
      agentManifest,
      resolveDocument(agentManifest, document.layer, document.title),
      `document:${document.path}`,
    ),
  }))
  files.push({
    path: 'packages/create-weapp-vite/src/generated/agents.ts',
    // eslint-disable-next-line ts/no-use-before-define
    content: renderGeneratedTemplateSource(),
  })
  if (options.target) {
    return files.filter(file => file.path === options.target)
  }
  return files
}

function renderGeneratedTemplateSource() {
  const entries = Object.entries(agentManifest.templates).map(([name, profile]) => {
    const document = resolveDocument(agentManifest, profile.layer, profile.title)
    const rendered = renderAgentDocument(agentManifest, document, `template:${name}`)
    // eslint-disable-next-line ts/no-use-before-define
    const key = toTsString(name)
    // eslint-disable-next-line ts/no-use-before-define
    const value = toTsString(rendered)
    return `  ${key}: ${value},`
  })
  return [
    '// Generated by pnpm agents:generate. Do not edit manually.',
    'export const generatedAgentGuidelines = {',
    ...entries,
    '}',
    '',
  ].join('\n')
}

function toTsString(value: string) {
  const quote = '\''
  return `'${value
    .replaceAll('\\', '\\\\')
    .replaceAll(quote, `\\${quote}`)
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')}'`
}

export function runAgentsCommand(argv = process.argv.slice(2)) {
  const options = parseArgs(argv)
  const validation = validateManifest(agentManifest)
  if (validation.issues.length > 0) {
    throw new Error(validation.issues.join('\n'))
  }
  for (const layerName of Object.keys(agentManifest.layers)) {
    resolveLayer(agentManifest, layerName)
  }
  if (options.profile && !agentManifest.templates[options.profile]) {
    throw new Error(`unknown template profile: ${options.profile}`)
  }

  const mismatches: string[] = []
  const files = expectedFiles(options)
  for (const file of files) {
    const actual = fs.existsSync(file.path) ? fs.readFileSync(file.path, 'utf8') : null
    if (options.write) {
      fs.mkdirSync(path.dirname(file.path), { recursive: true })
      fs.writeFileSync(file.path, file.content)
    }
    else if (actual !== file.content) {
      mismatches.push(actual === null ? `${file.path}: missing generated file` : `${file.path}: generated content drift`)
    }
  }
  if (!options.target && !options.profile && !options.write) {
    const expectedPaths = new Set(agentManifest.documents.map(document => document.path))
    for (const file of discoverAgentFiles()) {
      if (!expectedPaths.has(file)) {
        mismatches.push(`${file}: AGENTS.md is not registered in manifest`)
      }
    }
  }
  if (mismatches.length > 0) {
    throw new Error(mismatches.join('\n'))
  }
  console.log(options.write
    ? `[agents] generated ${files.length} file(s)`
    : `[agents] checked ${files.length} file(s)`)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    runAgentsCommand()
  }
  catch (error) {
    console.error(`[agents] ${error instanceof Error ? error.message : String(error)}`)
    process.exitCode = 1
  }
}
