import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_GET_LOG_MANAGER_TO_ADD_PHONE_CALENDAR: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'getLogManager',
    description: '获取日志管理器实例。',
    wxStrategy: '直连 `wx.getLogManager`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'nextTick',
    description: '延迟到下一个 UI 更新时机执行回调。',
    wxStrategy: '直连 `wx.nextTick`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'onWindowResize',
    description: '监听窗口尺寸变化事件。',
    wxStrategy: '直连 `wx.onWindowResize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.onWindowResize`',
    support: '⚠️',
  },
  {
    method: 'offWindowResize',
    description: '取消监听窗口尺寸变化事件。',
    wxStrategy: '直连 `wx.offWindowResize`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.offWindowResize`',
    support: '⚠️',
  },
  {
    method: 'reportAnalytics',
    description: '上报分析数据。',
    wxStrategy: '直连 `wx.reportAnalytics`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '直连 `tt.reportAnalytics`',
    support: '⚠️',
  },
  {
    method: 'openCustomerServiceChat',
    description: '打开客服会话。',
    wxStrategy: '直连 `wx.openCustomerServiceChat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createVKSession',
    description: '创建视觉识别会话。',
    wxStrategy: '直连 `wx.createVKSession`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'compressVideo',
    description: '压缩视频文件。',
    wxStrategy: '直连 `wx.compressVideo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openVideoEditor',
    description: '打开视频编辑器。',
    wxStrategy: '直连 `wx.openVideoEditor`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getShareInfo',
    description: '获取转发详细信息。',
    wxStrategy: '直连 `wx.getShareInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'joinVoIPChat',
    description: '加入音视频通话。',
    wxStrategy: '直连 `wx.joinVoIPChat`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openDocument',
    description: '打开文档。',
    wxStrategy: '直连 `wx.openDocument`',
    alipayStrategy: '直连 `my.openDocument`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'saveVideoToPhotosAlbum',
    description: '保存视频到系统相册。',
    wxStrategy: '直连 `wx.saveVideoToPhotosAlbum`',
    alipayStrategy: '直连 `my.saveVideoToPhotosAlbum`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'batchSetStorage',
    description: '批量异步写入缓存。',
    wxStrategy: '直连 `wx.batchSetStorage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'batchGetStorage',
    description: '批量异步读取缓存。',
    wxStrategy: '直连 `wx.batchGetStorage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'batchSetStorageSync',
    description: '批量同步写入缓存。',
    wxStrategy: '直连 `wx.batchSetStorageSync`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'batchGetStorageSync',
    description: '批量同步读取缓存。',
    wxStrategy: '直连 `wx.batchGetStorageSync`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createCameraContext',
    description: '创建相机上下文对象。',
    wxStrategy: '直连 `wx.createCameraContext`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'offMemoryWarning',
    description: '取消内存不足告警监听。',
    wxStrategy: '直连 `wx.offMemoryWarning`',
    alipayStrategy: '直连 `my.offMemoryWarning`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'cancelIdleCallback',
    description: '取消空闲回调。',
    wxStrategy: '直连 `wx.cancelIdleCallback`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'onBLEConnectionStateChange',
    description: '监听 BLE 连接状态变化。',
    wxStrategy: '直连 `wx.onBLEConnectionStateChange`',
    alipayStrategy: '映射到 `my.onBLEConnectionStateChanged`',
    douyinStrategy: '抖音无同等 API，调用时报 not supported',
    support: '⚠️',
  },
  {
    method: 'offBLEConnectionStateChange',
    description: '取消监听 BLE 连接状态变化。',
    wxStrategy: '直连 `wx.offBLEConnectionStateChange`',
    alipayStrategy: '映射到 `my.offBLEConnectionStateChanged`',
    douyinStrategy: '抖音无同等 API，调用时报 not supported',
    support: '⚠️',
  },
  {
    method: 'addCard',
    description: '添加微信卡券。',
    wxStrategy: '直连 `wx.addCard`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addFileToFavorites',
    description: '添加文件到收藏。',
    wxStrategy: '直连 `wx.addFileToFavorites`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPaymentPassFinish',
    description: '添加支付 pass 完成回调。',
    wxStrategy: '直连 `wx.addPaymentPassFinish`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPaymentPassGetCertificateData',
    description: '添加支付 pass 证书数据回调。',
    wxStrategy: '直连 `wx.addPaymentPassGetCertificateData`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'addPhoneCalendar',
    description: '添加日历事件。',
    wxStrategy: '直连 `wx.addPhoneCalendar`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
