import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_OPEN_OFFICIAL_ACCOUNT_PROFILE_TO_CREATE_BLECONNECTION: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'openOfficialAccountProfile',
    description: '打开公众号主页。',
    wxStrategy: '直连 `wx.openOfficialAccountProfile`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openPrivacyContract',
    description: '打开隐私协议页面。',
    wxStrategy: '直连 `wx.openPrivacyContract`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openSystemBluetoothSetting',
    description: '打开系统蓝牙设置页面。',
    wxStrategy: '直连 `wx.openSystemBluetoothSetting`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'reportEvent',
    description: '上报事件埋点。',
    wxStrategy: '直连 `wx.reportEvent`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'reportMonitor',
    description: '上报监控数据。',
    wxStrategy: '直连 `wx.reportMonitor`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'reportPerformance',
    description: '上报性能数据。',
    wxStrategy: '直连 `wx.reportPerformance`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openSingleStickerView',
    description: '打开单个表情贴纸详情。',
    wxStrategy: '直连 `wx.openSingleStickerView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openStickerIPView',
    description: '打开表情 IP 页面。',
    wxStrategy: '直连 `wx.openStickerIPView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openStickerSetView',
    description: '打开表情包详情页。',
    wxStrategy: '直连 `wx.openStickerSetView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openStoreCouponDetail',
    description: '打开小店优惠券详情。',
    wxStrategy: '直连 `wx.openStoreCouponDetail`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'openStoreOrderDetail',
    description: '打开小店订单详情。',
    wxStrategy: '直连 `wx.openStoreOrderDetail`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'pauseBackgroundAudio',
    description: '暂停后台音频。',
    wxStrategy: '直连 `wx.pauseBackgroundAudio`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'pauseVoice',
    description: '暂停播放语音。',
    wxStrategy: '直连 `wx.pauseVoice`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'playBackgroundAudio',
    description: '播放后台音频。',
    wxStrategy: '直连 `wx.playBackgroundAudio`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'playVoice',
    description: '播放语音。',
    wxStrategy: '直连 `wx.playVoice`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'postMessageToReferrerMiniProgram',
    description: '向来源小程序发送消息。',
    wxStrategy: '直连 `wx.postMessageToReferrerMiniProgram`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'postMessageToReferrerPage',
    description: '向来源页面发送消息。',
    wxStrategy: '直连 `wx.postMessageToReferrerPage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'preDownloadSubpackage',
    description: '预下载分包。',
    wxStrategy: '直连 `wx.preDownloadSubpackage`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'preloadAssets',
    description: '预加载资源。',
    wxStrategy: '直连 `wx.preloadAssets`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'preloadSkylineView',
    description: '预加载 Skyline 视图。',
    wxStrategy: '直连 `wx.preloadSkylineView`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'preloadWebview',
    description: '预加载 WebView 页面。',
    wxStrategy: '直连 `wx.preloadWebview`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'removeSecureElementPass',
    description: '移除安全元素卡片。',
    wxStrategy: '直连 `wx.removeSecureElementPass`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'chooseInvoiceTitle',
    description: '选择发票抬头。',
    wxStrategy: '直连 `wx.chooseInvoiceTitle`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'chooseLicensePlate',
    description: '选择车牌号。',
    wxStrategy: '直连 `wx.chooseLicensePlate`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'choosePoi',
    description: '选择兴趣点 POI。',
    wxStrategy: '直连 `wx.choosePoi`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'closeBLEConnection',
    description: '断开低功耗蓝牙连接。',
    wxStrategy: '直连 `wx.closeBLEConnection`',
    alipayStrategy: '`deviceId` 对齐后映射到 `my.disconnectBLEDevice`，并将 `errorCode/errorMessage` 映射为 `errCode/errMsg`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createBLEConnection',
    description: '创建低功耗蓝牙连接。',
    wxStrategy: '直连 `wx.createBLEConnection`',
    alipayStrategy: '`deviceId/timeout` 对齐后映射到 `my.connectBLEDevice`，并将 `error/errorMessage` 映射为 `errCode/errMsg`',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
