import type { WeapiMethodSupportMatrixItem } from '../types'

export const WEAPI_METHOD_SUPPORT_MATRIX_UPDATE_WE_CHAT_APP_TO_CREATE_MEDIA_AUDIO_PLAYER: readonly WeapiMethodSupportMatrixItem[] = [
  {
    method: 'updateWeChatApp',
    description: '拉起微信升级流程。',
    wxStrategy: '直连 `wx.updateWeChatApp`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getBackgroundAudioPlayerState',
    description: '获取后台音频播放状态。',
    wxStrategy: '直连 `wx.getBackgroundAudioPlayerState`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getDeviceBenchmarkInfo',
    description: '获取设备性能评估信息。',
    wxStrategy: '直连 `wx.getDeviceBenchmarkInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getDeviceVoIPList',
    description: '获取设备 VoIP 列表。',
    wxStrategy: '直连 `wx.getDeviceVoIPList`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getHCEState',
    description: '获取 HCE 状态。',
    wxStrategy: '直连 `wx.getHCEState`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getInferenceEnvInfo',
    description: '获取推理环境信息。',
    wxStrategy: '直连 `wx.getInferenceEnvInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getNFCAdapter',
    description: '获取 NFC 适配器。',
    wxStrategy: '直连 `wx.getNFCAdapter`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getPerformance',
    description: '获取性能对象。',
    wxStrategy: '直连 `wx.getPerformance`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getRandomValues',
    description: '获取随机值。',
    wxStrategy: '直连 `wx.getRandomValues`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getRealtimeLogManager',
    description: '获取实时日志管理器。',
    wxStrategy: '直连 `wx.getRealtimeLogManager`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getRendererUserAgent',
    description: '获取渲染层 UserAgent。',
    wxStrategy: '直连 `wx.getRendererUserAgent`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getScreenRecordingState',
    description: '获取录屏状态。',
    wxStrategy: '直连 `wx.getScreenRecordingState`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSecureElementPasses',
    description: '获取安全元素卡片列表。',
    wxStrategy: '直连 `wx.getSecureElementPasses`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSelectedTextRange',
    description: '获取已选中文本范围。',
    wxStrategy: '直连 `wx.getSelectedTextRange`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getShowSplashAdStatus',
    description: '获取开屏广告展示状态。',
    wxStrategy: '直连 `wx.getShowSplashAdStatus`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getSkylineInfo',
    description: '获取 Skyline 信息。',
    wxStrategy: '直连 `wx.getSkylineInfo`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getUserCryptoManager',
    description: '获取用户加密管理器。',
    wxStrategy: '直连 `wx.getUserCryptoManager`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getWeRunData',
    description: '获取微信运动数据。',
    wxStrategy: '直连 `wx.getWeRunData`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'getXrFrameSystem',
    description: '获取 XR 框架系统对象。',
    wxStrategy: '直连 `wx.getXrFrameSystem`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'isBluetoothDevicePaired',
    description: '判断蓝牙设备是否已配对。',
    wxStrategy: '直连 `wx.isBluetoothDevicePaired`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'isVKSupport',
    description: '判断是否支持视觉识别能力。',
    wxStrategy: '直连 `wx.isVKSupport`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createBLEPeripheralServer',
    description: '创建 BLE 外设服务实例。',
    wxStrategy: '直连 `wx.createBLEPeripheralServer`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createBufferURL',
    description: '创建缓冲区 URL。',
    wxStrategy: '直连 `wx.createBufferURL`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createCacheManager',
    description: '创建缓存管理器。',
    wxStrategy: '直连 `wx.createCacheManager`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createGlobalPayment',
    description: '创建全局支付对象。',
    wxStrategy: '直连 `wx.createGlobalPayment`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createInferenceSession',
    description: '创建推理会话。',
    wxStrategy: '直连 `wx.createInferenceSession`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
  {
    method: 'createMediaAudioPlayer',
    description: '创建媒体音频播放器。',
    wxStrategy: '直连 `wx.createMediaAudioPlayer`',
    alipayStrategy: '无同等 API，调用时按 unsupported 报错',
    douyinStrategy: '无同等 API，调用时按 unsupported 报错',
    support: '⚠️',
  },
]
