import { WEAPP_BUILTIN_HTML_TAGS_ADS_AND_META } from './adsAndMeta'
import { WEAPP_BUILTIN_HTML_TAGS_FORM_CONTROLS_PRIMARY } from './formControlsPrimary'
import { WEAPP_BUILTIN_HTML_TAGS_FORM_CONTROLS_SELECTION } from './formControlsSelection'
import { WEAPP_BUILTIN_HTML_TAGS_MAP_AND_MOVABLE } from './mapAndMovable'
import { WEAPP_BUILTIN_HTML_TAGS_MEDIA_CAPTURE_LIVE } from './mediaCaptureLive'
import { WEAPP_BUILTIN_HTML_TAGS_MEDIA_PLAYBACK } from './mediaPlayback'
import { WEAPP_BUILTIN_HTML_TAGS_TEMPLATES_AND_NAVIGATION } from './templatesAndNavigation'
import { WEAPP_BUILTIN_HTML_TAGS_VISUAL_VIEW } from './visualView'

export const WEAPP_BUILTIN_HTML_TAGS = [
  ...WEAPP_BUILTIN_HTML_TAGS_ADS_AND_META,
  ...WEAPP_BUILTIN_HTML_TAGS_TEMPLATES_AND_NAVIGATION,
  ...WEAPP_BUILTIN_HTML_TAGS_FORM_CONTROLS_PRIMARY,
  ...WEAPP_BUILTIN_HTML_TAGS_FORM_CONTROLS_SELECTION,
  ...WEAPP_BUILTIN_HTML_TAGS_MEDIA_PLAYBACK,
  ...WEAPP_BUILTIN_HTML_TAGS_MEDIA_CAPTURE_LIVE,
  ...WEAPP_BUILTIN_HTML_TAGS_MAP_AND_MOVABLE,
  ...WEAPP_BUILTIN_HTML_TAGS_VISUAL_VIEW,
]
