export function createInlineStyleModule(css: string) {
  const serialized = JSON.stringify(css)
  return [
    `const __weapp_injected_styles__ = new Map()`,
    `function __weapp_createStyleId__(css) {`,
    `  let hash = 2166136261`,
    `  for (let i = 0; i < css.length; i++) {`,
    `    hash ^= css.charCodeAt(i)`,
    `    hash += (hash << 1) + (hash << 4) + (hash << 7) + (hash << 8) + (hash << 24)`,
    `  }`,
    `  return 'weapp-web-style-' + (hash >>> 0).toString(36)`,
    `}`,
    `function __weapp_removeStyle__(id) {`,
    `  if (typeof document === 'undefined') {`,
    `    return`,
    `  }`,
    `  const style = __weapp_injected_styles__.get(id)`,
    `  if (style) {`,
    `    style.remove()`,
    `    __weapp_injected_styles__.delete(id)`,
    `  }`,
    `}`,
    `function injectStyle(css, id) {`,
    `  if (typeof document === 'undefined') {`,
    `    return () => {}`,
    `  }`,
    `  const styleId = id ?? __weapp_createStyleId__(css)`,
    `  const existing = __weapp_injected_styles__.get(styleId)`,
    `  if (existing) {`,
    `    if (existing.textContent !== css) {`,
    `      existing.textContent = css`,
    `    }`,
    `    return () => __weapp_removeStyle__(styleId)`,
    `  }`,
    `  const style = document.createElement('style')`,
    `  style.id = styleId`,
    `  style.textContent = css`,
    `  document.head.append(style)`,
    `  __weapp_injected_styles__.set(styleId, style)`,
    `  return () => __weapp_removeStyle__(styleId)`,
    `}`,
    `const css = ${serialized}`,
    `export default css`,
    `export function useStyle(id) {`,
    `  return injectStyle(css, id)`,
    `}`,
  ].join('\n')
}
