export { collectWevuPageFeatureFlags, injectWevuPageFeatureFlagsIntoOptionsObject } from './pageFeatures/flags'
export { injectWevuPageFeaturesInJs, injectWevuPageFeaturesInJsWithResolver } from './pageFeatures/inject'
export { createPageEntryMatcher } from './pageFeatures/matcher'
export { createWevuAutoPageFeaturesPlugin } from './pageFeatures/plugin'
export type { ModuleResolver, WevuPageFeatureFlag } from './pageFeatures/types'
