import type { WeapiCrossPlatformMethodDocsCanvasGetImageDataToOpenPrivacyContract } from './methodDocsCanvasGetImageDataToOpenPrivacyContract'
import type { WeapiCrossPlatformMethodDocsChoosePoiToShareFileToGroup } from './methodDocsChoosePoiToShareFileToGroup'
import type { WeapiCrossPlatformMethodDocsChooseVideoToOpenDocument } from './methodDocsChooseVideoToOpenDocument'
import type { WeapiCrossPlatformMethodDocsCreateVideoDecoderToSetInnerAudioOption } from './methodDocsCreateVideoDecoderToSetInnerAudioOption'
import type { WeapiCrossPlatformMethodDocsGetRealtimeLogManagerToCreateUDPSocket } from './methodDocsGetRealtimeLogManagerToCreateUDPSocket'
import type { WeapiCrossPlatformMethodDocsMissingMethods } from './methodDocsMissingMethods'
import type { WeapiCrossPlatformMethodDocsOpenSystemBluetoothSettingToChooseLicensePlate } from './methodDocsOpenSystemBluetoothSettingToChooseLicensePlate'
import type { WeapiCrossPlatformMethodDocsPluginLoginToGetAppBaseInfo } from './methodDocsPluginLoginToGetAppBaseInfo'
import type { WeapiCrossPlatformMethodDocsSaveVideoToPhotosAlbumToCanAddSecureElementPass } from './methodDocsSaveVideoToPhotosAlbumToCanAddSecureElementPass'
import type { WeapiCrossPlatformMethodDocsSendHCEMessageToGetRandomValues } from './methodDocsSendHCEMessageToGetRandomValues'
import type { WeapiCrossPlatformMethodDocsShareImageToGroupToSelectGroupMembers } from './methodDocsShareImageToGroupToSelectGroupMembers'
import type { WeapiCrossPlatformMethodDocsShowToastToOpenAppAuthorizeSetting } from './methodDocsShowToastToOpenAppAuthorizeSetting'

export type WeapiCrossPlatformMethodDocs
  = WeapiCrossPlatformMethodDocsShowToastToOpenAppAuthorizeSetting
    & WeapiCrossPlatformMethodDocsPluginLoginToGetAppBaseInfo
    & WeapiCrossPlatformMethodDocsChooseVideoToOpenDocument
    & WeapiCrossPlatformMethodDocsSaveVideoToPhotosAlbumToCanAddSecureElementPass
    & WeapiCrossPlatformMethodDocsCanvasGetImageDataToOpenPrivacyContract
    & WeapiCrossPlatformMethodDocsOpenSystemBluetoothSettingToChooseLicensePlate
    & WeapiCrossPlatformMethodDocsChoosePoiToShareFileToGroup
    & WeapiCrossPlatformMethodDocsShareImageToGroupToSelectGroupMembers
    & WeapiCrossPlatformMethodDocsSendHCEMessageToGetRandomValues
    & WeapiCrossPlatformMethodDocsGetRealtimeLogManagerToCreateUDPSocket
    & WeapiCrossPlatformMethodDocsCreateVideoDecoderToSetInnerAudioOption
    & WeapiCrossPlatformMethodDocsMissingMethods
